### ISSUE TITLE
Is it possible to export/import virtual foreign keys?

### ISSUE THREAD

**Issue by mwalkerr** [dbeaver/dbeaver#10004]
The virtual foreign keys feature is super helpful since we decided against keeping foreign keys in the actual schema. We have multiple versions of each database, so it'd be helpful to copy over virtual key definitions instead of redefining them each time. Same goes for sharing the config with teammates

**Comment by uslss** [comment]
Virtual foreign key are saved in .dbeaver/data-sources.json in project folder. Default project folder is workspace\workspace6\General.
Also you could use Git extension to share it.

**Comment by tuananh281098** [comment]
@mwalkerr @uslss 
Hi guys. Did you success to share virtual foreign key? I found the "virtual-models" key in data-sources.json file and I try to use it for sharing the virtual key but I can't. Could you tell me the way to export/import it? Thanks

**Comment by mwalkerr** [comment]
@tuananh281098
Sorry, I can't offer much help here since I haven't used DBeaver in a while. I think you can make this work but there's no convenient UI in the application to do it. Re-using virtual keys in a different installation would require copying over that data-sources.json file (or at least inserting the relevant bits). I believe I ended up deciding that it was more work than it was worth and ultimately gave up on trying to export them

**Comment by tuananh281098** [comment]
@mwalkerr 
Thanks for your response

**Comment by stonebeaver** [comment]
Found this issue here when looking for exchange of dbeaver's virtual constraints. Found nothing in the docs (and would be glad if corrected). Evaluated the ui. Found nothing useful.

As a contribution, I offer a table of scenarios which may illustrate the gaps and may foster the discussion of possible solutions.

1. **virtual constraints** \
A project with a real-world database, which has constraints that are not set up in the database schema but handled in the client code of a real-world application. The application database is maintained using dbeaver.
2. **dbeaver migrations** \
One user uses multiple workstations in scenario 1. The workstations are distributed across time and space. The user may use multiple workstations at the same time and expects the virtual constraints to be in sync. The user may reset/reinstall a workstation and expect to restore the virtual constraints from before the reset onto the new device.
3. **collaboration** \
Multiple users collaborate in scenario 1. The users are distributed over time and space. Some of the users occasionally figure out virtual constraints. Newly found and existing virtual constraints are reviewed and discussed. When consent is established, the consensual set of virtual constraints should be propagated to the working group.

#### Current Support

disclaimer: totally subjective personal assessment

| scenario               | support | note |
|:-----------------------|:--------|:-----|
| 1. virtual constraints | ★★★★☆ | world-class. minor ux flaws. |
| 2. dbeaver migrations  | ★★☆☆☆ | configuration file exists. may suffice some environments. |
| 3. collaboration       | ☆☆☆☆☆ | no feasible approach yet. |
