### ISSUE TITLE
Support for 'dark theme' (High Contrast [Standart/Eclipse 3/Reduced Palette])

### ISSUE THREAD

**Issue by cccp-1922** [dbeaver/dbeaver#10032]
#### System information: 
- Operating system (distribution) and version: Windows 7 x64
- DBeaver version: 7.2.2
- Java version: 1.8.0
- Additional extensions

Please check and if possible correct support for 'dark theme' (Apperance named High Contrast [Standart/Eclipse 3] in Eclipse).
By check apperance 'Reduced Palette' it´s no possibility to change background and selection color of data table editor (list view) in the table data and sql result set presentation view.

![DB-Beaber-dark_theme-01](https://user-images.githubusercontent.com/43439018/95588824-34833500-0a44-11eb-86ab-a1294b7a5bb2.jpg)
![DB-Beaber-dark_theme-02](https://user-images.githubusercontent.com/43439018/95588854-3cdb7000-0a44-11eb-91aa-d821f638f08c.jpg)
![DB-Beaber-dark_theme-03](https://user-images.githubusercontent.com/43439018/95589125-9ba0e980-0a44-11eb-82ba-b8bd5e83e8dc.jpg)
![DB-Beaber-dark_theme-04](https://user-images.githubusercontent.com/43439018/95589131-9e9bda00-0a44-11eb-8ca3-9f49f3e53264.jpg)

**Comment by 86kk614** [comment]
possible to have dbeaver themes not disabled when windows is using high-contrast theme?

**Comment by DaveBabler** [comment]
> possible to have dbeaver themes not disabled when windows is using high-contrast theme?

Yes Please!!! Not being  able to do this is unacceptable.

**Comment by DaveBabler** [comment]
I would also note that if you force windows out of high contrast mode, DBeaver demands a restart of the application.

**Comment by cccp-1922** [comment]
sure, I has dbeaver theme disabled. Enabling and restarting of dbeaver
has no effect.

**Comment by cccp-1922** [comment]
Hi!

My windows running always in high contrast mode. Restarting of dbeaver
brings nothing.

**Comment by E1izabeth** [comment]
We improved support of High-contrast theme. Could you share your feedback?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by biggytech** [comment]
I experience same issue on 25.3.3 DBeaver for Linux (Ubuntu):
- OS Ubuntu 24.04.3 LTS
- DBeaver Version 25.3.3.202601181752

**How to reproduce:**
1. Enable Dark theme on OS level
2. Enable "High Contrast" setting in OS Accessibility settings
3. Open DBeaver. **_Observe the DBeaver uses Light theme_**
4. Open Appearance preferences in DBeaver. **_Observe that themes settings are disabled and it's not possible to enable dark theme in DBeaver_**

**Expected result:** either themes settings shouldn't be disabled, either DBeaver should inherit theme from OS (_Dark theme in this case_)

<details>

<summary>Screenshots under the hood</summary>

Themes setting is disabled when I have **"High Contrast" OS setting turned on:**
<img width="802" height="139" alt="Image" src="https://github.com/user-attachments/assets/92e8647a-090b-4a50-bd69-47f39c12755f" />

DBeaver appearance theme settings are disabled in this case:
<img width="846" height="262" alt="Image" src="https://github.com/user-attachments/assets/3e444ff1-45e4-4810-abb3-f6d75ab8f708" />

**I can't enable dark theme in DBeaver because of this.**
But the OS is using the Dark theme, although the DBeaver defaults to Light theme when "High Contrast" is enabled:

OS uses "Dark theme":

<img width="763" height="367" alt="Image" src="https://github.com/user-attachments/assets/9e77f714-6c8c-4b94-a9b7-fa3e2a194904" />

DBeaver remains in Light theme and I can't enable Dark theme since theming is disabled in DBeaver:

<img width="1252" height="518" alt="Image" src="https://github.com/user-attachments/assets/57a84650-12c8-4c64-af28-0fb94818358e" />

</details>

<hr />

The issue resolves when I turn off the "High Contrast" in OS settings: in this case DBeaver automatically starts using Dark theme

So the question is how I can enable Dark theme in DBeaver while still having "High Contrast" enabled? Shouldn't DBeaver inherit OS theme regardless of "High Contrast" setting value?

I think the issue should be reopened

**Comment by biggytech** [comment]
Current workaround for me to have both Dark theme in DBeaver and High contrast is the following:
1. Disable "High contrast"
2. Start DBeaver, it automatically infers OS theme (_which is Dark_)
3. And now I can enable "High contrast" again.

On the last step DBeaver will ask for restart, the key is to ignore it and do not restart.

This solution is hacky and it's not convenient, but I didn't find any other ways to make it work
