### ISSUE TITLE
7.2.2 - bug - quick switch editor 

### ISSUE THREAD

**Issue by ceinmart** [dbeaver/dbeaver#10040]
I notice, after upgrade to 7.2.2 the CTRL+E / quick switch editor has two issues :
1) the filter not working.
2) when select a file, it always shows the shared area. 
(I have my scripts in separated blocks since I need to keep a lot of scripts opened and connect to a lot of instances)

![ezgif com-gif-maker (1)](https://user-images.githubusercontent.com/7062410/95640307-95296680-0a72-11eb-957b-505f1553f16f.gif)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by ShadelessFox** [comment]
Hello, @ceinmart, I cannot reproduce your second issue. Can you upgrade to newer version to see if the problem still occurs?
The first one seems like a bug, because it only matches editor's name from the very start. But this may make sense in some cases.

**Update**: According to the Eclipse documentation, you can use wild cards when typing editor's name, e.g: `*nfe`. Please let me know if it will suit your needs.

**Comment by uslss** [comment]
There is no update on the issue for a long time.
If the issue is still actual for you - feel free to reopen it.
