### ISSUE TITLE
Problem with timezone

### ISSUE THREAD

**Issue by jppo** [dbeaver/dbeaver#10055]
Hello,

I use Dbeaver for all my Mysql/MariaDB work and I get a problem with sone databases : I can't connect to some databases with a message : 
The server time zone value 'CEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the serverTimezone configuration property) to use a more specifc time zone value if you want to utilize time zone support.

I don't know how to solve that problem ...

Regards

JP P

**Comment by wietsewarendorff** [comment]
I have the same problem since upgrading from 7.2.0 to 7.2.2

Manually setting the timezone for the connection fixed it for now (edit connection, server time zone on the main tab).

**Comment by uslss** [comment]
The Default MySQL driver was changed to MySQL 8 since 7.2.2. Timezone isn't set on your MySQL server, so driver throws an error.
You could:
1) Change connection Driver from MySQL to MySQL 5
2) Set Timezone in Connection properties.
![image](https://user-images.githubusercontent.com/31996417/96459620-fdbed300-122a-11eb-9fd8-254e4a5a2ac0.png)
3) Set Timezone at MySQL server.

**Comment by serge-rider** [comment]
I've added a workaround for this nasty issue. 
DBeaver will automatatically set UTC as default serverTimezone. But only if it wasn't set in properties and only after connection attempt fail.

**Comment by uslss** [comment]
verified
