### ISSUE TITLE
Oracle SQL export refactoring

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10214]
#### System information: 
- DBeaver version 7.2.4 EA

#### Connection specification:
- Database name and version Oracle
 
#### Steps to reproduce, if exist:
Open export for Oracle table in SQL format and select  **replace into** option in SQL settings

**Comment by LonwoLonwo** [comment]
Now all the choice of syntax specific to different databases went to the "Insert keyword" setting. And if you need to use multi-row export from Oracle to Oracle, then you should choose "INSERT ALL" instead default "INSERT". 
Now the multi-line insert will export from any database.
![2020-11-17 11_44_34-Data Transfer](https://user-images.githubusercontent.com/45152336/99367615-3d7ce700-28cb-11eb-8ac3-429450360740.png)


Most likely, in the future we will change the formatting settings so that users can choose the target base.
like in this ticket https://github.com/dbeaver/dbeaver/issues/1745

**Comment by kseniiaguzeeva** [comment]
The setting is applied only if at least 1 more an additional setting is made for SQL export. Maybe it is a different issue, because actual for CSV and XLS formats too (the ticket for CSV is created: https://github.com/dbeaver/dbeaver/issues/10456). 

Steps:
1. Open export for a table
2. Select SQL and change only Insert keyword
3. Expected: the changes are applied
4. Actual result: the table is exported with default settings

Steps: for CSV:
1. Open export for a table
2. Select SQL and change only quote character
3. Expected: the changes are applied
4. Actual result: the table is exported with default settings

**Comment by kseniiaguzeeva** [comment]
It is difinetely another issue https://github.com/dbeaver/dbeaver/issues/10366

**Comment by kseniiaguzeeva** [comment]
verified
