### ISSUE TITLE
Snowflake: after time out disconnect, keeps opening multiple tabs in browser and does not stop

### ISSUE THREAD

**Issue by sirbard** [dbeaver/dbeaver#10402]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by sirbard** [comment]
OS: ?
Dbeaver: 725

Database: snowflake

Don't know answer to driver to tunnels

Problem and steps: after leaving dbeaver for some time, maybe an hour, it disconnects from snowflake.  problem is when I then try to wake up dbeaver, it then tries to reconnect and goes to browser and opens a new tab.  this is normal as this is how it normally connects, but the problem is it keeps opening new tabs and never stops.  I have to shut down dbeaver for it to stop.

**Comment by GTLangseth** [comment]
I wrote to Snowflake about this issue and found a solution that can be set up server-side: https://docs.snowflake.com/en/user-guide/admin-security-fed-auth-use.html#optional-using-connection-caching-to-minimize-the-number-of-prompts-for-authentication

This enables token caching for the MFA auth. It solved this problem for me because DBeaver can then re-use the auth token from the initial MFA request.

**Comment by sirbard** [comment]
Thank you, GTLangseth!  I'm going to share this, hopefully the admins can make the change.

**Comment by uslss** [comment]
is issue still actual against 23.1.1?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
