### ISSUE TITLE
Support INSERT OR UPDATE on data import

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#10533]
Currently we support only data insert. 
It makes records updating not possible.

We need support of UPDATE/UPSERT statements for all types of data import (from files or from table to table).

**Comment by LonwoLonwo** [comment]
Firebird: https://firebirdsql.org/refdocs/langrefupd21-update-or-insert.html UPDATE OR
MySQL+MariaDB: https://dev.mysql.com/doc/refman/8.0/en/replace.html REPLACE INTO
PostgreSQL - may be ON CONFLICT DO NOTHING at the end helps https://www.postgresql.org/docs/current/sql-insert.html (since 9.5 version)
db2 https://www.ibm.com/support/knowledgecenter/en/SSEPGG_10.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0010873.html
https://stackoverflow.com/questions/330241/does-db2-have-an-insert-or-update-statement
sqlite - https://www.sqlite.org/lang_conflict.html

sqlServer - to difficult https://stackoverflow.com/questions/108403/solutions-for-insert-or-update-on-sql-server

**Comment by LonwoLonwo** [comment]
In the Import Data transfer load settings window, the ability to select the behavior for the case when primary key values are duplicated has been added. 

![2020-12-13 22_12_29-DBeaver 7 3 1](https://user-images.githubusercontent.com/45152336/102021541-7eb0cb80-3d91-11eb-90a7-6c3c932cd173.png)

You can choose to replace or ignore rows with duplicate key values. Or leave the default value - None. 
Below the dropdown list of methods there is a link to [the documentation](https://dbeaver.com/docs/wiki/Data-Import-and-Replace/). 
The list of methods is not available if the target database does not support this feature or we have not implemented it yet.

If you know the syntax suitable for this situation for your database - write to us here, and we will implement it in the future.

**Comment by kseniiaguzeeva** [comment]
Verified. 
Another ticket for import to MySQL with none replace method will be created.
