### ISSUE TITLE
How to use a jdbc uri that's input manually?

### ISSUE THREAD

**Issue by hago** [dbeaver/dbeaver#10550]
#### System information: 
- Operating system (distribution) and version windows 10 2004
- DBeaver version 7.3

#### Connection specification:
- Database name and version
Hive configured with zoo keeper

#### Describe your question:
I tried to connect a hive with zookeeper enabled, using jdbc uri like: jdbc:hive2://node1:port1,node2:port2/db;serviceDiscoverMode=zookeeper;zookeepernamespace=XXX... But I can't find a way to input url like this using new connection dialog. What should I do? thanks

**Comment by SubOptimal** [comment]
Because lacking of a HiveServer2 / Zookeeper installation the following is untested.

- in the database connection dialog click on "Edit Driver Settings"
![Bildschirmfoto vom 2020-11-30 22-54-44](https://user-images.githubusercontent.com/653288/100672231-ec0c3780-3361-11eb-8f58-2523d7bd899e.png)

- in the driver settings dialog amend the URL template
![Bildschirmfoto vom 2020-11-30 23-06-57 2](https://user-images.githubusercontent.com/653288/100672337-165df500-3362-11eb-8f80-d96e75ae642a.png)

- after confirming the driver settings and back in the connection dialog enter the required values
![Bildschirmfoto vom 2020-11-30 23-07-50](https://user-images.githubusercontent.com/653288/100672541-62a93500-3362-11eb-9e3f-7efdc1d86de3.png)

- the JDBC URL looks like your example

**Comment by kseniiaguzeeva** [comment]
Please try to create a new driver (or change the existed one) for URL connection. Go to Database>Driver Manager and make necessary settings
![Screenshot 2020-12-07 at 18 53 21](https://user-images.githubusercontent.com/51405061/101372986-84a03b80-38bd-11eb-8a45-79520c0dd683.png)

Then select this driver to create the connection. The window will change the view:

![Screenshot 2020-12-07 at 18 51 59](https://user-images.githubusercontent.com/51405061/101373102-a13c7380-38bd-11eb-8872-1fd5ec40041e.png)

**Comment by hago** [comment]
It works well! Thank you so much.
