### ISSUE TITLE
Error opening modal window Shift + Enter

### ISSUE THREAD

**Issue by ems2811** [dbeaver/dbeaver#10557]
#### System information: 
- Windows 10 Pro x64
- DBeaver 7.3.0.202011291229
- No additional extensions

#### Connection specification:
- PostgreSQL 9.5
- PostgreSQL JDBC Driver [42.2.5]
- No tunnels or proxies (SSH, SOCKS, etc)

#### Describe the problem you're observing:
Modal does not open when trying to edit text cell (Shift + Enter)

#### Steps to reproduce, if exist:
Run the query below, stand on the code field in query results and press Shift + Enter (id field opens correctly)
```
select *
from(values(1,'123')) t(id, code)
```
#### Include any warning/errors/backtraces from the logs
[error.log](https://github.com/dbeaver/dbeaver/files/5616737/error.log)

**Comment by kseniiaguzeeva** [comment]
I can open both cells. What do we do differently (I can open Edit window by Shift +Enter and by the button from the bottom toolbar)? Please note the cells are in read-only mode from this query because  do not have corresponding table column
![LWUMZnTVXe](https://user-images.githubusercontent.com/51405061/100627168-ba7e7680-3337-11eb-8140-acb75c7a79f9.gif)

**Comment by ems2811** [comment]
![2020-11-30-19-18-32-285](https://user-images.githubusercontent.com/22142845/100635157-39c47800-3341-11eb-890a-3cbf3ed6bd5a.gif)

**Comment by ems2811** [comment]
Doesn't reproduces in version 7.3.1.202012201616
