### ISSUE TITLE
If the second table column is pinned, its row values appear in the column header filter list for the next column

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#10640]
DBeaver 7.3.0
Mac

Steps:
1. Open a table in Data Editor (e.g. MySQL sakila.address)
2. Pin the second column
3. Press filter icon in the column which is the next to the pinned one

Expected: the column values appear in the filter list
Actual result: the values of the pinned column are in the filter list

**Comment by flambchap** [comment]
There is another way to reproduce the same kind of problem.
1. Open DBeaver Sample Database, the table 'Artist'
2. Select some cells from the column 'Name'.
3. Add some cells from the column 'ArtistId' to the selection.
4. Click on the filter icon on the 'Name' column.
5. Distinct filter dialog for column 'ArtistId' opens.

Obviously, it's just a tiny example, the problem is actually a lot bigger, and we can generify it to the following:
1. Select 1 or more cells from 1 or multiple columns.
2. Let's call the column of the last clicked cell _x_. Click on the filter icon on some column _y_, _x_ =/= _y_.
3. Filter dialog for column _x_ opens.

**Comment by flambchap** [comment]
Fixed the general case and, consequently, the original problem.

**Comment by kseniiaguzeeva** [comment]
verified
