### ISSUE TITLE
ANY command denied to user 'root'@'%' for table ''

### ISSUE THREAD

**Issue by cuijiaxu** [dbeaver/dbeaver#10664]
#### System information: 
- windows10
- DBeaver version:7.3.0
- Additional extensions

#### Connection specification:
- Mysql 5.7 
- mysql-connector-java:5.1.44

#### Include any warning/errors/backtraces from the logs

![image](https://user-images.githubusercontent.com/15241705/101884093-2502a280-3bd3-11eb-9a5a-1bfe25569182.png)

**Comment by kseniiaguzeeva** [comment]
Could you check the user's privileges?
![Screenshot 2020-12-14 at 09 39 59](https://user-images.githubusercontent.com/51405061/102048584-7b98f800-3df0-11eb-91f9-b04c9379f798.png)

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with an additional info

**Comment by Maxxiey** [comment]
@cuijiaxu Hi there, I accidently ran into the same issue this day.

The script itself is right, but in order to create a view, you have to decide which database it should belong to, i.e., you have to execute `USE <db name>` first, or this error `ANY command denied to user 'root'@'%' for table ''` will occur.
