### ISSUE TITLE
Export Data data transfer fails to export PostgreSQL geometry columns

### ISSUE THREAD

**Issue by stefanon** [dbeaver/dbeaver#10684]
#### System information: 
- Windows 10
- DBeaver version    7.3.0.202011291229
- Additional extensions

#### Connection specification:
- Database name and version: PostgreSQL 11.10
- Driver name PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? no

#### Describe the problem you're observing:

If I export data tables with Database transfer target from Postgresql 1 to Postgresql 2 server, if the tables have geometry field, the destination tables, created new, have the field with the right name, but the wrong type, becoming varchar type. I need always to create the tables first in the destination, then I can export data in them. 

#### Steps to reproduce, if exist:
exporting a table with geometry type column:
![Immagine 2020-12-14 144045](https://user-images.githubusercontent.com/9317034/102088190-dcd5c100-3e1a-11eb-8000-dc23b08711ad.png)

result in the destination database:
![Immagine 2020-12-14 144320](https://user-images.githubusercontent.com/9317034/102088195-dfd0b180-3e1a-11eb-9049-f3e6d0a2781c.png)

**Comment by kseniiaguzeeva** [comment]
Thank you for the report.

**Comment by LonwoLonwo** [comment]
related https://github.com/dbeaver/dbeaver/issues/6110

**Comment by LonwoLonwo** [comment]
Fixed in 7.3.5

Now we reading PostgreSQL data types differently. 
First for the entire database, and then we distribute according to schemes, and not vice versa, as before. Now in the list of data types when creating columns, procedures or when mapping in datatransfer, a list of all database types will drop out (not just basic + schemas). 
This list includes standard, composite and custom types, does not include array types yet.
But if manipulations are made with a table in which there are array types, then these types are also cached for this session.

**Comment by uslss** [comment]
verified
