### ISSUE TITLE
Table owners not showing in autocomplete

### ISSUE THREAD

**Issue by rjake** [dbeaver/dbeaver#10832]
**Is your feature request related to a problem? Please describe.**
The table owner names don't show up as options in the SQL editor or object browser, it jumps right into table names. If I do type the owner, it then doesn't prompt me for the tables names.

**Describe the solution you'd like**
DBeaver to treat owners the way it treats schemas. I don't have a lot of technical knowledge of how SQL works, hopefully this makes sense.

**Describe alternatives you've considered**
Alternative IDEs. This is the biggest barrier to adoption by my team.

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggestion. Please tell me your database.

**Comment by rjake** [comment]
Netezza

**Comment by LonwoLonwo** [comment]
@rjake Could you give examples of not working queries, please? Better with pictures. 
SQL Editor offers different objects in different situations, so I want more specifics.

**Comment by rjake** [comment]
Yes:
`database.table` -- triggers intellisense but doesn't run
`database.owner.table` -- runs but doesn't trigger intellisense

### Screenshots:
From Aginity (Netezza), there are 3 owners and 1 schema ("ADMIN"):
![image](https://user-images.githubusercontent.com/14003618/104524997-45a48a80-55cd-11eb-88bb-5cf1d748c1de.png)

In DBeaver, it goes right into the table names and doesn't prompt me for the owners.
![image](https://user-images.githubusercontent.com/14003618/104526338-193e3d80-55d0-11eb-99d5-99cfb77a3cfa.png)


We're looking into enabling multiple schemas but as of now, only 1 schema is available and the rest are stored under owners:
https://www.ibm.com/support/knowledgecenter/SSULQD_7.2.1/com.ibm.nz.adm.doc/c_sysadm_netezza_db_schema_overview.html

**Comment by LonwoLonwo** [comment]
@rjake What type of object has "cdw_customer_uat"? We usually suggest the schema name after the directory/database name.
And what do you mean by "Owners"? Users? 
And also, how should the whole valid SQL-query look like? Because it seems that this is a specificity of Netizza, we do not have enough data about it.

**Comment by rjake** [comment]
Thanks for looking into this. `cdw_customer_uat` is a database. Netezza queries go `database.owner.table` and all sits under one schema `"admin"` that isn't used in the address. This idea of schema vs owners seems to have changed in later versions of Netezza so it might not be a universal need across all users with Netezza. The link above has more info about that.

An example query would look like
```sql
select *
from
   cdw_customer_uat.cdw.table_1  t1
   join cdwdev.rjake.table_2     t2 on t2.key = t1.key

**Comment by KrzysztofDusko** [comment]
worth to mention. Netezza have two modes, Schema on or shema off.

**Schema Off**
```sql
SELECT * FROM SOME_DB.RANDOM_WORD.SOME_TABLE
```
RANDOM_WORD  can be 'admin' ("default" schema name), valid owner, (fake = onther existing user) or **whatever else**
from example above completely valid is
```sql
select * from cdw_customer_uat."no such owner".table_1
```
the theory that it can be owner or "admin" coms probably from behavior of one specific application (Aginity Workbench) but it simply not true, middle word is ignored only two dots are necessary.
In my company this syntax (two dots) is way more popular than with middle word
```sql
SELECT * FROM SOME_DB..SOME_TABLE;
select * from cdw_customer_uat..table_1
```
**Schema On**

- SOME_DB.REAL_SCHEMA_NAME.SOME_TABLE - valid
- SOME_DB..SOME_TABLE   - valid
- SOME_DB.TEST_USER.SOME_TABLE - not valid  (leads to ERROR [HY000] ERROR:  Schema 'TEST_USER' does not exist)


My recomedation is
1. Detect with mode is "on" (according to mode autocompelte with schema or not)
2. Database..table - this should always trigger autocomplete ("intellisense")
if 1. is to complicated 
autocomplete with owner on "shema off mode" is OK **only on schema off** but is realy convention only one app.

**Comment by LonwoLonwo** [comment]
Hello @KrzysztofDusko 

Can you help me with few questions?

1. How can we detect schema off mode? I can find any information about it in Netezza system tables/views.

2. I correctly understand that the expression of type 
`SELECT * FROM DATABASE_NAME.SCHEMA_NAME.TABLENAME`
will not work in this mode (enable_schema_dbo_check=0) and the expression 
`SELECT * FROM DATABASE_NAME.OWNER_NAME.TABLENAME`
will not work in this mode (enable_schema_dbo_check=1/2)?

Because our test Netezza database support multiple schemas and I can't read tables, specifying the username in the query.

**Comment by KrzysztofDusko** [comment]
1. Multiple schema support can be enabled/disabled by edit of /nz/data/postgresql.conf file
https://www.ibm.com/docs/en/psfa/7.2.1?topic=overview-enable-multiple-schema-support
my _method_ to decet this is to check SELECT SCHEMA FROM _V_SCHEMA - if only one row is in result ="ADMIN" - multi schema support is off 
2. If Multple schema support is enabled  ```SELECT * FROM DATABASE_NAME.OWNER_NAME.TABLENAME``` - **will not work**
    If Multple schema support is disabled ```SELECT * FROM DATABASE_NAME.OWNER_NAME.TABLENAME``` - **wil work**
    but not only OWNER_NAME.. 
     If Multple schema support is disabled ```SELECT * FROM DATABASE_NAME..TABLENAME``` - **wil work**
     If Multple schema support is disabled ```SELECT * FROM DATABASE_NAME.anything.TABLENAME``` - **wil work**
     If Multple schema support is disabled ```SELECT * FROM DATABASE_NAME.WRONG_OWNER.TABLENAME``` - **wil work**

**Comment by LonwoLonwo** [comment]
So now I am confused.
When Multiple schema support is disabled - all queries work fine. Why do people use Multiple schema support then?

**Comment by KrzysztofDusko** [comment]
1. This is set by default
2. All queries work but you cannot organize tables by topics/business cases etc, 1 namespaces of tables are for 1 db 
 Multiple schema support is disabled = there is only one schema = really means there's no schema functionality = all tables are in one big bag.
Using many schemas in one DB is very common.

**Comment by LonwoLonwo** [comment]
Many thanks for your answers @KrzysztofDusko !

**Comment by LonwoLonwo** [comment]
Since we have support for Netezza users only in the [DBeaver EE version](https://dbeaver.com/), the possibility of an autocomplete for them we added only there.

![2022-01-13 22_14_00-](https://user-images.githubusercontent.com/45152336/149797019-3d873508-5ac9-4f16-b94a-ac02fc9d10b2.png)

![2022-01-13 22_12_34-DBeaver Ultimate 21 3 3 - _TEST_Script-101](https://user-images.githubusercontent.com/45152336/149797063-bad8219e-1b15-4f46-9b49-5c82f6ddfbbe.png)

![2022-01-13 22_13_25-](https://user-images.githubusercontent.com/45152336/149797069-65f6ef4f-2a1a-4179-a809-e9d8c9716d43.png)

Auto-completion will work in these cases:

`SELECT * FROM DATABASE_NAME.(schemas names + owners names)`

`SELECT * FROM DATABASE_NAME.OWNER_NAME.(this owner tables names)`

`SELECT * FROM OWNER_NAME.(this owner tables names)`

Also, the ability to create, rename and delete schemas via UI added ([DBeaver EE version](https://dbeaver.com/)).

![2022-01-14 00_53_03-DBeaver Ultimate 21 3 3 - _TEST_Script-101](https://user-images.githubusercontent.com/45152336/149798764-baf2f8c8-a6a9-4616-89d7-0e96e2935d12.png)

**Comment by Matvey16** [comment]
Verified
