### ISSUE TITLE
Working on Same Workspace File With Many Clients

### ISSUE THREAD

**Issue by emretuna01** [dbeaver/dbeaver#10886]
We want to create "er diagram" using dbeaver with three colleagues. Each of us designed a different module.  We tried working the same workspace file that located on a network and It works but when one of us makes a change, others have to reopen dbeaver client to see changes. 

Is there a way working on the same workspace file and seeing changes instant without reopening dbeaver

**Comment by kseniiaguzeeva** [comment]
Are you in auto-commit mode?
![dbeaver_hgXl43TLDN](https://user-images.githubusercontent.com/51405061/103747387-a05d4580-5013-11eb-85cc-6cb27b84ce08.png)

**Comment by emretuna01** [comment]
if we talk about section that determined red rectangle on the screenshot, yeah me and colleagues in auto-commit mode 

![image](https://user-images.githubusercontent.com/42046428/103747729-237e9b80-5014-11eb-87b2-400fa62f0ac3.png)

**Comment by kseniiaguzeeva** [comment]
It is not necessary to reopen DBeaver to see the changes on the diagram, press F5/Refresh to see them.
However, it is not a good idea when several persons use one workspace, because it can lead to workspace breaking.
Try to use Github for it or at least place the diagram to another folder and link the folder to ER Diagrams folder in DBeaver.
![Screenshot 2021-01-18 at 17 30 55](https://user-images.githubusercontent.com/51405061/104927891-09996d00-59b3-11eb-9b10-fa3c25b7d758.png)

**Comment by emretuna01** [comment]
we tried to working "Link Folder"  to share ER Diagram but when my colleagues connected the "Link Folder"  they saw white screen 

Someone had faced a similar situation here  https://github.com/dbeaver/dbeaver/issues/2440 

![image](https://user-images.githubusercontent.com/42046428/106996255-af115680-6791-11eb-95f5-be02c72a333b.png)

**Comment by kseniiaguzeeva** [comment]
The reason is that every user has his own database configuration with unique id.
![1](https://user-images.githubusercontent.com/51405061/107515536-3446a200-6bbc-11eb-9cc7-e0c82638b9dc.png)
You can:
- share your project in git
- share the file
- copy connection configuration data from the file to other users files 

Here you can find way to project configuration https://github.com/dbeaver/dbeaver/wiki/Workspace-Location

**Comment by emretuna01** [comment]
yeah, as you say it works with git. is it possible to using without git and seeing changes instantly.

Can this be considered as a feature request

**Comment by kseniiaguzeeva** [comment]
You already can do it. You and your collegues have to have the same data-source id. Have you tried to copy it from your file to other users files and then to open the linked diagram?:
![image](https://user-images.githubusercontent.com/51405061/109319660-281b3f80-7860-11eb-886b-f8c1a79562ac.png)

**Comment by uslss** [comment]
import diagram using UI will be implemented in the scope of #8180
