### ISSUE TITLE
Certain timestamps are queried incorrectly from Postgres

### ISSUE THREAD

**Issue by adamsoltesz** [dbeaver/dbeaver#10896]
#### System information: 
-Windows 10 Pro | Version: 20H2 | Build: 19042.685
- DBeaver version: 7.3.2.202101032114
- Additional extensions: No

#### Connection specification:
- Database: PostgreSQL (using Docker image: mdillon/postgis:latest)
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:

In certain cases timestamps are returned incorrectly by queries. 

The issue is only reproducible for specific timestamps, for 99.xx % of the timestamps it works correctly.

This issue also affects export-import functionality. During DB-to-DB import, the process could stop with uniqe key violation issue, due to the incorrectly queried timestamps (the importer tries to insert the same timestamps twice, even if in reality they are not the same, but due to the below detailed issue they queried as the same).

I have verified that the same issue is not reproducible in pgAdmin, so the source of the issue should be DBeaver and not the DB that is used.

#### Steps to reproduce:

Create a new table: 

```
CREATE TABLE public.newtable (
	timestamp_value timestamp(0) NULL
);
```

Insert these rows:

```
insert into newtable values('2040-03-25 02:00:00');
insert into newtable values('2040-03-25 03:00:00');
```

Run query:

```
select nt."timestamp_value" from newtable nt where "timestamp_value" between '2040-03-25 02:00:00' and '2040-03-25 03:00:00'; 
```

Observe what is returned:

```
2040-03-25 02:00:00
2040-03-25 02:00:00
```

They should not be the same. 

Using a different select, they show correctly:

```
select to_char(nt."timestamp_value", 'YYYY-MM-DD HH:MI:SS:US') from newtable nt where "timestamp_value" between '2040-03-25 02:00:00' and '2040-03-25 03:00:00';
```
Shows: 

```
2040-03-25 02:00:00:000000
2040-03-25 03:00:00:000000
```

**Comment by kseniiaguzeeva** [comment]
Cannot reproduce. Is it possible to send a screenshot with settings Data Editor>Data Formats?
![dbeaver_DHCQQXiYQA](https://user-images.githubusercontent.com/51405061/103984625-826d1d80-5198-11eb-8965-516b17d0c7e1.png)

**Comment by adamsoltesz** [comment]
I am using the default settings, which are: 
![Screenshot_15](https://user-images.githubusercontent.com/3513726/103984859-30240080-5188-11eb-9697-9f3f94cf0ac7.jpg)

**Comment by kseniiaguzeeva** [comment]
Please click Global settings in the right top corner. Are they the same?

**Comment by adamsoltesz** [comment]
Yes they are the same.

Also, if I turn on "Disable date/time formatting" as it is on your screenshot, then the issue goes away on my machine as well.

**Comment by kseniiaguzeeva** [comment]
You found the answer without my help). This setting allows to use default server settings and the application shows the time like pgAdmin.

**Comment by kseniiaguzeeva** [comment]
Please ask to reopen the ticket if your issue is not solved completely.

**Comment by adamsoltesz** [comment]
@kseniiaguzeeva Are you sure this is not a bug? I think that this behaviour with the dates is not correct, regardless of the settings.

**Comment by kseniiaguzeeva** [comment]
You are right, but I cannot reproduce it. Please tell your timezone and locale (it is written in the bottom toolbar)
![dbeaver_OSTCDQDC5O](https://user-images.githubusercontent.com/51405061/106104450-81099200-6153-11eb-846f-39a88956efb7.png)

**Comment by adamsoltesz** [comment]
Hi @kseniiaguzeeva ! It is "CET" and "en".

**Comment by kseniiaguzeeva** [comment]
Unfortunately, I still cannot reproduce. Does it fail with 2040 year only? What will you receive with the current year?

**Comment by uslss** [comment]
There is no update on an issue for a long time.
If it is still actual for you - feel free to reopen an issue.

**Comment by RobbieAuld-edf** [comment]
@uslss , I agree with @adamsoltesz that this is a bug with the timezone converter and the fact that you have to turn it off to get the correct times in native format is testament to that. I can reproduce it using the Europe/London timezone. I connect to a database in which the dates and times have been written as UTC dates and times, and stored as timestamps with no timezone. If the _Use native date/time format_ is switched on 

![image](https://user-images.githubusercontent.com/61539242/126295415-a01891b1-1ade-4cf0-ad22-4893adbd4957.png)

I get the following result for a half-hourly time series which is correct for UTC:

![image](https://user-images.githubusercontent.com/61539242/126291455-72578d0a-0b06-404f-81f1-46de9da316ef.png)

If I now switch off  _Use native date/time format_ and reconnect I get the following result for the same data:

![image](https://user-images.githubusercontent.com/61539242/126291159-82c80424-8c34-4664-b0ae-d9ba57f7f369.png)

This is not the correct behaviour for "Europe/London". The correct behaviour is that the hour 1-2am doesn't exist on the last Sunday of March every year. The repeated hour 2-3am is **wrong**.

Please re-open the issue.

Client OS: Win10
DBeaver: 6.3.3.202001191557
![image](https://user-images.githubusercontent.com/61539242/126293783-bef7a3f5-61f8-4782-ab14-4da31f03fd3f.png)

I wonder if this might be an issue with the conversion of times between linux and Windows due to different time standards? Might be something to test.

**Comment by E1izabeth** [comment]
Can't reproduce on the latest DBeaver version.

![image](https://github.com/dbeaver/dbeaver/assets/28875055/a8298009-562a-469c-b648-6a48cbf30f6f)
![image](https://github.com/dbeaver/dbeaver/assets/28875055/eb670557-f110-4b6f-8128-726101f78172)


Please let me know if the issue is still here.
