### ISSUE TITLE
Schema cannot be changed in SQL Editor top toolbar

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#11010]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 7.3.3 EA

#### Connection specification:
- Database name and version Informix

#### Steps to reproduce, if exist:
1. Open SQL Editor and press Ctrl+0
2. Select database and schema in the opened window
3. Execute a query

**Expected**: the query is executed or an error appears if the object is not found in the database
**Actual result**: the error appears in the ResultSet: "SQL Error [IX000]: Database not selected yet."

**Comment by sjivan** [comment]
I'm seeing this even with Postgres

**Comment by LonwoLonwo** [comment]
Informix is a special base. We cannot change the database in the connection, because it requires a separate connection. And we cannot make a scheme of default, because in the Informix scheme - this is the user who gave the rights to these objects. 
Therefore, when trying to choose a default scheme, nothing will happen now.
