### ISSUE TITLE
SQL column value auto-completion bug

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#11379]
When we query column values to fill auto-complete proposals:
- Quotes sometimes inserted incorrectly
- We must respect spaces inside values
- Auto-complete doesn't work when quote char is not present
- Auto-complete doesn't work inside strings (inside single quotes)

Sample: `SELECT from table where column1 like <ctrl+space>`.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/112994271-bdb53200-9172-11eb-82ba-07169b6c49d3.png)
![image](https://user-images.githubusercontent.com/6398845/112994320-cc9be480-9172-11eb-9304-770166030a5d.png)
![image](https://user-images.githubusercontent.com/6398845/112994402-dfaeb480-9172-11eb-925a-ff0799d808ba.png)

**Comment by kseniiaguzeeva** [comment]
1. Auto-assist doesn't show integer values out of the first limited batch.
https://user-images.githubusercontent.com/51405061/113176784-879cae80-9255-11eb-9372-a0868955d210.mp4

2. Auto-assist list jumps to its beginning when you scroll to its end
https://user-images.githubusercontent.com/51405061/113176926-aa2ec780-9255-11eb-876b-49de6787e428.mp4

3. Auto-assist shows a column value out of the first limited batch only  where there are not matches in the list
 https://user-images.githubusercontent.com/51405061/113175898-9b93e080-9254-11eb-8e3f-60c878f4960d.mp4

4. Auto-assist begins to show table columns instead of column values when you open Auto-assist list for a parsed value and delete its letter.
https://user-images.githubusercontent.com/51405061/113179819-afd9dc80-9258-11eb-9ce3-3ed02a170cd9.mp4

**Comment by hilti42** [comment]
Hi serge-rider,
the problem is that the tablename has spaces in the name. As following statement:
select * from [Cronus GmbH$KinoTech LotNo Entry] as T1

![image](https://user-images.githubusercontent.com/81740644/113259369-565fc500-92cd-11eb-8314-4c89f2b1e220.png)

if i have a table without spaces in the name it working fine.

Here an working statement:

select from Actsafe$Bin

![image](https://user-images.githubusercontent.com/81740644/113259399-5d86d300-92cd-11eb-9dbe-d3b20da44ee3.png)

I hope its help to fix this topic

**Comment by serge-rider** [comment]
@hilti42 this is another issue (see #10858)

**Comment by serge-rider** [comment]
@kseniiaguzeeva let's create another ticket for that minor issues.
Also I think we need to show more detailed information in the details popup (e.g. full list of columns/values).

**Comment by kseniiaguzeeva** [comment]
Ok
