### ISSUE TITLE
Use multi-row INSERTs in data transfer

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#11425]
We need this to speedup data load.
Currently it works terribly slow on some platforms like Redshift.
Using multi-row batches may increase performance dramatically.

**Comment by deepaksenthilkumar** [comment]
Is this planned for Monday's release team?

**Comment by LonwoLonwo** [comment]
Nope, sorry @deepaksenthilkumar 
It will be implemented in the 21.1.4 release (02 August).
Now runs the testing stage.

**Comment by LonwoLonwo** [comment]
We added the ability to use a multi-row insert with data import for better performance. You can turn it on on the data transfer settings page:

![2021-07-21 14_24_57-DBeaver Enterprise 21 1 3 - mood_data](https://user-images.githubusercontent.com/45152336/126481368-6f23b0ca-d8fd-490b-876b-d1faeccef11a.png)

It is the database-specific feature because not all databases support multi-row insert syntax like:

```sql
INSERT INTO table_name (column1, column2) VALUES
         (1,'First'),
	 (2,'Second'),
	 (3,'Third');
```

So it works with: 
- PostgreSQL
- Redshift
- Greenplum
- Cockroach
- MySQL/MariaDB
- SQLServer
- SQLite
- DB2
- Exasol

You can't use a multi-row insert with the "Disable batches" setting.

**Comment by deepaksenthilkumar** [comment]
Thanks @LonwoLonwo. Which version of DBeaver has this functionality. Is there an early build that we can use now?

**Comment by LonwoLonwo** [comment]
Hello @deepaksenthilkumar 
The current early version doesn't contain this feature, maybe a few days later it will be updated. You can check it here: https://dbeaver.io/files/ea/ (Release date must be at least 21.07)

**Comment by Matvey16** [comment]
Some inconsistency in the UI, checkbox becomes available after returning with **Back** button

![uljX5oXwdb](https://user-images.githubusercontent.com/82543000/126604303-fb4d771d-db15-41a6-b76d-6782dd47aee5.gif)

**Comment by LonwoLonwo** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified

**Comment by deepaksenthilkumar** [comment]
We built this from the developer branch and I tried to import an excel file with 1.5 Million records and 3 columns (for Redshift)

col1 varchar(180)
loaddate varchar(18)
cnt (int4)

In 26 minutes, it only imported 30k records, while it is faster than a single row insert, it is still relatively very slow.

**Comment by deepaksenthilkumar** [comment]
@LonwoLonwo I checked further and noticed the problem is in the Redshift JDBC Driver class PGEscaper which becomes exponentially slow with the number of question marks in the INSERT statement. I made a couple of crude changes (just to confirm that) and noticed now I am able to insert 1M records in 8 mins. (with a setting of 10k multi-row insert batch size and commit after 10k records)

In ExecuteInsertBatchImpl hardcode the string (should handle it better)
StringBuilder prepareQueryForStatement
if (valueHandler instanceof DBDValueBinder) {
				valuesPart.append(((DBDValueBinder) valueHandler).makeQueryBind(attribute, attributeValues[i]));
			} else if (useMultiRowInsert) {
				valuesPart.append(attributeValues[i] == null ? null : "'" + attributeValues[i].toString() + "'");
			} else {
				valuesPart.append("?"); //$NON-NLS-1$
			}

Avoided binding in ExecuteBatchWithMultipleInsert:
    private void bindAndFlushStatement(DBDValueHandler[] handlers, DBCStatistics statistics, DBCStatement batchStatement, Object[] allMultiInsertValues) throws DBCException {
        statistics.setQueryText(batchStatement.getQueryString());
        statistics.addStatementsCount();
        if(batchStatement.getQueryString().contains("?")) {
        	bindStatement(handlers, batchStatement, allMultiInsertValues);
        }
        batchStatement.addToBatch();
        flushBatch(statistics, batchStatement);
    }

Any suggestion on how we make this fix proper would be helpful. Thanks for your help in introducing this feature.

**Comment by deepaksenthilkumar** [comment]
Will implement PostgreValueHandlerProvider for Redshift and handle it accordingly.
