### ISSUE TITLE
Change default queries for backup/restore

### ISSUE THREAD

**Issue by ppcamp** [dbeaver/dbeaver#11478]
When I've tried to use dbeaver to backup my remote server, and then, restore it in my local machine, I've found an error:

This is the default query executed when I've tried to backup my server:
```bash
# Didn't work
pg_dump \
  --verbose --host=127.0.0.1 --port=5433 --username=postgres \
  --format=p --encoding=UTF-8 -n public pmi
```

However, for some reason, it fails when I've tried to restore it.

In my local test, I noticed that the problem was caused by the param `-n public`, i.e, when I execute the same instruction, without passing `-n public`, the dbeaver can execute the query successfully.
```bash
pg_dump \
  --verbose --host=127.0.0.1 --port=5433 --username=postgres \
  --format=p --encoding=UTF-8 -W pmi > db.sql
```

I wanna know if there's some config hidden in Dbeaver that i can change to make it works, some config file, or something like that.

**Comment by flambchap** [comment]
Hello @ppcamp. It's quite strange that the `-n` flag causes problems, seems more like a bug. Could you please tell me which version of PostgreSQL you use and your OS, and what kind of error DBeaver shows when it fails to restore the database? Thank you.

**Comment by ppcamp** [comment]
Hi @akilovich , what's up? Sorry about the mistake when I was putting the flags. In fact, given the origin of the problem, I thought that it shouldn't be there.

---

- OS: _Kubuntu 20.10; 5.8.0-44-generic #50-Ubuntu SMP Tue Feb 9 06:29:41 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux_
- Remote OS:  _Ubuntu 20.04; 5.4.0-52-generic #57-Ubuntu SMP Thu Oct 15 10:57:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux_

<br/>

- Local Postgres (Running over docker): _PostgreSQL 12.5 (Debian 12.5-1.pgdg100+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 8.3.0-6) 8.3.0, 64-bit_
- Remote Postgres (Connecting over ssh tunneling): _PostgreSQL 12.6 (Ubuntu 12.6-0ubuntu0.20.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0, 64-bit_

---

1. Using "Plain" in backup format:
When I backup with flag `-n public` (dbeaver approach), and try to restore it using the option `Execute script`, it freezes, forcing me to stop the execution, throwing the following log:
<pre>
ALTER TABLE

Task 'PostgreSQL script' finished at Thu Feb 25 11:02:08 BRT 2021
2021-02-25 11:02:09.070 - IO error: Process failed (exit code = 143). See error log.
2021-02-25 11:02:09.072 - java.io.IOException: Process failed (exit code = 143). See error log.
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.validateErrorCode(AbstractNativeToolHandler.java:214)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:194)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:254)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:60)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:122)
</pre>

2. Using "Directory" format:
In this approach, dbeaver will use pg_restore, and when doing so, it throws:
<pre>
pg_restore: warning: errors ignored on restore: 445

Task 'PostgreSQL restore' finished at Thu Feb 25 11:05:18 BRT 2021
</pre>
Which do not restore it.

---

Dbeaver version: 7.3.5.202102141704

> Obs.: Like I said before, if i make a backup manually and run it (using the same psql client version and without `-n public`), it run successfully.
> Obs<sup>2</sup>: The error occurs using flatpak and *deb versions.

**Comment by JamesInform** [comment]
That seems to be the misconception that a plain backup (setting pg_dump --format=p) can be restored with pg_restore. But it isn't. The parameter "--format=p"  generates a plain sql script that you need to execute using the psql command line client instead of pg_restore.

So as a workaround, if you want to restore your backup, you can use DBeaver's execute sql script functionality:

![image](https://user-images.githubusercontent.com/38714600/109463342-22427b80-7a65-11eb-8e53-a461d69500c4.png)

 The fix on DBeaver's side would be to trigger psql instead of pg_restore, if a plain backup is to be restored.

Hope this helps!

**Comment by charlieblevins** [comment]
Hello, I just figured out why this happens and wanted to provide the info here in case it helps whomever is going to write the fix.

The issue is that when specifying a schema (using `-n` as mentioned above) pg_dump will _not_ dump all objects. For me the issue happened because I had a few extensions installed. The restore would fail because I was referencing those extension's types within tables in the public schema. This caused errors. I found this SO issue which led me to the problem (see number 3): https://stackoverflow.com/questions/44442248/pg-dump-does-not-write-create-extension-postgis

**Comment by ppcamp** [comment]
@charlieblevins 
Ah! So, the whole problem was because I was using uuidv4. Indeed, I didn't think about it. Thanks a lot!

**Comment by LonwoLonwo** [comment]
Hello @ppcamp 

To avoid the -n flag, you can use pg_dumpall - the "Global Backup".

![2023-09-11 19_19_54-Window](https://github.com/dbeaver/dbeaver/assets/45152336/48646017-b867-4ca9-a751-9300d7ed6fa5)

Please let me know if it helps.

**Comment by ppcamp** [comment]
Hey @LonwoLonwo , probably it'll help. I think that this is a new feature introduced after that time that I've openned this issue (2 years ago). Therefore, I'm closing this. Although, thanks for the tip 😊
