### ISSUE TITLE
Unknown variable 'column-statistics=0'

### ISSUE THREAD

**Issue by matthijs-va** [dbeaver/dbeaver#11562]
#### System information: 
- Ubuntu 20.04.2 LTS
- DBeaver 21.0.0
- mysqldump  Ver 10.19 Distrib 10.5.9-MariaDB, for debian-linux-gnu (x86_64)

#### Connection specification:
- mysql  Ver 15.1 Distrib 10.5.9-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
- MariaDB Java Client 2.4.3

#### Describe the problem you're observing:

Whenever I try to dump a local or remote database I get following error:
```
/usr/bin/mysqldump --column-statistics=0 --routines --add-drop-table --disable-keys (...)
Task 'MySQL dump' started at Mon Mar 01 21:13:58 CET 2021
/usr/bin/mysqldump: unknown variable 'column-statistics=0'
```

I guess the version check in dbeaver/dbeaver#11444 doesn't properly detect MariaDB. Is there a way to prevent this option from being added?

**Comment by DavidRotert** [comment]
Same problem here on Manjaro with mysqldump (package maraidb-clients) 10.19. I think line 87 in plugins/org.jkiss.dbeaver.ext.mysql/src/org/jkiss/dbeaver/ext/mysql/tasks/MySQLDatabaseExportHandler.java is the problem. It only checks if mysqldump major version is >= 8. Maybe it should also check if the distribution is MariaDB so the option is not added because of the different MariaDB Version 10.x?

**Comment by flambchap** [comment]
Yep, you guys are right about the cause. Sorry for that, I will fix that soon.

**Comment by flambchap** [comment]
Fixed.

**Comment by simongcc** [comment]
@akilovich Hello! I am using MacOS version, did the fix already launched to the binary or need to wait for the launch?

Reference:
DBeaver Version 21.0.0.202103021012
MacOS Mojave 10.14.6
Local Client 10.5.8-MariaDB Homebrew
Remote DB MariaDB 10.x.x

**Comment by flambchap** [comment]
Hello, @simongcc. The fix will be available in the next version (21.0.1).

**Comment by simongcc** [comment]
@akilovich Thanks for the efforts!

**Comment by uslss** [comment]
verified
