### ISSUE TITLE
CSV file date format is not recognised as set in driver properties - default is used

### ISSUE THREAD

**Issue by r0bis** [dbeaver/dbeaver#11612]
#### System information: 
- Operating system:  WINDOWS 10 Latest
- DBeaver version: 21.0.0.202103021012
- Additional extensions: none

#### Connection specification:
- Database name and version: Flat Files / CSV
- Driver name: Flat files / CSV

#### Describe the problem you're observing:
I have data file where date is in dd/MM/yyyy format; dbeaver default format is yyyy-MM-dd
I created 2 test tables and connected to dbeaver (both files in same directory):
**caseload2**
```
"CreatedDate","ClientID"
01/08/1971,127207
02/04/1966,1443709
03/02/1969,144759
08/02/1987,1111932
19/01/1969,116062
```
and 
**caseload1**
```
"CreatedDate","ClientID"
1971-08-01,127207
1966-04-02,1443709
1969-02-03,144759
1987-02-08,1111932
1969-12-19,116062
```
I have specified column types and date format in driver properties:
dateFormat: dd/MM/yyyy
charset: UTF-8
columnTypes: date/integer
fileExtension: .csv

above are the only bold/non-default changes to driver properties.

CreatedDate is not read at all from caseload2
CreatedDate is read from caseload1 even though I have specified other format (with slashes) in driver properties.

#### Steps to reproduce, if exist:
e.g. make above 2 CSV files, make CSV connection to the directory and run:
```
select MAX(CreatedDate) 
FROM caseload2 
;
MAX([CreatedDate])|
------------------|
                  |
```
and
```
select MAX(CreatedDate) 
FROM caseload1 
;
MAX([CreatedDate])|
------------------|
        1987-02-08|
```

#### Include any warning/errors/backtraces from the logs
No errors are produced in logs.

**Comment by uslss** [comment]
seems it is driver-specific issue

**Comment by r0bis** [comment]
OK, thanks I will try to create a bug report or open a discussion about this on https://sourceforge.net/p/csvjdbc/

**Comment by simoc** [comment]
The SQL queries listed in this issue work correctly for me using DBeaver 21.0.1.202103211229 on Windows 10.

The SQL queries also worked correctly for me using CsvJdbc directly in a Java test program.

In the DBeaver Driver properties tab under Connection Settings, I added dateFormat dd/MM/yyyy to the User Properties list, like in the screenshot below.

![dbeaver-connection-settings-user-properties](https://user-images.githubusercontent.com/1910647/112733465-88c19900-8f40-11eb-9462-68c4cfd97b04.png)

It is also possible to edit dateFormat directly under Driver properties, like in the screenshot below. When I do this, the SQL queries do not work, because DBeaver does not pass the dateFormat dd/MM/yyyy property down to CsvJdbc. Could this be the problem?

![dbeaver-connection-settings-driver-properties](https://user-images.githubusercontent.com/1910647/112733471-8f501080-8f40-11eb-842c-3c54039db1a9.png)

**Comment by r0bis** [comment]
Interesting, thanks very much for this information; I only ever adjusted driver properties (it just seemed that if it is set there, it is what the driver should use), I never set User Properties; I will try to do this tomorrow. If that is the culprit, then it seems it is DBeaver side bug, perhaps?

**Comment by r0bis** [comment]
Yes, I verified - it works if there is **User Property** set for the **dateFormat**. It is however a bit confusing and I am not sure if that is the intended behaviour. Essentially what happens is that **dateFormat** is ignored  if set as @simoc described before the 2nd screenshot: "It is also possible to edit dateFormat directly under Driver properties, like in the screenshot below. When I do this, the SQL queries do not work, because DBeaver does not pass the dateFormat dd/MM/yyyy property down to CsvJdbc. Could this be the problem?"

**Comment by simoc** [comment]
I added some debug messages to CsvJdbc, so I can see exactly which driver properties are passed.

DBeaver is passing driver property " dateFormat" with a leading space, so CsvJdbc does not recognise it. The other driver properties ("charset", "columnTypes", "fileExtension", etc.) are passed correctly. User properties are also passed correctly.

I searched the DBeaver source code and found this line in file `/plugins/org.jkiss.dbeaver.ext.generic/plugin.xml` that explains the error.

    <parameter name="driver-properties" value="charset,columnTypes,[...many properties...],timestampFormat, timeFormat, dateFormat,timeZoneName,trimHeaders,trimValues"/>

You can see this problem in my "Connection settings" screenshots above. The labels "dateFormat" and "timeFormat" under Driver properties are shifted slightly further to the right than other driver properties because these two driver properties have a leading space.

**Comment by r0bis** [comment]
Many thanks @simoc; this was not a third party issue; hopefully this can be merged soon @uslss. Thanks for  great software; it can very useful to be able to query CSV files with SQL.

**Comment by uslss** [comment]
verified
