### ISSUE TITLE
SQL Server: put GO delimiter on separate line

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#11675]
We should place GO delimiters on a separate line (now we add them in generated SQL at the end of line).

**Comment by serge-rider** [comment]
Or, perhaps, we should use semicolon always.

**Comment by serge-rider** [comment]
Also see #1482

**Comment by LonwoLonwo** [comment]
Now default delimiter for all databases including SQL Server is semicolon (";").
This means that in the generated statements for the SQLServer we now use ";" instead of "GO." Including Merge.

You can partially change this behavior in the preferences.
Preferences -> Editors -> SQL Editor -> SQL Processing

Replace the semicolon in the "Statements delimiter" field on the desired separator and turn on the setting "Ignore native delimiter"

![2021-03-30 09_00_18-Preferences](https://user-images.githubusercontent.com/45152336/112941061-b112e880-9136-11eb-855e-66f24deb7447.png)

**Comment by uslss** [comment]
verified
