### ISSUE TITLE
Scroll down or up using mouse wheel in the list of databases displayed in connection menu

### ISSUE THREAD

**Issue by PerfKeeper** [dbeaver/dbeaver#11974]
**Is your feature request related to a problem? Please describe.**

Hi
I'm always frustrated when selecting a database from the list of databases displayed in connection menu (see picture below)...

**Describe the solution you'd like**
Just offer mouse wheel scrolling down / up inside this list please,

Thanks in advance.
Best regards

*Additional context**

![Screenshot 2021-04-02 122746](https://user-images.githubusercontent.com/35118911/113408085-fb9e9a00-93ae-11eb-9d55-06888fa3e774.png)

**Comment by uslss** [comment]
thanks for suggestion

**Comment by ShadelessFox** [comment]
Hello @PerfKeeper,

Unfortunately, it's not possible. This is a native Windows component and, as far as I know, it does not support scrolling.

Instead of using drop-down menu, you can simply click on the button and popup will appear:
![image](https://user-images.githubusercontent.com/35821147/119982563-ac986e00-bfc7-11eb-9b27-522826926fb7.png)

Similar issue: #11785
