### ISSUE TITLE
Support for DuckDb

### ISSUE THREAD

**Issue by travis-leith** [dbeaver/dbeaver#12068]
**Is your feature request related to a problem? Please describe.**
I would like to be able to query a [DuckDB ](https://duckdb.org/)file

**Describe the solution you'd like**
Add a connector for [DuckDB](https://duckdb.org/)

**Describe alternatives you've considered**
There are no alternatives

**Additional context**
DuckDB is like the OLAP version of Sqlite.

**Comment by serge-rider** [comment]
Java API (JDBC) - https://duckdb.org/docs/api/java

**Comment by serge-rider** [comment]
Done.
Known issues: JDBC driver doesn't perform database shutdown on disconnect. Thus database file remains locked for some time after disconnect.
DBeaver restart or explicit garbage collection helps.

**Comment by travis-leith** [comment]
For the duckdb R package, when disconnecting you have to explicitly set `shutdown = TRUE`. Not sure if that helps. I will raise an issue on the duckdb repo about this.

**Comment by uslss** [comment]
reopened.
Newly created objects are not visible until node refresh. Also, dbeaver switches to manual commit even if auto-commit is enabled in preferences
![2021-04-28_11h57_21](https://user-images.githubusercontent.com/31996417/116376731-331b2d80-a819-11eb-9c15-ba8d21e31799.gif)

**Comment by serge-rider** [comment]
@travis-leith unfortunately this is not supported in Java driver. 

@uslss this caused by loosy JDBC API support in DuckDB driver. Table is created in mixed case (as driver says it uses mixed case). But in fact it is then converted into lower case. And the dbeaver can't find this table when tries to re-read metadata. 

Creating tables in lower case helps.
Metadata refresh helps.

**Comment by travis-leith** [comment]
Ok, I will report back to the DuckDb repo

**Comment by uslss** [comment]
verified
