### ISSUE TITLE
Support types containing modifiers in their names in UI

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12142]
#### System information: 
- DBeaver version 21.0.3

#### Connection specification:
- Database name and version PostgreSQL GIS

#### Describe the problem you're observing:
Users can create only simple geometry type via UI now. We should add mixed-typed collection support too like `CREATE TABLE pois_ny(gid SERIAL PRIMARY KEY, poi_name text, cat text, geom geometry(POINT,4326));`
https://postgis.net/docs/using_postgis_dbmanagement.html

**Comment by ShadelessFox** [comment]
We should allow type modifiers in the metadata editor to allow creating attributes with signature like `geometry(POINT,4326)`. That's because in case of postgres we forbid entering any type but predefined.

**Comment by ShadelessFox** [comment]
Implemented for the following types:
* `geometry` (`geometry(point, 4326)`)
* `decimal` (`decimal(10)`, `decimal(10, 5)`)
* `interval` (`interval(3)`, `interval day to second(6)`)

Precision and scale columns are gone since they are embedded in type type's name itself.

You will need to test:
1. Viewing types
   1. Including user-defined types (which use these types as a base type)
   1. Type aliases which point to these types
1. Viewing DDL
1. Editing types (same as above)
1. Data transfer (from/to postgres)

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
Two more improvements needed:
#12883
#12882
