### ISSUE TITLE
SQL Editor is opened with default schema only via DB Navigator (where databases and schemas exist)

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12145]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.0.3

#### Steps to reproduce, if exist:
1. Expand a database in DB Navigator
2. Click any schema except default
3. Press SQL button on the top toolbar

**Expected:** SQL Editor is opened for the selected schema
**Actual result:** SQL Editor is opened for a default schema

PostgreSQL, Greeplum were tested.
https://user-images.githubusercontent.com/51405061/115201282-d7a4bd80-a0fd-11eb-8293-3fbb0059f720.mp4

**Comment by flambchap** [comment]
The original issue is gone. However, there is another one that is kind of connected. Suppose we connect to MSSQL database X and schema Y. Then we try to open script for database X' schema Y'. We shouldn't be able to do that since MSSQL does not support schema change. Indeed, when we open a script and execute 
```sql
SELECT DB_NAME(), SCHEMA_NAME();
```
, we see `X'.Y`. But schema selector lies to us and says `X'.Y'`.

**Comment by flambchap** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified
