### ISSUE TITLE
MSSQL temp table autocomple not work

### ISSUE THREAD

**Issue by wvolkov** [dbeaver/dbeaver#12182]
**System information:**
Operating system (distribution) and version: Windows 10 OS Build 2104 
DBeaver version: 21.0.3
Java version "1.8.0_191"
No Additional extensions

Describe the problem you're observing:
Column hints (a.k.a intellisence or autocomplete) doesn't work with MS-SQL temp tables.

**Steps to reproduce:**
1. Create a temp table
```sql
select 1 as col1, 'a' as col2
into #temp
```
2. invoke "column hint" via table alias:
```sql
select
           t. -- <- col1, col2 should appear
from #temp t
```
**Actual behavior:**
Column hint doesn't appear.
![image](https://user-images.githubusercontent.com/49549154/115427892-87675180-a20a-11eb-9e35-fd454f9ac100.png)

**Workaround:**
Type full-qualified name to a temp table:
```sql
select t. -- <- col1, col2 are shown
from tempdb.dbo.[#test_______________________________________________________________________________________________________________000000001C52] t
```
![image](https://user-images.githubusercontent.com/49549154/115428078-b251a580-a20a-11eb-8b6e-a4d2d5cfb01d.png)

**Comment by uslss** [comment]
thanks for the report

**Comment by ShadelessFox** [comment]
FYI `#temp` and `#test___...___000000001C52` are not the same names.

We can improve proposal analyzer, so it will lookup tables ~without this madness-looking hash at the end~ from `tempdb`.

**Comment by ShadelessFox** [comment]
After further investigation, it seems to be impossible to implement.

The problem is that we can't determine whether a given table is owned by current session, unfortunately. It is important because you can't access temporary tables created by other sessions.

In addition, several sessions may create table with single name, resulting in a mess like that:
![AnyDesk_6NTP8FRdYc](https://user-images.githubusercontent.com/35821147/123651377-16f53600-d834-11eb-9054-6ceed51e4e57.png)

**Comment by ShadelessFox** [comment]
Implemented:

![java_zBTC9e0z1M](https://user-images.githubusercontent.com/35821147/123681537-9f82cf00-d852-11eb-9b63-e8804eb623f2.png)

**Comment by Matvey16** [comment]
Need to include global temporary tables in search

**Comment by Matvey16** [comment]
Verified
