### ISSUE TITLE
Word Wrap NOT working in Editor. (Script Window)

### ISSUE THREAD

**Issue by techlock77** [dbeaver/dbeaver#12201]
Instead of going to the next line, editor is still using the same line even though words no longer fit on the same line.

![image](https://user-images.githubusercontent.com/66756251/115569347-23d13880-a28b-11eb-8763-6727841d40a3.png)

**Comment by uslss** [comment]
@techlock77 cannot reproduce it (gif attached). Probably some special steps are needed? what dbeaver version and OS do you use?
![2021-04-22_11h58_39](https://user-images.githubusercontent.com/31996417/115686802-41bd9c80-a362-11eb-993d-edd171061b6a.gif)

**Comment by techlock77** [comment]
After selecting "toggle word wrap" its working now! 

Somehow, it wasn't working earlier, evenafter having "folding enabled" tick marked under Window>Preferences>Editors>SQL Editor>Code Editor.

![image](https://user-images.githubusercontent.com/66756251/115728141-3d898300-a352-11eb-8aff-c722d911c436.png)

**Comment by techlock77** [comment]
Resolved!

**Comment by gitressa** [comment]
Thanks for the GIF, I couldn't find the place to toggle Word Wrap (Right click in the editor > "Format" > "Toggle Word Wrap") or the shortcut `Shift + Ctrl + Alt + W`.

Could Word Wrap be enabled by default, so that you have to actively disable it? It seems to me the preferred default state would be wrapping the lines ...
