### ISSUE TITLE
Sybase IQ. Double dash comment is not highlighted if not started at the beginning of the line

### ISSUE THREAD

**Issue by zolovey** [dbeaver/dbeaver#12206]
#### System information: 
- Windows 10 1909
- DBeaver version: 21.0.3

#### Connection specification:
- SAP IQ/16.1.040.1549
- jConnect

Double dash comment is not highlighted if not started at the beginning of the line

**Comment by LonwoLonwo** [comment]
Hello @zolovey 
Can you provide some examples please?

Or, may be, you are talking about case 4 from the image, where there is no space after double dash? In this case this is expected behavior.

![2021-04-22 10_53_51-DBeaver Enterprise 21 0 3 - _none_ Script-44](https://user-images.githubusercontent.com/45152336/115677578-4a5da500-a359-11eb-887c-3db936b49c4e.png)

**Comment by zolovey** [comment]
@LonwoLonwo but it is not necessary to put space after dash.

at least in SQL92 there is no such requirement, as as well in Sybase IQ

From documentation:
-- (Double hyphen) The database server ignores any remaining characters on the line. This is the SQL92 comment indicator.

**Comment by LonwoLonwo** [comment]
Ok, it sounds convincing.

**Comment by LonwoLonwo** [comment]
Fixed in DBeaver 21.0.4

**Comment by uslss** [comment]
verified
