### ISSUE TITLE
Elastic Search Connection 

### ISSUE THREAD

**Issue by gopalchauhanji** [dbeaver/dbeaver#12385]
0

I am trying to connect Elastic search DB from dbeaver which is SSL secured.

While connecting I get below error. Not sure how to connect to Elastic from dbeaver. Any help will be appriciated.

Unexpected driver error occurred while connecting to the database Cannot POST address https://XXXXXX:9200/?error_trace (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) Cannot POST address https://XXXXXX:9200/?error_trace (PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target) PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target unable to find valid certification path to requested target unable to find valid certification path to requested target

Thanks, Gopal

**Comment by DariaMarkaryan** [comment]
Usually this error occurs due to problems with the certificate itself and the JVM configuration. Maybe this stackoverflow discussion will help you create a connection:
https://stackoverflow.com/questions/9210514/unable-to-find-valid-certification-path-to-requested-target-error-even-after-c
And please give us response if everything worked out well or the problem remain

**Comment by uslss** [comment]
there is no update on the issue for a long time.
If it is still actual for you - feel free to reopen it with additional info
