### ISSUE TITLE
DBeaver 21.0.4: Not all columns showing in DB Navigation Pane/Generated SQL - View

### ISSUE THREAD

**Issue by Cwest99** [dbeaver/dbeaver#12396]
#### System information: 
- Operating system: Windows 10 v1909
- DBeaver version: 21.0.4

#### Connection specification:
- Database name and version: AWS Redshift
- Driver name: com.amazon.redshift.jdbc42.Driver, using local PostgreSQL Binaries
- Using SSL

#### Describe the problem you're observing:
None of the date/time fields are showing in the Navigation Pane for Views. Also, when generating SELECT, none of the date/time fields in the DDL are generated.

Example: DDL for View

CREATE OR REPLACE VIEW ei_ops.atom_prod_tasks_data AS
 SELECT atom_prod_tasks_data.id_nbr
, atom_prod_tasks_data.lni_text
, atom_prod_tasks_data.status_text
, atom_prod_tasks_data.has_hist_ind
, atom_prod_tasks_data.create_dts
, atom_prod_tasks_data.updt_dts
, atom_prod_tasks_data.msg_dts
   FROM ops.atom_prod_tasks_data with no schema binding;

The three *_dts fields are not showing in the navigation pane, or in the generated SELECT. (see attached images)

Is there a fix for this bug?
![DB_Generated_View_SQL](https://user-images.githubusercontent.com/83968374/117682079-f253da80-b16f-11eb-9d55-84a2269cc309.jpg)
![DB_Nav_Pane](https://user-images.githubusercontent.com/83968374/117682092-f7188e80-b16f-11eb-95aa-d28688ac4e29.jpg)

**Comment by LonwoLonwo** [comment]
Hello @Cwest99 
Can you provide DDL of ops.atom_prod_tasks_data table?

**Comment by LonwoLonwo** [comment]
connected with https://github.com/dbeaver/dbeaver/issues/12372 and https://github.com/dbeaver/dbeaver/issues/12204

**Comment by Cwest99** [comment]
Sure. The DDL for the tableis:

CREATE TABLE IF NOT EXISTS ops.atom_prod_auto_tasks_data
(
	id_nbr INTEGER   ENCODE RAW
	,lni_text VARCHAR(270)   ENCODE zstd
	,status_text VARCHAR(270)   ENCODE zstd
	,has_hist_ind INTEGER   ENCODE az64
	,ver_nbr INTEGER   ENCODE az64
	,type_name VARCHAR(120)   ENCODE zstd
	,create_dts TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,updt_dts TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,msg_dts TIMESTAMP WITHOUT TIME ZONE   ENCODE az64
	,rec_status_cd VARCHAR(3) NOT NULL  ENCODE zstd
	,create_dt DATE NOT NULL  ENCODE az64
	,inactv_dt DATE NOT NULL  ENCODE az64
	,del_dt DATE NOT NULL  ENCODE az64
	,dw_gen_ind VARCHAR(3) NOT NULL  ENCODE zstd
	,dw_mod_by VARCHAR(60) NOT NULL  ENCODE zstd
	,dw_mod_dts TIMESTAMP WITH TIME ZONE NOT NULL  ENCODE az64
)
DISTSTYLE KEY
 DISTKEY (id_nbr)
 SORTKEY (
	id_nbr
	)
;

**Comment by LonwoLonwo** [comment]
@Cwest99 thanks!

**Comment by mkosater** [comment]
A simple way to demonstrate this issue is create a table with each of the datatypes in redshift....

create table public.test_all_types(
    c1 SMALLINT,
    c2 INTEGER,
    c3 BIGINT,
    c4 DECIMAL,
    c5 REAL,
    c6 DOUBLE PRECISION,
    c7 BOOLEAN,
    c8 CHAR,
    c9 VARCHAR,
    c10 DATE,
    c11 TIMESTAMP,
    c12 TIMESTAMPTZ,
    c13 GEOMETRY,
    c14 HLLSKETCH,
    c15 TIME,
    c16 TIMETZ
)


then place two view over this table:

create or replace view public.test_all_types_nb
as
select * from public.test_all_types
with no schema binding
;

create or replace view public.test_all_types_b
as
select * from public.test_all_types
;

The "no schema binding" view will not show correctly for Time and Timestamp (with and without timezones). There is also a few columns that show a different datatypes.  

It appears that the issue is with how columns are created from the non binding view. The datatypes that have aliases defined seem to be there and are handled.  The simple fix is by adding the aliases to method getDataTypeAliases in plugins\org.jkiss.dbeaver.ext.postgresql\src\org\jkiss\dbeaver\ext\postgresql\model\impls\redshift\PostgreServerRedshift.java 

Additionally, I believe you will need to add timestamp types to plugins\org.jkiss.dbeaver.ext.postgresql\src\org\jkiss\dbeaver\ext\postgresql\PostgreConstants.java. 

However, you still get the slight different in the types that are shown in the explorer.

**Comment by DariaMarkaryan** [comment]
Verified
