### ISSUE TITLE
Data viewer ignores precision parameter for timestamp data type

### ISSUE THREAD

**Issue by git10135405** [dbeaver/dbeaver#12429]
If the column data type is timestamp(3), 6 more zeros will be displayed. As shown in the figure: 
![image](https://user-images.githubusercontent.com/35558611/117956905-15d37c80-b34c-11eb-8f7f-21bc8185e479.png)

#### System information: 
- Operating system：win10 LTSC 2018
- DBeaver version：21.0.4

**Comment by Matvey16** [comment]
Thank you for the report. I reproduced it in MySQL database. Can you add what database is used on your screenshot?

**Comment by git10135405** [comment]
> Thank you for the report. I reproduced it in MySQL database. Can you add what database is used on your screenshot?

thank you for your reply！I use MySQL database

**Comment by Matvey16** [comment]
The same bug on Datetime datatype [#12654](https://github.com/dbeaver/dbeaver/issues/12654)

**Comment by Matvey16** [comment]
@git10135405 This additional zeroes are added by the driver and are not influenced by Dbeaver. As a workaround you can either use another driver or enable data formatting in connection settings.
![2021-06-23_17h01_07](https://user-images.githubusercontent.com/82543000/123110473-cdc47100-d444-11eb-8e3c-45d7c2744b62.gif)

**Comment by CComparon** [comment]
Thank you @Matvey16 for the tip. Unfortunaly now regular DATETIME(0) columns get an extra triplet of zeroes.
Would you advise to report that to the MySQL crew as a bug?

**Comment by Matvey16** [comment]
@CComparon In my example I just added three `f` to see fractions, if you don't need them you can adjust it as you like. If you want precision to be 0, just don't add them and leave it as is `yyyy-MM-dd HH:mm;ss`
It is not necessarily a bug, this is just how their driver sends unformatted data to any tool. And for this reason among others we have an option to format data to your needs.

**Comment by CComparon** [comment]
@Matvey16 thank you for your reply. My misunderstanding revolves around the fact that MySQL datetime has an associated precision subscript e.g. datetime(0) or datetime(3) meaning with second precision (resp millisecond). Our db schemas make extensive use of various precision levels for various usage. Ideally dbeaver would offer such a client side formatting per subscript too instead of for all datetime columns at once to make this possible. Please confirm if I didn't get confused with the driver vs client side distinction.

**Comment by Matvey16** [comment]
MySQL database uses this precision parameter for storing data, so it will just delete all excessive milliseconds in time of inserting. But when sending data to client, the driver sends them unformatted with maximum precision.
For now Dbeaver client side formatting only works for the entire connection.
If you have a means to do it, you can propose an option to MySQL team, so they add a property for their driver to only send datetime data according to chosen precision.
Also you can try using earlier drivers for this connection because our tests showed that on earlier versions it was working just as like you are asking.

**Comment by git10135405** [comment]
@Matvey16 
awesome! I tried to update the mysql driver and the problem was solved! 
![image](https://user-images.githubusercontent.com/35558611/123248061-14d06600-d51a-11eb-8141-80f83026261b.png)

Here is a step-by-step guide：
![image](https://user-images.githubusercontent.com/35558611/123247985-fbc7b500-d519-11eb-9508-f15805186e17.png)
![image](https://user-images.githubusercontent.com/35558611/123248431-80b2ce80-d51a-11eb-8677-7e2ef2f92d58.png)

**Comment by Matvey16** [comment]
@git10135405 That's great, so they already fixed it.
@CComparon You can update the MySQL driver. It looks like someone already decided to fix this in their latest version.

**Comment by CComparon** [comment]
@git10135405 
Thanks a bunch! It works like a charm...

@Matvey16 
... except that I started liking the fact that DBeaver was converting datetimes to my local timezone (DB in UTC, locale is PST). Back to doing conversions on the fly ;)
