### ISSUE TITLE
Problem change parameter value

### ISSUE THREAD

**Issue by devscheffer** [dbeaver/dbeaver#12420]
#### Database
IBM db2
#### Dbeaver
Version: 21.0.4
#### Describe the problem you're observing:
once a set parameter like 
```sql
@set total = 12
```
it doesn't change the value total if I try to change the value from 12 to 15.

#### Steps
run
```sql
@set total = 12
select :total
-- return 12
```
Then run the same script but change the value
```sql
@set total = 15
select :total
-- return 12, it should  have return 15
```

**Comment by uslss** [comment]
@devscheffer please, provide more info about the issue.
What database do you use? Dbeaver version? Steps to reproduce an issue?

**Comment by devscheffer** [comment]
I have updated the info

**Comment by uslss** [comment]
@devscheffer do you use Execute SQL script (Alt+x) command or Execute SQL Statement (Ctrl+Enter).

The issue is reproducible for me only in case I re-execute just SELECT statement using Ctrl+Enter. Seems it is expected behaviour in this case, because the parameter wasn't set once again.

Sorry for the late response

**Comment by devscheffer** [comment]
Thank you, I was only using ctrl+enter
