### ISSUE TITLE
Shared SSH Tunnel Connection

### ISSUE THREAD

**Issue by kumarrsumit** [dbeaver/dbeaver#12430]
**Is your feature request related to a problem? Please describe.**
Each database connection open a new SSH Tunnel even though they share the same SSH Tunnel, this need multiple authentication of the said SSH connection

**Describe the solution you'd like**
If database connections share the same SSH Tunnel and we have an active connection to the said SSH Tunnel then all subsequent database connection should use the same tunnel connection instead of opening another connection.

**Describe alternatives you've considered**
The alternative is to invoke the SSH tunnel externally (like using Putty) and point all the connections in DBeaver to localhost

**Comment by kseniiaguzeeva** [comment]
Thank you for the idea. We will implement it.

**Comment by serge-rider** [comment]
This makes a lot of sense to save resources, especially in multi-user environments.

**Comment by ShadelessFox** [comment]
During the initial implementation, we came across several issues regarding tunnel invalidation.

#### When invalidating a tunnel, it must invalidate all other dependent tunnels (jump servers, reused tunnels) and connected data sources.

The "dumb" way:
1. Disconnect all data sources
2. Disconnect the tunnel
3. Connect the tunnel
4. Connect all data sources

The "better" way:
1. Find all connected tunnel sessions and mark them as _invalid_, meaning no further connections can be made
2. Find all data sources that used these tunnel sessions and invalidate them as well

Pitfalls:
1. Invalidation is not always a "connect-disconnect" thing. It depends on the underlying implementation of a data source. Therefore, the "dumb" way won't work.
1. Invalidated tunnel must use the same local port for port forwarding. This happens because we can't update the data source configuration during the invalidate process. Therefore, we need to do some bookkeeping.
