### ISSUE TITLE
Automatically display error when SQL entered runs, but errors

### ISSUE THREAD

**Issue by tomchiverton** [dbeaver/dbeaver#12522]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I write some SQL, press the CTRL-Enter shortcut to run it, and nothing happens. I have to take my hands of the keyboard, go to the mouse, move the cursor all the way to "Log" in the side bar, click that, then find the most recent row and double click it.

All to see I typo'd a table name.

**Describe the solution you'd like**
If the SQL run errors, display the error message automatically, e.g. in footer or as floating window.

**Comment by uslss** [comment]
@tomchiverton could you tell in which cases error isn't shown? which dbeaver version and OS do you use?
Usually, errors are shown next ways:
- default (e.g. instead of resultset)
![image](https://user-images.githubusercontent.com/31996417/118659360-ea420d80-b7f5-11eb-9ce6-8ec5c11a8a5b.png)
- pop-up with an error appears (if option is enabled in preferences)
![image](https://user-images.githubusercontent.com/31996417/118659465-02b22800-b7f6-11eb-8e83-20be9975e131.png)
![image](https://user-images.githubusercontent.com/31996417/118659570-1cec0600-b7f6-11eb-97ce-9377d0d59e04.png)

**Comment by tomchiverton** [comment]
21.0.5 on Ubuntu 20.04 LTS

* default - "result 1" tab flashes up for a split second, then vanishes. Nothing else appears.
* enable preference - this works, and provides a reasonable workaround.

So I suppose the bug is really why the "default" option doesn't work.

**Comment by tomchiverton** [comment]
Also the "Error executing query" modal does not appear when the app is maximised.

**Comment by uslss** [comment]
cannot reproduce it against 21.1.2.
If it is still actual for you - feel free to reopen it.

**Comment by alexandreSantosPulsus** [comment]
> Also the "Error executing query" modal does not appear when the app is maximised.

@uslss I'm quite late but... I'm trying to get rid of this "Error execution query" shown to the side of error messages in the results panel. Is there an option for that?? 
It's very annoying to click the arrow to hide it every time!
