### ISSUE TITLE
The auto-complete shortcut doesn't work

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#12718]
#### System information: 
- Operating system (distribution) and version Mac
- DBeaver version 21.1.0

#### Steps to reproduce, if exist:
1. Open a table in Data Editor
2. Click the top filter field and use auto-complete shortcut to select a table column

**Expected:** the list of table columns appears
**Actual result**: the column list doesn't appear

**Comment by flambchap** [comment]
The auto-complete shortcut doesn't work in the SQL editor as well. That's because it conflicts with the system shortcut (CTRL+SPACE BAR). We can't change this shortcut, however, because users of other operating systems will be affected, and that just sucks. I believe that we need to introduce a new separate keymap for macOS. This solution also sucks, but that's better than other alternatives. Life is pain, especially if you are a macOS user.

**Comment by serge-rider** [comment]
IT also doesn't work in Windows when there is some text before cursor

**Comment by serge-rider** [comment]
Very similar to #14721

**Comment by serge-rider** [comment]
#14721 was fixed.
On MacOS <kbd>CTRL+Space</kbd> is the default shortcut. It may not work if you have more than one keyboard layout (system shortcut bound it).

Workarounds: 
- use <kbd>fn+ctrl+space</kbd> shortcut
- redefine system shortcut for keyboard layout change

**Comment by Matvey16** [comment]
Verified

**Comment by sahanpulseid** [comment]
On MacOS CTRL+Space is the default shortcut. It may not work if you have more than one keyboard layout (system shortcut bound it). but you can fix this by doing this. 
go to
 **system setting -> keybord -> keybord shortcuts -> Input Sources -> untick the `Select the previous input source`
 and click done.**
 your problem solved
