### ISSUE TITLE
Allow to drag canvas

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#13002]
![image](https://user-images.githubusercontent.com/799021/123439258-3b55d600-d5da-11eb-8e25-42bcf58793d0.png)

Allow to drag canvas instead of just scrolling.

Many editors implement `hand` tool, which allow to catch canvas and move it, additionally to scrolling

**Comment by uslss** [comment]
thank you for the suggestion

**Comment by ShadelessFox** [comment]
Implemented:
1. Horizontal scrolling using <kbd>Shift</kbd>+<kbd>Mouse Sheel</kbd>
2. Hand tool that allows you to pan diagram (toggleable, default shortcut is <kbd>Tab</kbd>)

Note: unfortunately, we can't assign <kbd>Space</kbd> for toggling hand tool, since this key is used for selecting entities.

https://user-images.githubusercontent.com/35821147/129013418-14c30215-ac13-44a2-bc5a-cc466e0d0de7.mp4

**Comment by Matvey16** [comment]
Verified
