### ISSUE TITLE
Hanging and freezing in OS X

### ISSUE THREAD

**Issue by shearerpmm** [dbeaver/dbeaver#13049]
#### System information: 
- Operating system (distribution) and version: OS X 10.15.7
- DBeaver version: 21.1.1
- Additional extensions: none

#### Connection specification:
- Database name and version: Vertica 10.1
- Driver name: Vertica JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Corporate laptop, use a VPN and SSL/TLS authentication to connect to Vertica

#### Describe the problem you're observing:
The new version of DBeaver is creating catastrophic system stability issues for me. I get long periods of spinning pinwheel and the OS eventually comes to a complete stop, with no ability to move the cursor or type, so I have to do a hard reboot. 

I have rebooted and reset PRAM and SMC three times, but every time I start up DBeaver the issue recurs within minutes of startup. 

In the minutes before the system freezes completely, DBeaver is usable, it is possible to run queries, but DBeaver seems to be working hard in the background, maybe setting up autocomplete proposals.

I downgraded to version 7.3.5 today, and since then I have worked for several hours with no issues.

**Comment by kseniiaguzeeva** [comment]
Unfortunately, I cannot reproduce it. Could you please provide me with more information in order to I could to assess the issue and find a solution:
1. Do you use standalone DBeaver or Eclipse exstension?
2. Could you please send me [log files](https://github.com/dbeaver/dbeaver/wiki/Log-files)
3. Could you please look at [Query manager](https://github.com/dbeaver/dbeaver/wiki/Query-Manager): what queries run when .it happens. All query and object types should be enabled.
4. Could you please tell what exactly do you do before DBeaver freezes, any steps to reproduce?

**Comment by shearerpmm** [comment]
It looks like the association with DBeaver was a coincidence; I started seeing the same behavior in other applications after a couple days. I got some advice that still being on Catalina might be the issue. I upgraded to Big Sur and no problems so far with DBeaver 21.1.2.
