### ISSUE TITLE
Session manager not refreshing correctly on Postgres

### ISSUE THREAD

**Issue by alesc2000** [dbeaver/dbeaver#13154]
#### System information: 
- Operating system (distribution) and version Linux Mint and Windows
- DBeaver version 21.1.2
- Additional extensions Office

#### Connection specification:
- Database name and version Postgres 9.6, Postgres 12
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Session manager list not refreshing correctly. New sessions not showing up when refreshing and/or statuses not changing. If I close the Session manager tab and open it again, the data gets refreshed.

#### Steps to reproduce, if exist:
Run a long operation (say ANALYZE VERBOSE; on a big database), then open session manager. It shows the query with the correct Xact Start and state active. Then the analyze finishes, but when refreshing the sessions, the analyze task is still active.
After closing and reopening Session manager tab, ANALYZE disappears from the table.

![image](https://user-images.githubusercontent.com/19900533/125048183-53ccf280-e0a8-11eb-85e4-babf138a1f7c.png)
![image](https://user-images.githubusercontent.com/19900533/125048218-5d565a80-e0a8-11eb-9d7e-0e19c3105dc9.png)
![image](https://user-images.githubusercontent.com/19900533/125048441-9989bb00-e0a8-11eb-8958-a3198fed1912.png)

Thanks.

**Comment by Matvey16** [comment]
@alesc2000 Thank you for the report

**Comment by panla** [comment]
and on mysql.

**Comment by Matvey16** [comment]
@panla Can you add what happens in MySQL?

**Comment by panla** [comment]
@Matvey16 

like alesc2000`s description

click `refresh sessions` can`t refresh, and reopen tools/session manager can refresh

**Comment by panla** [comment]
close it?

**Comment by Matvey16** [comment]
@panla no, we will work on it in 21.2.1 version

**Comment by Crazy-Hopper** [comment]
Since it is a planned work, I think I can add some details on mysql session manager problem I still see with 21.2.0 version.
When opening session manager and make it periodically refresh, I can see that new connections are listed, complete connections are removed, but for running connections columns like Command, Time, State, and Query aren't updated. Reopening session manager of course displays fresh data at first, but then the same behaviour. Clicking "Hide Sleeping" button refreshes the data, too.

**Comment by Matvey16** [comment]
Verified
