### ISSUE TITLE
The key "V" as shortcut for Paste on context menu

### ISSUE THREAD

**Issue by ahhmedbilal** [dbeaver/dbeaver#13183]
**Describe the solution you'd like**
On right click context menu if we press C, then it copies the selected text. In the same way, if we have to paste the text, then after right click, if we press V, then it should pate the text i.e we dont have to take mouse pointer to "Paste" menu to click. By pressing V, it should do the work on right click context menu.

**Comment by ShadelessFox** [comment]
Hello @ahhmedbilal,

The letter `C` works because it's a mnemonic for the `Copy` command.
Similarly, the letter `P` is the mnemonic for the `Paste` command.

You can view mnemonics by opening any context menu using the <kbd>Alt</kbd> key:

![image](https://user-images.githubusercontent.com/35821147/169847034-8ab56193-9426-4bf4-9461-6c77bf176115.png)

We can't change the mnemonic of the `Paste` command because it has no letter `V` in it.

**Comment by ahhmedbilal** [comment]
Hi

You can use like this "Paste(v)" to enable this feature?

Regards

**Comment by ShadelessFox** [comment]
It's a questionable change, unfortunately. Have you considered using keyboard shortcut instead, <kbd>Ctrl+V</kbd>?

**Comment by ahhmedbilal** [comment]
Yes, i hv used Ctrl+V, but having "v" as shortcut on context menu will also
facilitate the process of pasting.
