### ISSUE TITLE
Wrong value in decimal part of TIMESTAMP

### ISSUE THREAD

**Issue by michal-bartak** [dbeaver/dbeaver#13331]
#### System information: 
- Kubuntu 20.04
- DBeaver 21.1.3
- Additional extensions

#### Connection specification:
- Postgresql 12, Postgresql 9.5
- Postgres
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Decimal part of TIMESTAMP and TIMESTAMPTZ is contains wrong values. 

![image](https://user-images.githubusercontent.com/7868445/127147523-91122622-81ac-43f5-a783-c1fa831406dd.png)
See, decimal part contains digits from minutes and seconds

#### Steps to reproduce, if exist:

1. execute: `SELECT '2015-05-05 22:45:22.8642'::TIMESTAMP`
2. you get result 
```
text                    |
------------------------+
2015-05-05 22:45:22.4522|
```

**Comment by ShadelessFox** [comment]
Hello @michalk-k,

I was unable to reproduce your issue:
![image](https://user-images.githubusercontent.com/35821147/127148754-a99cc46d-7c21-442c-a45e-5674295ab41d.png)

What's your date/time formatter settings? Is it disabled?

**Comment by Matvey16** [comment]
@michalk-k You enter fractions of a second in your query, but the result is shown in milliseconds.
You need to either disable date/time formatting or change the pattern to show fractions instead of milliseconds

![dbeaver_ArO2WZerpY](https://user-images.githubusercontent.com/82543000/127150937-441491ea-2d03-4809-baba-e67960ee1270.png)
![dbeaver_8dW5vdyyz1](https://user-images.githubusercontent.com/82543000/127150949-258b1378-b38d-4a79-8384-da19f09e474a.png)
![dbeaver_DHNXCtgBb1](https://user-images.githubusercontent.com/82543000/127150956-e460aed5-1f9e-47b6-9365-c1f14103b591.png)

**Comment by michal-bartak** [comment]
Thank you very much guys. 
Verification of the configuration was great advice. Half an hour ago I wasn't aware it exist.. but someone (obviously me) had to change the default setttings, entering wrong pattern for fraction of seconds

![image](https://user-images.githubusercontent.com/7868445/127149449-01e75b94-f38a-4994-8142-864e86d7738e.png)

I changed it to ffffff and now it works as correctly.
I suppose that disabling time formatting results in displaying time in server format (or local machine one)?

Anyway, thank you for instant support. The case can be closed.
