### ISSUE TITLE
Git and debug extensions cannot be installed

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#13387]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.1.4

#### Describe the problem you're observing:
Git extension cannot be installed
Error:
```
Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver Git support 1.0.49.202107181810 (org.jkiss.dbeaver.git.feature.feature.group 1.0.49.202107181810)
  Missing requirement: DBeaver Git support 1.0.49.202107181810 (org.jkiss.dbeaver.git.feature.feature.group 1.0.49.202107181810) requires 'org.eclipse.equinox.p2.iu; org.eclipse.egit.feature.group 0.0.0' but it could not be found
```
Similar issue for debug ext:

```
Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver Debug 6.1.51.202107181810 (org.jkiss.dbeaver.debug.feature.feature.group 6.1.51.202107181810)
  Missing requirement: DBeaver Debug 6.1.51.202107181810 (org.jkiss.dbeaver.debug.feature.feature.group 6.1.51.202107181810) requires 'org.eclipse.equinox.p2.iu; org.eclipse.debug.ui 0.0.0' but it could not be found
```

**Comment by martinseifertmobility** [comment]
Hey @uslss 

I still have that issue, what's your solution?

`Cannot complete the install because one or more required items could not be found.
  Software being installed: DBeaver Git support 1.0.50.202108020335 (org.jkiss.dbeaver.git.feature.feature.group 1.0.50.202108020335)
  Missing requirement: DBeaver Git support 1.0.50.202108020335 (org.jkiss.dbeaver.git.feature.feature.group 1.0.50.202108020335) requires 'org.eclipse.equinox.p2.iu; org.eclipse.egit.feature.group 0.0.0' but it could not be found`

**Comment by martinseifertmobility** [comment]
For some reason (no idea why) it now worked with 1.0.50.202108020335
