### ISSUE TITLE
SQL Highlighting Not Functioning Properly When Create HIVE Table

### ISSUE THREAD

**Issue by drawnfallow** [dbeaver/dbeaver#13409]
#### System information: 
- win10
- 21.1.4

#### Describe the problem you're observing:
Highlighting breaks when creating HIVE table

#### Steps to reproduce, if exist:

CREATE TEMPORARY TABLE matrix (	
	distribution_channel STRING,
	campaign_code STRING,
	campaign_name STRING,
	coupon_code STRING
)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ("separatorChar" = ",", "quoteChar" = "\"")
STORED AS TEXTFILE
LOCATION '/mapr/lux.mapr.com/tmp/snd_crm/coupons_raw'
TBLPROPERTIES ("skip.header.line.count"="1")
;

**Comment by drawnfallow** [comment]
![image](https://user-images.githubusercontent.com/24426786/127910038-02856228-5976-43e7-8e2f-7238c26d851b.png)

**Comment by drawnfallow** [comment]
It doesn't respect the semi-colon as the end of the query.

**Comment by Matvey16** [comment]
@drawnfallow Thank you for the report. As I see it, the problem is with the triple quotes at the end of this line `WITH SERDEPROPERTIES ("separatorChar" = ",", "quoteChar" = """)` even with an escape char the editor formats it as though it was a long quoted line. Maybe we can add a setting to respect a particular escape char when changing the color of text in the editor.

As you can see, the same thing happens with Github's markdown.

```sql
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.OpenCSVSerde'
WITH SERDEPROPERTIES ("separatorChar" = ",", "quoteChar" = "\"")
STORED AS TEXTFILE
LOCATION '/mapr/lux.mapr.com/tmp/snd_crm/coupons_raw'
TBLPROPERTIES ("skip.header.line.count"="1")
;
```

**Comment by Matvey16** [comment]
Verified
