### ISSUE TITLE
Where filter can be modifyed in 'Statistics' tab (SQL Script execution result)

### ISSUE THREAD

**Issue by Wroud** [dbeaver/dbeaver#13431]
#### Describe the problem you're observing:
Where filter can be edited in statistics tab, result set can be refreshed (only once)

#### Steps to reproduce, if exist:
execute any SQL Script (Alt + X) in SQL Editor

![image](https://user-images.githubusercontent.com/811729/128060897-8649bc18-6f0a-4805-9d1c-9da057c413bf.png)
![image](https://user-images.githubusercontent.com/811729/128060941-5cb35c87-53a9-465e-9cc3-cb2d2b811012.png)

**Comment by uslss** [comment]
![image](https://user-images.githubusercontent.com/31996417/158546461-e613756f-bd21-40e0-ae2c-0fdc69e13e69.png)
filter panel is still available if the result is an error

**Comment by uslss** [comment]
verified

**Comment by ShadelessFox** [comment]
Editing the filter on a valid query to become invalid hides the filter panel, and I believe this is NOT the expected behavior:

https://user-images.githubusercontent.com/35821147/158721952-4486b911-bda8-4024-8fbc-4cfa9e7ae060.mp4

There's no way to stop the automatic refresh if a database error occurs during refresh (simulated by dropping the selected table):

https://user-images.githubusercontent.com/35821147/158722829-4ba097cb-5cf7-4559-bb57-839a2f46f2bb.mp4

Can we gray-out the filter panel instead of hiding it? This blank space drives me nuts.

**Comment by serge-rider** [comment]
Last fix was reverted. We need filters in error panel.

**Comment by uslss** [comment]
verified
