### ISSUE TITLE
Quick Switch Editor search should find anywhere in tab name 

### ISSUE THREAD

**Issue by ftobin** [dbeaver/dbeaver#13456]
**Is your feature request related to a problem? Please describe.**
The Quick Switch Editor search dialog (default Ctrl+E) has a largely useless search functionality, since the search is anchored at the beginning of the tab name, which includes the DB name.  For example, if the tab name is `<mydb> scratch.sql`, and I search for `scratch`, no search result pops up -- I have to search for a string anchored at the beginning `<mydb> scr`.

**Describe the solution you'd like**
Text entered into the Quick Switch Editor search dialog should search anywhere in the tab name.  Ideally it would be a space-separated list of search strings that are AND-ed together.  For example, if I search for `gamma beta`, it should find `<mydb> alpha-beta-gamma.sql`.

**Comment by uslss** [comment]
thank you for the suggestion

**Comment by GuenterSch** [comment]
Hello,
the new logic is good, but it finds to many entries.
E.g. Search for **DS** returns
**DS**\_HALLO
HALLO\_**DS**
**D**O not **s**how

The last line will also be shown, because the D is in DO and the S is in show.

**But it would be better if you search for words and not for letters.** (With underscore a word ends or begins)

Search for **D S** can return all three lines.
Thanks, BR
Günter
