### ISSUE TITLE
When importing CSV with a column name with a period eg S.No the import fails.

### ISSUE THREAD

**Issue by Izzyray** [dbeaver/dbeaver#13483]
#### System information: 
- Windows 10
- 21.1.4

#### Connection specification:
- Postgres

#### Describe the problem you're observing:
When importing a csv file, if the csv file contains a column header with a period in it "S.No" vs "SNo", it will fail to import or map properly despite both database column name, and csv column name matching.

It worked fine in 21.1.3.

#### Steps to reproduce, if exist:
create a csv with column name S.No
create a database with column name S.No
import csv into the database.

#### Include any warning/errors/backtraces from the logs
![image](https://user-images.githubusercontent.com/85926355/128816710-dcedfd4a-36c9-4a8c-9031-3dd99d9f8257.png)
![image](https://user-images.githubusercontent.com/85926355/128816765-977078b4-4dea-498e-affd-ba9db0cc6a54.png)

**Comment by vani0vani0** [comment]
Same thing happens with other special symbols, such as underscore. It happens when you use column names that are recognized as reserved sql words, such as "day" or "time". I have a CSV file and an empty table with the following column names:
`_time, day`
The import task fails with the same message:
`Can't find target attribute [_time]`
Even though in the mappings everything is set up correctly.

**Comment by ilne** [comment]
Most likely the same issue as described in https://github.com/dbeaver/dbeaver/issues/13402.

**Comment by Matvey16** [comment]
Yes, this looks like the same issue and we are working on it. Thank you for the report
