### ISSUE TITLE
Can't enable all tables in one list with hide folders

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#13565]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 21.1.5
- Additional extensions

#### Steps to reproduce, if exist:
1. Enable `Hide folders` and `Show all tables in a single list` in custom connection view
2. Try to open objects list

**Expected:** List is shown
**Actual:** Error is thrown

![pt7jSjyohv](https://user-images.githubusercontent.com/82543000/129681174-5b7bd025-0504-4e7b-b209-7f8727c17d9d.gif)

#### Include any warning/errors/backtraces from the logs

```
SQL Error [208] [42000]: Sybase.dbo.sysobjects not found. Specify owner.objectname or use sp_help to check whether the object exists (sp_help may produce lots of output).

  Sybase.dbo.sysobjects not found. Specify owner.objectname or use sp_help to check whether the object exists (sp_help may produce lots of output).

  Sybase.dbo.sysobjects not found. Specify owner.objectname or use sp_help to check whether the object exists (sp_help may produce lots of output).

    Sybase.dbo.sysusers not found. Specify owner.objectname or use sp_help to check whether the object exists (sp_help may produce lots of output).

```

**Comment by uslss** [comment]
verified

**Comment by aranapatona** [comment]
this is still not fixed.

**Comment by aranapatona** [comment]
Just happened to me but I also found out that the options menu for the Global setting (Default settings for new connections)
behaves differently but the problem is in the same two checkboxes:
 
**Datasource settings:
Right click connection->Edit Connection->General**

in the Navigator view "Customize" options menu
"Show all tables in a single list" is grayed out,
can NOT select it no matter what other checkboxes are ticked/unticked.

**Global settings:
Window->Preferences->Connections**

connections tab (Default settings for new connections) then "Show all tables in a single list" is available but "Hide Folders" is dimmed/grayed. If I tick and untick the "show all tables in single list" checkbox then "Hide Folders" option becomes undimmed/available and "show all tables" gets dimmed, but then even if you untick or tick "hide folders" you can no longer make the disabled option available, you have to cancel and changes and open again.
