### ISSUE TITLE
In Redshift, during data import the column length has to be based on the byte length/octet length for string columns instead of length of the columns.

### ISSUE THREAD

**Issue by deepaksenthilkumar** [dbeaver/dbeaver#13611]
**Is your feature request related to a problem? Please describe.**
In Redshift, during data import, the column length has to be based on the byte length/octet length for string columns instead of the length of the columns.

**Describe the solution you'd like**
Calculate byte length and use if for field lengths.

**Comment by deepaksenthilkumar** [comment]
@ShadelessFox Any suggestion on where to start. Is this configurable by database?

**Comment by ShadelessFox** [comment]
I'm not sure what you're talking about. You're talking about the case when you import data to non-existing table in Redshift?

**Comment by deepaksenthilkumar** [comment]
Yes.

**Comment by ShadelessFox** [comment]
The target column's length is determined using the source attribute's length. Unfortunately it's a generic code and it can't handle such specific cases. You still can take look at it and maybe add yet another function to `SQLDialect`.

**Comment by deepaksenthilkumar** [comment]
Can you point me to where the length is calculated now, I will see if we can modify the SQLDialect for Redshift.

**Comment by ShadelessFox** [comment]
Sure, see `DBStructUtils#mapTargetDataType`.

**Comment by deepaksenthilkumar** [comment]
Made it generic, as it might benefit any other database that needs to use this option.

**Comment by Matvey16** [comment]
@deepaksenthilkumar I've tested this feature and found few issues.
1. The option doesn't work if you go back in import wizard and change it, it remembers the first choice.

![h5ZI3Q2dRr](https://user-images.githubusercontent.com/82543000/130787720-5f40c809-1c58-49d6-b733-628660a95f04.gif)

2. I performed an import with this option disabled (which obviously led to a fail, because it tried to insert values with multiple 2 byte symbols after creating column with lenght based on number of characters) But in any additional import after that, this feature was not working (see gif below, the longest value is 77 bytes, not 60)

![1VERxM2lta](https://user-images.githubusercontent.com/82543000/130788253-20cc765c-eb91-4def-95a1-0a5aec5225a8.gif)


@ShadelessFox do you think, those issues can be solved in scope of only this ticket?

**Comment by deepaksenthilkumar** [comment]
@Matvey16 - I will check and fix this.

**Comment by deepaksenthilkumar** [comment]
This seems to be an existing problem (refresh of target DDL when settings change). Test it just based on column sample count
Have 3 records
1
10
100

Test each time with sample count 1,2,3 see the DDL. Same issue.

**Comment by deepaksenthilkumar** [comment]
The issue is because once the attribute is set, we are unable to update the maxlength, precision, scale.
@Matvey16 -We should raise a new issue for that and not treat this as a problem for this feature. 
@ShadelessFox - This is the reason why I ended up using setFullTypeNamefor RedshiftView instead of setPrecision, setScale as part of #13536. Any reason why we can't update maxLength, precision, the scale for a PostgreAttribute?

In org.jkiss.dbeaver.ext.postgresql.model 
PostgreAttribute.java

    @Override
    public void setMaxLength(long maxLength) {
        log.warn("Attribute does not support updating its max length");
    }
    @Override
    public void setPrecision(Integer precision) {
        log.warn("Attribute does not support updating its precision");
    }

    @Override
    public void setScale(Integer scale) {
        log.warn("Attribute does not support updating its scale");
    }

**Comment by Matvey16** [comment]
Verified

**Comment by Matvey16** [comment]
@deepaksenthilkumar Thank you for your work, all of the issues I found are global and are not specific to your feature
