### ISSUE TITLE
Unable to select DBeaver CE as default app in Windows 10

### ISSUE THREAD

**Issue by tony352** [dbeaver/dbeaver#13646]
#### System information: 
- Operating system (distribution) and version:   Windows 10
- DBeaver version:  DBeaver 21.1.0.202106032102
- Additional extensions

#### Describe the problem you're observing:
When I click on an .sql file, my PC opens up another application to open these.  I would like to use DBeaver as my default application.  However, Windows doesn't give me this option. 

#### Steps to reproduce, if exist:
1) Open Windows Explorer
2) Right click on a file ending in ".sql"
3) Select (left click) on "Open With" 

DBeaver does not appear here.  Also, it's path does not appear when viewing Windows Explorer to find it.  (The folder appears to be hidden).

**Comment by uslss** [comment]
@tony352 sorry for the late response.
How did you install dbeaver (msi installer or from the MS Store)?

**Comment by tony352** [comment]
Hi, thank you and no problem at all!

I installed DBeaver through the Microsoft Store.  It downloaded and
installed directly from there.

This is the only way I can install software due to restrictions on my
laptop (as it's a work laptop).

Thank you in advance for any thoughts you might have!

Tony

**Comment by Matvey16** [comment]
@tony352 Hello, I'm guessing you are clicking `look for an app in a Microsoft store` button. If so than it happens because the Store searches for an sql keyword, which we don't have for some reason. You can manually search for DBeaver on that page and pick it as a default app.

Also we need to add a keyword to our page on Microsoft store so Dbeaver would be visible as an option to be default for `.sql` files

![chrome_GWJEB4QD7K](https://user-images.githubusercontent.com/82543000/132212350-65041448-91e8-4010-98d5-0e7dc5879c6b.png)

![ApplicationFrameHost_FmPvehNlNH](https://user-images.githubusercontent.com/82543000/132212374-f60dd39e-29eb-4b94-93d3-a3083858d93a.png)

**Comment by tony352** [comment]
Thank you for letting me know!

Yes, that's right--I just checked and see what you mean re the search on
the MS Store.  It searches for "sql", but I don't see DBeaver on the list
of apps on that page.  If I try to search for "DBeaver", then it does an
overall search through the store and gives me an option to "Launch" the
app.  However, it doesn't give m.e a way to set it as a default app.

If you could add the "sql" keyword on your page, that would be incredibly
helpful! :).

Tony

**Comment by Matvey16** [comment]
@tony352 you can try setting Dbeaver as default with this setting

![ApplicationFrameHost_otGAcdl6Ms](https://user-images.githubusercontent.com/82543000/132223277-8439153e-7e24-4d49-9365-e017c64245b8.png)

**Comment by tony352** [comment]
Hi, I just tried this but DBeaver doesn't appear in the list of apps,
unfortunately.

Best regards,

Tony

**Comment by serge-rider** [comment]
New DBeaver CE release associates with .sql files by default.

**Comment by Matvey16** [comment]
Verified

**Comment by tony352** [comment]
Thank you all!  I just got the updated version and it now works.  I look
forward to using this app!

Tony
