### ISSUE TITLE
Text search goes on "Output" tab

### ISSUE THREAD

**Issue by wiwwo** [dbeaver/dbeaver#13658]
Run a whatever query, and try to search a text in SQL window...
In this case, search for "THISISABUG"; as you can see, "String not found" in the find window, even if Sql Script window is selected. Keep selecting the Sql Script window, focus keeps going to Output window, and "String not found".

DBeaver Community Edition	21.1.5.202108160727
MacOs BigSur 11.4 (20F71)

<img width="718" alt="image" src="https://user-images.githubusercontent.com/3930671/130734128-03e8a624-4ecd-4038-bf5a-3ff22779ae74.png">

**Comment by ShadelessFox** [comment]
Thanks for bug report

**Comment by sg-cmusser** [comment]
I'm having this issue as well - Version 21.1.4.202108020335, Windows 10. 

Also, I've found that a work around it to close the "Output" tab which causes the search to default back to the text editor. But, this isn't ideal if I want to keep the Output tab.

**Comment by Xylandor** [comment]
This is still an issue with latest version and because it's been awhile since any update on this, I thought I'd share another work-around. I found out that if you uncheck the `Show panels in results tabs` option (`SQL Editor > Panels`), this behavior does not occur. It's only a problem when Output is displayed as a results tab. This will cause the Output window to display on the right side of the script window, but at least you'll be able to view the output while searching in the script. 

![image](https://user-images.githubusercontent.com/24617679/147975189-09142334-7e55-4744-9267-67f9900c8bdb.png)

**Comment by ShadelessFox** [comment]
Hello @wiwwo,

I'm unable to reproduce your issue against DBeaver 21.3.5.

Could you please download the latest version and see if the issue is gone there?

**Comment by Xylandor** [comment]
#### System information: 
- macOS Catalina - version 10.15.6
- DBeaver version 22.0.0.202203060510
- Additional extensions: None

#### Connection specification:
- Database name and version: MySQL 5.7
- Driver name: MySQL 5
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No


I've been meaning to follow up with this, but haven't had the time lately. At the time of this writing, I downloaded the latest version (22.0.0.202203060510), and it is still a problem.

Reproductive Steps:
1. From the menu bar, enable the option, "Show panels in result tabs" (SQL Editor > Panels).
2. Run the following query which will cause the Output tab to display in the Results pane. 
`SELECT CAST('abc' AS Unsigned) AS test`
3. In the Find window, search for the value, `abc`, which exists in both the editor windows and Output tab. It will highlight `abc` in the Output pane, but not the editor. 

The expected behavior is that it would highlight findings in the editor window only; not the output pane window. 

The attached video will demonstrate this behavior.

https://user-images.githubusercontent.com/24617679/157060359-3d967106-af52-4480-a9db-1d7ae2b3d058.mov

**Comment by ShadelessFox** [comment]
Hello @Xylandor,

Thank you, I managed to reproduce the issue now.

I didn't pay enough attention to the `Show panels in result tabs` option.
