### ISSUE TITLE
Failed object (view) prevented generation of the whole ERD

### ISSUE THREAD

**Issue by YuriDude** [dbeaver/dbeaver#13969]
#### System information: 
- Operating system (distribution) and version: Windows 10.0.19042.1165
- DBeaver version: Version 21.2.0.202109011400
- Additional extensions: none

#### Connection specification:
- Database name and version: SQL Server 2014
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : VPN

#### Describe the problem you're observing:
While trying to generate ERD whole process failed on "bad" view.
See attached.
![2021_09_21_12_17_11_DBeaver_21 2 0_dbo](https://user-images.githubusercontent.com/5156159/134210380-d4dd2718-95a7-4173-af23-c1de0822f323.jpg)

A single failed object (especially when it is a view)  should not prevent generation of whole ERD. 
Process should just "step over" and continue. In case of failed table and if there a reference to it, code downstream should ignore all failed objects upstream.

#### Steps to reproduce, if exist:
That happed when all tables under the schema name were highlighted and DDL option was used from context menu.
View itself seems does have some issues as I was not able to get DDL of it using Dbeaver.
Nonetheless - **one** failed object should not be an obstacle for the whole ERD!

#### Related feature request that would solve it fundamentally:
https://github.com/dbeaver/dbeaver/issues/13967

**Comment by tati-kru** [comment]
I think we should display a warning if DBeaver failed to load an object and continue diagram loading anyway. Thank you for the report.

**Comment by YuriDude** [comment]
> I think we should display a warning if DBeaver failed to load an object and continue diagram loading anyway. Thank you for the report.

Perhaps ...
But a single object should not stop "the whole" process.
As an option: you may add configuration feature that sets **threshold** of failed objects, e.g. when 5 (X amount) failed - ABORT the process.

**Comment by LonwoLonwo** [comment]
This is a very strange behavior because DBeaver usually does not read object DDLs on step ERD diagram generations. 
I have an SQL Server connection with a schema with the view whose DDL cannot be read. But schema ERD is correct and contains all objects, including the "bad" view. 

![2021-11-09 13_59_04-](https://user-images.githubusercontent.com/45152336/140912425-42b0782a-c333-4e26-be32-39f7d1fa80a2.png)

Unfortunately, I can't reproduce your problem.

Clear steps/videos of the issue and [logs](https://github.com/dbeaver/dbeaver/wiki/Log-files) will be very helpful.

**Comment by uslss** [comment]
There has been no update on the issue for a long time. If it is still actual for you - feel free to reopen it with additional info
