### ISSUE TITLE
Auto-backup of Database Navigator list

### ISSUE THREAD

**Issue by rodrigoguariento** [dbeaver/dbeaver#14125]
**Is your feature request related to a problem? Please describe.**
I've frustrated for twice after update my DBeaver when something went wrong and I lost my Database Navigator list. Of course it didn't happen in same month, but its the second time that occurs.

**Describe the solution you'd like**
I suggest an auto-backup of Database Navigator list and a way to recover it when something wrong occurs.

**Describe alternatives you've considered**
A manual backup.

Thank you!

**Comment by Matvey16** [comment]
@rodrigoguariento Hello. What do you mean when you say you lost your Database Navigator list?

**Comment by rodrigoguariento** [comment]
> @rodrigoguariento Hello. What do you mean when you say you lost your Database Navigator list?

For twice, after update DBeaver (first I was installed DBeaver via snap, and second via apt), some error occurred after weekly update. I've needed to uninstall and reinstall DBeaver. When it worked after the reinstallation, my Database Navigator list was lost. What happened I don't know, because the uninstall and reinstall solved the problem. The only thing I remember, in both cases even the shortcut into my Favorites (Dock) was crashed. I'm using Ubuntu 20.04LTS.

Uninstalling and reinstalling is not the problem, the problem is to configure the entire Database Navigator list when it is lost, because I usually have a long list.

Any other suggestion instead of making this list safer to avoid loss when something goes wrong is welcome.

![image](https://user-images.githubusercontent.com/25516653/136662565-a6c9f3c1-47b7-423b-a009-d249d1e4d65b.png)

**Comment by p91paul** [comment]
This should only be a problem when using snaps. Unistalling a snap removes configuration files as well. If you consistently use apt, you shall never lose your configuration (unless you manually remove the DBeaver configuration folder under your home directory).

**Comment by rodrigoguariento** [comment]
> This should only be a problem when using snaps. Unistalling a snap removes configuration files as well. If you consistently use apt, you shall never lose your configuration (unless you manually remove the DBeaver configuration folder under your home directory).

Thanks for the tip. My last installation was using apt, and when this issue after upgrade occurred I couldn't get DBeaver to work. After each reinstallation, DBeaver would not start, the same symptoms would occur. Since I was using DBeaver to work at the time, I had to find an alternative, so I uninstalled from apt and installed it again using the snap that worked. Among those steps, I even have to insist on a way to easily back up and restore this list to avoid further loss. Thanks!

**Comment by p91paul** [comment]
there is a file in DBeaver config folder in your home directory which is called .dbeaver-data-sources.json. That is your backup: you just have to copy that file across installation and you'll be fine. However, when you install snaps, that's not going to help you. snaps have their own home directory which gets deleted when you uninstall them. So they cannot read the same config file the apt version reads. This is not DBeaver's choice, is a snap design choice. I have no idea if you can write to a snap internal memory to restore your datasources backup. That's why I recommend you get back to using apt. Every time you uninstall a snap, you lose all the configuration you did for it, and you can't get it back. If you uninstall an apt package, instead, your configuration stays there. I hope I clarified why you have those problems with snaps. Also you might try to post on discussions what kind of error you see with the apt version if you still can't run it.

Of course a way of backing up and restoring the .dbeaver-data-sources file from GUI could be a useful addition.

**Comment by rodrigoguariento** [comment]
Thanks. Hope this helps me. Anyway, if I have problems again with the DBeaver update I will try to post the problem before fixing it (reinstalling). Thank you again!
