### ISSUE TITLE
Remote host terminated the handshake

### ISSUE THREAD

**Issue by yongyaoli** [dbeaver/dbeaver#14287]
#### System information: 
- WIN10
- 21.2.2.202110030714

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
Remote host terminated the handshake

**Comment by uslss** [comment]
@yongyaoli what db do you use? please provide clear steps to reproduce the issue

**Comment by yongyaoli** [comment]
help->check update.   can update dbeaver.
Daily update reminder.  NO!

**Comment by LonwoLonwo** [comment]
Hello @yongyaoli 

Maybe this [answer](https://stackoverflow.com/questions/21245796/javax-net-ssl-sslhandshakeexception-remote-host-closed-connection-during-handsh) can help you?

**Comment by uslss** [comment]
@yongyaoli unfortunately, still cannot catch what the issue is about.
Please provide more clear problem description. Steps to reproduce also will be very helpful for the issue investigation

**Comment by jammmmin2** [comment]
@LonwoLonwo @uslss 
I am using SQL developter, and an error occurs while trying to create a DB clude user constructor. 
I proceeded in the same way as other team members, and I am not alone.
I checked the username, PW, and zip file many times and it is definitely correct. But the test fails because 'Remoto host teminate the handshake' occurs.

what is mean ''Remoto host teminate the handshake" ? Or 
what is soluction.. please...

**Comment by LonwoLonwo** [comment]
So... The problem appears in SQL developer too?
Maybe you can make a video of the issue for us?
Also, the [log file](https://github.com/dbeaver/dbeaver/wiki/Log-files) will be very helpful!

**Comment by jammmmin2** [comment]
@LonwoLonwo Thanks, I'll try! I hope you get good results.

**Comment by uslss** [comment]
there is no update on the issue for a long time. If it is still actual - feel free to reopen it with additional info.
