### ISSUE TITLE
Linux packages: omit JRE in favour of dependency

### ISSUE THREAD

**Issue by 2019-05-10** [dbeaver/dbeaver#14321]
The beauty of Linux packages is that you don't need to include everything, but may define dependencies on other packages.
Java is available in all Linux distributions, in Debian (and possibly others as well) as package
`default-jre`
Instead of including a complete JRE withe Linux packages, why not simply define a dependency on that package?

It would significantly cut down the size of DBeaver packages, thus also reducing download volume.
It would remove a bunch of dead files for those that already have a JRE installed (probably quite a lot of Linux users).
And it would remove the need to fix 
`dbeaver.ini`
after each update to switch to system JRE instead.

**Comment by flambchap** [comment]
At the same time, this approach gives tight control over the execution environment. It allows fixing issues like [this one](https://github.com/dbeaver/dbeaver/issues/12668).

By the way, tarballs don't have pre-bundled JRE. They might serve your needs better than packages.

**Comment by flambchap** [comment]
Unfortunately, we cannot do it for the reasons I stated above.

**Comment by 2019-05-10** [comment]
Uh, what reasons stated where?

**Comment by flambchap** [comment]
We chose to include JRE into Linux packages, Windows installer, and macOS dmg because it allows us to fix a number of bugs related to the execution environment. 

The ticket in my previous reply is a good example. To summarize, after upgrading to JRE 11.0.11, our users started complaining about the inability to connect to MSSQL 2008. It turned out that it was the result of the new security policy in OpenJDK. The only option for us was to patch the shipped JRE.

Unfortunately, issues of this sort appear more frequently than we would want. The decision to include JRE wasn't an easy one. After all, you need a pretty solid reason to increase the size of your binary by 35%. At the same time, we understood that some users would still want to use DBeaver with the JRE of their choice. For that reason, we also distribute DBeaver in zip and tarball forms, which ship without JRE.
