### ISSUE TITLE
Incorrect SRID in Value panel is shown for values without SRID

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#14420]
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.2.4 EA

#### Describe the problem you're observing:
![image](https://user-images.githubusercontent.com/31996417/139102970-bdca2ffa-19b8-4f8d-a855-881c114951e0.png)

**Comment by andrelinslima** [comment]
Difference between version is due to #14232, which changes srid internal datatype in 21.2.3.
Per EPSG specification, anything 50k+ is not defined and is considered proprietary definition. 
Both in this case just means dbeaver doesn't know the crs and I'm guessing the mapviewer requires it to be non-null

**Comment by ShadelessFox** [comment]
Hello @andrelinslima,

Thanks for clarification.

In this case, no SRID is specified, so it's stored internally as `0xFFFFFF` (`16777215`). Before #14232, we were truncating SRID to `0xFFFF` (`65535`).

We just don't handle this case.

**Comment by andrelinslima** [comment]
EPSG code 0 is as invalid as the previous values, codes start at 1024. That's why I mentioned possible limitation of non-null, but at least it's a rounder invalid code :)

**Comment by uslss** [comment]
still reproducible
![image](https://user-images.githubusercontent.com/31996417/139711353-3abf4276-28a4-488d-8ef2-334618fdb7d4.png)

**Comment by uslss** [comment]
verified
