### ISSUE TITLE
Export task in new table ignores options "Selected columns only"

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14442]
#### System information:
- Win10, DBeaver CE 21.2.4
-
#### Connection specification:
- MS SQL Server (AWS RDS)

#### Describe the problem you're observing:
I want run export task to the new table with checked options "Selected columns only" and/or "Selected rows only" but they are ignored.

#### Steps to reproduce, if exist:
Open table with several columns.
Highlight some columns and rows.
Begin export.
Select Database export type.
Select target table as new table (Mapping = create)
Check "Selected columns only" and save task.
Close Data transfer dialog and run created task.
**Expected:** only selected columns were exported
**Actual:** all columns and rows of the source table are copied to the target table despite on the enabled options "Selected columns(rows) only"

**Comment by Matvey16** [comment]
The problem is with the fact that export started from data editor, but saved as a task, still shows `selected columns/rows` as enabled in parameters enabled even though this option is unavailable for saved export task 

![dbeaver_YWtMcQvaBR](https://user-images.githubusercontent.com/82543000/139456129-97be217f-4aeb-4a21-9537-73632d9167b6.png)

**Comment by LonwoLonwo** [comment]
Unfortunately, we can't fix this behavior because the tables mapping page in the Data Transfer Wizard is before the Extraction settings (with setting "Selected columns only"). 

The best solution in this situation will be a change of columns mapping to "skip" on the "Tables mapping page".

![2022-04-12 11_22_48-Data Transfer](https://user-images.githubusercontent.com/45152336/163116293-1a4e4eae-3f89-496d-945b-46382ab9178f.png)
