### ISSUE TITLE
Cockroach: rowid column created in export into table

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#14557]
#### System information: 
- Win10
- DBeaver CE 21.2.5
- Additional extensions

#### Connection specification:
- Cockroach 42.2.20

#### Describe the problem you're observing:
When you perform export into table rowid column is exported too. But in the new table also creates row_id, so data transfer falls with errors.
The solution to the problem may be to exclude the rowid column from the export by default, since if you explicitly set the "skip" status for it during export, then it will be successful.
 
![image](https://user-images.githubusercontent.com/43252954/141752244-78ec66fa-ea26-4dd1-b90c-21ea93b9a23f.png)

#### Steps to reproduce, if exist:
Just try to start export from table to table in Cockroach.

#### Include any warning/errors/backtraces from the logs
```
Can't insert row
  SQL Error [23502]: ERROR: null value in column "rowid" violates not-null constraint
  SQL Error [23502]: ERROR: null value in column "rowid" violates not-null constraint
    ERROR: null value in column "rowid" violates not-null constraint
    ERROR: null value in column "rowid" violates not-null constraint
```

**Comment by LonwoLonwo** [comment]
rowid columns in Cockroach: https://github.com/cockroachdb/cockroach/issues/3293

**Comment by LonwoLonwo** [comment]
Rowid column is now hidden for Cockroach (as it was in table DDL and in the Data Viewer).

Also, button "Show comments" was removed for Cockroach tables/views, because table DDL readed from Cockroach already has this rows.

![2022-04-07 21_17_01-DBeaver Ultimate 22 0 2 - test_rowid_2](https://user-images.githubusercontent.com/45152336/162270128-8efd72a4-fe89-4020-a754-e1aa46ad8b5f.png)

![2022-04-08 09_54_46-DBeaver Ultimate 22 0 2 - test_rowid](https://user-images.githubusercontent.com/45152336/162389144-3039def8-074d-41b6-b8bc-2486d7225a83.png)

![2022-04-08 10_36_55-DBeaver Ultimate 22 0 2 - test_rowid](https://user-images.githubusercontent.com/45152336/162389149-02696ec1-9dd8-49df-8255-3adf87b6b668.png)

**Comment by uslss** [comment]
verified
