### ISSUE TITLE
Support H2 2.0.202

### ISSUE THREAD

**Issue by lukaseder** [dbeaver/dbeaver#14752]
#### System information: 
- DBeaver version: Version 21.2.4.202111011413

#### Connection specification:

- Database name and version: `com.h2database:h2:2.0.202`

#### Describe the problem you're observing:

The H2 database has drastically changed their `INFORMATION_SCHEMA` to be more standards compliant. Unfortunately, this means a variety of functionality in DBeaver may no longer work correctly.

#### Steps to reproduce, if exist:

For example, click on `Procedures` in the connection's menu and you get:

```
Table "FUNCTION_ALIASES" not found; SQL statement:
SELECT * FROM INFORMATION_SCHEMA.FUNCTION_ALIASES WHERE ALIAS_SCHEMA = ? [42102-202]
```

There may be other things, which I haven't checked. If you ever query the `INFORMATION_SCHEMA` directly, just check if those queries still work...

**Comment by LonwoLonwo** [comment]
Thanks for the idea @lukaseder

**Comment by LonwoLonwo** [comment]
![2022-02-17 10_20_11-Connect to a database](https://user-images.githubusercontent.com/45152336/154439200-1d20bf8f-f8ba-4b7c-9b8f-150244bd9b4a.png)


New H2 driver added for embedded version. Due to partial incompatibility of versions of databases and drivers.

All support added here: https://github.com/dbeaver/dbeaver/issues/14496

**Comment by uslss** [comment]
verified
