### ISSUE TITLE
Could you please make navigator tree more compact?

### ISSUE THREAD

**Issue by ghYura** [dbeaver/dbeaver#14764]
Could you please make navigator tree more compact?
I mean, economize space on the left from expanded tree, because after all tree expansion I have to shrink main SQL-editor and DB-data-view-column tab/windows (and I have opened them very lot on the right side) so this is feel uncomfortable.

Take a look at possibility for this option for IntelliJIDEA:
https://stackoverflow.com/a/70195443/11714800

![dbeaver connection tree](https://user-images.githubusercontent.com/42974628/111424514-8ff3d600-86fa-11eb-89f1-309aa153a82e.jpg)

_Originally posted by @ghYura in https://github.com/dbeaver/dbeaver/discussions/11753#discussioncomment-492222_

**Comment by ShadelessFox** [comment]
Hello @ghYura,

It's not possible, unfortunately. DBeaver runs on Eclipse platform that uses OS's native widgets for its graphics.

It is possible in Intellij IDEA because it is powered by Swing library that is entirely written in Java and has no OS-specific widgets and thus can be highly customizable.

**Comment by ghYura** [comment]
@ShadelessFox  Thanks for descriptive clarification
