### ISSUE TITLE
PostgreSQL Roles missing comments feature in GUI

### ISSUE THREAD

**Issue by RickSaavedra** [dbeaver/dbeaver#14908]
When viewing postgresql roles in dbeaver, there is no place where comments are displayed.

**Describe the solution you'd like**
Similar functionality to other objects: Display/Edit/Add comments. Add comments to Generate DDL for Roles

**Comment by LonwoLonwo** [comment]
@RickSaavedra 
Thanks for the idea.

**Comment by michal-bartak** [comment]
Hello. Any chance to see this feature any soon?

**Comment by LonwoLonwo** [comment]
Hello @michalk-k 

This task, for now, is in our plans for the 22.2.2 release. 
You can see it in the "Milestone" section on this GitHub page.

**Comment by michal-bartak** [comment]
Thank you for the clarification.
Please don't get me wrong or offensive, but I found those milestones often not fulfilled. There are issues planned for v21 but still not delivered while being more critical.
So because I don't know the policy of using/changing milestones I'm asking directly for plans/activity around a particular issue.

Anyway, keep up the good work
With regards

**Comment by michal-bartak** [comment]
It's in 22.2.2 now. Thank you!

**Comment by LonwoLonwo** [comment]
Yep, we implemented it in version 22.2.2

![2022-09-26 16_39_56-test_as - Persist Changes](https://user-images.githubusercontent.com/45152336/192338880-e5a5a4cf-ecfe-4ebb-8cbb-f122313483f5.png)
