### ISSUE TITLE
Not able to run the athena queries

### ISSUE THREAD

**Issue by Swapnali1996** [dbeaver/dbeaver#15120]
Hi Team ,
             I am facing the issue with dbeaver since 2-3 days .I am not able to run my athena queries .Queries are taking much time and giving session timeout error.it also giving other error like Some data source connections wasn't closed on shutdown in 5000ms. Probably network timeout occurred.
Solutions I tried:
    reinstalled many times.
    deleted .eclipse and .metadata files and reinstalled.

![image](https://user-images.githubusercontent.com/39511034/148334908-17179f4d-69f1-4ed7-867c-294fd5a72836.png)
![dbeaver issue](https://user-images.githubusercontent.com/39511034/148335038-c84c8f1a-5d4d-4ecf-88be-4e59c6fc0da4.PNG)

**Comment by LonwoLonwo** [comment]
Hello @Swapnali1996 

What DBeaver version do you use? And what Athena driver version do you use?

We updated Athena driver version in the last version: https://github.com/dbeaver/dbeaver/issues/13784

Maybe your issue is with the new driver?

Then you can try manually change new driver on the old driver version: https://s3.amazonaws.com/athena-downloads/drivers/JDBC/SimbaAthenaJDBC-2.0.16.1000/AthenaJDBC42.jar

![2022-01-06 18_25_26-DBeaver 21 3 2](https://user-images.githubusercontent.com/45152336/148406845-448f86fb-5d63-4794-ab9c-e261f2cea40b.png)

**Comment by Swapnali1996** [comment]
@LonwoLonwo 
 i am using Dbeaver 21.3.2 with athena jar 2.0.25
i also tried older version
also tried to reset workspace .Do you know any way to stop all previous sessions.
![image](https://user-images.githubusercontent.com/39511034/148525843-c2c6b6d3-d191-451b-89d0-e09c2de5e3f5.png)

**Comment by LonwoLonwo** [comment]
Did the old driver version help you to run your athena queries?

Usually, a restart of DBeaver helps to stop all previous sessions.

**Comment by uslss** [comment]
There have been no updates on the issue for a long time. If the issue is still present - feel free to reopen it.
