### ISSUE TITLE
AADSTS700082: The refresh token has expired due to inactivity.

### ISSUE THREAD

**Issue by IanMoroney** [dbeaver/dbeaver#15297]
#### System information: 
- Windows 10
- DBeaver version - 21.3.3
- Additional extensions

#### Connection specification:
- Azure SQL database
- Azure SQL driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? - no

#### Describe the problem you're observing:
When an Azure AD refresh token expires, the driver does not use an access token to generate a new refresh token, or open a browser based workflow to generate a new refresh token.
When the refresh token expires, you can never log into the database again.

Tried:
disconnecting and reconnecting
removing and re-adding connection

#### Steps to reproduce, if exist:
Log into Azure SQL database with AAD & MFA authentication
Wait until refresh token expires (default is 12 hours now)
Try to log into database again.

#### Include any warning/errors/backtraces from the logs

```
Failed to authenticate the user <username> in Active Directory (Authentication=ActiveDirectoryInteractive).
  java.lang.RuntimeException: AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2022-01-25T14:46:36.9135534Z and was inactive for 12:00:00.
Trace ID: db40d60d-a197-4dd8-b301
Correlation ID: a7c7e7ae-631a-4bba-8e1c
Timestamp: 2022-01-26 12:12:25Z
  java.lang.RuntimeException: AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2022-01-25T14:46:36.9135534Z and was inactive for 12:00:00.
Trace ID: db40d60d-a197-4dd8-b301
Correlation ID: a7c7e7ae-631a-4bba-8e1c
Timestamp: 2022-01-26 12:12:25Z
    AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2022-01-25T14:46:36.9135534Z and was inactive for 12:00:00.
Trace ID: db40d60d-a197-4dd8-b301
Correlation ID: a7c7e7ae-631a-4bba
Timestamp: 2022-01-26 12:12:25Z
    AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2022-01-25T14:46:36.9135534Z and was inactive for 12:00:00.
Trace ID: db40d60d-a197-4dd8-b301
Correlation ID: a7c7e7ae-631a-4bba-8e1c
Timestamp: 2022-01-26 12:12:25Z
```

**Comment by IanMoroney** [comment]
Question on this issue, is DBeaver or the Azure SQL Driver doing anything to detect that a refresh token has expired and going through a workflow to request a new one?

**Comment by Matvey16** [comment]
@IanMoroney It seems like an expectected behavior of the driver and looks like we won't be able to change this behavior. Have you seen any other tool that works differently?

**Comment by wayneyaoo** [comment]
Hi is it possible to pop up a Window for re-authentication? If the driver cannot handle the refresh token at least providing a way for user to re-authenticate seems to be a good alternative. I'm having this issue to mostly because of my tenant had hardcoded token expiration time. After the expiration I can no longer connect to the DB with dbveaver because it doesn't allow me to re-auth even rebuild the connection (due to cache I think).

Let me know if i need a separate issue to track this. Thanks.

**Comment by LonwoLonwo** [comment]
Thanks for the report. We will look into it.

**Comment by pinei** [comment]
Same problem here (needed to change the AD password)

AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2022-05-23T13:21:11.7862814Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2022-06-01T23:27:22.0000000Z'.

Windows 10
DBeaver Version 21.3.5.202202200327

**Comment by pinei** [comment]
Problem was solved updating the authentication library (was 1.9.1)

Library: com.microsoft.azure:msal4j:RELEASE
Version: 1.11.3

Don't know if the problem will be back if I change my AD password again

**Comment by LonwoLonwo** [comment]
Interesting solution @pinei 

Then keep us in the know, because your decision will become the basis of the upcoming fix from our side.
