### ISSUE TITLE
Authentication plugin 'caching_sha2_password' cannot be loaded

### ISSUE THREAD

**Issue by zoran-petrovic-87** [dbeaver/dbeaver#15319]
DBeaver Version 21.3.3.202201221033 on WIndows 11, 

When trying to execute script or restore database I get this error: 

```
Task 'MySQL restore' started at Thu Jan 27 22:23:13 CET 2022
ERROR 2059 (HY000): Authentication plugin 'caching_sha2_password' cannot be loaded: The specified module could not be found.
```

When creating DB connection I selected MySQL (when I hover over icon it says "Driver for MySQL 8 and later").

Local client was downloaded by DBeaver:

- Product name: MySQL/MariaDB
- Product version: 5.5.62

**Comment by LonwoLonwo** [comment]
Hello @zoran-petrovic-87 

Can you please try [this solution](https://stackoverflow.com/a/49935803/14220989):

```sql
ALTER USER 'yourusername'@'localhost' IDENTIFIED WITH mysql_native_password BY 'youpassword';
```

**Comment by zoran-petrovic-87** [comment]
Hello @LonwoLonwo

In that case I will be configuring my user on MySQL server to use legacy authorization on MySQL.
I think that this is a bug on DBeaver side since it is using MySQL client that is not compatible with MySQL 8.

**Comment by LonwoLonwo** [comment]
Ok.

Have you tried to connect through MySQL 5 driver? Maybe it can resolve your issue?

![2022-01-28 14_45_44-Connect to a database](https://user-images.githubusercontent.com/45152336/151541822-89dd53ee-cb7e-4f34-9b55-964a214ad40c.png)

**Comment by zoran-petrovic-87** [comment]
@LonwoLonwo after some investigation, this is what I have found:

Case 1:

- User on server is protected with "Default – MySQL **8+**"
- In DBeaver I create connection for MySQL **8**
- I can connect.
- Running '_Tools > Restore database_' or '_Tools > Execute script_' gives this error: _ERROR 2059 (HY000): Authentication plugin 'caching_sha2_password' cannot be loaded: The specified module could not be found._

Case 2:

- User on server is protected with "Default – MySQL **8+**"
- In DBeaver I create connection for MySQL **5**
- I cannot connect. I get this error: _Unable to load authentication plugin 'caching_sha2_password'._

Case 3:

- User on server is protected with "Legacy – MySQL **5.x**"
- In DBeaver I create connection for MySQL **8**
- I can connect.
- Running '_Tools > Restore database_' or '_Tools > Execute script_'  works!

Case 3 shouldn't be necessary but it is a working workaround.  
I think that for some reason DBeaver is not using the same client (maybe different configuration?) when connecting to the database and executing scripts / restoring database. In my book, this is a bug since I am able to connect to MySQL 8 database but options for database restore and execute script are not working.

**Comment by serhiikartashov** [comment]
Workaround for docker:

> docker run --name mysql -e MYSQL_ROOT_PASSWORD=root -d -p 3306:3306 mysql:8.0.27 mysqld --default-authentication-plugin=mysql_native_password

@LonwoLonwo Would it be possible to fix the issue in the 22.1.0 milestone?

**Comment by LonwoLonwo** [comment]
If the problem is in the different connections, maybe disabling these settings can help?

![2022-03-11 12_29_07-Preferences](https://user-images.githubusercontent.com/45152336/157840324-22abf094-fe87-4b1f-8770-7b58eab8931d.png)

![2022-03-11 12_29_33-Preferences](https://user-images.githubusercontent.com/45152336/157840329-da66806d-471a-4e36-9c2c-8671c7bfbefa.png)

**Comment by serhiikartashov** [comment]
@LonwoLonwo these settings (Open separate connections for metadata read and Open separate connection for each editor) do not help with this issue.

**Comment by clicktodev** [comment]
Similar issue, Connection to database is successful however I only get this error when dumping the database.

**Comment by Maxxiey** [comment]
Hey guys, I got the same issue and I managed to find a solution. It works for me (on a windows 10 laptop) and I hope it helps~

In a nutshell, you have to download a `mysql.exe` and `mysqldump.exe` which has the right version (above `8.0`) and use it to do the `dump` and `restore` operations instead of using the default `mysql.exe` and `mysqldump.exe`, whose version is `5.x`.

How to do it? Well, in my case, I downloaded [Mysql Workbench](https://dev.mysql.com/downloads/workbench/) and installed it on my laptop. After that, I added `path to Mysql Workbench` , under which lies those `.exe`, to local client. Then Dbeaver will ask you whether to reconnect using the client you just added, select `Yes` and you are ready to go! 

![企业微信截图_16500068165307](https://user-images.githubusercontent.com/42697295/163537816-bb532aa7-a997-465d-9089-4db711b4be9a.png)

**Comment by aditimahabole** [comment]
![image](https://github.com/dbeaver/dbeaver/assets/78752342/6f3b7002-a40a-4adf-b947-4c49baf5982c)

I am getting above error when I go to http://localhost/phpmyadmin/
this url 

![image](https://github.com/dbeaver/dbeaver/assets/78752342/515df73e-11a4-454e-9a07-eae3ac68814e)

in my xampp both are on 
where is the problem and how to solve it?
please help

**Comment by divinity76** [comment]
When switching from mysql_native_password to `caching_sha2_password` , I get this error on connect from DBeaver:
```
Connection to 'stage2' cannot be established.
Reason:
Public Key Retrieval is not allowed
```
- Googling `Public Key Retrieval` reveal that it's a "client is incompatible with caching_sha2_password" error.
- "Check for updates" reveal that I'm running the latest DBeave CE release version 24.3.0.202412011650
- tried both the bundled MySQL 8.0.19 and 5.5.62 client libraries

as a workaround, I switched to [HeidiSQL](https://github.com/HeidiSQL/HeidiSQL).

**Comment by hichemfantar** [comment]
https://github.com/beekeeper-studio/beekeeper-studio is also available for those who need an alternative

**Comment by Avejack** [comment]
So this problem still persists... I am coming from HeidiSQL because it has no macOS compatibility, but it still seems to be the best client for Windows out there... Sad.

**Comment by marcelo-amorim** [comment]
So years have passed and nobody uses DBeaver to import dumps?
