### ISSUE TITLE
Authentication username is used as database name

### ISSUE THREAD

**Issue by pasolid** [dbeaver/dbeaver#15352]
If authentication username is different than `postgres` while the `Database` field is empty then DBeaver fails to establish a connection to the DB because it uses authentication username as a database name.

I'm using DBEaver Community, Version 21.3.3.202201221033, Release 24th January 2022.

I'm using `pavel` as my authentication user name:
![Screen Shot 2022-02-01 at 17 02 43](https://user-images.githubusercontent.com/76808982/151993589-cdc1b59c-9bb8-4d29-a14d-cae8d43ceea2.png)

When I click on `Test Connection` button I get fatal error that database with name `pavel` does not exists
![Screen Shot 2022-02-01 at 17 04 01](https://user-images.githubusercontent.com/76808982/151993752-8cd93454-b909-420f-b0d7-087b2fc63f9c.png)

Seems like the only reason it worked previously is because I used `postgres` for authentication name.
This is very annoying bug as this prevents from using users names to separate permissions and track users operations in audit log.

**Comment by Matvey16** [comment]
@pasolid That happens because you can't connect to postgres server if no database is specified. We can probably change it so that DBeaver will connect to either of the default databases `postgres` or `template1`. Will that fix your issue?

**Comment by pasolid** [comment]
> @pasolid That happens because you can't connect to postgres server if no database is specified. We can probably change it so that DBeaver will connect to either of the default databases `postgres` or `template1`. Will that fix your issue?

Hey, 
Thanks for response, yes I figured it out already this was the issue.
We don't have `postgres` DB on the servers so it took me a moment later to realize that was needed for postgres server (default one).

The problem is that the error is confusing, instead of something like "empty DB name" for some reason it defaults to user name to be sued as DB name and then fails on that. 

But I do think it would be a better way to  solve it, as you mentioned, to default it to `postgres` if the field is left empty.
Or maybe to avoid hidden logic, then it could be in a style of message that notifies user that if DB name is not specified, then it will use default `postgres` value.  

Up to you

**Comment by andrelinslima** [comment]
Connecting to the database with the same name as the user is the default behavior for postgresql. It is as documented for the native psql client
![image](https://user-images.githubusercontent.com/33740641/156196759-2f09f428-c65a-4e75-b216-d84ebcdc653d.png)

**Comment by iraidaa** [comment]
The issue still exist. I reprosuce the issue using UE 22.2.0. One of the PRO users have encountered this issue too. 

If you select “Show all databases” in the connection settings, and leave the Database field empty on the Main tab, then there will be an error “FATAL: Database <USERNAME> does not exist”. You have to specify the database. You won't get an error, only if the username matches the name of the database, then the Database field on the Main tab can be left blank. 

The error I get:

![image](https://user-images.githubusercontent.com/49681450/190433948-d0637d5b-c43b-484a-9e06-9d277f1afbf3.png)

**Comment by brlarini** [comment]
About this matter, I needed the opposite from what OP described.
I have users that have the same usernames as the databases they own.
For example, user CUSTOMER1 owns database CUSTOMER1; user CUSTOMER2 owns database CUSTOMER2.

These are accessed only by developers, not the customers themselves. So my objective is that there's only one connection profile that developers would use, and the username inserted would default to their database (so the username becomes the selector for the database).

The issue in my case is that this behavior only happens if the 'postgres' database doesn't exist.
So the message "Username is used if not specified" is not true, unless the 'postgres' database was removed.
I was hoping to keep the default database.

Is that intentional? Wouldn't be better if this logic was inverted? (search first for a database with the same name as the username, else, fallback to postgres).

I'm on DBeaver 23.0.0 and PostgreSQL 15.

**Comment by E1izabeth** [comment]
This is the PostgreSQL behaviour. DBeaver doesn't do something with it by himself.

**Comment by brlarini** [comment]
Sorry, maybe I couldn't explain it correctly.
I'll try it again.

1. There's an user called B_TESTE1, but no database with the same name. If I log in now with that user without setting a database in the connection config, it will exit with the error posted by OP: Fatal: database "B_TESTE1" does not exist.
![image](https://user-images.githubusercontent.com/23079160/227620906-8df9b089-5a57-4c25-9600-14ba26cba250.png)

2. Then I create a database with the same name
![image](https://user-images.githubusercontent.com/23079160/227621224-0a51ff28-dbab-4782-973e-0248eb2564c7.png)

3. Now I log in with the B_TESTE1 user (still without setting up the database name in the connection config). No error now, but instead of defaulting to B_TESTE1 database, it will connect to the postgres database anyway.
![image](https://user-images.githubusercontent.com/23079160/227621694-fdc5c8d6-4865-466d-b09c-85af4a4bb7a2.png)

4. I'm pretty sure this is a **peer action** (not PostgreSQL server's responsibility), to set the database you want to connect. For example, I can describe what I had in mind in the command line:
![image](https://user-images.githubusercontent.com/23079160/227622759-448254e2-8794-4e7d-afc6-44715641999a.png)

So, the message in the config says "Username is used if not specified", but even if the database exists it's not what happens.
So, DBeaver is checking if a database with the username's name exist. It gives an error if it doesn't, but if it does exist, **DBeaver does nothing with it** and connect to postgres anyway.

Also, I said something wrong in my previous comment. If postgres database does not exist, DBeaver will default to the first database in alphabetical order (apparently). I had tested only with "A_TESTE1", so I thought it worked.

I hope I was clear enough.
Thanks for your help!

**Comment by E1izabeth** [comment]
Thank you for detailed explanation
