### ISSUE TITLE
AdvancedPaste into Query

### ISSUE THREAD

**Issue by GITMichaelK** [dbeaver/dbeaver#15359]
#### System information: 
- Operating system MANJARO
- DBeaver 21.3.2

#### Connection specification:
- PostgreSQL
- JDBC

A query reports from a single table a couple columns and several lines based on a WHERE-clause. This works fine.  
For this selection I have a CSV-set with updated data which I was planning to "AdvancedPaste" into the query. dBeaver does not allow the AdvancedPaste here. How can I solve this?
**UPDATE:** I found, using the table with a WHERE and an ORDER-statement, it allows AdvancedPaste. Why this difference?

**Comment by uslss** [comment]
@GITMichaelK Could you provide screenshots or video with the issue? It will be helpful for further investigation

**Comment by GITMichaelK** [comment]
Thank you @uslss,
attached a screenshot, sorry for poor quality, I need the context-menu and could not start any snipper while the menu is active.
You can see a sql-query with the sql-statement in the top area. I ran this, the result underneath. I select column ^Name and few lines, then a right click to activate "AdvancedPaste / Erweitertes Einfügen (in German language" (see the small black arrow).  
![AdvancedPaste](https://user-images.githubusercontent.com/34304987/152321437-f03c7d21-ebf9-4c2e-a7d7-06d46db6ef38.png)
The screenshot shows, that this option is greyed-out, not accessible. Why?
As I wrote, I can select from that table  table with the WHERE and the ORDER-statement, this works. Why the difference?

**Comment by GITMichaelK** [comment]
Are there still open questions in regards to my description? @uslss: If not, I'd appreciate if someone could remove the "Wait for  response" flag or let me know, how I can do this.

**Comment by LonwoLonwo** [comment]
Hello @GITMichaelK 

As I can see on your picture, you have read-only columns - they have little orange circle on the column name. 
I'm not sure about "Datum" column, but "^Name" column is generated. It is changed "Vorname" column, yes. But usually DBeaver nothing knows about original column in this case, because not all drivers can return this info.
And since DBeaver does not know which column is original - it cannot insert data into generated column, because it (e.g "^Name") does not actually exist in the table.

I hope my answer helped you. Write if you have any more questions.

![2022-03-22 20_01_36-DBeaver Ultimate 22 0 1 - _postgres_ Script-10](https://user-images.githubusercontent.com/45152336/159535275-8bf46b95-f7b7-4588-9b12-bda312f27998.png)

**Comment by GITMichaelK** [comment]
Thank you @LonwoLonwo  for the explanation, this makes it absolutely clear! Sorry for late response, too much different tings here ...
