### ISSUE TITLE
It is impossible to add new values to nested arrays via UI

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#15429]
related to #14327 
#### System information: 
- Operating system (distribution) and version win10
- DBeaver version 21.3.5

#### Connection specification:
- Database name and version PostgreSQL
#### Describe the problem you're observing:
1. For now, it is impossible to add values to nested arrays via UI accordingly to their structure (only the first root element could be edited).
2. Also it is not possible to add a new root element.

![dbeaver_c7SJiRcWVy](https://user-images.githubusercontent.com/31996417/153054772-ebad111d-7c17-41fb-aec6-4b07d52c2098.gif)

**Comment by ShadelessFox** [comment]
We need to think about the proper UI for that.

We want to add new elements to the selected object, but it will prevent the user from adding new root elements since we can't have the focus set to "nothing".

The issue can be solved by showing a single root element with all its children underneath, but it may look weird.

**Comment by uslss** [comment]
#13804

**Comment by ShadelessFox** [comment]
Perhaps we should create a separate issue (since it is very database-specific) to allow the creation of nested array elements.

**Comment by ShadelessFox** [comment]
Now new elements in the children can be created:

https://user-images.githubusercontent.com/35821147/158216770-95cd08bc-8c24-4a86-8f50-5cc4f3e30037.mp4

**Comment by uslss** [comment]
verified
