### ISSUE TITLE
Filtro não considerando triggers/producedures 

### ISSUE THREAD

**Issue by matheuscomaru** [dbeaver/dbeaver#15625]
Olá pessoal, tudo bem ?

Estou abrindo essa Issue pois não encontrei nenhuma outra com o que preciso. Sobre o titulo, eu não consegui encontrar um título melhor que esse... então se ficou muito genérico, peço perdão.

Eu notei que na versão 7.2.1, quando eu faço o filtro de uma tabela por exemplo, eu consigo expandir e ver todas as triggers que tem nessa tabela, independente do nome do filtro.

![7 2 1](https://user-images.githubusercontent.com/18369750/155647697-420bf8f5-afe2-43d0-9a2e-e2d3047ae859.gif)

Nas versões mais recentes, isso não ocorre, eu preciso remover o filtro e expandir novamente para ver todas as triggers.

![21 3 4](https://user-images.githubusercontent.com/18369750/155647949-f4c14999-b6f2-4fce-93be-0a607c12bd2c.gif)

Se isso for somente uma configuração, poderiam me mostrar onde seria ?

**Comment by andrelinslima** [comment]
A maior parte dos maintainers não fala português, seria mais fácil manter inglês para referência dos outros usuários também.
Há um template para a criação, que pede a versão, tipo de banco, etc, diferentes conectores podem ter comportamentos diferentes.
O título está invertido, você está reportando que o filtro rápido passou a levar em conta as triggers. Isso foi uma alteração em maio do ano passado ( #12362, na versão 21.0.5 ). Não há opção para voltar ao comportamento antigo.
Mas pode ser usado o filtro de tabela ao invés do filtro rápido, para obter o resultado antigo. Basta clicar com o lado direito no nível Tables, selecionar Filter -> Table Filter ( https://github.com/dbeaver/dbeaver/wiki/Filter-Database-Objects ) . O filtro aí não é "substring" por padrão, precisa colocar * no final para fazer match parcial.
![image](https://user-images.githubusercontent.com/33740641/156176158-02c18092-b21b-4847-b22a-7174dd2911f3.png)


Summary: Reporting that current versions (since 21.0.5) quick filter is also filtering out the tiggers related to the table. I'm pointing out that it was changed by #12362, with no option to revert to old behavior. And that it's possible to use Table Filter instead, with slight different syntax, since object level filter is doesn't do partial matches by default

**Comment by matheuscomaru** [comment]
Entendido. Bom, o uso do filtro rápido que era a vantagem para meu processo aqui.

Como não tem como voltar o comportamento antigo, ainda será mais fácil eu clicar na tabela e limpar o filtro rápido em seguida.

De qualquer forma obrigado pela sugestão e resposta !!
