### ISSUE TITLE
Read data in SQL editor require additional action now

### ISSUE THREAD

**Issue by M-Ahall** [dbeaver/dbeaver#15628]
#### System information: 
- Ubuntu 21.04
- Version 21.3.5.202202200327

#### Connection specification:
- Doesn't make a difference

#### Describe the problem you're observing:
When rightclicking on a table and choosing "Read data in SQL editor", the generated SELECT query doesn't execute automatically anymore.

Before, it consisted of two lines of SQL. The cursor was placed at the beginning of the first line. The query executed automatically.

From 21.3.5 (21.3.4 is using the old behavior) there is now an empty line at the bottom, and the cursor is placed there.
It is now necessary to move cursor up and execute manually.

#### Steps to reproduce, if exist:
Right-click on a table and choosing "Read data in SQL editor".

**Comment by LonwoLonwo** [comment]
Hello @M-Ahall 

Thanks for the bug report.

**Comment by ShadelessFox** [comment]
Fixed.

**Comment by Matvey16** [comment]
Verified

**Comment by M-Ahall** [comment]
Hi, thanks for the quick update, but the cursor is still placed at the end of the editor in 22.0.0.

**Comment by ShadelessFox** [comment]
Hello @M-Ahall,

We have fixed the other issue (#15562) within this issue.

As described in this issue, only the latter query was executed (or no query at all) because the cursor is moved to the editor's end. We fixed that, and now the first query is performed as in previous versions.

Some of my colleagues think that the current cursor's behavior makes sense. Think of the `Read data in SQL editor` action as an operation that results in a new SQL editor window containing the template script. You might expect the cursor to be placed at the end, so you can start writing your own queries right ahead.

But since it is a behavioral regression, we will discuss it and fix it within #15765.
