### ISSUE TITLE
Dbeaver 21.0.4 external updates in tables not visible

### ISSUE THREAD

**Issue by icstreispe** [dbeaver/dbeaver#15786]
I am using version 21.0.4.202105021514 of Dbeaver and connect to Oracle database.
Using sql editor set up to manual commit & smart commit mode & read commited:
I do a query, results are ok
I externally modify the table queried and change some data (using another application or sql developer tool)
I can see the changes in the table data in sql developer tool but not in dbeaver
Same problem happens if I extternally change the definition of the table, no updates of the information in dbeaver to see the new or changed constraints.
What is going on? What should a change? I couldnt find this issue on the net, so it must be something Im doing wrong. Where should I look. Please help
PS I am using Windows 10, Oracle driver ojdbc8 12.2.0.1, direct connection to database, no extension to dbeaver

**Comment by Karlodun** [comment]
-->> Change to auto commit mode.

This is not a DBeaver issue. Oracle uses MVCC:
https://docs.oracle.com/cd/E17276_01/html/bdb-sql/mvcc.html

Which means different versions of the table can exist. If any of the "editors" (who updates or inserts values into table, not SQL clients) or you as a reader enter a session, you will not see changes of other users.
By using manual commit you will enter an isolated session which will stay stable until you logoff or commit the changes.
This is not a bug, this is on purpose.
Imagine you run a count(*) on a table, while values are continuously inserted.  Your query would never end or give weird results. You always want to know the count for the time when you actually fired the query.
Same counts for changes of the data model. There are only few changes which will break through your session.

**Comment by icstreispe** [comment]
So you are telling me that in this dBeaver program there is no way I can see external commited modifications on tables after I did some initial queries on them? Even if I dont do any modifications on the tables but only queries. If it is possible tell me how do I set dBeaver up so I can still commit manually every modification (write) I do.

**Comment by Karlodun** [comment]
It is not a DBeaver feature. You are using manual commit. In manual commit
mode you force the db to stay "frozen" for you. Most other SQL clients do
not support these postgres features.
Change to autocommit and it will work.
Imagine like this: manual commit keeps your queries running inside a BEGIN
block.
So you could use real BEGIN blocks instead of manual commit mode.

пт, 11 мар. 2022 г., 01:06 Mihai ***@***.***>:

**Comment by icstreispe** [comment]
But if I change to autocommit any modification will be automatically commited to the database? The others will see those modifications immediately after I run them?
Experimented now and:
If I choose autocommit + smart and do a commit/rollback manually it fails to go back to autocommit mode after that (its not that smart).
If i choose autocommit + no smart it autocommits everthing which is not acceptable.
**So what options should I choose** in order to **not have an autocommit but a manual commit on modifications** (insert/update/delete) and **still be able to see what others have commited meanwhile**. I think it's something missing in this dbeaver cause I can do these things in SQLDeveloper.
PS just to be more clear, in sqlDeveloper I can do this:
1. query 
2. do an insert and not commit 
3. query to see the uncommited insert 
4. externally do an insert 
5. query again to see my uncommited insert + the newly externally added line
what special combination allows me to do the same in dBeaver?

**Comment by Karlodun** [comment]
You could set DBeaver to use separate connections for each editor and you could keep one of them in auto-commit mode, while keeping another one in manual commit mode.
Also you can use DBMS internal "BEGIN; ..... END;/ ROLLBACK;" Functionality to start and either commit and end or rollback a transaction.

![image](https://user-images.githubusercontent.com/11210115/157873491-b217507d-b015-4e07-b3b2-324dd674edcd.png)

**Comment by icstreispe** [comment]
for a user friendly tool that should simplify user life don't you think its a little too much work for such a basic request?

**Comment by icstreispe** [comment]
I have already set up dbeaver with that checkbox as you suggest and the behaviour brought me here. 
Also do you suggest that I have 2 editors open and use one for my inserts and another for seeing the real image in the database? If so thats a little complex also.
I do my inserts in the editor and prefer to click a commit/rollback button on every successfull (chain of) operation (after I check with a query everything was ok) so using scripts and creating transactions for trivial tasks looks like an overkill. I thought that's the purpose of a user application, to simplify user actions. I am dissapointed to say the least cause I've seen the program has a small memory footprint.

**Comment by Karlodun** [comment]
I can feel your frustration, but here is the thing:
You want to run an isolated and a non-isolated sessions at same time. This is complex.
You cannot see changes in a DB from within an isolated session, which happen in other sessions. Has nothing to do with DBeaver it has something to do with DBMS.
If you have SQL Editors which can do this, then they are broken. The purpose of an isolated session is to be in an isolated session.
DBeaver supplies the power to work with such a complex requirement, but you still need the knowledge.
My suggestion is to go and to read about MVCC and how to run sessions. You also need to understand how multi-tenant databases work, otherwise you might screw up your data. And from your comments I must tell: you're on a good way to do so and I'm talking out of experience.

If you want to probe several operations and then apply them: store the scripts and run them one by one. DBeaver offers you possibilities to copy the scripts, instead of saving data changes. If you are working qualitatively (changing single entries) then you should also create scripts to check whether the data you want to change is still there and your change makes sense, or make smarter update statements.

**Comment by LonwoLonwo** [comment]
Hello @icstreispe 

Do you still have any questions after all this discussion? 
About the main topic - yes, DBeaver can't show external changes. It doesn't work like that.

**Comment by icstreispe** [comment]
This dBeaver seemed to me over engineered and very complicated and instead of using very simple buttons to use it we need to change switches and routes inside it just to make it behave like a normal sql editor. So I just had to abandon it even though it had a small memory footprint and a couple of other cool features I liked. Maybe in the future will get simpler for the user, cause now its simple only for the developer.

**Comment by LonwoLonwo** [comment]
Sorry to hear it.
