### ISSUE TITLE
Confirm 'Delete this script' in the the SQL Editor tab context menu

### ISSUE THREAD

**Issue by racic** [dbeaver/dbeaver#15798]
#### System information: 
- Operating system (distribution) and version: Archlinux newest
- DBeaver version: 21.3.4.202202142347
- Additional extensions: none

#### Connection specification:
N/A

#### Describe the problem you're observing:
It is possible to permanently delete a SQL file (or any file) opened in the SQL editor from the tab context menu.

#### Steps to reproduce, if exist:
In the open SQL Editor tab click RMB to see context menu.

#### Include any warning/errors/backtraces from the logs
N/A

This is a bad UI design practice. Even with a confirmation modal window, it is still inappropriate place for such a profound action. It is too similar to other actions that require confirmation too. Permanent deletion of a file calls for at least familiar file management window, if not external file manager to handle the issue.

**Comment by Karlodun** [comment]
You're asking to delete a feature, because you've failed hitting proper option / reading the confirmation window. Confirmation windows are there to be read, not ignored.
DBeaver saves you already so much of your work time, spend those 2 sec.

Using this feature a lot.
Sometimes I'm working with >30 open scripts, and many of them are not needed sooner or later. Searching for the file in project navigator is an overhead.

**Comment by racic** [comment]
First thing DBeaver is a really great tool, no doubt.
But ..

> Confirmation windows are there to be read, not ignored.

This is always true.

This particular option as well as the confirmation window is barely distinguishable from other options however, and it leads to a irreversible action which results in a possible loss of your work. 

In my case I misclicked and wanted to quickly do away with the annoying window and .. I deleted my own work from the file system, from the context menu of a tab. It is just unexpected. But I fully take blame for not reading the confirmation window's contents :).

Still, I think you can agree that no other option in the context menu has such severe effect, so, some sort of color-coded warning inside the confirmation modal would be sensible I think, maybe a red button with label 'Yes, delete this file' ?

**Comment by Karlodun** [comment]
We're all human, we all make mistakes.
Adding some color to the button and to the confirmation window would be nice.

Since a warning color will not be sufficient to 100% prevent from such failures, here some additional hints:
1. don't put too much code into single script file.
2. If needed use query history to recover lost code. 
3. do Backups of your final scripts, ex. with GitHub, or in a dedicated folder. You can export whole projects once a week / month.

**Comment by Matvey16** [comment]
@racic Thank you for the report. If anything, the confirmation should for sure have a red exclamation mark to emphasize the fact that something is going to get deleted. We will see what we can do about it.
