### ISSUE TITLE
"Next Query", "Previous Query" shortcut keys work error

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#15839]
#### System information: 
- Windows 10 Pro
- DBeaver 22.0.0
- Additional extensions

When executing "Next Query", "Previous Query" shortcut keys, general SQL works normally.
However, in the "@set" syntax, it moves only to the upper syntax.

Thank for reading.

**Comment by ShadelessFox** [comment]
Hello @podoni,

I cannot reproduce your issue:

https://user-images.githubusercontent.com/35821147/158419462-4ed3be48-fca8-4599-8e61-5c8f6c78d6ba.mp4

Could you please provide a little bit more information about your issue?  What database are you using?

**Comment by podoni** [comment]
This error occurs when there are multiple "@set" statements.
In the previous version, it worked normally.

For example

@set col1 = '1'
@set col2 = '2'
@set col3 = '3'
@set col4 = '4'
@set col5 = '5'

SELECT 'test1' FROM daul;

SELECT 'test2' FROM dual;

Thank for reading. :)

**Comment by ShadelessFox** [comment]
Now I was able to reproduce the issue. Thanks for the clarification.

**Comment by arvillion** [comment]
Hello, @ShadelessFox . I'd like to work on this issue.

**Comment by ShadelessFox** [comment]
Hello @arvillion,

We are open to contributions!

You can read more about the development process in our wiki: https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse

**Comment by arvillion** [comment]
It seems that the problem occurs that when the cursor is put at the head of commands like `@set col1 = '1'`, because then the program will mistake the current script element.

I found that commands like `@set col1 = '1'` are recognized as token of type `SQLTokenType.T_CONTROL`. This kind of token will set the variable `isDelimiter` to true and cause the problem in the following code.

So my idea is not to set the variable `isDelimiter` to true when encountering tokens of type `SQLTokenType.T_CONTROL`. It seems that the issue is solved through it.

https://user-images.githubusercontent.com/3462292/159030942-e2cf15f8-9a3c-4685-abe6-e7b1f5d29ddd.mp4

If this behavior is expected, I will submit a PR later :)








`.

**Comment by ShadelessFox** [comment]
AFAIK this type of token is used only for such control statements, so it should be fine.

You can submit your PR addressing this issue :)

**Comment by uslss** [comment]
verified
