### ISSUE TITLE
How to disable "Problems" tab

### ISSUE THREAD

**Issue by JamesInform** [dbeaver/dbeaver#15977]
DBeaver 22.0.1
OS: Mac
DB: PostgreSQL

I just updated to DBeaver 22.0.1 on Mac and there is a new "problems" tab that appears every time  an sql statement has an error.
This tab hasn't been there before and it steel valuable space on my desktop.

<img width="1492" alt="image" src="https://user-images.githubusercontent.com/38714600/160236609-563d4e7e-0c89-470a-982b-cc03ff39e3da.png">

Question: How can I prevent the "problems" tab from appearing automatically?
If this is not possible, please add a configuration option to do so as soon as possible.

Greetings,
James

**Comment by ghost** [comment]
DBeaver 22.0.1
OS: Windows 10
DB: MS SQL Server

I have this same problem. I can't find a way to disable it. I've tried every filter option and it still appears when an sql statement has an error. It can be undocked but not put into the same pane as the Results tab. My preference is not to see it at all. The SQL error is quite clearly shown in the Results tab,

Thanks,
Paul

**Comment by LonwoLonwo** [comment]
Hello @JamesInform and @PaulSlater25 

The [new option](https://github.com/dbeaver/dbeaver/issues/15961) was added a few days ago and will be available in the next DBeaver release 04-04-2022.
Or you can download the [Early Acces](https://dbeaver.io/files/ea/) version. The fix is available in the Early Acess version.
