### ISSUE TITLE
Turn off red underline

### ISSUE THREAD

**Issue by rjake** [dbeaver/dbeaver#15989]
**Is your feature request related to a problem? Please describe.**
When a query encounters an error, all the text of my script is underlined in red. I do not find this to provide helpful information. It actually makes it harder to edit the code as becomes difficult to distinguish commas from periods. I also cannot find a setting to disable it. I noticed it started with the latest release (22.0.1)

**Describe the solution you'd like**
I'd like the red squiggly line to be more selective (in this example, underline all instances of `wk`) or for it to be easy to turn off. When I looked at settings relevant to "underline" and "error", I did not see a setting to change. I might've missed it.

![image](https://user-images.githubusercontent.com/14003618/160453221-8677cbae-cc35-46b9-a7fa-2465dc0b04cf.png)

**Comment by LonwoLonwo** [comment]
The [new option](https://github.com/dbeaver/dbeaver/issues/15961) was added a few days ago and will be available in the next DBeaver release on 04-04-2022. Option to disable issue marking.

Or you can download the [Early Acces](https://dbeaver.io/files/ea/) version. The fix is available in the Early Acess version.
