### ISSUE TITLE
Words that start with underscore are treated as keywords

### ISSUE THREAD

**Issue by michal-bartak** [dbeaver/dbeaver#16132]
#### System information: 
- Operating system (distribution) and version: Fedora 35
- DBeaver version: Version 22.0.2.202204041542
- Additional extensions: N/A

#### Connection specification:
- Database name and version: Postgresql 12, 13
- Driver name: Postgres
- Do you use tunnels or proxies (SSH, SOCKS, etc)? NO

#### Describe the problem you're observing:
Keywords, when prefixed with non-literal characters are still highlighted as keywords. 
While a lot of those non-literals are not valid as starting characters for variables, underscore is an accepted one.
This results in highlighting words like _sql, _default as to be keywords. Which is obviously not true.
See the image below.
it's just a screenshot of a fragment of the code. Note % as variable name prefix will not work likely. Just to show behavior pattern.
![image](https://user-images.githubusercontent.com/7868445/162442869-6a79d005-6265-45fd-b2b4-4085c4615a1f.png)

#### Steps to reproduce, if exist:
See above

#### Include any warning/errors/backtraces from the logs
N/A

**Comment by E1izabeth** [comment]
Thank you for bug report

**Comment by PILINING** [comment]
Hello, I'd like to work on this issue.

**Comment by PILINING** [comment]
It seems that the problem arises in the determination of the starting character of the word when the word is detected.

When '_' is detected, `isUnicodeIdentifierStart('_')` in `isWordStart()` will return false, which causes evaluate to return `TPTokenAbstract.UNDEFINED`.

So my idea is to add a judgement on ' _ '  to `isWordStart()` so that it will return true when '_' is encountered. 
This seems to solve the issue.
![screenshot](https://user-images.githubusercontent.com/58755868/164889885-9a8fad2e-e9e2-497a-967d-67cbc914d57b.png)

**Comment by PILINING** [comment]
#16290
