### ISSUE TITLE
Context menu in SQL Editor doesn't respect cursor position on which it is called

### ISSUE THREAD

**Issue by Matvey16** [dbeaver/dbeaver#16172]
#### System information: 
- Operating system (distribution) and version Win10
- DBeaver version 22.0.3

#### Steps to reproduce, if exist:
1. Type two different queries in SQL Editor (e.g. two selects from different table)
2. Left-click on one of the queries to put a text cursor on it
3. Right-click on another query and pick Export from query in the context menu
4. Perform export

**Expected:** Exported data is fetched from the query on which the context menu was called
**Actual:** Data is fetched from the query that had the caret prior to the right-click

![dbeaver_tqH2Y3T4m9](https://user-images.githubusercontent.com/82543000/163142889-026a38b2-6845-4855-b49c-28e15651677f.gif)

**Comment by CalmaKarma** [comment]
Hi, @Matvey16 . I'd like to work on this issue!

**Comment by CalmaKarma** [comment]
@Matvey16 I do not think it's a bug, but an intentional feature.

To demonstrate, for example, there are two lines of code. I put a text cursor in the first line(regardless of inserted between letters or selecting letters), and I right-click on the second line:

1. In some cases using other editors like PyCharm, it will first place the text cursor to the second line, and the context menu will always be from wherever the text cursor is,  which is the second line in this case.

2. In other cases, like Eclipse which dbeaver uses, it does not re-place the text cursor. The text cursor will still be in the first line as-is, and the context menu will still regard to the first line, regardless of where I right clicked.

I think either way is can be chosen by developers intentionally, as both have advantages and disadvantages. To me, it seems like DBeaver chose the second way, as DBeaver depends on Eclipse, and Eclipse goes for the second way.

**Comment by ShadelessFox** [comment]
We need to respect block text selection as well.
