### ISSUE TITLE
Patch query with limit causing problem on ClickHouse

### ISSUE THREAD

**Issue by zhicwu** [dbeaver/dbeaver#16189]
#### System information: 
- macOS 12.3.1
- DBeaver Version 22.0.2.202204021640

#### Connection specification:
- ClickHouse 22.3
- clickhouse-jdbc 0.3.2-patch7
- No tunnel or proxy used

#### Describe the problem you're observing:

`select * from numbers(5) format JSONEachRow` does not work because DBeaver patched the query with limit, resulting below query sent to ClickHouse. This was discussed in PR #15492.

```sql
select * from numbers(5) format JSONEachRow
LIMIT 0, 200
```

#### Steps to reproduce, if exist:

Issue above query against ClickHouse.

**Comment by E1izabeth** [comment]
Hi, @zhicwu! Thank you for bug report! 
You can turn off "Use SQL to limit fetch size" setting (Connection settings -> Data editor). It should help.

![image](https://user-images.githubusercontent.com/28875055/163466739-8d38eca2-ffb7-4896-b3e2-ace3cb0fe8aa.png)

I think we should return it back to disabled state by default as it was workaround due to bug in Clickhouse driver. Now bug seems to be fixed https://github.com/dbeaver/dbeaver/pull/15492#issuecomment-1066736083.
