### ISSUE TITLE
Trailing semicolons cause queries not to run

### ISSUE THREAD

**Issue by Petrosophia** [dbeaver/dbeaver#16242]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 22.0.3 (also happens on 22.0.2)
- Additional extensions: None

#### Connection specification:
- Database name and version: Netezza 
- Driver name: jdbc
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Attempting to run any query for which there is a semicolon on a line by itself at the end of the query produces no results, but running it either without the semicolon OR with the semicolon at the end of the last line of the query (i.e. not on a line by itself) does produce results.

#### Steps to reproduce, if exist:
```
SELECT * FROM table;
--this runs
```
vs
```
SELECT * FROM table
--this also runs
```
vs
```
SELECT *
FROM table
;
--this does not run
```

**Comment by E1izabeth** [comment]
Hi, @Petrosophia! Thank you for bug report! It has been already reported here [#16077](https://github.com/dbeaver/dbeaver/issues/16077). As a workaround you can try this [#16077 (comment)](https://github.com/dbeaver/dbeaver/issues/16077#issuecomment-1099991921).
The bug will be fixed in 22.0.4 with [#16218](https://github.com/dbeaver/dbeaver/pull/16218). I'll close this issue.
If you encounter the same problem after upgrading to 22.0.4, please, reopen this issue.
