### ISSUE TITLE
Restore Database Navigation Expanded/Collapsed state after restarts 

### ISSUE THREAD

**Issue by jmagnone** [dbeaver/dbeaver#16293]
**Is your feature request related to a problem? Please describe.**
I have a list of database connections configured and showing under the Database Navigation pane. Usually, I keep the tree organized with the connections that I use the most expanded, and I keep all other nodes collapsed. 

But when Dbeaver is restarted, all the nodes in the Database Navigation pane appear collapsed.

![image](https://user-images.githubusercontent.com/202688/164999758-294a1b04-2342-4420-b293-884964596bed.png)

**Describe the solution you'd like**
It would be great if Dbeaver could save the state of the Database Navigation pane and its tree when restarting the app, preserving the open nodes.

**Describe alternatives you've considered**
The only alternative I found is starting to open the same nodes in the tree again after restarting Dbeaver.

**Additional context**
I am currently using Dbeaver Version 22.0.0.202203060510 in Windows 11 but this concern has been ongoing for years.

**Comment by uslss** [comment]
Hi @jmagnone , mentioned behavior could be changed in Preferences. Also, restore depth could be set. Does it resolve your issue?
![image](https://user-images.githubusercontent.com/31996417/165053741-c0ed9801-4c1a-4e14-946d-33dcdf199413.png)

**Comment by rccc** [comment]
Hello,

In my case checking "Expand navigation tree on connect" and settings the restore depth to "3" does not have any effects. 

I can't stand to click so many times anymore. Do not want to use dbeaver anymore because of this.

Dbeaver community 22.2.5 on Debian 10.

**Comment by Kaldo** [comment]
I have a fresh installation of dbeaver and this issue is still present, even after checking the "Expand navigator tree on connect" and setting "restore navigator state up to depth" to any number. Any time I close and reopen dbeaver, all the folders with connections are fully collapsed and I have to go folder by folder and reopen them manually every day.

This ticket has been closed in error because the proposed solution is not for the issue the user was describing. This setting only expands the connection details upon connection, not the connections themsevels upon restart of dbeaver (even if they are disconnected).

**Comment by kevin868** [comment]
This may slightly help - if you primarily care about one connection.. You can save the navigation state of one object :)

Click the `Save database navigator filter` option, right at the same spot mentioned above.

**Comment by JormungandrWrangler** [comment]
I know this is a supposedly closed issue, but I still have this problem and can't find a solution.

I already have the "_Expand navigation tree on connect_" checked, as well as "_Save database navigator filter_".
"_Elements fetch size_" is set to 5000 and "_Restore navigator state up to depth_" to 25.
But every time I reconnect (which I have to do every several hours because of expiring access tokens I am required to use) the navigator reopens, but ALWAYS defaults to "_Databases -> postgres -> Schemas -> public_" !

I don't know If I am missing something, or if the feature just doesn't work as intended, but it is also a reason for me to maybe stop using DBeaver if I can't find a way to make this work. (It obviously should also work on closing/reopening DBeaver)
