### ISSUE TITLE
Editor SQL: End Statement with semicolon in Script SQL not working properly

### ISSUE THREAD

**Issue by ceugenio** [dbeaver/dbeaver#16311]
#### System information: 
- Windows 10 pro
- DBeaver version   22.0.3.202204170718

#### Connection specification:
- Driver name DB2 iSeries/AS 400

#### Describe the problem you're observing:
After the update to this version old script stop to work, cause the end of the SQL statement is not recognized properly. If the semicolon is placed at the beginning of a new line after the statement it is not recognized.

#### Steps to reproduce, if exist:

![image](https://user-images.githubusercontent.com/15365719/165248058-d93f2d75-8831-4ef1-bf9b-98c9ce8c3b9f.png)

When I execute the statement, I can see that the query is only the semicolon.

![image](https://user-images.githubusercontent.com/15365719/165248359-2f8d21c4-4b1d-40ab-8b8c-4366878fd03e.png)

**Comment by E1izabeth** [comment]
Hi, @ceugenio! Thank you for bug report! It has been already reported here [#16077](https://github.com/dbeaver/dbeaver/issues/16077). As a workaround you can try this [#16077 (comment)](https://github.com/dbeaver/dbeaver/issues/16077#issuecomment-1099991921).
The bug will be fixed in 22.0.4 with [#16218](https://github.com/dbeaver/dbeaver/pull/16218). I'll close this issue.
If you encounter the same problem after upgrading to 22.0.4, please, reopen this issue.
