### ISSUE TITLE
sql statement delimiter no longer being recognized in certain situations

### ISSUE THREAD

**Issue by mahonetim** [dbeaver/dbeaver#16348]
#### System information: 
- Windows 10 Pro version 1607
- DBeaver version: 22.0.3.202204170718
- Additional extensions: NA

#### Connection specification:
- Database name and version: Snowflake
- Driver name: JDBC 3.13.14
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describe the problem you're observing:
I just upgraded from DBeaver version 22.0.0, so not sure which release this started on, but I have never experienced this issue on 22.0.0 or earlier. Now when my sql statement delimiter is on the very first space of a new line, it is no longer being recognized and the sql statement corresponding to it is not parsed and executed. If the delimiter is any other position (immediately at the end of the sql or even not on the first position of the new line) it works fine, but when it is the very first character of a new line its not being recognized.

#### Steps to reproduce, if exist:
Open a new connection (I'm using snowflake, I'm not sure if this is a problem with other connections) and a new sql editor, this code is not executed with either Ctr + Enter or Alt + x 

SELECT 1
FROM DUAL
;  -- this is the issue

however with the delimiter in any other place it will work fine:
SELECT 1
FROM DUAL; 

SELECT 1
FROM DUAL
  ;  --indented

**Comment by E1izabeth** [comment]
Hi, @mahonetim! Thank you for bug report! It has been already reported here [#16077](https://github.com/dbeaver/dbeaver/issues/16077). As a workaround you can try this [#16077 (comment)](https://github.com/dbeaver/dbeaver/issues/16077#issuecomment-1099991921). The bug will be fixed in 22.0.4. 
I'll close this issue. If you encounter the same problem after upgrading to 22.0.4, please, reopen this issue.

**Comment by mahonetim** [comment]
I apologize, I tried searching for open issues relating to this before submitting, but didn't find that one. Thank you.
