### ISSUE TITLE
Semicolon on same line or next line

### ISSUE THREAD

**Issue by ahhmedbilal** [dbeaver/dbeaver#16353]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 22.0.3
- Additional extensions

#### Connection specification:
- Database name and version: Teradata 17.10
- Driver name: Teradata JDBC 17.10
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

when i run this sql...
sel * from dbc.DBCInfo d; 
it is run fine. 
![image](https://user-images.githubusercontent.com/46369037/165727367-25f507fe-270b-4f3c-bd6c-b0788f26ba4c.png)

but when i run this

sel * from dbc.DBCInfo d
; 

then i get following error...
![image](https://user-images.githubusercontent.com/46369037/165727238-6a9cf8c3-3a9e-42b9-ac0c-40bd6444fc2e.png)

however this sql was running fine on 21.1.x ver....

**Comment by E1izabeth** [comment]
Hi, @ahhmedbilal! Thank you for bug report! It has been already reported here [#16077](https://github.com/dbeaver/dbeaver/issues/16077). As a workaround you can try this [#16077 (comment)](https://github.com/dbeaver/dbeaver/issues/16077#issuecomment-1099991921). The bug will be fixed in 22.0.4. 
I'll close this issue. If you encounter the same problem after upgrading to 22.0.4, please, reopen this issue.
