### ISSUE TITLE
[bug]can not auto refresh，Mistakenly deleted other data for SQLite

### ISSUE THREAD

**Issue by hktalent** [dbeaver/dbeaver#16375]
<img width="432" alt="image" src="https://user-images.githubusercontent.com/18223385/166097347-5d600a70-cf2e-4f4a-a342-89e4899a3f4a.png">

<img width="682" alt="image" src="https://user-images.githubusercontent.com/18223385/166097304-555ef6a6-abbd-4caf-b0c2-02a5bc6d7942.png">

<img width="645" alt="image" src="https://user-images.githubusercontent.com/18223385/166097222-211bbbaa-d3e3-4b3f-ab74-19e50697f0fa.png">

<img width="997" alt="image" src="https://user-images.githubusercontent.com/18223385/166097212-ede0ae94-fff8-45ce-9d3d-dad880e21088.png">

can not auto refresh
After multiple operations above, manually refreshed, and then found that the data that was not deleted was also deleted by mistake
Now, there is no data
a big bug
<img width="980" alt="image" src="https://user-images.githubusercontent.com/18223385/166097272-6d03fa18-5a13-4b57-8d01-036c3a9226d1.png">

😭😭😭😭😭

**Comment by Destrolaric** [comment]
Hi, could you provide the video that demonstrates mentioned issue?

**Comment by LonwoLonwo** [comment]
Hello @hktalent 

I can see in your table that you have the "id" column marked as a key. But unlike other databases, SQLite can have a NULL value as a value for the Primary key column. And this is not correct because the value must be unique for the good work of the primary key.

![2022-05-02 12_50_36- bug can not auto refresh，Mistakenly deleted other data for SQLite · Issue #1637](https://user-images.githubusercontent.com/45152336/166218133-9c16ca6d-4f58-4459-92fa-a47f52e5a904.png)

![2022-05-02 12_54_37-Preview Changes](https://user-images.githubusercontent.com/45152336/166217752-4b6b22c1-b02d-4427-84c3-887bbcd59e58.png)

**Comment by LonwoLonwo** [comment]
You can check your delete script with the help of the "Script" button.

![2022-05-02 13_06_49-Preview Changes](https://user-images.githubusercontent.com/45152336/166218351-628f7434-c4a0-4664-a418-0653af39c3d0.png)

**Comment by hktalent** [comment]
It is confirmed that it is because the id is empty
