### ISSUE TITLE
SQL Formatting settings are not applied correctly

### ISSUE THREAD

**Issue by Essentia-G** [dbeaver/dbeaver#16408]
Go to Preferences -> Editors -> SQL Editor -> Formatting
1. Uncheck "Use bold font for keywords": does not apply to an existing query (and new queries too)
2. Change a keyword case: does not apply to an existing query, but works with a new one
3. Check "Insert line feed before commas": does not apply to an existing query, but if you select a query and go to Format -> Format SQL in the context menu, it will apply. Now if you uncheck this checkbox the comma will remain in the same place.
---
It make sense to check the behavior of other formatting settings.

**Comment by Essentia-G** [comment]
![bold or not](https://user-images.githubusercontent.com/54938058/166683114-1612f3a0-63cb-490a-8ae7-8680082c2fbe.gif)

**Comment by Tazhio** [comment]
I tested this bug on my dbeaver as well. This feature never worked on my side except in the preference previewer. I think this bug happened because the SQL formatting feature was not implemented except in the preference previewer. I tried to work on this, and here is the improvement. 

Now clicking on the formatting preference page will actually perform changes. But to perform changes several times may require the user to reopen the script file. 


<img width="1440" alt="Screen Shot 2022-05-26 at 20 57 08" src="https://user-images.githubusercontent.com/39872036/170492190-2101f442-ae49-467a-85a7-fbd517d238a8.png">
<img width="1438" alt="Screen Shot 2022-05-26 at 20 57 20" src="https://user-images.githubusercontent.com/39872036/170492196-d5fc73bf-6713-4c5c-9e2d-c05736e110d7.png">
<img width="1439" alt="Screen Shot 2022-05-26 at 20 57 33" src="https://user-images.githubusercontent.com/39872036/170492205-e6bf4902-1b27-45fa-bb7a-a828867de483.png">
