### ISSUE TITLE
Value in the cell is not highlighted.

### ISSUE THREAD

**Issue by troizet** [dbeaver/dbeaver#16435]
#### System information: 
- Operating system: Ubuntu 20.04
- DBeaver version: 21.3.4.202202051448, 22.0.4.202205011839

#### Describe the problem you're observing:
When you double-click on a cell with the data type date, the value in the cell is not highlighted.

https://user-images.githubusercontent.com/9607501/167280542-3c5e2c41-39e0-4001-b671-f2269b58adeb.mp4

**Comment by PILINING** [comment]
Hello, @troizet, is this issue a duplicate of #16436 ?

**Comment by E1izabeth** [comment]
This issue is about changing the cell borders, [another one](https://github.com/dbeaver/dbeaver/issues/16436) is about value selection. I see on the video you submitted in the [comment](https://github.com/dbeaver/dbeaver/issues/16436#issuecomment-1137295015) that your PR might cover it too. So, if your PR pass QA and will be merged, it will close this issue too.

**Comment by PILINING** [comment]
> This issue is about changing the cell borders, [another one](https://github.com/dbeaver/dbeaver/issues/16436) is about value selection. I see on the video that you submitted in the [comment](https://github.com/dbeaver/dbeaver/issues/16436#issuecomment-1137295015) that your PR should cover it too. So, if your PR pass QA and will be merged, it will close this issue too.

I see, thanks you for your explanation. 😃

**Comment by troizet** [comment]
Yes, E1izabeth explained it correctly
