### ISSUE TITLE
"Create new connection from JDBC URL" dialog does not find drivers.

### ISSUE THREAD

**Issue by raymond-lum** [dbeaver/dbeaver#16446]
#### System information: 
MacOS Intel 64
DBeaver 22.0.4

#### Describe the problem you're observing:
When going to the "Create new connection from JDBC URL" dialog and typing in a JDBC URL, the Drivers never lists a suitable driver.

#### Steps to reproduce, if exist:
1. Install and launch DBeaver 22.0.4
2. Go to Database > New Connection from JDBC URL
3. Type in the field JDBC URL "jdbc:postgresql://localhost
Expect to see the PostgreSQL driver listed but it doesn't.

Note the same is for any other driver (i.e. mariadb, etc.)

When I try DBeaver 21.3.5 this works as expected in that it shows the Drivers and allows me to proceed.

**Comment by ShadelessFox** [comment]
Hello @raymond-lum,

This URL is matched against the sample URL of the driver.

In the case of the PostgreSQL driver, there's a mandatory `/` at the end, so `jdbc:postgresql://localhost/` should match just fine.

Of course, we could improve this behavior to be driver-agnostic since it will give us a lot of room for enhancements.

**Comment by ShadelessFox** [comment]
Will be fixed within #16129
