### ISSUE TITLE
[MySQL] Can't delete row with JSON column

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#16687]
#### System information: 
- Win11
- DBeaver CE 22.1.0

#### Connection specification:
- MySQL

#### Describe the problem you're observing:
The row with column of JSON type can be deleted, but it returns after the table refresh

https://user-images.githubusercontent.com/43252954/171807856-a950f3ee-8ca1-4e64-b50c-d337c63321d2.mp4

#### Steps to reproduce, if exist:
1. Create a table with json column
2. insert some data
3. try to delete row

#### Include any warning/errors/backtraces from the logs
no errors in the error log

**Comment by LonwoLonwo** [comment]
As I can see, the problem is in the DELETE statement, in the WHERE part. Probably we can't use some statement like this:

```sql
DELETE FROM mydbtest.t1_json
	WHERE c1='{"x": "red"}'
```

Also we can't use json column as a key in the table.

![2022-06-06 10_17_47-DBeaver Ultimate 22 1 0 - t1_json_key](https://user-images.githubusercontent.com/45152336/172114685-51d3a708-d3ab-4880-adcc-b5739503e403.png)

Maybe we can use some workaround like in PG: https://github.com/dbeaver/dbeaver/issues/11704
