### ISSUE TITLE
Dbeaver is very slow to run big SQL scripts

### ISSUE THREAD

**Issue by lukaseder** [dbeaver/dbeaver#16756]
#### System information: 
- Operating system (distribution) and version: Microsoft Windows [Version 10.0.22000.675]
- DBeaver version: Version 21.3.2.202112271055

#### Connection specification:
- Database name and version: Any, they're all the same

#### Describe the problem you're observing:

I'm often loading big piles of data into a database. For some databases, I don't have any tools to expedite this process, so I'm using Dbeaver. The loading takes forever in some cases, e.g. 20 minutes.

#### Steps to reproduce, if exist:

Use any of these sakila database scripts, e.g. the SQL Server one:
https://github.com/jOOQ/sakila

- https://github.com/jOOQ/sakila/blob/main/sql-server-sakila-db/sql-server-sakila-schema.sql (reasonably fast)
- https://github.com/jOOQ/sakila/blob/main/sql-server-sakila-db/sql-server-sakila-insert-data.sql (very slow)

A VisualVM session shows that a large amount of time is spent in resizing some control:

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/734593/172795233-020fb9d9-7f59-418f-8057-2994465daa12.png">

This seems to be a completely avoidable thing, at least for large scripts. I suspect that this is for this scrolling animation? I think I could do without that, even for smaller scripts

The following ZIP file contains a VisualVM snapshot, if you want to look at that without running the above SQL script: [snapshot-1654761133115.zip](https://github.com/dbeaver/dbeaver/files/8868167/snapshot-1654761133115.zip)

Even opening the large file takes a long time (~20s), though I could live with that if the execution was faster. Here's what Dbeaver is doing when opening the large file:

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/734593/172796053-ef7c1252-01af-428d-8aae-21ffc7977de3.png">

And another VisualVM snapshot file: [snapshot-1654761535592.zip](https://github.com/dbeaver/dbeaver/files/8868195/snapshot-1654761535592.zip)

Again, I think that effort could be avoided for this use-case? I don't care for editing the file much (though it should still be possible in case it has errors, but perhaps with less tooling). I just want to run it.

Anyway, I don't know how to best fix this:

- By offering simpler additional editors with less features, so they're faster
- By optimising slow stuff
- By removing unnecessary features, such as the auto-scrolling while executing

I trust that you know this better than me

**Comment by manticore-projects** [comment]
Greetings.

Sorry for involving myself into that, I am just a curios person.
I did some tests with Lukas' script myself for testing performance. I have used JSQLParser for parsing and RSyntaxTextArea for highlighting and have been able to open the Large 8MB SQL file in less than 2 second. Just a ball park figure for benchmarking.

I will also work on statements, which JSQLParsrer could not digest yet. Thanks for providing the reference.

**Comment by lukaseder** [comment]
Thanks for the reference, @manticore-projects.

The file also opens super quick in Oracle SQL Developer. Execution there is also a bit slow, but much faster than in Dbeaver. SQL Developer also scrolls through the file while executing...

MySQL Workbench takes a long time to open such a file, but executes them much faster. They only update a status view for the latest statements, not the editor.

I really think that it's key not to maintain a mostly unnecessary animation for such large files...

**Comment by DenisSbragion** [comment]
+1 for this issue. I'm having the same problem. Never complained before because apart from this DBeaver is such a great tool, but if you're going to check into it anyway, well, lukaseder isn't the only one having to deal with really big SQL scripts. Even an option or a key shortcut to temporarily disable what makes the editor slow with such big scripts would be of great help.

**Comment by riqi-rob-mcconeghy** [comment]
We're having a similar issue. We have a large query that executes 200-400X faster in MS SQL Server Management Studio than dBeaver. We found it because our DMX/Precisely/Syncsort code took 430 minutes to run this step, the dBeaver takes 60+ minutes, and SQL MS took less than 10 seconds. I don't know if it's JDBC vs ODBC?

**Comment by serge-rider** [comment]
Thanks for the bug report.
I think we can disable query scrolling/highlighting for big scripts.

**Comment by IanMayo** [comment]
Hmm, the fix referred to (#18277) in this issue overcomes the performance cost of performing syntax highlighting on large files.

But, this issue seems to be related to the cost of updating the UI while very large files of scripts are run.

I'm working with files with 20k lines of insert statements, and I suspect there is a performance cost in DBeaver updating the editor view as it moves down it.  This would be overcome if editor view updates were deferred until running the script was complete.

An alternate solution to the same problem would be to be able to run a script from the "Projects` view - since that would even require an editor to be open.

**Comment by E1izabeth** [comment]
@IanMayo you can vote for [this issue](https://github.com/dbeaver/dbeaver/issues/4738) with 👍🏻
