### ISSUE TITLE
Please replace the uwp version on Microsoft store with the win32 version

### ISSUE THREAD

**Issue by BraveMomo** [dbeaver/dbeaver#16764]
#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:

Please replace the uwp version on Microsoft store with the win32 version. The uwp version is too stuck and the user experience is very poor. Now Microsoft store supports win32 software. In addition, DBeaver has been updated so many versions. When you switch to tab, you still feel stuttered. It may be because you insist on developing with java. If you may want you to develop in other languages and greatly improve the user experience, I am willing to pay for it and support you.

**Comment by ShadelessFox** [comment]
Hello @BraveHL,

The distribution of DBeaver found on the Microsoft Store is the same as the one you can download from our site. The overall user experience should not be any different from other distributions. So I'm not sure what do you mean by the `uwp` version. Can you please elaborate?

Unfortunately, it's impossible to re-write DBeaver using any other language because it will take an infinite amount of time. Moreover, we use Java for a reason - it has managed run-time, it's cross-platform, and is easy to use so that anyone can contribute to DBeaver.

Additionally, DBeaver has support for so many databases because it uses JDBC. Using, for example, C++ will limit us to clunky, and limited on its own, ODBC API that is only available on Windows.

**Comment by ghost** [comment]
I think you should read [this](https://docs.microsoft.com/en-us/windows/uwp/get-started/universal-application-platform-guide) to understand what really `UWP` is. I think you've been confused.

First things first: we insist to code in Java because dbeaver was born like this. Doing an entire source code refactor would take a while (and transition wouldn't be fluid; many errors could born).
By the way, dbeaver on Microsoft Store is the same as the one on official website.
We all know that dbeaver has problems in its build but ofc they will be debugged soon.

As @ShadelessFox we're not going to refactor source code from `Java` to `C++` or any other lang currently.
