### ISSUE TITLE
No suitable driver

### ISSUE THREAD

**Issue by DanGeekyWorld** [dbeaver/dbeaver#16818]
No suitable driver foudn for jdbc:mysql

I'm using a mac with Big Sur IOS.

I install all the JAva and no letting me connect to any DB of Mysql.

#### System information: 
- Operating system (distribution) and version
- DBeaver version
- Java version 
- Additional extensions

#### Connection specification:
- Database name and version
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)?

**Comment by LonwoLonwo** [comment]
Hello @DanGeekyWorld 

Often this "No suitable driver foudn for jdbc:MySQL" issue occurs, then DBeaver can not download driver because of Internet or security problems.

In this case you can download drivers by your own from the wendor web-site:

![2022-06-17 00_31_07-DBeaver 22 1 0 - Playlist](https://user-images.githubusercontent.com/45152336/174169610-f314422e-8193-4ace-842c-64a6c5d117b9.png)

**Comment by uslss** [comment]
There has been no update for a long time.
If issue is still actual for you - feel free to reopen it
