### ISSUE TITLE
User cannot see MySQL triggers in DB navigator tree without TRIGGER privilege

### ISSUE THREAD

**Issue by yoni-yad2** [dbeaver/dbeaver#16842]
#### System information: 
- Operating system (distribution) and version: Windows 10 64 bit
- DBeaver version: 22.1.0.202206051253

#### Connection specification:
- Database name and version: MySQL 5.7.34 RDS
- Driver name: MySQL Server 5.7
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
Triggers do not show up in DB navigator tree for user with "SELECT on *.*" privilege unless the user has also a TRIGGER privilege which allows him to modify triggers as well - which is not desirable.

#### Steps to reproduce, if exist:
With admin/root user:
- Create trigger X on table Y
- CREATE USER 'test_user'@'%' IDENTIFIED BY 'some_password';
- GRANT SELECT ON *.* TO 'test_user'@'%';
- FLUSH PRIVILEGES;

Connect with test_user:
- Open table Y in DB navigator tree 
- Confirm you cannot see trigger X or its definition

*SHOW TRIGGERS command shows trigger X

**Comment by emironovDB** [comment]
Hello @yoni-yad2,

Thanks for the bug report

**Comment by LonwoLonwo** [comment]
Hello @yoni-yad2 

I'm in process of investigating your issue.

You wrote: `*SHOW TRIGGERS command shows trigger X`

 But as I can see in the MySQL documentation: 
[SHOW TRIGGERS](https://dev.mysql.com/doc/refman/8.0/en/show-triggers.html) lists the triggers currently defined for tables in a database (the default database unless a FROM clause is given). This statement returns results only for databases and tables for which you have the [TRIGGER](https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html#priv_trigger) privilege

So, what is your actual request? If we can't show triggers for users without trigger permission due to the database restrictions.

**Comment by yoni-yad2** [comment]
Never mind, I was mislead by the fact that the user needs to reconnect in order to be affected  by the new TRIGGER privileges.

**Comment by LonwoLonwo** [comment]
Yeah, reconnect sometimes can help.

Thanks for the answer.

**Comment by lazarevkristijan** [comment]
Hey if someone else is having this issue where in VSCODE they can't see their triggers in the side DB navigator tree, do this:
(if using MySQL manager from Weijan Chen)
Go to settings of the database up top
![image](https://github.com/dbeaver/dbeaver/assets/133780727/28cca02f-3ff7-46f5-90e8-9cb05318ce32)

In the **CONSOLE** tab
![image](https://github.com/dbeaver/dbeaver/assets/133780727/05d92adf-1d08-44e9-a805-ede5fd5d7dcc)

There is a tree options menu to see what to shoow and not to show, you're wellcome
