### ISSUE TITLE
Using Table Aliases.

### ISSUE THREAD

**Issue by fayca121** [dbeaver/dbeaver#1684]
Hi,

Is it possible to add alias automatically as autocomplete after each table name in sql editor  for example:

select * from TABLE_AAA_BBB_CCC   [AS]  **tabc** (first letter of each word).

it would be also very useful if we can activate/deactivate this alias logic in parameters as checkbox option.

thanks.

**Comment by kyleflan** [comment]
I agree this would be useful, but the logic probably isn't as trivial to implement as you suggested. For example, the following would generate conflicting aliases:

SELECT * FROM product_sales AS ps
SELECT * FROM product_shipments as ps

SELECT * FROM inventory
SELECT * FROM items

**Comment by fayca121** [comment]
Hi,
I agree, the problem occurs when you use those tables in the same qurey for joining purpose 
but you can avoid this situation by concatenating an incremental digit

For Example :

SELECT * FROM product_sales ps, product_shipments  ps1, product_sxyz ps2 where ......

**Comment by serge-rider** [comment]
+ prefs option:
![image](https://user-images.githubusercontent.com/6398845/65512692-5fa2f100-dee2-11e9-984c-561c47c94280.png)

**Comment by jim256** [comment]
Awesome! Looking forward to this.

**Comment by kseniiaguzeeva** [comment]
Verified (first letter of each word is used)

**Comment by dhcrain** [comment]
Would be nice to have the `AS` as in option so that this will work for Oracle DB's

**Comment by gbilski** [comment]
Such an annoying feature. While I can see that some people may find this useful, why is it enabled by default?

**Comment by ZeGuigui** [comment]
> Would be nice to have the `AS` as in option so that this will work for Oracle DB's

I created an issue for Oracle database: #7084

**Comment by nithyavpm** [comment]
Latest version of dbeaver is inserting table alias by default which is very irritating. Please disable by default option and let people who need this can have this enabled.

**Comment by vicnett** [comment]
I really like this feature but why is it only auto-inserting an alias on the first table? I'd like aliases to be autofilled on JOINs as well.

In the following example:

`SELECT * FROM table_one AS to JOIN table_two AS tt`

The first alias gets automatically inserted if I accept an auto-complete suggestion of the table name, but I have to type out the second one myself. This entirely prevents me from getting used to using the feature because I can't always expect it to happen or not.

**Comment by Fizard** [comment]
> I really like this feature but why is it only auto-inserting an alias on the first table? I'd like aliases to be autofilled on JOINs as well.
> 
> In the following example:
> 
> `SELECT * FROM table_one AS to JOIN table_two AS tt`
> 
> The first alias gets automatically inserted if I accept an auto-complete suggestion of the table name, but I have to type out the second one myself. This entirely prevents me from getting used to using the feature because I can't always expect it to happen or not.

I really miss this feature in JOIN too. Why not have an option "Insert Table Alias (in Join Clause)" too? This would be nice!

**Comment by MuqadderIqbal** [comment]
I just found out that DBeaver doesn't add aliases to the second (or subsequent) tables in a JOIN clause. This will indeed be a very useful feature to have since it correctly creates alias for first table and then just stops creating them if a JOIN clause is used.

I logged this as a bug here: https://github.com/dbeaver/dbeaver/issues/8912

**Comment by ArqamRafay** [comment]
As of DBeaver v21, this setting can be now be found under Window -> Preferences -> Editors -> SQL Editor -> Code Completion -> Insert Table Alias -> N/A
