### ISSUE TITLE
BigQuery support

### ISSUE THREAD

**Issue by kclulow** [dbeaver/dbeaver#1687]
Please add support for the SIMBA driver for Google BigQuery.

**Comment by r-richmond** [comment]
In case it helps someone I wrote a quick [blog post](https://justnumbersandthings.com/post/2018-09-22-dbeaver-bigquery/) illustrating how to connect to BigQuery with Dbeaver. 

Note: BigQuery's types aren't fully supported with this solution (Structs & Arrays are represented as json strings) but hopefully full support for BigQuery will be addressed later.

**Comment by serge-rider** [comment]
Thanks, I'll take a look. 
With JDBC driver BigQuery become much easier to integrate.

**Comment by serge-rider** [comment]
I think we need a special connection page for BigQuery. They use quite unusual connection props, using the standard Generic driver connection page will confuse users.

**Comment by serge-rider** [comment]
First version of BigQuery connector is ready:
![image](https://user-images.githubusercontent.com/6398845/46261597-86605e80-c4fe-11e8-8c61-49ffd2c8649f.png)

Driver will be downloaded and configured automatically. Auth types 0 and 1 are supported.
Simba driver is a bit glitchy (e.g. provides incorrect data type information for arrays), workarounds added for some of its specific behaviors.
Also implicit LIMIT clause will be automatically added to SELECT queries because of bad driver performance.

Please check it in EA version (https://dbeaver.io/files/ea)

**Comment by r-richmond** [comment]
Question: Did you do overwrite the incorrect data type information for arrays & structs so that Dbeaver displays text/json for those fields.

I was going to take a look myself but can't launch the newest version per #4308

**Comment by serge-rider** [comment]
@r-richmond Yes.
Looks like I forgot to publish EA Mac installer last time. Now published (it is bundled with proper Java).

**Comment by r-richmond** [comment]
The formatting of structs looks a little off.
{f=[{v=https://github.com/appden/less.tmbundle}, {v=true}, {v=2009/09/19 16:46:18 -0700}

demo script
```sql
select
  t.repository
from `bigquery-public-data`.samples.github_nested as t
limit 10```

**Comment by brylie** [comment]
When trying to enable the BigQuery plugin, I get the following error:
![flameshot-2019-01-11t14 03 13](https://user-images.githubusercontent.com/17307/51032724-bad9c100-15a9-11e9-8be6-e3fa15dc0e80.png)

**Comment by Omkarcgd01** [comment]
![image](https://user-images.githubusercontent.com/105201412/168037929-c63847a1-dda4-436d-82b9-2fa32969edaa.png)
i got this error while connecting Bigquery with Dbeaver
