### ISSUE TITLE
Missing underscore in column headers

### ISSUE THREAD

**Issue by rpalloni** [dbeaver/dbeaver#17079]
#### System information: 
- Ubuntu 20.04

#### Connection specification:
- Snowflake
- Dbeaver 22.1.2

#### Describe the problem you're observing:
Column names are not showing underscores in table result. See image

SELECT 
query_id, 
query_text, 
bytes_scanned, 
partitions_scanned,
partitions_total
FROM QUERY_HISTORY

![image](https://user-images.githubusercontent.com/17080117/178782988-d3be294a-c02e-4d14-a963-6fd8f3126e1c.png)

All good in web ui

![image](https://user-images.githubusercontent.com/17080117/178784427-3747b5dd-4f73-46ad-8af9-b31ee5584eaa.png)

**Comment by LonwoLonwo** [comment]
Hello @rpalloni 

I can't reproduce your issue for now.

![2022-07-14 11_24_39-DBeaver Ultimate 22 1 2 - _SNOWFLAKE_SAMPLE_DATA_ Script-33](https://user-images.githubusercontent.com/45152336/178937639-a345de4a-bf1c-4b6a-b8dd-a8a318218c8a.png)

Can you please check any other databases? SQLite? To localize this problem (Snowflake data or DBeaver GRID)

**Comment by LonwoLonwo** [comment]
Also, QUERY_HISTORY DDL will be also very helpful. Thanks.

**Comment by rpalloni** [comment]
Actually happens in any table. Might be the dark theme? I'll check

**Comment by uslss** [comment]
there has been no update on the issue for a long time.
If the issue is still reproducible for you - feel free to reopen it with additional info.

**Comment by pararang** [comment]
Hi, this issue is also happening to me, using dbeaver Version 22.1.4.202208051447 Com. edition. Run on Ubuntu 22.04.1 LTS.

![Screenshot from 2022-08-13 14-34-15](https://user-images.githubusercontent.com/8720184/184472042-d32ccc91-d4af-4daf-88ad-197d669c6fb3.png)
![Screenshot from 2022-08-13 14-33-51](https://user-images.githubusercontent.com/8720184/184472043-b8c374a5-1cc7-4715-bf67-76b420fde8d9.png)
