### ISSUE TITLE
Search>File: File Search Replace Button is wrong

### ISSUE THREAD

**Issue by GuenterSch** [dbeaver/dbeaver#17328]
### Description

In the dialog **File Search**, the replace button is wrong, because there is no possibility to set a replace value.

**Please remove the Replace button.**

![grafik](https://user-images.githubusercontent.com/99535516/183913025-15d4ad20-fd57-4c64-a791-9dd91315d8f1.png)

### DBeaver Version

22.1.4

### Operating System

Windows 10 21H2

**Comment by Matvey16** [comment]
@GuenterSch Thank you for the report, but you will be able to replace the text, that's why replace button has ellipsis at the end.

If any match is found a new window would be opened

![dbeaver_lvJJlX0UIV](https://user-images.githubusercontent.com/82543000/184102965-54323949-3770-40d3-ab0c-58d055c78b1f.png)

**Comment by GuenterSch** [comment]
Hello Matvey16,

thanks for the clarification.
For me, this is unusual and therefore I did not have the idea, that a new window will be opened. In my test there was no match and therefore the Replace dialog did not open.

BR
Günter

**Comment by GuenterSch** [comment]
There exist the possibility to replace a text.
