### ISSUE TITLE
Export/import of DBeaver preferences

### ISSUE THREAD

**Issue by goryushkinov** [dbeaver/dbeaver#17368]
Hi all ! Can anybody help with the question in which file are the installation settings stored ? We need to replace automatically some of the default settings when installing for many users. For example: in "Connections→Metadata" remove mark for "Open separate connection for metadata read". This will reduce the number of sessions created when reading metadata. Thanks.

**Comment by goryushkinov** [comment]
Colleagues, please pay attention ! Thanks.

**Comment by flambchap** [comment]
Hi. Unfortunately, the settings are all over the place. I think we can add a way to export and import settings similarly to Eclipse or IntelliJ platform. Thank you for the idea.

**Comment by goryushkinov** [comment]
> Hi. Unfortunately, the settings are all over the place. I think we can add a way to export and import settings similarly to Eclipse or IntelliJ platform. Thank you for the idea.

**Comment by goryushkinov** [comment]
Hi everybody ! Nikita, thanks for the answer ! Can you also inform about еstimated timeframe for this opportunity ?

**Comment by arhayka** [comment]
We want to add a possibility to export all the setting in the file/archive and to import it from the file/archive.

**Comment by flambchap** [comment]
Hi @goryushkinov. Unfortunately, we cannot give you solid estimates. For now, the issue is scheduled for 23.1.1, but we cannot guarantee delivery in that particular release. I suggest tracking the current milestone here on GitHub: 

<img width="1512" alt="Screenshot 2023-05-26 at 12 13 17" src="https://github.com/dbeaver/dbeaver/assets/26031301/54c04453-d91c-483e-b034-c8c04a51ac68">
