### ISSUE TITLE
Paragraph Character shows up in DBeaver IDE that is not present in Array datatypes

### ISSUE THREAD

**Issue by BradLeeHines-ST** [dbeaver/dbeaver#17509]
### Description

We've written a SELECT query against an ARRAY column datatype in Snowflake.
When we do this, a Paragraph character ¶  shows up to separate elements in the DBeaver IDE.

[
  0.3,
  0.5
]

### DBeaver Version

Version 22.1.3.202207240747

### Operating System

OSX 12.5

### Database and driver

Snowflake with Maven Snowflake driver 3.13.6 JDBC

### Steps to reproduce

Write a select statement against a snowflake array data column type
![Screen Shot 2022-08-30 at 2 27 52 PM](https://user-images.githubusercontent.com/82233020/187547770-454d75a2-b5dc-4c72-94b6-6ee178adf4e8.png)

**Comment by flambchap** [comment]
Looks suspiciously similar to https://github.com/dbeaver/dbeaver/issues/17120

**Comment by LonwoLonwo** [comment]
Hello @BradLeeHines-ST 

Please tell me more about your issue.
What kind of discrepancy do you see here? DBeaver shows your value with special symbols inside because it tries to show inline.

![2022-09-01 12_47_03-Window](https://user-images.githubusercontent.com/45152336/187897237-ad81f7c0-4a73-41f5-ada3-178696f95916.png)

You can open the Value panel and see your data without special symbols but on different lines.

So Paragraph Characters are some auxiliary characters here.

**Comment by uslss** [comment]
There have been no updates for a long time. If the issue is still actual for you - feel free to reopen it with additional info.
