### ISSUE TITLE
Data Transfer Dialog cannot be minimized

### ISSUE THREAD

**Issue by igortank** [dbeaver/dbeaver#17502]
### Description

Hellow!
When uploading to a file, the "data transfer" window is active and cannot be minimized, and when the file is being formed, it becomes impossible to use the main application.
Previously, the "data transfer" window could be minimized.

### DBeaver Version

22.1.5.202208211008

### Operating System

windows 10

### Database and driver

oracle

**Comment by uslss** [comment]
thanks for the report

**Comment by Destrolaric** [comment]
@igortank Hi, we disabled the minimize due to many issues with the Eclipse platform. It was done in the scope of https://github.com/dbeaver/dbeaver/issues/16867, maybe we should allow Windows users to minimize, but it also works not as well as it should.
For now, unfortunately, you can only reduce the size of the unwanted panels so you can focus on other tasks.

**Comment by tati-kru** [comment]
As @Destrolaric said, this behavior was implemented for a purpose, and we won't return an option to minimize the data transfer window. We recommend you to use tasks to avoid the described issues.
