### ISSUE TITLE
Error when creating postgresql connection: "unable to find valid certification path to requested target" 

### ISSUE THREAD

**Issue by jflambert** [dbeaver/dbeaver#17714]
### Description

On a brand new Windows 10 VM, I can't create postgresql connections because driver files can't be downloaded.

It doesn't look like the bundled "Java" works fully.

### DBeaver Version

Community Edition 22.2.0

### Operating System

Windows 10

### Database and driver

This doesn't matter, I can't download drivers, but otherwise:

1. postgresql 13.8
2. JDBC 42.5.0 (presumably the latest)

### Steps to reproduce

1. brand new Windows 10 VM x86 64 bits
2. no other customization/apps/update/etc
3. Download and install DBeaver 22.2.0
4. Make sure the "Java" checkbox is selected (by default it is)
5. Start DBeaver and double-click the postgresql logo
6. Download error

![image](https://user-images.githubusercontent.com/11539524/191966459-763bce0a-7681-46f1-9eaa-fbece091f007.png)

**Comment by E1izabeth** [comment]
Thank you for bug report. We already have an issue with the same bug #17591. As a workaround you can remove `-Djavax.net.ssl.trustStoreType=WINDOWS-ROOT` from `dbeaver.ini` file.

**Comment by jflambert** [comment]
@E1izabeth  is there an older version of dbeaver available for download that doesn't have this issue?

**Comment by E1izabeth** [comment]
I hope that this issue is not about DBeaver itself, but about your certificates, so I can't suggest you some other version to downgrade to. It seems that some required certificate is missing in your WINDOWS-ROOT. If you delete this parameter from the dbeaver.ini file, DBeaver will use java certificates and everything should be ok.
P.S. dbeaver.ini file is in the same location where dbeaver.exe file is - in the folder where you installed DBeaver.

**Comment by E1izabeth** [comment]
@jflambert I encountered the same issue and it disappeared after one of the latest (in September) windows updates. Maybe it will help you too.
