### ISSUE TITLE
ERD diagram

### ISSUE THREAD

**Issue by enaut** [dbeaver/dbeaver#17846]
### Description

Hello and thank you for the tool!

The problem:
1. I created an ERD diagram and rearranged all the boxes so that they are visually clearly sorted with little crossing lines.
2. With what I learned I adjusted the database model slightly (Django) and migrated the database.
3. Next I want the modifications to appear in the diagram.
  4. refresh does nothing
  5. refreshing the database does add the modifications to the table tree on the right
  6. I can drag and drop the new and changed tables to the ERD
  7. However the existing and layouted Elements do not connect to the modified foreign keys.
  8. So where there was on initial import a line automagically generated there is none generated to the key now. Only if I drag in all again the lines are generated within the new boxes but that means I have to rearrange everything again.
I created a screenshot: The boxes with colored headers are the existing and layouted ones the black ones are added/updated. As you can see the lines (importer_mitgliedimportline -> mitgliederverwaltung_mitglied) do not connect even though the foreign key is still there:

![migrated-tables](https://user-images.githubusercontent.com/290005/194559093-5296d60c-04e9-4d7a-8dfb-5e326e5eadb4.png)

### DBeaver Version

CE 22.2.1

### Operating System

Linux

### Database and driver

sqlite

**Comment by Matvey16** [comment]
@enaut Hello. What type of diagram do you have? Is it a custom diagram created in the project or the diagram tab for an object opened from the navigator?
For custom diagrams the changes are all manual, they are made by the user and changed by the user. For the diagram of the objects you may try disabling `Keep Layout` button before the refresh.
![image](https://user-images.githubusercontent.com/82543000/199696051-f35261c8-33ac-4d13-a86c-ee4be3870abd.png)

Let me know if that helped

**Comment by enaut** [comment]
But disabling keep layout does require me to rearrange everything afterwards isn't it?

I think the ERD file was initially in the diagram tab, but then saved and loaded again. So I guess that means it is now a custom Diagram?

**Comment by Matvey16** [comment]
@enaut Yes, disabling keep layout does refresh the diagram and rearrange it from scratch.

The custom diagram is the one that is located in the Diagrams folder of the project and actually has different functionality than a diagram that can be opened for most of the database objects.

![dbeaver_8bV7MByhVg](https://user-images.githubusercontent.com/82543000/209136747-fb74b4b7-7ea8-4dee-a77d-2f104ae5a3c0.png)

I am assuming your diagram is in this issue is the one that is opened for the database in object ER Diagram tab like this

![dbeaver_ZPPfOg5WUr](https://user-images.githubusercontent.com/82543000/209136910-ab317824-bc20-44ab-a900-100d485e9f0e.png)

Am I correct?

**Comment by enaut** [comment]
Thank you! I guess the tool just doesn't work as I expected.
