### ISSUE TITLE
pageant doesn't show in 'SSH Agent' list

### ISSUE THREAD

**Issue by Spongman** [dbeaver/dbeaver#18021]
### Description

i'm running pageant. it doesn't show in the list:

![image](https://user-images.githubusercontent.com/1088194/197672028-284f1327-745d-4ee8-9714-728fb81e2678.png)

### DBeaver Version

Version 22.2.2.202210092258

### Operating System

windows 10 x64

**Comment by ShadelessFox** [comment]
Hello @Spongman,

This dialog comes from Eclipse. It has nothing to do with database connectivity.

Please consider choosing to use the agent here:

![image](https://user-images.githubusercontent.com/35821147/202470510-c72e21db-bcb1-4ae4-9b21-8da37b335139.png)

Please let me know if your issue was solved.

**Comment by Spongman** [comment]
> This dialog comes from Eclipse

Not sure what you mean, I don't have Eclipse installed.

**Comment by ShadelessFox** [comment]
Sorry for confusing you. You see, DBeaver is built on top of the Eclipse platform, which itself brings a lot of things like this dialog. As I said, it has nothing to do with database connectivity.

Please ignore this dialog and stick with our native support for SSH agents.

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
