### ISSUE TITLE
Problem using drag and drop of table name into a simply select

### ISSUE THREAD

**Issue by paoloholzl** [dbeaver/dbeaver#18026]
### Description

If you open SQL window creaqting a select using Drag And Drop give error.

### DBeaver Version

Community Edition 22.2.3

### Operating System

Windows 10

### Database and driver

Try in SQL Server, Postgresql, MySQL, Oracle.

### Steps to reproduce

If you open SQL window
select * from (and drag an drop table name)
If you play the button give error.
If you add at end of command ; than play work correctly.
If you remove ; and try again than play work correctly.
Try in SQL Server, Postgresql, MySQL, Oracle.

**Comment by E1izabeth** [comment]
Could you show the query which you see in the [Query Manager](https://dbeaver.com/docs/wiki/Query-Manager/) when you run it for the first time (with error)?

**Comment by paoloholzl** [comment]
https://user-images.githubusercontent.com/96785200/197987253-aae4906c-d6cf-4c36-9a06-86210f24928f.mp4

Now demostration, drag and drop Not work.
Adding ; work. 
After removing ; work.

**Comment by E1izabeth** [comment]
Execute button sends the selected part to the database if something is selected. Otherwise it executes the nearest to the cursor position query.
The selection stayed on the table name after the second drag-n-drop. So, the selected part of text - table name is trying to be executed as a query and failed as it's not a complete query. You need to click somewhere nearby to remove selection and then press Execute. Then Execute button button will catch and execute the whole select statement. And that's exactly happening after your next actions, because selection is gone.

**Comment by paoloholzl** [comment]
Ok! I got it. 
But to avoid misunderstandings, perhaps it would be better to present the deselected line after dragging. 
What is the advantage of having it selected?
I would say more, for greater convenience, not only would it be better to have it unchecked, but it would be better to add a subsequent space and present the cursor after the space (to continue typing instruction).

**Comment by flambchap** [comment]
Thank you for the idea.

**Comment by E1izabeth** [comment]
We don't want to change this because this is the default behavior for all text editors.

Also, if you drag something into the middle of a query or script by mistake, and it's not selected, there's no way to trace what and where you dragged it and why it's broken.
