### ISSUE TITLE
Maintain State between application loads

### ISSUE THREAD

**Issue by sfscgjohnson** [dbeaver/dbeaver#18281]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I exit the application, restart my computer, or force quit because it requests saving all of my files which most of them are working and I never want to save them.

**Describe the solution you'd like**
When I close the application it saves my current state and loads that when I come back to DBeaver.  This allows me to work and gracefully leave and come back without having to close 20 windows.

**Describe alternatives you've considered**
I've tried force quitting but when I do that it loads all the windows but they are all empty.

**Additional context**
VSCode does this and maintains the session.   Love DBeaver but Azure Devops Studio

**Comment by ShadelessFox** [comment]
Hello @sfscgjohnson,

I believe you're referring to the auto-save feature. If all editors' have their contents saved, there's nothing to prompt about.

DBeaver has this feature:

![image](https://user-images.githubusercontent.com/35821147/203183065-7b86d330-b0fb-4eee-bcd0-81fec13e59dd.png)

Please let me know if your issue was solved.

**Comment by uslss** [comment]
there have been no updates for a long time. If the issue is still actual - feel free to reopen it.
