### ISSUE TITLE
Stored procedure not generating DDL on IBM i DB2 platforms

### ISSUE THREAD

**Issue by xantari** [dbeaver/dbeaver#1857]
When trying to generate the DDL on IBM i DB2 platforms we get this:

-- Source code not available;

**Comment by serge-rider** [comment]
This is not supported yet.
IBM i DB2 driver uses plain JDBC for metadata reading. JDBC API doesn't provide stored procedures source code.

**Comment by JMarkMurphy** [comment]
Please re-open this, Stored procedure source code is available from the system catalog on DB2 for i. The catalog view you need to interrogate is QSYS2.SYSROUTINES. Documentation is [here](https://www.ibm.com/support/knowledgecenter/ssw_ibm_i_73/db2/rbafzcatsysrout.htm)

**Comment by xantari** [comment]
I can beta test for you when this is ready

**Comment by serge-rider** [comment]
Please test in Early Access version (https://dbeaver.io/files/ea)

**Comment by JMarkMurphy** [comment]
Still see -- Source code not available

![image](https://user-images.githubusercontent.com/2379218/60723071-a7783480-9f00-11e9-823a-49af83860fd3.png)

**Comment by serge-rider** [comment]
Thanks for testing. Could you try it one more time? (new EA was just published)

**Comment by JMarkMurphy** [comment]
Getting closer. One problem, and a comment.

Problem first: you are getting user defined functions, but not stored procedures:
![image](https://user-images.githubusercontent.com/2379218/60735925-2bdbaf00-9f23-11e9-88e8-5f79f023bccb.png)

In the query result of sysroutines we see a bunch of functions (some of these are table functions) and a single lonely procedure. But the procedure does not appear in the Database Navigator.

And now the comment: you will notice that in the ROUTINE_BODY column, some say SQL, and others say EXTERNAL. DB2 for i allows registering functions, procedures, and triggers that are not defined in SQL. These show as EXTERNAL. The ones with SQL show source now. The others still say -- Source code not available.  It would be nice if instead of that it would indicate that the routine is externally defined, and also provide the external name, language, and parameter style. You still won't be able to get the source from these, but it would be nice to be able to find the program that is registered.

**Comment by serge-rider** [comment]
Good (more or less). Thanks for checking this!

Procedure list is provided by jt400 driver (currently DBeaver doesn't make direct selects from SYSROUTINES). Generally we can change this behavior but it is not very easy for me to write this code in blind mode.
Could you write a SQL query which will return all procedures/functions with all needed properties (including type and body) so I could use it in procedure reading routine? Input param is schema name.

Procedure object may have any number of properties (if they make sense in UI). Please write short description of such properties.

**Comment by emuggie** [comment]
DB2 for i 7.2 user.
Commented Column --Column meanings (DataType) : confirmed values.
Please correct me if there's wrong info.

--Query
SELECT
	SPECIFIC_SCHEMA --SYSTEM SCHEMA NAME(VARCHAR)
	, SPECIFIC_NAME --SYSTEM NAME(VARCHAR)
	, ROUTINE_SCHEMA --SCHEMA(VARCHAR)
	, ROUTINE_NAME	--ROUTINE NAME(VARCHAR)
	, ROUTINE_TYPE	-- TYPE(VARCHAR) : FUNCTION, PROCEDURE
	, ROUTINE_CREATED	--CREATED TIME(TIMESTAMP)
	, ROUTINE_DEFINER	-- USER WHOM CREATED ROUTINE(VARCHAR)
	, ROUTINE_BODY	-- ROUTINE(VARCHAR) : SQL, EXTERNAL 
	, EXTERNAL_NAME	--(VARCHAR)
	, EXTERNAL_LANGUAGE	--(VARCHAR)
	, PARAMETER_STYLE	--(VARCHAR)
	, IS_DETERMINISTIC	-- IS DETERMINISTIC(VARCHAR) : YES, NO
	, SQL_DATA_ACCESS	-- IS MODIFING DATA(VARCHAR) : READS, MODIFIES
	, SQL_PATH	--(VARCHAR)
	, PARM_SIGNATURE	--(VARCHAR)
	, NUMBER_OF_RESULTS	--(SMALLINT)
	, MAX_DYNAMIC_RESULT_SETS --(SMALLINT)
	, IN_PARMS	-- NUBMER OF IN PARAMETERS(SMALLINT)
	, OUT_PARMS	-- NUMBER OF OUT PARAMETERS(SMALLINT)
	, INOUT_PARMS	--NUMBER OF INOUT PARAMETERS(SMALLINT)
	, PARSE_TREE	--(VARCHAR)
	, PARM_ARRAY	--(BLOB)
	, LONG_COMMENT	--ROUTINE COMMENT(VARCHAR)
	, ROUTINE_DEFINITION	--SQL SCRIPT  FOR ROUTINE(DBCLOB)
	, FUNCTION_ORIGIN	--(CHAR)
	, FUNCTION_TYPE		--(CHAR)
	, EXTERNAL_ACTION	--(CHAR)
	, IS_NULL_CALL	--(VARCHAR)YES,NO,[NULL]
	, SCRATCH_PAD	--(INTEGER)[NULL]
	, FINAL_CALL	--(VARCHAR)YES,NO,[NULL]
	, PARALLELIZABLE --(VARCHAR)YES,NO,[NULL]
	, "DBINFO"	--(VARCHAR)YES,NO,[NULL]
	, SOURCE_SPECIFIC_SCHEMA	--(VARCHAR)
	, SOURCE_SPECIFIC_NAME	--(VARCHAR)
	, IS_USER_DEFINED_CAST	--(VARCHAR)YES,NO,[NULL]
	, "CARDINALITY"	--(BIGINT)[NULL]
	, "FENCED"	--(VARCHAR)YES,NO,[NULL]
	, COMMIT_ON_RETURN	--(VARCHAR)YES,NO,[NULL]
	, IASP_NUMBER	--(SMALL INT)
	, NEW_SAVEPOINT_LEVEL --(VARCHAR)YES,NO
	, LAST_ALTERED	--(TIMESTAMP)[NULL]
	, DEBUG_MODE	--(CHAR)0,2
	, DEBUG_DATA	--(CLOB)
	, ROUNDING_MODE	--(CHAR)E
	, ROUTINE_TEXT	--(NVARCHAR)
	, SECURE		--(CHAR)N
	, ROUTINE_ENVIRONMENT	--(BLOB)
	, ROUTINE_DEFAULT_QDT	--(BLOB)
FROM
	QSYS2.SYSROUTINES

**Comment by serge-rider** [comment]
@emuggie Thanks. This feature will be tracked in #6241

**Comment by JMarkMurphy** [comment]
SPECIFIC_SCHEMA and SPECIFIC_NAME are not SYSTEM SCHEMA NAME and SYSTEM
NAME. They are there because DB2 is polymorphic. The same routine name can
select one of multiple routines with the same name based on the parameter
signature. The specific name allows the user to drop or replace one
specific instance of a routine. There is no system name or system schema
for a routine. For other objects like tables, there is a system_table_name
and system_table_schema which is a CHAR(10) name of the object which allows
the user to find it in the library file system.

For routines, the EXTERNAL_NAME is the closest you will come to SYSTEM_NAME
and SYSTEM SCHEMA. The external name comes in a few different forms
depending on whether ROUTINE_BODY is SQL or EXTERNAL, and the
EXTERNAL_LANGUAGE is JAVA or something else. If EXTERNAL_LANGUAGE is JAVA,
then ROUTINE_BODY is EXTERNAL, and EXTERNAL_NAME provides a fully qualified
java method,
(e.g. SYSTOOLS.DB2RESTUDF:com.ibm.db2.rest.DB2UDFWrapper.base64Encode). If
the ROUTINE_BODY is SQL, then EXTERNAL_LANGUAGE is null, and the
EXTERNAL_NAME is a qualified program name in the form <library
name>/<program name> where <library name> and <program name> are both
character values with a maximum length of 10. And for the interested, the
program is a C program, but you would need to look at the object itself to
see that. Finally, if the ROUTINE_BODY is EXTERNAL and EXTERNAL_LANGUAGE is
not JAVA, then the EXTERNAL_NAME might be a qualified program name as in
the SQL definition, or a qualified sub-procedure name which looks like this
<library name>/<service program name>(<sub-procedure name>) where <library
name> and <service program name> are both character values with a maximum
length of 10, and <sub-procedure name> is a character value with a maximum
length of 128.

PARAMETER_STYLE has several values, these can be provided as is for
ROUTINE_BODY = EXTERNAL.

SQL_DATA_ACCESS has several values which can be provided as is.

PARM_SIGNATURE, PARSE_TREE, PARM_ARRAY, ROUTINE_ENVIRONMENT, and
ROUTINE_DEFAULT_QDT are only used internally, and are not useful for
display. Might as well not even retrieve them.

Character encoding is a mixed bag.
ROUTINE_DEFINITION is in UCS-2 format, this is a subset of UTF-16.
LONG_COMMENT and ROUTINE_TEXT are in UTF-16.

**Comment by Condor70** [comment]
There is an error in the 6.1.2 implementation which results in:
```
/* ERROR WHILE READING SOURCE:

SQL Error [42704]: [SQL0204] SYSROUTINES in MYSCHEMA type *FILE is niet gevonden.
*/
```

The line:
`SELECT ROUTINE_DEFINITION FROM SYSROUTINES`
should be:
`SELECT ROUTINE_DEFINITION FROM QSYS2.SYSROUTINES`

([reference](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_74/db2/rbafzcatalogtbls.htm))
