### ISSUE TITLE
Why change option filter column? Please revert same 22.3.0

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#18589]
Why change option filter column? Please revert same 22.3.0

**Comment by jun-daground** [comment]
also the filter button of column with comment is weird. seeing it next to comment, but can click upper like a ghost button.

**Comment by ghost** [comment]
> also the filter button of column with comment is weird. seeing it next to comment, but can click upper like a ghost button.

But it's not easy to use. i think same ver 22.3 is best choice. Please consider come back  this function

**Comment by serge-rider** [comment]
@vncdn we want to reduce number of icons on the screen. Currently there are too many of them in the data editor control.
Please clarify what exactly makes it invonvenient/bad looking?

@jun-daground could you clarify what do you mean? Some screenshot would be very helpful.

**Comment by jun-daground** [comment]
> @vncdn we want to reduce number of icons on the screen. Currently there are too many of them in the data editor control. Please clarify what exactly makes it invonvenient/bad looking?
> 
> @jun-daground could you clarify what do you mean? Some screenshot would be very helpful.

@serge-rider 
I rollbacked to 22.3.0 so cannot show screenshot to you totally, but can explain to u with more detail.
![image](https://user-images.githubusercontent.com/99629249/209541977-c2458b83-1bed-45d5-ac60-da2aac0fb5f3.png)
maybe that shape is reverse triangle in 22.3.1.
the triangle button were located next to comment like "Error" on that picture, but click-site is the location of original filter button. Test it. the new button will react nothing

**Comment by serge-rider** [comment]
Ah, you probably have enabled option "Show column description in header".
It is a bug. Thanks for the report.

**Comment by joanrega** [comment]
I am sorry to intrude in this issue, but do I understand that having only the dropdown menu and not being able to sort or filter with a single click is the intention, @serge-rider ? There is no way to activate the old version? I really appreciated the quick options. Now when I click the dropdown and click on filter by value it offers to filter by the first column or the column that is focused instead of the one I clicked the dropdown on.

I understand wanting to clean the clutter, but having one-click options and filtering what I click is a big deal in terms of agility to me.

**Comment by serge-rider** [comment]
@joanrega Yes, it is one of two main reasons. The second reason is to avoid accidental click on value filter icon which executes expensive SQL query (group by which may heavily load database server in case of big tables).

At the moment there is no way to activate old behavior.
However, if there will be more votes, we could make it configurable.

**Comment by fl-ashutosh-datar** [comment]
How do I vote to make it configurable? I think the old implementation was very handy to filter. 
I think I want that option back.

**Comment by Dkrav-UA** [comment]
> @joanrega Yes, it is one of two main reasons. The second reason is to avoid accidental click on value filter icon which executes expensive SQL query (group by which may heavily load database server in case of big tables).
> 
> At the moment there is no way to activate old behavior. However, if there will be more votes, we could make it configurable.

Quick filter is 90% of my work with fields. It's very uncomfortable now. Maybe if you set this option at the beginning of the menu it will be a little better. This option is now placed too far away.

**Comment by Pallieguy** [comment]
Apologies if this is not the correct way to vote for a way to revert to the former system, but I made extensive use of it and removing the single click option has a noticeable impact on my use of DBeaver.  Perhaps moving the filter option to the left side of the header box and leaving the sort option on the right would minimize clicking the incorrect icon?

**Comment by serge-rider** [comment]
Icons customization will be added in #18671

**Comment by Rebsos** [comment]
I'm also reverting back to 22.3.0. I think it is OK to have many Icons. It's not a touch app, where accidental clicks occur and the devices have small screens. As long as the productivity is high. I'm using a lot of fast filtering in my use-case, so it slows me down right now.

**Comment by ghYura** [comment]
@serge-rider 
You could save new feature existed in v. 22.3.1 ...to 22.3.4 of column menu filtering by changing its behavior of being called (pressed).
Say, this new context menu needed to be pressed at old filter icon (prior to 22.3.0) that click lasts, say more than 1 second and unpressed click-button up after delay. The behavior of calling one or another menu 'look-and-feel' (and its delay being pressed by click or adding to click, say Ctrl + mouse click) should be configurable according to each user customisation preferences menu (since no totally everyone universally agree with desire of another user)
I agree, that it is inconvinient, that while long-cost queries have easy to **accidentially click** on ordering-filtering button.
So, as many people - as many opinions
