### ISSUE TITLE
Update wiki article 'Data Editor'

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#18617]
We changed several controls in the Data editor:
- filters in the table headers (dbeaver/pro#1263),
- the Refresh button on the bottom toolbar (dbeaver/pro#1264),
- status details (dbeaver/pro#1261),
- export icons (dbeaver/pro#1260),
- and possibly something else.

We need to add new screenshots to the [Data Editor page](https://github.com/dbeaver/dbeaver/wiki/Data-Editor) and describe the new functionality.

**Comment by E1izabeth** [comment]
- [x] Switches to **the** grid view of data.
- [x] Switches to **the** plain text view of data.
- [x] Switches to **the** spatial view. 
- [x] Switches to **the** chart view.
- [x] Refreshes the whole results set including all items that are not visible on the screen, while its dropdown option allows **to customize** the refresh frequency over a specific period.
- [x] Saves all unsaved changes to the data such as adding, duplicating, deleting rows, inline editing of values **. See** [the Data Viewing and Editing](https://github.com/dbeaver/dbeaver/wiki/Data-Viewing-and-Editing) article for information.
- [x] Opens the cell in focus for editing in a separate editor or dialog box **. See** details in the [Cell Editor section](https://github.com/dbeaver/dbeaver/wiki/Data-Viewing-and-Editing#cell-editor) of our article.
- [x] Opens a _dropdown_ menu with settings. - it's not a dropdown, isn't it?
- [x] Displays the selected number of rows in the result-set, which can be updated by clicking the Refresh button. - Not clear enough for me. I propose something like that: "Displays the **initial fetched** number of rows in the **result set on loading or refreshing**".
- [x] Why `data table` everywhere instead of `table data`? Or you mean `data grid`? I fixed some at the beginning thinking that it's a typo. Was it intentional? Maybe I didn't get it. Please check such cases over the article, I believe it's better to replace it to one of the proposed options.
- [x] Advanced Paste - Pastes several values delimited with a tabulation or line break **starting from the selected cell**.
- [x] Deletes the row that has the cell in focus - add dot at the end of the sentence please
- [x] Displays a submenu that allows **to specify a** filter criteria for the data.
- [x] Opens a submenu that provides _tools_ for formatting and modifying the view of data, see the [Data View and Format](https://github.com/dbeaver/dbeaver/wiki/Data-Filters) article. - it's not a tools, it's more like options
- [x] Opens a submenu that helps users **to** navigate throughout the data table, see the [Navigation](https://github.com/dbeaver/dbeaver/wiki/Navigation) article.
- [x] Opens the Data Transfer wizard that guides you through the steps to **export data to a selected format**, 
- [x] Opens a submenu **where** you can select the type of SQL query to generate, see the [SQL Generation](https://github.com/dbeaver/dbeaver/wiki/SQL-Generation) article.
- [ ] Column context menu - probably we should tell here how to customize the header of the column with the following settings to show the arrows directly on the column, for example. I believe it may be already described in some article.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/b01b0ef8-6731-4dc6-91b1-3ac22e7c1b36)

**Comment by daelynum** [comment]
Edited.

Column context menu - In the [Data Filters](https://github.com/dbeaver/dbeaver/wiki/Data-Filters) article, we have a description of the filters, but there is currently no information on customizing column headers. I will update the article to include information on possible customization when I have the opportunity.

**Comment by E1izabeth** [comment]
Approved.
