### ISSUE TITLE
22.3.1: 'Columns filtering/ordering menu was redesigned' -- the redesign is horrible!

### ISSUE THREAD

**Issue by exsell-jc** [dbeaver/dbeaver#18610]
Thank you for your work. The patch overall is great. I would like to nitpick one part of the patch.

Column filtering/ordering has been ~75% my DBeaver workflow outside of queries.

Now, not only does it take extra clicks, it also doesn't work very well. Though it's only few problems, they are such basic functions that reporting bugs proportionately feels too big of a time sink to report.

Please revert this as soon as possible, and consider making this frustrating 'redesign' optional in the future.

**Comment by Nick-Nal** [comment]
I can also add that option 'Show attribute ordering' in Editors -> Data Editor -> Appearance -> Grid menu currently not doing anything at all

I've always had 'Show attribute filtering' unchecked and 'Show attribute ordering' checked. Since 22.3.1 it just makes ordering icon to disappear, and filtering menu isn't there, too

At least, leave ordering icon alone just and don't mix it with filtering

**Comment by ptarant** [comment]
really sucks. reverted to the previous version.

**Comment by uslss** [comment]
#18589

**Comment by danyel117** [comment]
I'd also vote to re-instate the previous quick filter and ordering buttons! It's confusing that now when I click the button it filters on the first column (i guess?) instead of filtering in the column that I clicked on.

**Comment by exsell-jc** [comment]
> really sucks. reverted to the previous version.

How did you revert it? Did you do it from source?

For my Debian for some reason, it was unable to find version 22.3.0 when I did `sudo apt install dbeaver-ce=22.3.0`.

**Comment by uslss** [comment]
Сonfig option to customize sort and filter icons will be added in the scope of #18671 .
Close this issue as a duplicate
