### ISSUE TITLE
Editor catalog/schema chosen changes default catalog/schema in DB navigator

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#18623]
### Description

For snowflake Editor catalog/schema chosen changes default catalog/schema in DB navigator.

### DBeaver Version

22.3.1

### Operating System

win10

### Database and driver

snowflake

### Steps to reproduce

https://user-images.githubusercontent.com/31996417/209942813-4201868a-b724-4b02-b9c0-670ad081a9e3.mp4

**Comment by LonwoLonwo** [comment]
This is expected behavior. Because by default Snowflake DBeaver opens only one connection for all operations, including SQL Editor.

![2023-02-07 12_23_57-Window](https://user-images.githubusercontent.com/45152336/217207496-f2a9c623-0a3c-4aa4-83d4-70a23cf1f329.png)

This behavior can be changed in the connection settings -> SQL Editor by changing the "Default" setting on the "Always"

![2023-02-07 12_24_22-Window](https://user-images.githubusercontent.com/45152336/217207889-2ce40c11-ce48-44d5-9fd0-7e4fffb94686.png)
