### ISSUE TITLE
Copy-pasting from code editor to OneNote produces bad formatting

### ISSUE THREAD

**Issue by brankoradovanovic-mcom** [dbeaver/dbeaver#18723]
### Description

Copying syntax-highlighted code from code editor and pasting it into an external application such as Word or OneNote produces bad formatting, i.e. loss of whitespace.

### DBeaver Version

Community Edition 22.3.2

### Operating System

Windows 10 x64

### Database and driver

n/a

### Steps to reproduce

The following code:

```
with cte as
( 
	select col1, col2
	from my_table
)
select * from cte;
```

...looks like this in DBeaver's code editor:
![code_editor](https://user-images.githubusercontent.com/101108585/211619011-fbdc6b17-7ef6-4bb3-a96d-e401876263e6.png)

...but copy-pasted from DBeaver to Microsoft Word looks like this:
![word](https://user-images.githubusercontent.com/101108585/211619060-475d51ea-a1d1-4171-871d-97df95d3cdd1.png)
(leading whitespace lost; vertical spacing looks funny but is actually OK, no blank lines are produced)

...and copy-pasted from DBeaver to OneNote looks like this:
![onenote](https://user-images.githubusercontent.com/101108585/211619112-8f105e50-7f1d-4148-8ebe-04980e166011.png)
(leading whitespace and whitespace around highlighted words lost)

Copying to Outlook is affected too; the end result looks like the Word example above.

This used to work fine in recent versions (22.0-22.1?).

**Comment by bikeridercz** [comment]
This is a reason why I downgraded to 22.3.0 where it works fine, maybe it helps

**Comment by brankoradovanovic-mcom** [comment]
Let me just add that vertical spacing as produced by copying to Outlook and Word does not break the SQL, but is still rather annoying. IIRC that was also fine in earlier versions.

**Comment by bikeridercz** [comment]
Here is a screenshot from my MicrosoftOutlook client @MacOS where the same SQL script is copied via clipboard from DBEAVER 22.3.0 and then from the newest release 22.3.2 where the formatting is broken ...
<img width="1078" alt="image" src="https://user-images.githubusercontent.com/5019226/212394489-a6860cff-6185-4fe3-99fd-8dbc8735c6a5.png">

**Comment by iraidaa** [comment]
I confirm that copying the code from Editor in DBeaver CE  22.3.2 and pasting it to Word and OneNote (using Ctrl+C and Ctrl+V) produces bad formatting.

DBeaver 22.3.2:
![image](https://user-images.githubusercontent.com/49681450/213408377-ab41f999-15c2-49a2-8191-a5b1130b24a8.png)


Word:
![image](https://user-images.githubusercontent.com/49681450/213408234-a8e427a8-f821-4497-b889-bbafa22cb376.png)

OneNote:
![image](https://user-images.githubusercontent.com/49681450/213408552-ead202b1-1310-4fc0-b1e4-8f9605cf0f5a.png)


In 22.3.0, DBeaver didn't have this issue.

DBeaver 22.3.0:
![image](https://user-images.githubusercontent.com/49681450/213408842-c51cfe73-1a2b-4218-b896-fbd33c8299f4.png)

Word:
![image](https://user-images.githubusercontent.com/49681450/213409098-76d47654-d89f-4a5c-8fa7-d6824a47d5f0.png)


OneNote:
![image](https://user-images.githubusercontent.com/49681450/213409190-8219e93a-44c4-41e1-852b-0a7420b81d7b.png)

**Comment by stonux** [comment]
Pasting into word: 
- Cause: A \n creates a new paragraph in Word, while you expect a line break (like pressing Shift+Enter in Word).
- Workaround 1: Format paragraph with no vertical spacing after.
- Workaround 2: Paste into editor, copy again and paste into Word. Loses syntax highlighting.
- Fix proposal: If copy would create \r instead of \n at each end of line, pasting into Word could work better.

**Comment by roadrunner71** [comment]
I am seeing the same problem, very frustrating. I can get it to paste correctly into Toad and then copy back out from there but I only have Toad on one machine so a bit of a hastle.

**Comment by Dextertje** [comment]
I use this all the time and now it's broken. It would be nice to have this fixed.

**Comment by ShinobiAlsedo** [comment]
The added new lines and removed indents also happens when pasting from DBeaver CE 23.0.0 into Microsoft Excel. It used to work fine with DBeaver CE 22.2.0 (albeit with loss of formatting).

Example in either version of DBeaver:

![image](https://user-images.githubusercontent.com/92803377/233136897-54134ed8-eb5e-493d-ab3c-b62cb62fd671.png)

Pasted from DBeaver CE 23.0.0 into Excel:

![image](https://user-images.githubusercontent.com/92803377/233133508-a6bab419-fe00-422b-9af1-3876419f1fbb.png)

Pasted from DBeaver CE 22.2.0 into Excel:

![image](https://user-images.githubusercontent.com/92803377/233133625-fe59e6f2-9027-47b4-9c5e-42f7f198fc19.png)

It seems like it's due to the fancier way of copying that preserves formatting. The way I work around it is to use Paste Special (Ctrl+Alt+V) in Excel and select either Unicode Text or Text.

**Comment by LGil133** [comment]
problem remains in Version 23.0.2.202304091457
the maijor problem is loss of identation
waiting for a solution

**Comment by nmoreaud** [comment]
Workaround: copy paste to vscode, then copy paste from vscode to word.
VsCode applies its own syntax coloration.
You can choose a white background with Ctrl+Shift+P, Color theme, light+

**Comment by LGil133** [comment]
Issue solved in version 23.0.4.202305071722

**Comment by brankoradovanovic-mcom** [comment]
In the last version (I've tried 23.0.5.202305211610, Win 10 x64), formatting of code copy-pasted to Word and Outlook looks flawless to me, however OneNote is the same as reported. I hope this is ultimately fixable, i.e. that it's not a some sort of OneNote quirk that can't be worked around.

**Comment by MashaKorax** [comment]
can't reproduce in DBeaver 23.1.0

**Comment by brankoradovanovic-mcom** [comment]
Unfortunately this does not appear to be fully resolved in 23.1.0. Bad formatting, as described, is still produced when copy-pasting to OneNote (both Office 365 and Windows 10 versions of the app):

![image](https://github.com/dbeaver/dbeaver/assets/101108585/05bb3520-0989-4f03-ac76-fbfdc0fdef4d)

The web version of OneNote is not affected, though.

**Comment by MashaKorax** [comment]
You are right. This does not affect the web version, but it affects the desktop version OneNote. Thanks for the suggestion!

**Comment by E1izabeth** [comment]
It's not a DBeaver bug. I checked raw clipboard content and it's contains whitespaces in the correct positions. We can't fix it from our side.

Also I noticed that the same happens when copying highlighted text from Eclipse (for example, xml).

Workaround that works for me: copy to Word, then copy from Word to OneNote

**Comment by brankoradovanovic-mcom** [comment]
Of course, if OneNote treats the clipboard data in a strange way, it's unfortunate, as indeed it can't be helped.

One last recourse might perhaps be to try and see why older versions of DBeaver do work with OneNote.

That put aside, I'd say copying to e.g. Word first is fine as a workaround.

**Comment by E1izabeth** [comment]
DBeaver don't handle copy events by itself, it's done by Eclipse. So, probably it worked in older DBeaver versions and doesn't work now, because the way Eclipse put metadata about text style has changed.
