### ISSUE TITLE
External SQL formatter "SQLinForm" expects UTF-8, gets UTF-8 but Umlaute (äöü) get destroyed

### ISSUE THREAD

**Issue by Marmeladenbrot** [dbeaver/dbeaver#18735]
### Description

External SQL formatter: SQLinForm (https://www.sqlinform.com/)

Forum discussion: https://forum.sqlinform.com/dbeaver-external-formatter/german-umlaute-will-be-destroyed/
"The external formatter is not converting any codepages. It assumes the SQL statement in UTF-8"

When I try to format SQL code that contains Umlaute in a column name or a string the Umlaute will get replaced by "�" or "??" despite DBeaver and "SQLinForm" working with UTF-8 encoding.

I dont' know if the error is in DBeaver or in "SQLinForm".

### DBeaver Version

Community Edition 22.3.2

### Operating System

Windows 11 22H2 22621.963

### Database and driver

Database name and version: Exasol 7.0.9
Driver and name: "maven:/com.exasol:exasol-jdbc:RELEASE", 7.1.16

### Steps to reproduce

1. Download "SQLinForm" (https://www.sqlinform.com/download-sql-formatter-windows-app/) and set "SQLinForm" as external formatter in DBeaver (![grafik](https://user-images.githubusercontent.com/9965585/211800788-6edcfc30-9272-4289-80a4-398d9bd5e7c9.png))
2. Setting "SQLinForm" settings ([SQLinFormDesktop Profile.txt](https://github.com/dbeaver/dbeaver/files/10391855))
3. Setting encoding in DBeaver to UTF-8 (
![grafik](https://user-images.githubusercontent.com/9965585/211796877-5c9fb4bc-bdc0-4cbe-b727-08012667953e.png))
4. Creating a new SQL script
5. SQL Code before formatting:
```
SELECT ÖFFIS, OFFISß
FROM TEST
WHERE a = 'AÄOÖUÜaäoöuüß' AND b = 'AOUaouß'
```
6. Format via CTRL + SHIFT + F
7. SQL Code after formatting:
```
SELECT
    �FFIS
  , OFFIS�
FROM
    TEST
WHERE
    a = 'A�O�U�a�o�u��'
AND b = 'AOUaou�'
```

### Additional context

Extensions: 
![grafik](https://user-images.githubusercontent.com/9965585/211797431-f63cf0eb-76c1-4aac-ad44-6cf489c249e3.png)

**Comment by ShadelessFox** [comment]
Thank you for your report.

**Comment by guidomarcel** [comment]
Hello, I am the author of the mentioned external SQL Formatter for DBeaver  'SQLinForm'. This issue is very probably related to how SQLinForm was writing the formatted SQL to stdout. It wrote the formatted SQL like this
`Console.WriteLine(formattedSQL);`
I changed this into
`Console.OutputEncoding = System.Text.Encoding.UTF8;
 Console.Write(formattedSQL);`
and did some tests. It looks like it is working now fine.

![grafik](https://user-images.githubusercontent.com/29659482/229899426-69ce4e1c-6b70-4689-86c3-e0250faa6fd5.png)


Hope this helps

**Comment by Marmeladenbrot** [comment]
@guidomarcel Thanks, that fixed it.

Ticket can be closed.
