### ISSUE TITLE
Sort/Filter Database Navigator by table size

### ISSUE THREAD

**Issue by benzdouglas** [dbeaver/dbeaver#18897]
I'm importing a client's existing third party database that I am in charge of rebuilding into a shiny new system, and many of the existing tables they do not use, so it would save me a good amount of time to either sort or filter the database navigator by any tables that have data in them.

Maybe just having a sort function in the header, or an option to filter by something other than name would be good.

Alternatively I can use an SQL query to sort by size so there is an easy workaround, but would be nice to add to the UI

**Comment by LonwoLonwo** [comment]
Hello.

You can sort your tables via UI. Steps:

1. Choose the "Tables" folder in the navigator tree.

![2023-01-30 12_08_13-DBeaver Ultimate 22 3 3 - public](https://user-images.githubusercontent.com/45152336/215434811-83a11a76-8be7-4d8c-a0d2-fdf3073a0b58.png)

2. Open the "Configure columns" menu.

![2023-01-30 12_08_57-DBeaver Ultimate 22 3 3 - public](https://user-images.githubusercontent.com/45152336/215434898-f1a2c997-a677-417c-8835-cd503bbe422b.png)

3. Find Disk space or another property name with the same meaning (it is database-specific) and enable it.

![2023-01-30 12_09_11-DBeaver Ultimate 22 3 3 - public](https://user-images.githubusercontent.com/45152336/215435413-21a009c5-ad4f-4fb6-a4b1-28bcb03a93ed.png)

4. You can sort columns by clicking on the column header so that you can now sort your tables by size.

![2023-01-30 12_09_48-DBeaver Ultimate 22 3 3 - public](https://user-images.githubusercontent.com/45152336/215435716-ebf9aa95-a60a-4343-85d0-e239cfbaf593.png)

**Comment by benzdouglas** [comment]
Ah! You're a genius, I didn't even think to check there. I was only trying to sort the tables in the navigator window but didn't think to open up the Tables properties panel. Disregard the feature request!
