### ISSUE TITLE
MISSING GENERATES SQL -> INSERT 

### ISSUE THREAD

**Issue by MaddoCXX** [dbeaver/dbeaver#18918]
### Description

When I select Query and after the query result when I right it doest not appear. However on my other other SQL script it is showing 

On this script it is missing, does not show (ORACLE)
![image](https://user-images.githubusercontent.com/112743692/215967061-ae8a61fc-ae0f-40b0-927e-36ef592a0669.png)

However on the other script it appears (ORACLE)
![image](https://user-images.githubusercontent.com/112743692/215967135-dcb6dfa2-2e99-4c58-8324-e82ea42d3efc.png)

### DBeaver Version

Dbeaver Community Edition 22.3.3.202301211053

### Operating System

Windows 11

**Comment by nmankus** [comment]
+1 for postgresql build on basic select statements on the same version of mac build. Coworker on windows build is not experiencing it

**Comment by E1izabeth** [comment]
Can be reproduced on sample query like 
`SELECT 1, 2, 3 from Album a;`
It seems that the issue happens if the result set is readonly (marked with a golden lock in the left top corner).

**Comment by serge-rider** [comment]
`SELECT 1, 2, 3 from Album a;` doesn't contain any columns from original table, it doesn't make sense to use such queries.
Can we reproduce it somehow else?

**Comment by LonwoLonwo** [comment]
Hello @MaddoCXX 

![2023-02-23 15_54_53-MISSING GENERATES SQL -_ INSERT · Issue #18918 · dbeaver_dbeaver — Mozilla Firef](https://user-images.githubusercontent.com/45152336/220912413-8f19cc67-ba8e-43f9-90b4-2b84e658e774.png)

Generate SQL dialog can't appear because your result columns are read-only. Yellow lock says about it.
So, the question is - does it expected behavior for you - that this result is read-only? If not, please provide your query for testing/

**Comment by MaddoCXX** [comment]
> Hello @MaddoCXX
> 
> ![2023-02-23 15_54_53-MISSING GENERATES SQL -_ INSERT · Issue #18918 · dbeaver_dbeaver — Mozilla Firef](https://user-images.githubusercontent.com/45152336/220912413-8f19cc67-ba8e-43f9-90b4-2b84e658e774.png)
> 
> Generate SQL dialog can't appear because your result columns are read-only. Yellow lock says about it. So, the question is - does it expected behavior for you - that this result is read-only? If not, please provide your query for testing/

@LonwoLonwo So how to disable this lock? so meaning if i disable the lock it will now show the GENERATE-> INSERT?

**Comment by LonwoLonwo** [comment]
Maybe yor database have read-only status? 
If not - please provide query for testing. Without a query I can't help.

**Comment by uslss** [comment]
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it.

**Comment by lulungsatrioprayuda** [comment]
Hi there, I was having the same issues, but I found the root cause. In my opinion, based on my check, it happened cause some of people who have set ur account connection or limited the feature of generating SQL or disabled that feature from ur account connection to DB, i  checked  my DB Oracle personal account ,and that feature "Generate SQL" is not visible , but when I tried supper account who have managed that feature "Generate SQL" are available, idk how they manage it. but I tried find tutorial how to manage the feature in google and I found it maybe that people use this method

![Image](https://github.com/user-attachments/assets/2ffa9f19-0109-44b0-9d43-bd48aa7d7b73)
