### ISSUE TITLE
Functional Requirements

### ISSUE THREAD

**Issue by lzb-libra** [dbeaver/dbeaver#18990]
How should I set this place so that he directly displays the total number of entries instead of 100+, I don't want to click once to display the total number of entries, this is too troublesome.
![QQ截图20230207185459](https://user-images.githubusercontent.com/63389341/217226234-51b103ef-54f5-41a9-8d24-3738650aa108.png)

**Comment by ShadelessFox** [comment]
Hello @lzb-libra,

Thank you for your request, but we want to keep the current behavior the same.

Let me explain: DBeaver executes a separate query for counting the number of rows in the result set. Because of that:

1. It can result in performance degradation if always performed without the user's intention.
2. It can result in side effects if the source query contains invocations of non-pure procedures or functions
3. It can result in side effects if the source query is DML
