### ISSUE TITLE
backup CreateProcess error=206, filename too long

### ISSUE THREAD

**Issue by akira32chen** [dbeaver/dbeaver#19169]
### Description

When I back up postgresql, it appears some errors in seeming file too long. My DBeaver version is Version 22.3.5.202302171528. My OS is Windows 10 64bit Traditional Chinese.

if I do not select public some tables, then the problem will appear.
If I select all public tables, then the problem will not appear.

eclipse.buildId=unknown
java.version=17.0.6
java.vendor=Eclipse Adoptium
BootLoader constants: OS=win32, ARCH=x86_64, WS=win32, NL=en
Command-line arguments:  -os win32 -ws win32 -arch x86_64

org.jkiss.dbeaver.model
Error
Thu Feb 23 22:04:58 GMT+08:00 2023
CreateProcess error=206, 檔名或副檔名太長。

=====

Error executing process
  Cannot run program "C:\Users\user1\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win\14\pg_dump.exe" (in directory "C:\Users\user1\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win\14"): CreateProcess error=206, 檔名或副檔名太長。
  Cannot run program "C:\Users\user1\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win\14\pg_dump.exe" (in directory "C:\Users\user1\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win\14"): CreateProcess error=206, 檔名或副檔名太長。
    CreateProcess error=206, 檔名或副檔名太長。
    CreateProcess error=206, 檔名或副檔名太長。

### DBeaver Version

Community Edition Version 22.3.5.202302171528

### Operating System

Windows 10 64bit Traditional Chinese

### Database and driver

1.Database Postgresql

### Steps to reproduce

1.try to backup database of posrgresql to tar file, and then errors appear.

**Comment by LonwoLonwo** [comment]
Hello @akira32chen 

Can you please provide a filename for reproducing this issue?

Also, what backup type did you use - Database or schema backup? And what is the version of your PostgreSQL server?

**Comment by akira32chen** [comment]
filename : odoo20230223_2.tar
Objects:public
Table: unselected 20 tables
PostgreSQL version: PostgreSQL 12.10 (EnterpriseDB Advanced Server 12.10.14) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-36), 64-bit

I think the problem is combining the command line with too many unselect table, so the system crash. If I do not unselect 20 tables, the system is no problem.

**Comment by LonwoLonwo** [comment]
Can you please provide a screen from the backup settings page?

![2023-02-24 12_32_55-DBeaver Ultimate 22 3 5 - _TEST_DB_ Script-85](https://user-images.githubusercontent.com/45152336/221143806-7dc0a51a-96ef-499e-80d1-462bc32376c9.png)

**Comment by uslss** [comment]
There have been no updates for a long time.
If the issue is still actual - feel free to reopen it.

**Comment by 928290713** [comment]
解决了吗

**Comment by okortoreno** [comment]
This issue is still reproducible, (probably it's from beginning)

The problem occurs when you try to backup PostgreSQL database with many tables.
At "Choose objects to export" dialog all tables are checked by default.
If you don't won't to backup all tables and uncheck one or more
remaining tables (I guess) are passing to pg_dump.exe as command line parameters one by one
(by pg_dump.exe "-t pattern" parameter I guess)

With many tables It causes error:

`java.io.IOException: Cannot run program "C:\Users\xxx\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win\17\pg_dump.exe" (in directory "C:\Users\xxx\AppData\Roaming\DBeaverData\drivers\clients\postgresql\win\17"): CreateProcess error=206, The filename or extension is too long 
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at java.base/java.lang.ProcessBuilder.start(Unknown Source)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.executeProcess(AbstractNativeToolHandler.java:227)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.doExecute(AbstractNativeToolHandler.java:285)
	at org.jkiss.dbeaver.tasks.nativetool.AbstractNativeToolHandler.lambda$0(AbstractNativeToolHandler.java:88)
	at org.jkiss.dbeaver.runtime.RunnableContextDelegate.lambda$0(RunnableContextDelegate.java:39)
	at org.eclipse.jface.operation.ModalContext$ModalContextThread.run(ModalContext.java:124)
Caused by: java.io.IOException: CreateProcess error=206, The filename or extension is too long 
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(Unknown Source)
	at java.base/java.lang.ProcessImpl.start(Unknown Source)
	... 7 more
`


Maybe, if few tables are unchecked and many tables are checked "--exclude-table-data=pattern" parameter should be used



As workaround: check all tables and add parameter to "Extra command args": "--exclude-table-data=my_unwanted_tables"


DBeaver Version 24.3.5.202502162012 at Windows 11 64bit

This issue should be reopened but i have not permissions to do it.
