### ISSUE TITLE
About debugger optimization

### ISSUE THREAD

**Issue by yangmeng66** [dbeaver/dbeaver#19321]
**Is your feature request related to a problem? Please describe.**
As we all know, dbeaver is still lacking in debugger at present. The only function of postgres debugger does not support step into, stop return, console, variable watch, source lookup, and so on. When will you optimize these? Or support more popular databases, such as mysql, oracle, etc

**Comment by LonwoLonwo** [comment]
Hello @yangmeng66 

DBeaver will support it someday. 
But since, at the moment, the interest shown by the community in this feature is insignificant - then the priority of tasks related to debugging is insignificant. 
If you have any specific ideas for improvement - please publish them here. Otherwise, I will transfer this Ticket to discussion to the "General Ideas" section. 
If any existing tickets on our board seem essential to you, you can put a sign 👍  on the first message, and create feedback for us this way.

**Comment by yangmeng66** [comment]
I think many people who use Oracle should use PLSQL and debugging. Why don't they pay attention to it?
I have already tried to realize the debugging function of our self-developed database. Do you have any good reference materials? In addition to the source code of eclipse and JDT
![image](https://user-images.githubusercontent.com/51857567/224662794-f04efc77-261f-4929-ae68-6c063e34a9c9.png)
