### ISSUE TITLE
Unable to install the Darkest Dark theme

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#19504]
### Description

Problem with installing the Darkest Dark theme after updating to version 23.0.1: 

"I just updated DBeaver to the latest community edition and I noticed that I cannot install the Darkest Dark theme anymore." [Found on Twitter](https://twitter.com/hnavia/status/1640395894259417089?s=12)

![image](https://user-images.githubusercontent.com/12581569/228045534-6e9e0e81-dc77-4be4-92de-7dc8f3c02078.png)

### DBeaver Version

CE 23.0.1

**Comment by hnavia** [comment]
I'm the reporter of this issue.

So, after the update, I tried to install Darkest Dark theme but I got that error. I remembered that some months ago, there was a similar issue that required me to install the following software:

CodeTogether CI Update Site - https://www.codetogether.com/updates/ci/

After installing it, I tried again with the same result. However, frustrated I repeatedly clicked on the "next" button which showed me the message to complete the installation. After that, I restarted the instance and noticed that the GUI was mixed, restarted again and it started working.

I don't have much more information about this and the reason for the "clicking rage" was because I saw the "Next" button available for a second when selecting all the dependencies.

I know this isn't much but I hope it helps a bit.

Please feel free to ask me anything, I'll try to provide the information as soon as possible.

**Comment by Destrolaric** [comment]
@hnavia It looks like Darkest Dark extensions have migrated to Java 17. Unfortunately, we are bundling Java 11 for now. As a workaround, you could use Java 17 as your Runtime java.

**Comment by hnavia** [comment]
> @hnavia It looks like Darkest Dark extensions have migrated to Java 17. Unfortunately, we are bundling Java 11 for now. As a workaround, you could use Java 17 as your Runtime java.

I didn't know it was possible to change the Java version. Where can I find a document to do this?

Thank you in advance and kind regards.

**Comment by Destrolaric** [comment]
@hnavia There are two ways, you could replace VM in `jre` folder of the installation with desired java distribution or, as I remember, you could pass your Java path in `-vm` argument in dbeaver.ini in the installation folder.

**Comment by E1izabeth** [comment]
The issue is not reproducible anymore on DBeaver 23.0.2
