### ISSUE TITLE
DBeaver Importing Templates Not Working for Enterprise Edition

### ISSUE THREAD

**Issue by flambchap** [dbeaver/dbeaver#19562]
### Discussed in https://github.com/orgs/dbeaver/discussions/19527

<div type='discussions-op-text'>

<sup>Originally posted by **siracdemir** March 29, 2023</sup>
Hi,

I was using Dbeaver community.
Recentyl, I have been using Enterprise Edition.
I exported templates from Dbeaver comminity.
I have imported that exported template to Enterprise Edition, but nothing appears. 
Almost all of my template snippets are SQL and SQL Server context.

The ss below is from Dbeaver community while exporting template.
Please , you can also see a very simple exported template below(templates_2023-03-29.zip)
Note: my Dbeaver community version: 23.0.0.202303040621
Enterprise Edition version: 23.0.0.202303131136
![image](https://user-images.githubusercontent.com/49415453/228455948-e84b3330-26d2-489e-8a5c-d102b831155c.png)

[templates_2023-03-29.zip](https://github.com/dbeaver/dbeaver/files/11097587/templates_2023-03-29.zip)
</div>

**Comment by Xylandor** [comment]
This issue isn't just with Enterprise because I'm having a related issue with Community. Apparently, it seems the shortcut key Control+Option+Space (Mac) / CTRL+ALT+Space (Win) only shows templates that are set with the context of "SQL". Anything else is not shown. This isn't limited to imported templates. You can reproduce the behavior with a new template. I don't use this feature too often, but it used to work just fine, so not sure which build broke it. 

Reproduction Steps: (BTW, I am connected to a MySQL instance in my editor window.)
1. In settings under Editors > SQL Editor > Templates, select any item in the template list to make the New button active. (Side note: The New button should always be active without having to have an item selected.)
2. Click the New button.
3. Specify a name and in the Context dropdown, choose an option other than "SQL" (in my case, since I'm connected to MySQL instance, I chose MySQL). 
4. Specify a simple query and save changes.
5. In an editor window, use the shortcut keys to display a list of available templates. Notice that the new template created is not showing in the list. 
6. Now go back and edit that template and change the Context option to "SQL" and save changes.
7. Now when you use the shortcut keys, the new template is now showing in the list. 

The template context list is showing the following:
![image](https://user-images.githubusercontent.com/24617679/232821232-b152c4b0-d2ac-4083-aa07-1016130c6b86.png)

Which are the only ones with the Context set to SQL.
![image](https://user-images.githubusercontent.com/24617679/232821513-d607dc78-9801-41e6-940d-fafad6702e1c.png)

**Comment by E1izabeth** [comment]
Reproduced the issue from description.
Can't reproduce the issue described in the comment.
