### ISSUE TITLE
Throwing errors even the sql is correct while using Timescale Db

### ISSUE THREAD

**Issue by vimalaathythan** [dbeaver/dbeaver#19617]
### Description

I'm using Dbeaver to connect with my Timescale Db. It's like a glitch or something. my SQL editor throws errors even if the SQL is correct.  I'm attaching an image of it.
I typed the same SQL 2 times. but 1st one throws an error.
![DBEAVER ERROR](https://user-images.githubusercontent.com/125578423/230250600-8b70f173-b1cd-4624-8928-9b2853045b6c.png)

### DBeaver Version

23.0.1

**Comment by E1izabeth** [comment]
Please provide a script as a file with the broken query

**Comment by ShadelessFox** [comment]
Hello @vimalaathythan,

Try disabling the following option or remove empty lines inside your query:

![image](https://user-images.githubusercontent.com/35821147/230305097-7acf6e2e-de9c-4c5e-97c3-58d20469c5d7.png)

Otherwise, you can manually select your query and hit <kbd>CTRL+ENTER</kbd> to execute everything within the selection.

Please let me know if it helps.
