### ISSUE TITLE
after crash i can not open the dbeaver EE version 23.0.0

### ISSUE THREAD

**Issue by szekka9** [dbeaver/dbeaver#19735]
### Description

I had a crash, and i had to force close the application. When i tried to start after it, this error message came up:
![image](https://user-images.githubusercontent.com/33115003/232761688-02bcd6a4-3626-4235-be4e-a08544819198.png)

behind the details button here the error message:
An internal error occurred during: "AutoRegisterSchemeHandlersJob".
C:\Users\xxxxx\AppData\Local\Temp\jna-2032413889\jna10245239113087894989.dll: This program is blocked by group policy. For more information, contact your system administrator

nothing changed on my laptop, the group policy is already there.

i attach the log files
[dbeaver_debug_log.txt](https://github.com/dbeaver/dbeaver/files/11261116/dbeaver_debug_log.txt)
[metadata_log.txt](https://github.com/dbeaver/dbeaver/files/11261117/metadata_log.txt)

### DBeaver Version

Enterprise Edition Version 23.0.0

### Operating System

Win

### Steps to reproduce

1. try to start the app
2. load successfully and my workplace is appear
3. immediately pop up the error message
4. the app is closing itself

### Additional context

tried to remove the dll folder, didn't work
tried to remove the org.eclipse.core.resources folder, didn't work
tried to restart my laptop, didn't work

**Comment by iraidaa** [comment]
Hi @szekka9,

Could you please create a ticket in the system on the DBeaver website? This board is mostly for DBeaver CE

**Comment by szekka9** [comment]
oh, thanks.

**Comment by serge-rider** [comment]
I think the same issue will happen with DBeaver CE.
The error in the log is: `This program is blocked by group policy. For more information, contact your system administrator`.
This happens when DBeaver starts and JNA library is activated it extracts dll into C:\Users\${USER}\AppData\Local\Temp\ folder and then tries to load/link this DLL to DBeaver process.

Most likely it is restricted by your corporate group policy (load of DLLs from AppData). It is a very restricted policy and many applications won't start in your environment.

Here is a similar issue:
https://stackoverflow.com/questions/53484413/jna-the-specified-module-could-not-be-found-in-compiled-jar

You could consult you system administrator and add DBeaver to a whitelist.

We will add a workaround for this problem to include native libraries to DBeaver installation directly to avoid temp folder usage at all.

**Comment by szekka9** [comment]
Thank you very much for the prompt response. I understand the issue, it's just strange because it was working before and it works for my other colleagues as well. After the program froze, it stopped working without me having to restart my computer. What's even more interesting is that I have a Community edition installed on my computer and it starts up fine.

**Comment by szekka9** [comment]
i showed this problem our IT department and they changed something in the policy, so today i could run without any problem. Thanks
