### ISSUE TITLE
Displays overflowed int when using arrays (clickhouse)

### ISSUE THREAD

**Issue by jadrovski** [dbeaver/dbeaver#19865]
### Description

There is some display logic bug when running query in clickhouse against array.

### DBeaver Version

Community Edition 23.0.3

### Operating System

Ubuntu

### Database and driver

1. Clickhouse server 23.3.0
2. Any modern clickhouse driver, tried 0.4.x

### Steps to reproduce

1. Connect to clickhouse db
2. Run query 
```sql
SELECT [60000]
```
3. [-5536] (should [60000])

**Comment by zhicwu** [comment]
Hi @jadrovski, it's not an issue with DBeaver. By default, ClickHouse JDBC driver uses `short[]` for UInt16, and similarly `int[]` for UInt32 and `long[]` for UInt64, for better performance and smaller memory footprints. You may change connection property `use_objects_in_arrays` to true, so that you'll see the correct value in a database client like DBeaver or DataGrip.

**Comment by jadrovski** [comment]
> Hi @jadrovski, it's not an issue with DBeaver. By default, ClickHouse JDBC driver uses `short[]` for UInt16, and similarly `int[]` for UInt32 and `long[]` for UInt64, for better performance and smaller memory footprints. You may change connection property `use_objects_in_arrays` to true, so that you'll see the correct value in a database client like DBeaver or DataGrip.

Thank you!
