### ISSUE TITLE
Unify Restore Defaults behavior in Preferences

### ISSUE THREAD

**Issue by arhayka** [dbeaver/dbeaver#19928]
When the user changes settings in Preferences and saves them, the **Restore Defaults** button sometimes restores those saved settings instead of the defaults. This works in some sections, for example, in Spelling.

https://github.com/dbeaver/dbeaver/assets/12581569/58140252-cc77-452c-a768-eb34b4f2a7da

We need to find these sections and change the behavior of the **Restore Defaults** button.

Acceptance criteria: The **Restore Defaults** button in all sections in Preferences restores default settings.

**Comment by E1izabeth** [comment]
See #12480

**Comment by E1izabeth** [comment]
Now we want to sync preferences in Team Edition and the behavior of `Restore defaults` button broke everything at least for Data Formats preference page. Restore defaults uses BundlePreferenceStore when it should use CustomPrefStore, which brings chaos.

**Comment by LonwoLonwo** [comment]
Already have expected behavior:

- [x] Connections - Connection Types
- [x] User Interface - Confirmations (all true by default)
- [x] Editors - Schema Compare

Changed:

- [x] User Interface
- [x] User Interface - Navigator
- [x] User Interface - Error Logs
- [x] User Interface - Query Manager
- [x] Editors - Data Editor
- [x] Editors - Data Editor - Appearance
- [x] Editors - Data Editor - Appearance - Grid
- [x] Editors - Data Editor - Appearance - Plain Text
- [x] Editors - Data Editor - Binary Editors
- [x] Editors - Data Editor - GIS Viewer
- [x] Editors - Data Editor - Dictionaries
- [x] Editors - Data Editor - Data Formats
- [x] Editors - Diagram Editor
- [x] Editors - SQL Editor
- [x] Editors - SQL Editor - Scripts
- [x] Editors - SQL Editor - Code Completion
- [x] Editors - SQL Editor - Code Editor
- [x] Editors - SQL Editor - Processing
- [x] Editors - SQL Editor -Terminal
- [x] Editors
- [x] Connections
- [x] Connections - CLI - AWS (empty text as default)
- [x] Connections - CLI - GCP (empty text as default)
- [x] Connections - Drivers
- [x] Connections - Drivers - Oracle
- [x] Connections - Drivers - PostgreSQL
- [x] Connections - Errors and Timeouts
- [x] Connections - Metadata
- [x] Connections - Transactions (1 about notifications to true)
- [x] General - Mail
- [x] Connections - Kubernetes

To future:

- [ ] General - Security - Enterprise security
- [ ] Connections - Cloud Configurations ?
- [x] Editors - Data Editor - Appearance - JSON
- [ ] Gneral - Install/Update - TrusStore
- [ ] Hex Editor?
- [ ] Editors - SQL Editor - Formatting
- [ ] Editors - SQL Editor - templates?
