### ISSUE TITLE
Search in JSON viewer

### ISSUE THREAD

**Issue by loancarre** [dbeaver/dbeaver#20092]
It would be nice to have a search in JSON viewer.

**Comment by LonwoLonwo** [comment]
Hello @loancarre 

Please provide more info about your request.

Because we already have the ability to search in the JSON Viewer:

![2023-05-25 10_50_57-DBeaver Ultimate 23 0 5 - json_test_json_without_pk](https://github.com/dbeaver/dbeaver/assets/45152336/e8c55896-75e4-4883-b033-61cb8a5e3d74)

![2023-05-25 10_51_36-DBeaver Ultimate 23 0 5 - json_test_json_without_pk](https://github.com/dbeaver/dbeaver/assets/45152336/247178f2-5004-4e5c-b5e5-5ff646f94747)

**Comment by loancarre** [comment]
hello @LonwoLonwo 
Oh sorry, i didn't know, maybe it would it better to add the keyboard shortcut "ctrl+F" ?

**Comment by arhayka** [comment]
Thank you for the idea.
We may want to add a search icon there and figure out what to do with shortcuts.

**Comment by ShadelessFox** [comment]
Will be implemented in #20336.
