### ISSUE TITLE
Autofill inputs the table names in quotes

### ISSUE THREAD

**Issue by hozdenoren** [dbeaver/dbeaver#20391]
### Description

Autofill started to input names as  "DATABASE"."SCHEMA"."TABLE" instead of the previous behavior DATABASE.SCHEMA.TABLE. 

All seems to be working well except when backspace is used to delete the last ". Then it is not finding the match. Not sure if this is the intended behavior.  

### DBeaver Version

Community Edition 23.1.1.202306251800

### Operating System

Windows 11

### Database and driver

Snowflake

**Comment by torgny-elwmar** [comment]
Good thinking in doing this but maybe even better if there is a setting to turn this off if not wanted/needed? I agree with @hozdenoren that I personally do not like this feature.

**Comment by the-rexmundi** [comment]
This came from #20189 
https://github.com/dbeaver/dbeaver/pull/20189/files

To me, it is not functioning as expected because quotes should only be required if there are spaces, not Latin characters/underscore or $ in the identifier

https://docs.snowflake.com/en/sql-reference/identifiers-syntax

In the example below, COLUMN_ONE and COLUMNTWO should not require quotes

![image](https://github.com/dbeaver/dbeaver/assets/42777316/636f96aa-992e-4460-8c5b-659d44142e83)

![image](https://github.com/dbeaver/dbeaver/assets/42777316/78df52c2-3376-44fe-b9c9-7fae8f3334d8)

**Comment by Granite-Astronaut** [comment]
I doubly agree with @torgny-elwmar. After looking through parameter options on SF driver and sql editor settings I couldn't find anywhere to turn this off.  I ended up reverting my DBeaver version to 23.1 simply to turn this off. Hoping to hear a fix for this soon.

**Comment by E1izabeth** [comment]
Thank you for bug report and investigation.

**Comment by ChrisV-Newsday** [comment]
How do I disable the autocomplete double quotes?

**Comment by torgny-elwmar** [comment]
Hi,

I think this has been corrected in a new release. Suggest that you do an upgrade, which should solve your problem.

Br
Torgny

**Comment by ChrisV-Newsday** [comment]
> 

I did upgrade to the early release v23.1.5.202308210819 and it still adds the double quotes.

**Comment by torgny-elwmar** [comment]
That is strange, I use the same version: 23.1.5.202308201919 (almost at least). Please check settings for editor if that is a possible way.

Br,
Torgny
