### ISSUE TITLE
Impossible to import/export configuration on mac

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#20460]
### Description

On Windows I can firstly select a directory then write a name for the file. On  mac I can't select the final directory. If you write a file name, the Finish button becomes available, but nothing happens when you click it

https://github.com/dbeaver/dbeaver/assets/84867187/733ff98f-d6a1-461f-b492-24571ba107e6

### DBeaver Version

23.1.1

### Operating System

mac M1 monterey 12

**Comment by mroeling** [comment]
Confirmed for Ubuntu 22.04. Same issue, for Workspace export (in 23.1.1) and for Preferences (in 23.1.2). 

"Select file" is used, but this should be a "select directory", since the file itself does not exist at that moment.

![image](https://github.com/dbeaver/dbeaver/assets/2706186/bc11e940-f34b-4202-a9e2-cfeec9b693ac)
