### ISSUE TITLE
Provide P2 update site for automatic update

### ISSUE THREAD

**Issue by MahatmaFatalError** [dbeaver/dbeaver#2049]
Currently the update mechanism of DBeaver is cumbersome. Eclipse E4 provides a standard way to let the RCP app update itself via P2 update site

 see https://wiki.eclipse.org/Equinox/p2/Adding_Self-Update_to_an_RCP_Application or http://www.vogella.com/tutorials/EclipseP2Update/article.html

**Comment by serge-rider** [comment]
Generally we have P2 update site for Eclipse plugin version (https://marketplace.eclipse.org/content/dbeaver). However it doesn't work for standalone application right now.

A few version ago (3.x) we have tried to use the same approach in standalone version but there were a few issues. Because of massive plugins versions update on each release and some dependencies mess P2 update didn't work as expected.
We are going to try again later in 4.x.

**Comment by serge-rider** [comment]
Our standard update site https://dbeaver.io/update/latest/ must work in newer DBeaver versions
