### ISSUE TITLE
Bug in light theme

### ISSUE THREAD

**Issue by Kamandlou** [dbeaver/dbeaver#20511]
### Description

![Screenshot from 2023-07-08 15-02-23](https://github.com/dbeaver/dbeaver/assets/77993374/a24eb3c1-4f0e-48de-92c7-93068d031225)

### DBeaver Version

Community Edition 23.1.1

### Operating System

Ubuntu 20.04

**Comment by E1izabeth** [comment]
Hi, @Kamandlou 
Have you restarted DBeaver after theme switching?

**Comment by Kamandlou** [comment]
> Hi, @Kamandlou Have you restarted DBeaver after theme switching?
Hi
Yes, I have

**Comment by Kamandlou** [comment]
Hi @E1izabeth 
Yes, I have

**Comment by flambchap** [comment]
@Kamandlou What system theme do you use?

**Comment by Kamandlou** [comment]
> @Kamandlou What system theme do you use?
![Screenshot from 2023-07-16 13-02-57](https://github.com/dbeaver/dbeaver/assets/77993374/f1d41f55-b728-4ce4-ae5c-914fa7e80a40)

**Comment by Destrolaric** [comment]
@Kamandlou Hi. This happens when the system theme and DBeaver theme use opposite color palettes. Unfortunately, nothing can be done due to issues coming from the Eclipse side. I suggest using the same color palettes in DBeaver and OS as a workaround. Duplicate of:
https://github.com/dbeaver/dbeaver/issues/18911
