### ISSUE TITLE
Oracle: (Modiying privileges grant/revoke) Not working "Refresh" button in any public synonym & Not refreshing the Select-Query Result

### ISSUE THREAD

**Issue by esteban-coder** [dbeaver/dbeaver#20530]
### Description

Oracle: 
Modiying privileges grant/revoke: 
- Not working "Refresh" button in any public synonym
- Not refreshing when executing the query even when it should not have the privilege for SELECT

### DBeaver Version

Community Edition Version 23.1

### Operating System

Windows 10

### Database and driver

1. Database name and version: Oracle 12c 12.2.0.1.0
2. Driver name and version: Oracle JDBC driver 12.2.0.1.0 (ojdbc8-12.2.0.1.jar)

### Steps to reproduce

> In the DB:

- 2 Roles: RA, RB

- 2 Squemas: US, WS

- 1 Table: T1 (in squema and owned by WS)

- 1 Public Synonim: S1 (for table WS.T1)

> Steps:

1. GRANT RB TO US
2. [Connect with user WS] GRANT SELECT ON T1 TO RA 
3. [Connect with user WS] GRANT RA TO RB 

4. [Connect with user US] Do a SELECT * FROM S1 (actually to table WS.T1). Success showing all the table's rows.

5. [Connect with user WS] REVOKE RA FROM RB: 
 
- [Connect with user US] The SELECT * FROM S1 still shows the same result, i.e, all the table's rows.

> **It should shows an error message that the table does not exit, as user US now doesnt have privilege of SELECT table T1**

Partial solution: I have to reconnect the connection (or close the connection and open it again), and then doing the Select to synonim S1, now it is ok that it shows an error message "table or view does not exist".

- The details's page of the public synonim S1 is not updated (specifically the property Object). 
> **As user US now doesnt have privilege of SELECT table T1, in Object property of the sysnonym should be blank, and not still referencing the table as table does not exist for user US**
Partial solution:  I have to reconnect the connection (or close the connection and open it again).

6. [Connect with user WS] REVOKE SELECT ON  S1 FROM RA (previously, revert step 6, ie, grant again: GRANT RA TO RB)
 
- The details's page of the public synonim S1 is not updated (specifically the property Object). 
For this case, the SELECT * FROM S1 is ok.
Partial solution: I have to close the tab page, and double clic again in the public synonim S1.

### Additional context

For these errors, the same happens when, once revoked, you do granting again.

**Comment by LonwoLonwo** [comment]
Hello @esteban-code 

> [Connect with user US] The SELECT * FROM S1 still shows the same result, i.e, all the table's rows.

Could you please explain to me what solution you see here? Because DBeaver just sends your query to the database. And shows you the result set from the database. If Oracle returns this result on this step during one session - then probably this is Oracle's peculiarity. 

> The details's page of the public synonim S1 is not updated (specifically the property Object).

What type of refreshing do you expect here? Especially for the Object. I do not see any object changing for the synonym S1.

**Comment by esteban-coder** [comment]
I have added some bold comments in the "Steps to reproduce" so you can see it clearer.

**Comment by LonwoLonwo** [comment]
And still, it needs to be clarified.

> It should shows an error message that the table does not exit, as user US now doesnt have privilege of SELECT table T1

My answer is

> Could you please explain to me what solution you see here? Because DBeaver just sends your query to the database. And shows you the result set from the database. If Oracle returns this result on this step during one session - then probably this is Oracle's peculiarity.

> The details's page of the public synonim S1 is not updated (specifically the property Object).

Did you try to refresh the object? f5?

**Comment by esteban-coder** [comment]
I didnt try it with sql+ (a more native client) that if removing privileges to do SELECT to a certain table, then the next action in the same session is doing a SELECT to that table (through the public sinonym) and it still get the same results as it the privileges were still assigned. It shouldn't, because it would a terrible bug from Oracle. Have you tried doing the steps to reproduce the case?

Regarding of refreshing, yes I did right clic to the public synonim in the left panel several times, and property "Object" doesnt change.

**Comment by iraidaa** [comment]
Hello @esteban-code , 

Following the steps directly, in step 4, we get the `SQL Error [942] [42000]: ORA-00942: table or view does not exist` error while running the `select` statement for the first US user. Could you please share more information about privileges and other details regarding the 1-3 steps? At the same time, we see that if we use the following statements as the second WS user
```
GRANT SELECT ON S1 to US;
REVOKE SELECT ON S1 from US;
```
They work in DBeaver CE 23.1.5 so that if you try to rerun the `select` statement as the first US, you will immediately get the `SQL Error [942] [42000]: ORA-00942: table or view does not exist` error. 

As to the details page of the public synonym S1, it is still not updated. Looks like the data is cached. Even refreshing the entire synonyms folder does not help. Only if we close the view and open it again, the Object will change to N/A.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
