### ISSUE TITLE
Shortcut info in tooltip for buttons in metadata editor

### ISSUE THREAD

**Issue by DariaMarkaryan** [dbeaver/dbeaver#20889]
### Description

There are no shortcut info in tooltip in metadata editor for buttons at the start of using of DBeaver.

To enable shortcut, you need to switch between folders in metadata editor (Keys, Foreign keys, Indexes etc...)
![image](https://github.com/dbeaver/dbeaver/assets/43252954/45d2eb1a-1983-4a74-b70a-1724abda01de)

![image](https://github.com/dbeaver/dbeaver/assets/43252954/7bd69163-4331-472d-a340-6ce916d92055)

### DBeaver Version

23.1.4

### Operating System

win10

### Steps to reproduce
1. delete user/AppData/DBeaverData.
2. Open metadata editor and hover mouse on Create new column button. The tooltip is "Create New Column".
3. Switch between tabs and back to columns tab -> the tooltip is "Create New Column (Alt+Insert)"

https://github.com/dbeaver/dbeaver/assets/43252954/2aa76e1e-2165-42e3-98ab-a67809b3e57a

**Comment by DariaMarkaryan** [comment]
r̶e̶p̶r̶o̶d̶u̶c̶e̶d̶ ̶o̶n̶l̶y̶ ̶i̶n̶ ̶U̶I̶ ̶t̶e̶s̶t̶i̶n̶g̶

**Comment by E1izabeth** [comment]
Shortcut info in tooltips is being managed by the Eclipse platform itself according to the current active input context (currently focused editor or tool view and its actual state). See [getToolTipText method using getBestActiveBindingFor(command) at platform ui sources](https://git.eclipse.org/c/platform/eclipse.platform.ui.git/tree/bundles/org.eclipse.ui.workbench/Eclipse%20UI/org/eclipse/ui/menus/CommandContributionItem.java#n642).
One command can also have multiple hotkeys either depending on the context or active at the same time (see "Context Information" and "Close All" commands for example in the *User Interface -> Keys* preference page), so we just cannot fix the tooltip label for all times, as user can reconfigure hotkeys settings, while the command handlers activation still being managed by the underlying platform.

The problem description contains incorrect statement about tooltips depending on the switching between metadata folders. The reason for the observed behavior is exactly the act of active input context switching itself, not the folder switching specifically. You can click the empty area inside of any other top-level tool view besides Project and Database navigators, and note how the tooltip of the "Create New Column" tool button now lacks the shortcut again (due to the command being unavailable in that view). Then click any empty space in the entity editor without folder switching (near the *Table Name* for example), then the "Create New Column" tool button' tooltip has the shortcut notion again.
