### ISSUE TITLE
[Redshift] Error Backup execution

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#20923]
### Description

1. Select in database context menu Tools> Dump Database
2. Choose objects to export
3. Press "Next"
 Getting an error

https://github.com/dbeaver/dbeaver/assets/84867187/f80c10e2-2e92-405e-bdcf-410627f47bd5

### DBeaver Version

23.1.5

### Operating System

win 10

**Comment by LonwoLonwo** [comment]
We already hide the Native Clients section on the connection page of Redshift. Because it is not clear - how well exactly pg_dump works with Redshift. 

I can read the tables list (and can not reproduce the issue. You just lost your connection), but my dump process always fails with the error like:

`ERROR:  syntax error at or near "stdout"`

For this reason, I think we need to hide the "Backup" and "restore" buttons for Redshift. And maybe for MySQL forks, which do not support native clients to.
