### ISSUE TITLE
select result has some problem

### ISSUE THREAD

**Issue by ccczhouxin** [dbeaver/dbeaver#21037]
### Description

I use select function SELECT erfc(4.56);，the result in database console is 1.1272898309535822E-10
，but in dbeaver is
![image](https://github.com/dbeaver/dbeaver/assets/43168824/78cfa9da-c8a5-4ea6-9187-b6791435eafb)

### DBeaver Version

21.2.4

### Database and driver

PostgreSQL

**Comment by ShadelessFox** [comment]
Hello @ccczhouxin,

The output is completely fine. The only difference is the way it's formatted.

The given formatting is called a "scientific notation". You can read more here: https://en.wikipedia.org/wiki/Scientific_notation.

Unfortunately, we can't determine whether the given number was represented using a scientific notation. Moreover, due to how floating point numbers are stored in binary, it would be impossible to restore the original number of 16 digits after the decimal point from just 6 (even when represented using a scientific notation, the precision is the same, so just 7 first digits will be preserved).

**Comment by ccczhouxin** [comment]
> 1.1272898309535822E-10

If this value is rounded up to be different from the original value, the result will be incorrect

> Hello @ccczhouxin,
> 
> The output is completely fine. The only difference is the way it's formatted.
> 
> The given formatting is called a "scientific notation". You can read more here: https://en.wikipedia.org/wiki/Scientific_notation.
> 
> Unfortunately, we can't determine whether the given number was represented using a scientific notation. Moreover, due to how floating point numbers are stored in binary, it would be impossible to restore the original number of 16 digits after the decimal point from just 6 (even when represented using a scientific notation, the precision is the same, so just 7 first digits will be preserved).

If this value is rounded up to be different from the original value, the result will be incorrect.Can the value returned by the database be displayed.
