### ISSUE TITLE
update teradata driver, continued

### ISSUE THREAD

**Issue by mmmikelee** [dbeaver/dbeaver#21227]
**Is your feature request related to a problem? Please describe.**
the merge for prior issue is great, but incomplete.
https://github.com/dbeaver/dbeaver/issues/19427
the default teradata driver should be updated.
The new driver superceded the old driver 15 yrs ago.
Teradata was spun off as an independent company; ncr is no longer the company name.

**Describe the solution you'd like**
I have a patch for you. 
Remove the old teradata driver and keep the new driver, please.
Note that in the referenced previous issue's fix, the new driver name is used, removing the old ncr driver name.
Do the same in the org.jkiss.dbeaver.ext.teradata/plugin.xml
Or at the very least, swap the order of the new and old so the new one is preferred.
But really, please remove the old one from the teradata/plugin.xml.

**Describe alternatives you've considered**
users have to remember to manually update which driver they're using, and realize the default (with dbeaver) is the old one.

**Additional context**
[teradata-update.patch](https://github.com/dbeaver/dbeaver/files/12639716/teradata-update.patch)

**Comment by LonwoLonwo** [comment]
Hello @mmmikelee 

DBeaver tries to keep backward compatibility in the code.

`com.ncr.teradata.TeraDriver,com.teradata.jdbc.TeraDriver`

So, both drivers are supported here for users who use the old Teradata driver version.
And it is just a list of two components. An ordering here has no influence anywhere.

> users have to remember to manually update which driver they're using, and realize the default (with dbeaver) is the old one.

Could you please explain - what do you mean?

Because we are already using the newest class in the code:

class="com.teradata.jdbc.TeraDriver"

And a link to a maven repository as well as default versions.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
