### ISSUE TITLE
The externalbrowser authenticator must not ask for a password for authentication

### ISSUE THREAD

**Issue by TB-HunBoka** [dbeaver/dbeaver#21322]
### Description

The password field is currently required for External browser authentication, however it should be empty and grey.
Only the Username should be required.

### DBeaver Version

23.2.1.202309250303

### Operating System

Windows 10

### Database and driver

Snowflake db connection

### Steps to reproduce

1. add new connection
2. select snowflake
3. select externalbrowser for authenticatior.

**Comment by LonwoLonwo** [comment]
Hello @TB-HunBoka 

Could you please provide further steps?

What do you mean about

> The password field is currently required

The password field can be empty for a Snowflake connection. 

So, do you have an error during the connection? Could you please provide it?

**Comment by TB-HunBoka** [comment]
Hello @LonwoLonwo,

I made a snowflake connection without saving my password and when I tried to connect to the snowflake, I got a popup window to enter my password. I was confused about that, because it was a DBeaver popup not the SSO login page. 

The snowflake password was not shared with me, so I used the SSO login everywhere, so I was confused why do the DBeaver asking for my password.

Then, I could login by leaving the password field empty as you mentioned. Also the empty password can be saved, so it will not came up every time I connect to snowflake.
At first the password seemed mandatory for me.

If there isn't any real use case where the password is required for external browser authenticator, then it would make sense for me to disable or gray out the password field.

**Comment by LonwoLonwo** [comment]
Maybe this setting is unchecked in your case?

![2023-09-27 09_40_16-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/f8154a86-fd04-4762-b470-29d4ed987abd)

Because DBeaver prompts to add a password during connection only if it is unchecked.

Also, you can try our PRO products; authentication via SSO is implemented there:

![2023-09-27 09_41_02-Connect to a database](https://github.com/dbeaver/dbeaver/assets/45152336/39598b12-4cff-42d3-ac85-13d3e7da482e)

You can try it for free: https://dbeaver.com/trial/

For Snowflake, we have the support of materialized views, tasks, pipes viewing, and more. https://github.com/dbeaver/dbeaver/wiki/Snowflake

**Comment by TB-HunBoka** [comment]
Hello @LonwoLonwo, 

Yes, you are right, the save password checkbox was not checked for me.
However, I was not typing a password in that field, so I tought there isn't anything it can save. I was wrong.

I didn't know about the pro version having a different SSO implemented.
Looking at your screenshot, this is what I was expecting from the externalbrowser, only username and role is requested. No password field.

I misunderstood the externalbrowser. I tought that, it is the SSO login authenticator, that's why I wasn't expectind any password field in it. Now it makes sense.

Sorry for any inconvenience.
This ticket can be closed.
