### ISSUE TITLE
Unique constraints in column view

### ISSUE THREAD

**Issue by 6801318d8d** [dbeaver/dbeaver#21397]
**Is your feature request related to a problem? Please describe.**

In the column view, there is no column for unique constraints. There is one for not null constraint, and one for autoincrement, but none for unique:

![image](https://github.com/dbeaver/dbeaver/assets/144167388/6c143871-cdd9-4772-887a-f80c639c966e)

**Describe the solution you'd like**

Insert a GUI column that shows whether a database column has a unique constraint on it

**Describe alternatives you've considered**

SQLite Browser shows this

**Additional context**

Related #4340

**Comment by LonwoLonwo** [comment]
Hello @6801318d8d 

First of all - DBeaver has a special folder for keys - it is next to columns. But columns and keys are read separately. It will degree performance if we read unique keys and columns at the same time.

![2023-10-02 11_00_03-DBeaver Ultimate 23 2 1 - Employee](https://github.com/dbeaver/dbeaver/assets/45152336/330b56f3-7132-4fe2-ba67-bebb43273484)

2. This folder contains info about unique columns:

![2023-10-02 11_02_01-DBeaver Ultimate 23 2 1 - Employee](https://github.com/dbeaver/dbeaver/assets/45152336/f8de710c-8d26-4671-b0c3-b77b0c9cfa2d)

3. After key reading, you can return to columns and refresh them. You will see a special sign on a unique column:

![2023-10-02 11_01_43-DBeaver Ultimate 23 2 1 - Employee](https://github.com/dbeaver/dbeaver/assets/45152336/07288d26-ac66-44c2-8f96-d8666ac6a2d3)

So, I think, we have enough info about keys here.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by sutakos** [comment]
Hey I also think it would be a great thing to add constraint into the columns tab since it's related, moreover it looks like in the newer version its not possible anymore to see the little key when we have a PK, nor a U for unique. On other DB viewer we can see their constraint inside the tab and I think it would only be better to add it !
Edit : Not null is a constraint and is in the Columns section too

<img width="1344" height="295" alt="Image" src="https://github.com/user-attachments/assets/118a4b3e-1fc1-4708-94c2-cc34db2ea82a" />

**Comment by E1izabeth** [comment]
@sutakos thanks! We'll bring the information about keys back to the columns.
