### ISSUE TITLE
SQL folding improvements

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#2156]
Code folding must work incrementally (current implementation resets all folds below edit position).
"Collapse/expand all folds" actions should be provided.

(see #1664 for details)

**Comment by absnc** [comment]
Hi, I am new using you tool. very promising, and already wonderful for my current needs.

I tried your early release (ea), and got this error message.
```
Gtk-Message: Failed to load module "overlay-scrollbar"
Gtk-Message: Failed to load module "atk-bridge"
Unrecognized option: --add-modules=ALL-SYSTEM
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

(dbeaver:27893): Gtk-WARNING **: Unable to locate theme engine in module_path: "pixmap",
```

should I build a freshly compiled version from devel/master from now on, if to possibly
avoid those errors? Thanks for your work.

**Comment by serge-rider** [comment]
@absnc This is still the same old bug with Java 9: https://bugs.eclipse.org/bugs/show_bug.cgi?id=493761
Adding default parameter (`--add-modules=ALL-SYSTEM`) in dbeaver.ini still seems to be problematic. Although it shouldn't.

What is your OS and Java version (run `java -version` in terminal)?

Workaround: remove line `--add-modules=ALL-SYSTEM` from dbeaver.ini file.

This is a wrong ticket to discuss such things actually :(

**Comment by ches** [comment]
Is the folding implemented with custom Eclipse actions? Built-in folding has actions like `org.eclipse.ui.edit.text.folding.collapse` and `expand`, and Vrapper maps these to their usual Vim mappings, but they aren't working in DBeaver so I wondered if I can override the command mappings.

By the way, it took me a moment to find the "Folding enabled" checkbox in preferences, it's on the "SQL Completion" page although folding doesn't really have anything to do with completion. I think the "SQL Editor" page would make sense.

**Comment by Xylandor** [comment]
The code folding is about as useless as it can be as it is. I'm using the latest version of DBeaver and it will unfold all code when ANY edit is done; regardless if the edit takes place above or below the collapsed code. Is there any hopes that this will actually be fixed? This has been an on-going issue for quite some time now.

**Comment by Xylandor** [comment]
Using DBeaver 5.1.4.

**Comment by Tix2garr** [comment]
Bump

**Comment by richdevboston** [comment]
I have been using DBeaver for a lot of SQL Coding for about 5 weeks now, and I started using it in my training business too, because it is a nice multi-database editor.  

I really like it, but there are 2 crucially important things that I have not been able to get working properly.   I am using the Community Edition. 

Code Folding doesn’t work.  I’ve enabled it in the Preferences Panel, but it just doesn’t work.  My current program is over 500 lines of SQL and I really need the ability to hide (“fold”) major blocks of code so that I can jump to different parts of the script fast.  It really slows me down to not have code folding.  

Text Compare – I frequently need to compare 2 versions of the same script.  

Right now I have to move the code over to Notepad++ to work with large blocks of code or script files, and use either BeyondCompare or Notepad++ to compare two script files to see their differences.  

Please help on these points, because folding and file comparisons are functions that I depend upon heavily when coding.

**Comment by richdevboston** [comment]
Code folding is not working for me.  I have been using DBeaver for a lot of SQL Coding for 5 weeks.  It is a nice multi-database editor.  

There are 2 crucially important things that I have not been able to get working properly in the Community Edition. 

Code Folding... it simply doesn’t work.  I’ve enabled it in the Preferences Panel, but it just doesn’t work.  My current program is over 500 lines of SQL and I really need the ability to hide (“fold”) major blocks of code so that I can jump to different parts of the script fast.  It really slows me down to not have code folding.  

What are the SQL object types or syntax element triggers that trigger code folding to work?  Where are the "Save Folding" options on the toolbar or menus?  

Text Compare – where is this function?  I frequently need to compare 2 versions of the same script.  

Right now I have to move the code over to Notepad++ to using code folding or work with large blocks of code or large script files, and use either BeyondCompare or Notepad++ to compare two script files to see their differences.  This is a hassle and requires a few extra steps to bring the code back to DBeaver for execution.  

Please help on these points, because code folding and side-by-side file comparisons are functions that I depend upon heavily when coding.  I can do this in NotePad++, Spyder for Python, VScode, and PyCharm.  

I’m posting these questions to StackOverflow so that perhaps people in the community can share an answer.  I am pretty sure I am not the only person having trouble getting this to work.

**Comment by avrilconseil** [comment]
@richdevboston : About "Code Folding", I managed to make it work by also enabling "Toggle Block Selection" from "Edit" menu (ALT+SHIFT+A). You can disable it once the folding items appear (next to BEGIN or DECLARE statements).

**Comment by akilovich** [comment]
Fixed the issues with folding. In the context menu near breakpoints, there is now an option to quickly enable and disable folding, as well as expand or collapse all statements.

**Comment by uslss** [comment]
folding is enabled/disabled for big scripts (in attach) after reopening only.
[Script-348.txt](https://github.com/dbeaver/dbeaver/files/5524091/Script-348.txt)

**Comment by akilovich** [comment]
Fixed the issue described above. Also disabled folding in consoles.

**Comment by uslss** [comment]
Toggle breakpoint is available for source/ddl tab at object properties page - an error appears in case of choosing the mentioned option
![image](https://user-images.githubusercontent.com/31996417/98930626-f0290000-24ed-11eb-9957-906405141b09.png)

Toggle Breakpoint is also available for usual script and console - has no effect after clicking on it
![2020-11-12_13h52_37](https://user-images.githubusercontent.com/31996417/98930922-63cb0d00-24ee-11eb-816c-17b8db1c585a.gif)

**Comment by akilovich** [comment]
Works just fine with the latest EA.

**Comment by uslss** [comment]
verified
