### ISSUE TITLE
update 23.2.3 after utf-8 x

### ISSUE THREAD

**Issue by criskim-kkk** [dbeaver/dbeaver#21638]
### Description

After the update, the annotated Hangul is broken.
Try editing the ini file and changing utf-8,
Even if I edit the environment variables, it's the same.
Is there any way?

--  ��������
SELECT ooi.*
FROM out_order_if ooi ,
`me xxxx` m 
 WHERE  ooi.m_idx  = m.m_idx 
 -- AND ooi.site_name  LIKE '�Ｚ����%'

### DBeaver Version

23.2.3

### Operating System

windows 10.

**Comment by Matvey16** [comment]
@criskim-kkk  Does it happen in new scripts also, or only in old ones? If you type korean in new scripts would it also appear as incorrect symbols?

**Comment by CROMBAE** [comment]
> @criskim-kkk 새 스크립트에서도 발생합니까, 아니면 이전 스크립트에서만 발생합니까? 새 스크립트에 한국어를 입력하면 잘못된 기호로 표시되나요?

All Korean annotations of the saved SQL statement are not displayed normally.

All newly created Korean words will be displayed normally.

**Comment by LonwoLonwo** [comment]
Hello @CROMBAE 

Could you please find the .ini file (located with the .exe file), delete this parameter
`-Dfile.encoding=UTF-8`
save the file and restart DBeaver?

**Comment by LonwoLonwo** [comment]
Or could you click on your script Alt+Enter and choose other encodings for your file?

**Comment by GuenterSch** [comment]
> Or could you click on your script Alt+Enter and choose other encodings for your file?

Hello Anastasiya,
I could not find how can I change this settings (encoding) via Alt+enter. Can you advice?
Thanks Günter

**Comment by GuenterSch** [comment]
Why is it not possible to load the file how it is (ANSI or UTF-8, ..).
In German I have the problems with Umlaute (like my name Günter).
We use files in ANSI and in UTF-8. One of them will not displayed in a correct way.
Also, the normal editor notepad (it is realy very old) can load the file in UTF-8 or ANSI and displays the character correct.
If it is helpful for you, then it would be possible to convert an ANSI file to UTF-8 first (in DBeaver) and store it always as UTF-8.

**It would be very helpful, if you can change this soon**
because we have many troubles with that.

Thanks, BR
Günter

**Comment by LonwoLonwo** [comment]
Hello @GuenterSch 

You can try to change encoding like this:

![2024-01-31 11_38_00-DBeaver Ultimate 23 3 2 - _dev 8_ Script-170](https://github.com/dbeaver/dbeaver/assets/45152336/e75a12e4-4ed0-4b70-a428-eb075e47ba21)

Or you can use this my advice: https://github.com/dbeaver/dbeaver/issues/21638#issuecomment-1836133887

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
