### ISSUE TITLE
Automatically save sql scripts

### ISSUE THREAD

**Issue by myloginid** [dbeaver/dbeaver#21823]
**Is your feature request related to a problem? Please describe.**
Each time dbeaver is closed or is killed for any reason any non saved scripts are lost. 

**Describe the solution you'd like**
Dbeaver should support 
- automatically saving scripts every x minutes / each time a new query is run
- automatically synching scripts to github 

**Describe alternatives you've considered**
Saving scripts before closing is buggy and at times (esp on ubuntu) when you close the app the save dialog gets missed in a hurry

**Comment by ShadelessFox** [comment]
Hello @myloginid,

Thanks for the feature request.

DBeaver offers a set of features that might fulfill your needs.

1. You can enable editor autosaving here:
![image](https://github.com/dbeaver/dbeaver/assets/35821147/ebbd3c3f-3d0f-41b8-b7b3-994271d48e8e)
2. You can use Git integration feature:
https://github.com/dbeaver/dbeaver/wiki/Project-team-work

Please let me know if it helps.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by anborg** [comment]
Please setup an auto-recovery like Notepad++.  Notepad++ is relatively less work-loss compared to an SQL-IDE like dbeaver. If computer crashes for some updates, and NP++ is reopened after reboot, it still has all the work done (some intermediary files?!).  Yesterday my computer force shutdown due to some security updates, and dbeaver lost few hours of work, but Notepad++ did not loose. 

**Please serialize 'un saved' work, as some temporary file:**  
- **Scenario1:**  If Save is applied (for any reason, take the change and save it
- **Scenario2:** If the IDE aborts (for any reason like force power off), when IDE opened again, show where the user left off.


I wish this 'recover files' feature is available in underlying Eclipse framework, if not, it is a good time to add it in the framework, and make AUTO-recovery enabled by default in sql-editors without prompting users for save yes/no (same like NP++).

**Comment by E1izabeth** [comment]
@anborg, this issue is closed, please create a new feature request about that
