### ISSUE TITLE
Cannot type >= in SQL editor

### ISSUE THREAD

**Issue by valsamis-d** [dbeaver/dbeaver#22189]
### Description

Hello,

I'm not sure if this is an issue on my side, but the following occurs only in DBeaver (community edition, portable):

When I type >= as soon as I press the spacebar, >= changes to ≥ which of course fails when I execute the query.

Any pointers?

### DBeaver Version

Community Edition 23.3.0 Portable

### Operating System

Windows 11 Enterprise 22H2

**Comment by E1izabeth** [comment]
Hmm.. It's not happening for me. Have you installed some additional plugins?

**Comment by valsamis-d** [comment]
@E1izabeth first off, thanks for the follow-up.

I think I have found what is causing this.

When I set 'JetBrainsMono Nerd Font' (https://github.com/ryanoasis/nerd-fonts/releases/tag/v3.1.1) as a monospace font, then >= changes automatically to ≥.

Switching back to another monospace font, such as Courier, all is good. However, this occurs only in DBeaver. In other editors >= is maintained regardless the font used.

Is this something that could be fixed in DBeaver or I should report it to Nerd Font GitHub?

**Comment by E1izabeth** [comment]
I think we should try it on Eclipse to be sure it's not a DBeaver issue.

**Comment by PzaThief** [comment]
@valsamis-d Sorry to interrupt, but could you please check for the error?
The font simply tells the user how the actual value will be rendered.
The actual value has not changed, and neither has the script.
Fonts can even contain images rather than Unicode values, so it would be really strange for these values ​​to be passed through a shell or script.
So it seems to me that the error you encountered is not caused by this, but by some other cause.

working screenshot
![image](https://github.com/dbeaver/dbeaver/assets/60059706/74edfe3a-912c-4d58-8ad1-303fa6056e1c)

**Comment by valsamis-d** [comment]
@PzaThief thank you so much for the update. I tested it in the latest DBeaver release and indeed it works just fine:

![image](https://github.com/dbeaver/dbeaver/assets/17590539/0b708c60-3c7a-4ad4-b4ec-5e3a58c71dd2)

I'm happy I will keep using my favorite monospaced font :)
