### ISSUE TITLE
Cannot set data in clipboard

### ISSUE THREAD

**Issue by Ariobar** [dbeaver/dbeaver#22300]
### Description

when trying to copy the content of a window, get a error
"unhandled event loop exception
cannot set data in clipboard"

Using last version (23.3.1.202401010022) on windows 11

### DBeaver Version

Community Edition 23.3.1.202401010022

### Operating System

Windows 11

### Database and driver

Postgres 13
PostgreSQL JDBC Driver

### Steps to reproduce

I try to copy from a window or script to clipboard with crtl+c

**Comment by MashaKorax** [comment]
Hello @Ariobar . I can not reproduce your issue. Please, provide more clearly the steps to reproduce.

**Comment by E1izabeth** [comment]
Please, provide the log files. You can find instructions here https://dbeaver.com/docs/wiki/Log-files/.

**Comment by Ariobar** [comment]
After restart windows, it worked ok

Thanks for your attention

**Comment by bramoin** [comment]
I have a similar issue with the exact same error message "Cannot set data in clipboard" on version 24.1.3.202407211303, I copy text from Notepad++ v8.6.8 (64 bit) and when i try to paste it to the dbeaver sql window, it does not paste it.  But if i copy from notepad.exe then it is pasted into DBeaver.  This issue is repeatable. I have attached an image that shows the Error Log and the details window from this error.  Oh, i can copy from Notepad++ 24.1.3.202407211303 and then paste into Notepad.exe and it works with no issues.  I will restart my laptop and see.

![DBeaver-ver 24 1 3 202407211303](https://github.com/user-attachments/assets/38f67ebf-4400-4f59-955e-ec4fdf51ba08)

[dbeaver-debug-1722450744433.log](https://github.com/user-attachments/files/16446365/dbeaver-debug-1722450744433.log)

Restarted my laptop and it did not happen anymore.

**Comment by earnestware** [comment]
same issue. it must have something to do with how the code interacts with windows clipboard. when this happens i have issues copying/pasting from other apps. the problem is windows and reboot fixes the problem because the clipboard issues go away.
