### ISSUE TITLE
Smart Commit mode

### ISSUE THREAD

**Issue by JLA7777** [dbeaver/dbeaver#22313]
### Description

When using the smart commit mode in new versions when we commit, in the next query it asks to commit again.

I attach images for your review.

### DBeaver Version

DBeaver Community 23.3.1

### Operating System

Windows 11 Pro

### Database and driver

Database DB2 i Series

### Steps to reproduce

1. I make a modification to a record.
2. I save the modification and commit.
3. I do a "Select * from" and it shows me as if I had modified the registry again.

![SmartCommitMode1](https://github.com/dbeaver/dbeaver/assets/155552803/c1d86e7b-c18c-431a-969c-1a2c1dc767e3)
![SmartCommitMode2](https://github.com/dbeaver/dbeaver/assets/155552803/f83dd228-484f-408c-a366-3352b81e554e)

**Comment by opus-2** [comment]
I'm experiencing the same issue on linux ubuntu 23.10, mariadb driver. It started a few releases ago. On manual commit mode, basically every query is being interpreted as a "modifying statement" and is triggering a transaction (even a simple select). It seems smart commit is not working as intended. 
It happens both in sql editor and data editor. In the data editor, a simple refresh triggers a transaction start and adds "1" to the pending transactions count.
Also, the smart commit option tooltip says I can configure which keywords will activate a transaction, but I can't find it anywhere in the very confusing settings dialogs.

**Comment by JLA7777** [comment]
The last version that worked well was dbeaver-ce-23.1.3.
In the following versions the problem began.

**Comment by philosaur** [comment]
This is happening to me too.  I've tried several permutations of the commit mode settings, both in the connection itself and the connection type settings, and nothing changes.  It's like the settings are being ignored completely.

Postgres DB, Windows 10, DBeaver CE 23.2

**Comment by philosaur** [comment]
If you're using Postgres...

In your individual connection config dialog AND in the Connection Types config dialog, uncheck:
1. Smart commit mode
2. Return to autocommit on transaction end

While you're in the Connection Types dialog, uncheck:
1. Auto-commit by default

Now everything autocommits as expected.  The commit mode indicator in the toolbar is happily displaying "Auto", and not reverting to manual mode after every command.  I've checked that this solution works for DBeaver CE 23.1.2, 23.1.3, and 23.3.0. 

Here's what [Postgres docs](https://www.postgresql.org/docs/current/sql-begin.html) say (_emphasis_ mine):

> BEGIN initiates a transaction block, that is, all statements after a BEGIN command will be executed in a single transaction until an explicit [COMMIT](https://www.postgresql.org/docs/current/sql-commit.html) or [ROLLBACK](https://www.postgresql.org/docs/current/sql-rollback.html) is given. _By default (without BEGIN), PostgreSQL executes transactions in “autocommit” mode_, that is, each statement is executed in its own transaction and a commit is implicitly performed at the end of the statement (if execution was successful, otherwise a rollback is done).

So, through my hand or due to an update, I'm thinking the "Auto-commit by default" setting value got flipped and produced this problematic behavior.

Postgres 16 DB, Windows 10, DBeaver CE 23.1.2, 23.1.3, and 23.3.0

**Comment by E1izabeth** [comment]
I reproduced the issue.
