### ISSUE TITLE
DBeaver SQL Editor - Cursor Disappoears

### ISSUE THREAD

**Issue by Jamesm46** [dbeaver/dbeaver#22608]
### Description

I have only noticed this in the SQL Editor, so far. My cursor keeps disappearing after executing SQL statements. I read on here that clicking on the lefthand scroll bar brings it back, which worked for me.

### DBeaver Version

Community Edition 23.3.3

### Operating System

mac os Sonoma 14.2.1

### Database and driver

I Use SQLite43

**Comment by ShadelessFox** [comment]
Hello @Jamesm46,

Can you please provide footage showing your issue?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by bobort** [comment]
I'm using DBeaver on Windows Server 2019 Datacenter. I had mouse trails on. Whenever I clicked on the SQLEditor, the mouse cursor would disappear. I turned off the mouse trails, and that seemed to work. I tested on several versions of DBeaver, including the latest version of 7. The issue was on all of them.

**Comment by ShadelessFox** [comment]
@bobort

> including the latest version of 7

The latest version is 24.3.5. None of the recent versions (starting from 2021) have the digit `7` in the name. What particular version are you referring to?

Also, it's worth creating a new issue with all details provided.
