### ISSUE TITLE
When I updated Dbeaver, the plugin was removed.

### ISSUE THREAD

**Issue by qingyashizi** [dbeaver/dbeaver#22698]
I downloaded the 23.3.4 version of Dbeaver compressed package in .zip format this morning and updated my 23.3.3 version of Dbeaver. I deleted the Dbeaver folder located on the D drive, then decompressed the compressed package and placed it on the D drive. 

After restarting, I found that the previously installed Git and Office plug-ins were also deleted, and I had to reinstall them. 

I hope that after updating Dbeaver, the plugin will still be there.

**Comment by serjiokov** [comment]
Hello @qingyashizi, generally  If you deleted Dbeaver folder it reasonably to expect that all preintalled bundles will be removed because all located in Dbeaver folder.
I would recoment to unzip new version near to previous (just in the new folder) in order to have a chance switch on to previus if something go unexpectevlly. For now please use a marketplace or Install new software menu item to install tools required.

**Comment by lpena-dvelop** [comment]
This problem happend if you use the upgrade in the new update notification as well

**Comment by LonwoLonwo** [comment]
This is a duplicate of https://github.com/dbeaver/dbeaver/issues/5317

You can vote for the original ticket.
