### ISSUE TITLE
End transaction in Dbeaver 23.3.4

### ISSUE THREAD

**Issue by RobiABC** [dbeaver/dbeaver#22709]
### Description

Hi, from today, with the new version of Dbeaver 23.3.4 I noticed this message "End transaction" at the end of every query I run. And it automatically performe a rollback. This is very boring if I'm running an "update" query. 

### DBeaver Version

23.3.4

### Operating System

Windows 11 Pro

### Database and driver

Oracle 11

**Comment by regrog** [comment]
Same error here:

Also setting the value of "Close idle connection after" from 0 to 1800 doesn't  change the behavior.
I also created a new connections from 0 but the problem is still here.
![image](https://github.com/dbeaver/dbeaver/assets/7606880/74b81570-3ac7-442f-b36e-b773f0063663)

![image](https://github.com/dbeaver/dbeaver/assets/7606880/480b2c6a-eb88-43a9-9e75-df3bb05233ee)

### DBeaver Version
23.3.4

### Operating System
Ubuntu 22.04.3 LTS

### Database and driver
My SQL 8

**Comment by ricardo-froehlich** [comment]
It seems this option is turned off now, by default, in configuration of connection type.
Checking it solved this problem.
![image](https://github.com/dbeaver/dbeaver/assets/61745479/1944df33-5e8e-4660-ba89-0b149b2d92e7)

**Comment by p91paul** [comment]
I do not think this should be closed. This is a regression, when the box is unchecked there should be no automatic ending of transactions, instead it now defaults to end the transaction immediately!

**Comment by Crovax1990** [comment]
Same Problem Here after executing any query immediatly the ide pop up this panel

![image](https://github.com/dbeaver/dbeaver/assets/159149597/8642f279-ce3a-492a-9577-27bc2232b862)

here is my version

23.3.4 just updated this morning

**Comment by E1izabeth** [comment]
Issue about checkbox saving #22721

**Comment by NorbertSandor** [comment]
With Postgres, too :(

**Comment by serge-rider** [comment]
Issue with immediate transaction end fixed.
Also current statement execution tracking added
