### ISSUE TITLE
CE Ver 23.3.4.  dropping/losing SQLite3 connection since upgrade

### ISSUE THREAD

**Issue by ddDerelict** [dbeaver/dbeaver#22776]
### Description

- SQLite3 DB accessed via DBeaver and Visual Studio C# Winforms GUI app on Win 10 Pro x64
- all table definitions done in DBeaver; GUI app accesses/updates data
- GUI app has a high level of dependence on the DB; DB required for app startup/operation
- successfully using config more than 2 1/2 yrs
- only change to dev environment preceding emergence of issue: DBeaver upgrade
- all connection Settings left at default since initial installation
- automatically opens connection to "last used" DB when DBeaver starts

The disconnection appears to be time based: if I leave DBeaver open but idle over lunch (approx. an hour) the disconnect occurs.

If the workspace active Tab is a Table the data listing is replaced with  a "Reconnect to Database" button.  Although that successfully reconnects to the DB it is mildly disruptive to my workflow.

If the active Tab is an SQL script the Reconnect button is not displayed.  Instead the Table columns all show the disconnected state.  Reconnecting by right-clicking on connection name appears to reconnect for the active Table tab but when a different Table tab is activated its columns show as disconnected.  The quickest way to solve the problem seems be closing/restarting DBeaver.

From the log file (attached): 
!ENTRY org.eclipse.ui 4 0 2024-02-10 15:52:33.172
!MESSAGE Unhandled event loop exception

### DBeaver Version

Community Edition Version 23.3.4.202402041841

### Operating System

Edition Windows 10 Pro Version 22H2 (Bld 19045.3803)

### Database and driver

SQLite 3.39.3
Driver sqlite_jdbc (no version provided)

BTW: your link for driver documentation for SQLite in the Edit Connection window landed at SQLite.org's PRAGMA documentation ...

### Steps to reproduce

1. Start Visual Studio 2022
2. Start DBeaver CE v 23.3.4 ; auto connect on startup to SQLite 3.39.3
3. click a couple Table tabs to ensure connectivity
4. leave idle in background for a few hours

**Comment by ShadelessFox** [comment]
Hello @ddDerelict,

Please make sure you have this option set to zero:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/22ed66e3-9bfb-470e-866c-1ab9a96f0db3)

You are likely need to change it here as well:

![image](https://github.com/dbeaver/dbeaver/assets/35821147/e9099161-1e77-45a4-8592-dd4d59817891)

Its behavior was changed in the latest release. Previously, it would do nothing, and now it was fixed.

**Comment by coleman-rik** [comment]
This is happening with PostgreSQL connections as well after the last upgrade, and it's very annoying.

As you can see in the image below, the "**Close idle connection after (seconds):**" setting is set to 0, which according to the documentation should disable auto closing idle connections. It doesn't.
![dbeaver_settings_20240210_125118](https://github.com/dbeaver/dbeaver/assets/3697063/aff7d5b4-af49-43a6-bdf3-4fe005f4f317)

Apparently that setting is being ignored and the "**Close idle connection after (seconds)**" setting on the **Connection Types** dialog, which defaults to 3600 seconds, is superseding the previous setting and closing connections after 3600 seconds. 
![dbeaver_connection_type_settings_20240210_125118](https://github.com/dbeaver/dbeaver/assets/3697063/2ef7a0ca-1473-4ef6-ad73-3df82669a1ae)

This is extremely disruptive behavior.  Either the setting on the main Initialization dialog should be controlling, as it states in the documentation, or it should be removed with a link to the identical setting _buried_ in the **Connection Types** sub-dialog.  Since I don't make use of **Connection Types** I was initially unaware that there was a setting that secretly overrode the setting on the main **Connection setting ->  Initialization** dialog area.

Thanks

**Comment by ShadelessFox** [comment]
Thanks for the feedback. I'm going to discuss this issue with my colleagues.

**Comment by Adam-HertzbergDell** [comment]
To be clear, for me at least, the disruptive part is not that the connections are getting disconnected. The disruption is that everything that was loaded goes away and is replaced by a "Reconnect to the database" screen. Please don't invalidate what was loaded simply because it is disconnected.

Also, although I found this with greenplum connections, I assume it is a problem on all types.

**Comment by nilber** [comment]
> Thanks for the feedback. I'm going to discuss this issue with my colleagues.

I would like to contribute, I am also facing the same problem with Postgres, I have an application that does not have a frontend, I always need to manage it via the database, and since the last update, after a certain time my filter/query disappears and the connection with the database is lost, I have to keep reconnecting, accessing the table and creating the filter again, this really affects it because I previously left it open for months in the same table.

I just saw the images and did the configuration, I hope it works :)

**Comment by pcoffinwork** [comment]
I am also seeing this behavior on DB2. The keepalive setting that I have (120 sec) used to be effective with prior release, but no longer works to keep the session alive.

**Comment by teschste-reyrey** [comment]
I am having either the same or a very similar issue with Postgres.  I am running Community v23.3.4.202402060628.  I go in and uncheck the "Close idle connection after (seconds)" option for all Connection Types and everything is fine until I close and re-open DBeaver.  When I go back in, the "Close idle connection after (seconds)" option is checked again for all Connection Types.

Is there another setting somewhere overriding this option, which is forcing it back to checked?  So far, I have not been able to find one.  If you give us the option to turn on/off a settings, I would expect it to stay on/off.  If there is a potential overriding settings, a note or pop-up letting us know that, and where the overriding setting is located, would help a lot.

Any help would be appreciated!

**Comment by E1izabeth** [comment]
@teschste-reyrey it's a bug that we fixed. Fix will be available in the next release on Monday
Or you can try Early Access version with this fix now https://dbeaver.io/files/ea/

**Comment by kh** [comment]
I have the same problem with a local postgresql connection, was not having the issue before 23.3.4.202402041841. It is annoying to have because I sometimes let Dbeaver open all day and only briefly interact with it.
If the connection is idle for too long, despite having the close if idle set to 0, the connection will close.
If it can help the debug, I have a message "Connection will close in" that appears with a countdown from 60 min I think.

**Comment by E1izabeth** [comment]
@kh you can try Early Access version with the fix now https://dbeaver.io/files/ea/ or wait for the next release

**Comment by arhayka** [comment]
We decided:
- disable by default for embedded drivers
- increase default timeout to 4,2, 1 hours.

**Comment by teschste-reyrey** [comment]
This resolved my issue.  Thanks!

**Comment by RachelAmbler** [comment]
I'm getting very random issues with this. I followed all the advice here, set both places for a timeout (0, and 14,400) and reconnected.

All seemed fine. Until I got disconnected some 20 minutes later.

Then I connected. 10 seconds later, I got disconnected.

Back to connected now for several minutes.

This feels very unstable.

Testing EE on 24.0.0.202403110838
