### ISSUE TITLE
"Persist" and "Save" mean the same thing (?)

### ISSUE THREAD

**Issue by Siddhant** [dbeaver/dbeaver#22948]
**Is your feature request related to a problem? Please describe.**
In the English version, it looks like the words "Save" and "Persist" are used interchangeably throughout various menus, options, buttons, dialog boxes, etc. leading to a less than awesome UI experience.

**Describe the solution you'd like**
I think using the same verb should help give a more consistent user interface to user.
I would personally prefer "persist", but "save" is fine as well.

**Additional context**
If I am wrong in assuming that "save" and "persist" are the same thing, can you kindly add an FAQ documentation describing the difference? Would be helpful.

**Comment by arhayka** [comment]
Thank you for the question!
We cannot use "Save" instead of "Persist" in all cases. For example, when you create a new table in DBeaver UI and try to save it, you will see the following window:
<img width="549" alt="Screenshot 2024-02-28 at 22 03 30" src="https://github.com/dbeaver/dbeaver/assets/12581569/f0c0ca86-fa02-4897-b6cc-406cbf24cc68">

There is a query, DBeaver doesn't save it. It will be executed when the button is pressed.

However, we decided that "Persists" might be unclear in such a case, and we could replace it with "Execute".

**Comment by Sridhar9095** [comment]
All over the world 90% of people know the 'save' and othe 10% people don't know about persist so 'save' know all of them.
