### ISSUE TITLE
[CUBRID] Add supplementary features to the CUBRID plugin

### ISSUE THREAD

**Issue by longhaseng52** [dbeaver/dbeaver#22963]
- Display list of indexes
- Display list of serials
- Display list of synonyms
- Display list of triggers
- Display list of functions & procedures
- Display DDL of view
- Create & edit table using UI
- Remove Virtual Tab
- Export DB SQL
- Export Excel

**Comment by LonwoLonwo** [comment]
Hello @longhaseng52 

We already have the ability to export to Excel: https://github.com/dbeaver/dbeaver/wiki/Extension-Office

> Export DB SQL

And here you can read about other data export features: https://github.com/dbeaver/dbeaver/wiki/Data-transfer#export-data

> Remove Virtual Tab

You can't remove our basic functionality without a good explanation.

**Comment by kisoo-han** [comment]
@LonwoLonwo ,
* The 'export to excel' function does not mean exporting table data to Excel, but exporting schema info to Excel. However, since we believe this is sufficiently covered by DBeaver's other functions, we will exclude it from this extension as you recommended.
* As the 'Remove Virtual Tab' function is a basic & unique feature of DBeaver, we will maintain it instead of removing it from the plugin, also as you recommended.

**Comment by LonwoLonwo** [comment]
Ok, thanks. We can probably check the code and then decide if this is a new feature for DBeaver or an existing one. Thanks for the update.

**Comment by kisoo-han** [comment]
@LonwoLonwo 
Regarding the features we planned described above, there is a feature entitled '**Export DB SQL**'.

In fact, this refers to the ASCII format backup/export used in CUBRID. We have CUBRID utilities called 'loaddb/unloaddb'. They are tools for selectively or entirely backing up and restoring database objects such as tables, views, indexes, synonyms, etc. in ASCII format. 

Our intention is to back up database objects selected in DBeaver in the so-called '**CUBRID loaddb format**' and restore them using the CUBRID 'loaddb' utility. What do you think about adding this feature in the CUBRID plugin.
