### ISSUE TITLE
Change in Result Sets - Binaries parameters for cachning BLOB/LOB has no effect

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#2318]
It do not understand how the caching of BLOB/LOB work, but I thought that if I choose not to cache BLOB's those table columns was not read until I explicit asked for them.

If I show a table data contents in a grid or do a "_SELECT * FROM MyTable_" and the table contains BLOB data, I get a **Java Heap Space** error when passing the default 1GB (memory limit set in **dbeaver.ini** file).

If this is not how the Result Sets - Binary Settings work for BLOB/LOB columns. What effect do they have and are there a way to not read BLOB's or read a smaller amount of their data until I need it (want to save column data do disk, edit it, etc). ?

**Comment by serge-rider** [comment]
This depends.
If you have real LOBs then cache disable will help (DBeaver won't fetch LOB contents).

But if, for instance, it is MySQL then there are no real BLOB or CLOB data types. Binary columns are read along with other columns and it is not possible to omit this.
The only thing you can do is to use custom SQL query with column list (instead of *) which won't select binary/longtext columns.

**Comment by pdanie** [comment]
We are using _SQL Server 2014 Express_ which I would guess has real BLOB/CLOB handling.

When I use **SELECT** statement I usually clip down the resultset, but if you choose a table in the **Database Navigator** I get the whole table contents. It is mostly here that it would be benificial if _DBeaver_ did skip loading the BLOB contents.

**Comment by serge-rider** [comment]
I can't reproduce that in SQL Server. Generally BLOBs shouldn't be cached.
Could you post a DDL of your table?

**Comment by tati-kru** [comment]
Hi @pdanie! Do you have additional info about this problem?
