### ISSUE TITLE
Add option to edit the owner

### ISSUE THREAD

**Issue by PedroSolintel** [dbeaver/dbeaver#2516]
Is it possible to add an option to edit the owner of tables/functions/views/etc? Just like the one used to rename the table, but for the owner instead?

**Comment by serge-rider** [comment]
This depends on database. But usually this is not supported because it is actually a move operation (move table from one schema to another).
In most cases you will need to create new table, recreate all constraints and properties, then move data from original table to a new one and then drop original table.
That's complicated, not safe and quite fragile operation for simple property value change.
So..

**Comment by StevenLQ** [comment]
Whether this has been added to dbeaver and which databases support this ?
I tried PostgreSQL and Oracle, but I can't edit the owner of tables

**Comment by black-snow** [comment]
Doesn't seem "completed" for postgres.
