### ISSUE TITLE
Wrong message when Mac not install jdk

### ISSUE THREAD

**Issue by JackKuo-tw** [dbeaver/dbeaver#2562]
When a user does not install JDK, DBeaver will notify me to install Java for OSX in support.apple.com.
But when I install it, an error occurs.
In fact, Mac user needs to install JDK 9 but not Java for OSX or Oracle JRE.
I'm using High Sierra 10.13.1.

**Comment by serge-rider** [comment]
DBeaver requires any Java 1.8+ (Oracle or OpenJDK). MacOS show confusing alert about some legacy Java version. I can't fix this because this is a system alert (and actually a bug in some 3rd party software).

We going to make MacOS installer with bundled Java in the next DBeaver version (see #2429). 
This will resolve most of problems with Java on MacOS.

**Comment by tati-kru** [comment]
It looks like this question was solved. So it will be closed. But if you have any additional questions, please write a comment and we will reopen it.
