### ISSUE TITLE
Full-Text search in PostgreSQL is always case-sensitive

### ISSUE THREAD

**Issue by PedroSolintel** [dbeaver/dbeaver#2616]
Even though the "Case-sensitive" option is unmarked, DBeaver is performing case-sensitive search. I've observed that the generated search queries in the search results are using `LIKE`, which is case-sensitive. Instead, DBeaver should be using `ILIKE` for case-insensitive queries.

**Comment by mdahlman** [comment]
I'd like to add a vote for this.

It's listed as an enhancement... but one could make an argument to say that it's a bug. I mean, there's a checkbox displayed when configuring the search labeled "Case-sensitive". It's reasonable to say that DBeaver ought not give the user this option and then ignore the user's choice.

Even hard-coding `ilike` rather than `like` would be a practical improvement. I suspect that the use cases that full-text search is handling are better met by a case insensitive search in most situations.

Workaround for future readers: It's possible to view the generated query in the Query Manager. Then a manual find/replace of like/ilike will get you the query you want.

**Comment by jim256** [comment]
Another vote here. Agree with mdhalman.

**Comment by kseniiaguzeeva** [comment]
verified
