### ISSUE TITLE
How do I change the default path for where scripts are stored?

### ISSUE THREAD

**Issue by snakyjake1** [dbeaver/dbeaver#2650]
I want to change the default path for where scripts are saved/opened/stored.

**Comment by serge-rider** [comment]
In "Projects" view open Project properties->DBeaver settings->SQL Scripts.
You can assign any folder mapped in DBeaver workspace. 

To assign external folder you need to link it first. Right click on any workspace folder (e.g. SQL Scripts)->Link folder.

**Comment by tati-kru** [comment]
It looks like this question was solved. So it will be closed. Bit if you have any additional questions, please write a comment and we will reopen it.

**Comment by zero-jack** [comment]
@serge-rider I have the same problem but I could not find "Projects" selection due to the language. Could you give some photos describing the steps?

**Comment by serge-rider** [comment]
@zero-jack check #3012 , it is very similar

**Comment by givihuda** [comment]
I'm not sure what's meant by:

> In "Projects" view open Project properties

Though I clicked into issue #3102, but doing what's suggested there doesn't give me the absolute file path on my Mac of where the scripts are saved by default, and it doesn't appear to let me change the path to anything but the parent folder "General".

![image](https://user-images.githubusercontent.com/74785256/125299501-70566e00-e2e6-11eb-8879-8178d1934e60.png)

Can someone explain what I'm missing here?

It would be best to just have breadcrumb click instructions to find the setting, because this doesn't appear to be it.

Note that I found the absolute path by clicking the blue gear icon in any panel then clicking Resource, where I found the Scripts folder with the Scripts-# files (which are nice to be able to move or delete), but that doesn't appear to let me change the default saving folder for the Scripts-# files.

**Comment by Matvey16** [comment]
@givihuda 
You need to first link your external folder to Scripts in workspace, and then this folder will be available inside Scripts folder in properties like on your screenshot

![dbeaver_c65ClIL6Sz](https://user-images.githubusercontent.com/82543000/125405772-c1d32b80-e3c0-11eb-95d8-ffbe17caa2d7.png)

**Comment by givihuda** [comment]
OK so that's how to change the default folder for new Scripts-# files? My question was just based on something I stumbled on through all of the suggested answers here, but I'm not sure if that's actually the proper or best way.

Did I miss which webpage or permalink just shows the current steps, 1 2 3, or is that not exactly documented for the current version of DBeaver? 

Right now it appears the answer is across multiple posts in this thread cobbled together with links in those posts, which is not straightforward.

**Comment by Matvey16** [comment]
@givihuda This feature is not documented for now. But this is the proper and the only way to set an external folder as default for SQL scripts.

**Comment by DidierLLanten** [comment]
> De acuerdo, ¿así es como se cambia la carpeta predeterminada para nuevos archivos Scripts- #? Mi pregunta se basó en algo con lo que tropecé a través de todas las respuestas sugeridas aquí, pero no estoy seguro de si esa es realmente la mejor o la mejor manera.
> 
> ¿Me perdí qué página web o enlace permanente solo muestra los pasos actuales, 1 2 3, o eso no está exactamente documentado para la versión actual de DBeaver?
> 
> En este momento, parece que la respuesta está en múltiples publicaciones en este hilo improvisado junto con enlaces en esas publicaciones, lo cual no es sencillo.

--------------------------------------------------------------------------------------------------------------------------------------------
A little guide how do it.
Una pequeña guia de como se hace.

1- [Cambiar Ruta Scripts.docx](https://github.com/dbeaver/dbeaver/files/6986941/Cambiar.Ruta.Scripts.docx)
2- https://dbeaver.com/docs/wiki/Script-Management/

**Comment by ClodoaldoPinto** [comment]
> @givihuda You need to first link your external folder to Scripts in workspace, and then this folder will be available inside Scripts folder in properties like on your screenshot
> 
> ![dbeaver_c65ClIL6Sz](https://user-images.githubusercontent.com/82543000/125405772-c1d32b80-e3c0-11eb-95d8-ffbe17caa2d7.png)

The scripts folder is already linked to a network folder. Now I want to link it to a local folder. The selected path (in blue) below is what I want to change:

![image](https://user-images.githubusercontent.com/1433209/222444051-1daec4b9-3271-4e00-a819-a00e3cd34c84.png)
 
If I try to link to the local "Scripts" folder it errors because the folder already exists
