### ISSUE TITLE
Open Editors

### ISSUE THREAD

**Issue by RobertHana** [dbeaver/dbeaver#26621]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have lots of editors open and I can't find them easily.

**Describe the solution you'd like**
I would like to have open editors list.

**Describe alternatives you've considered**
I installed the Eclipse Marketplace Client, found, and installed the Open Editors plugin.

**Additional context**
I would like that Eclipse Marketplace Client be installed by default, perhaps the Open Editors plugin installed by default, not sure yet about other items.

**Comment by E1izabeth** [comment]
You can see all open editors by clicking on `>>` button in the editors tabs toolbar. You can view all open editors and search them.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/2f57e42a-1146-4432-92cf-59cf381082d8)

Does it satisfy your needs?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by bitadmiral** [comment]
The `>>` control by itself is inadequate by itself because it doesn't show up until your tabs are so numerous that they can't be displayed at all. It would be beneficial to have an ability to call up the full list of open SQL Editors regardless of how many are open ( like in VS Code which has an exemplary management of open editors).  

Even when all your tabs are visible, if your connection names or your file names are more than a dozen characters _combined_, then you still can't tell what's in _any_ tab because they all look the same.  Here's an example:

<img width="954" height="56" alt="Image" src="https://github.com/user-attachments/assets/65421e32-5e83-4875-b8e9-5e3dd93526d2" />

How can you tell what's in these tabs without opening them each individually?
