### ISSUE TITLE
Put config files in $XDG_CONFIG_HOME/dbeaver instead of ~/.dbeaver as per basedir-spec

### ISSUE THREAD

**Issue by Zulgrib** [dbeaver/dbeaver#2755]
dbeaver shouldn't use user's root directory to store configuration files, as per [freedesktop spec](https://www.freedesktop.org/wiki/Specifications/config-spec/) and [basedir-spec
](https://specifications.freedesktop.org/basedir-spec/basedir-spec-0.6.html)

Here's a preview :

> $XDG_CONFIG_HOME defines the base directory relative to which user specific configuration files should be stored. If $XDG_CONFIG_HOME is either not set or empty, a default equal to $HOME/.config should be used.

On Windows, if `$XDG_CONFIG_HOME` is not set, `%appdata%\dbeaver` , `%localappdata%\dbeaver` or `%userprofile%\.config\dbeaver` should be used.

**Comment by serge-rider** [comment]
What is wrong with user's home directory? 
It is a quite standard place to keep configuration for big number of software.

**Comment by serge-rider** [comment]
@Zulgrib any update?

**Comment by fer22f** [comment]
> What is wrong with user's home directory?
> It is a quite standard place to keep configuration for big number of software.

There is much more software using XDG paths, so most people look for configuration in that directory first. One more clutter directory in $HOME for each application is just a bit maddening.

**Comment by shanff** [comment]
+1 for XDG spec.  In addition, dbeaver is dropping 2 directories.  I for application and one for drivers.  These should be under $XDG_CONFIG_HOME

**Comment by serge-rider** [comment]
Agreed.

**Comment by maln0ir** [comment]
> In addition, dbeaver is dropping 2 directories. I for application and one for drivers. These should be under $XDG_CONFIG_HOME

Not really.

`$XDG_CONFIG_HOME` is not a place for binaries (like drivers) or logs. This directory is supposed to be _user-level_ `/etc` directory, so in ideal world only configuration files should be stored here.  
Drivers downloaded by DBeaver should go to `$XDG_DATA_DIR` - _user-level_ `/usr/share`.  
Logs, temporary files etc. should go to `$XDG_CACHE_DIR` - _user-level_ `/var`.  
There is also `$XDG_RUNTIME_DIR`, as name suggests, used only during runtime - _user-level_ `/run`, `/var/run`, `/var/lock` etc. - good place for `.lock` file (or other kinds of data that could be shared between running instances of an application).

**Comment by mkgrgis** [comment]
https://habr.com/ru/post/440620/

**Comment by mkgrgis** [comment]
Something like
.dbeaver_drivers -> $XDG_DATA_HOME/dbeaver_drivers
.dbeaver -> $XDG_CONFIG_HOME/dbeaver 
Other variables will be useful.

**Comment by serge-rider** [comment]
I'm afraid we can't fix this :(
1. We can't split workspace contents (.dbeaver folder) onto configuration, scripts, data files etc. Because of solid nature of Eclipse workspaces. So we should keep it in $XDG_DATA_DIR along with configs and other stuff.
2. Perhaps we shouldn't use $XDG variables at all because DBeaver can be run in headless mode as a console application (at least we are hardly working in this direction) and can be run on server-side. Keeping stuff in desktop-specific folder would be strange.
3. It will require a lot of effort to support backward compatibility with older versions.
4. Linux, Mac and Windows version will work differently (in terms of workspace location). And this is also frustrating.

No closing it yet.

**Comment by esarbe** [comment]
+1 for $XDG

2. $XDG is not for GUI applications only but for console applications as well. So that should not be a problem.

3. How about a one-time migration once a newer version is started?
4. Don't the Windows, Mac and Linux versions already work differently?

**Comment by serge-rider** [comment]
Version 6.1.3 will use new workspace format and new location workspace location.

- Linux: `${XDG_DATA_HOME}/.DBeaverData`
- Max: `~/Library/DBeaverData`
- Windows: `%AppData%/DBeaverData`

If XDG_DATA_HOME is not set then `~/.local/share` folder will be used on Linux.

On first start DBeaver 6.1.3+ will ask about workspace migration and will automatically copy/convert all configurations.

**Comment by untainsYD** [comment]
> Version 6.1.3 will use new workspace format and new location workspace location.

@serge-rider it doesn't work, DBeaver ignores xdg specification, it creates a lot of folder like `.eclipse .swt .local .pki` ignoring `XDG_DATA_HOME` env var that I have set.

**Comment by serge-rider** [comment]
@untainsYD Yes, unfortunately this happens whenever DBeaver is installed in a write-protected folder (which is the default of deb/rpm packages). Because it need to extract several native binaries to launch.

However original ticket was about own DBeaver configs and workspaces.

Could you create a new ticket about Eclipse-related artifacts? 
Please write more details about folders and their contents (e.g. I don't see folder .local and .pki in my test env)

**Comment by untainsYD** [comment]
> Could you create a new ticket about Eclipse-related artifacts? Please write more details about folders and their contents (e.g. I don't see folder .local and .pki in my test env)
I have created new ISSUE [here](https://github.com/dbeaver/dbeaver/issues/21610)
