### ISSUE TITLE
Cubrid charset problem

### ISSUE THREAD

**Issue by devSonicgirl** [dbeaver/dbeaver#2767]
hi,
I am using it well with cubrid support last time.
There is one problem, Korean is broken.
Server charset is utf-8 and DBeaver's string encoding is utf-8.
I changed string encoding, but nothing changed.

**Comment by dorbae** [comment]
Hi, devSonicgirl.
I think it is because of not dbeaver, but Cubrid JDBC driver.
Do you use DBeaver in windows?
If you use windows, **file.encoding** in System properties is may be MS949 and cubrid convert character as it.
How about this?

1. Add **-Dfile.encoding=utf8** line in **dbeaver.ini** file
or
2. Edit your Cubrid Connection and add property (**charSet=utf8**).

I wish to solve the problem.

**Comment by devSonicgirl** [comment]
@dorbae  
I solved it with your help.
Thank you very much. 👍
