### ISSUE TITLE
Can't connect do DB2 z/OS

### ISSUE THREAD

**Issue by lcocbr** [dbeaver/dbeaver#2810]
Hi,
I'm trying to connect to IBM DB2 z/OS from DBeaver. However, an error dialog message comes to the screen: Bad driver [DB2 z/OS] configuration. Reason: Can't create driver instance. Can't load driver class 'com.ibm.db2.jcc.DB2Driver'. com.ibm.db2.jcc.DB2Driver.

DBeaver version 4.3.2 (Win10/64bits)

Any hint?

Thanks in advance.

**Comment by serge-rider** [comment]
In order to connect to DB2 z/OS you need to download DB2 driver from IBM web site (http://www-01.ibm.com/support/docview.wss?uid=swg21363866)

Then you need to attach driver jars to DBeaver driver library list (click on Edit Driver Setting on connection properties dialog). OR you could use trial EE version (driver jars are already bundled in product).
Then you need to attach z/OS license jar to driver library list (you can get it from your DBA).

**Comment by lcocbr** [comment]
Thank you so much for that! It worked perfectly!
