### ISSUE TITLE
DBeaver toolbar in non DBeaver perspective

### ISSUE THREAD

**Issue by p91paul** [dbeaver/dbeaver#2840]
In the release notes of version 4.3.3 you say:
Main toolbar was fixed (now it is visible only in DBeaver perspective) 

What is the rationale for this decision? When I use DBeaver as an Eclipse plugin, and i liked to be able to open a quick SQL editor from the Java perspective just by pressing the "New SQL Editor" button from the DBeaver toolbar. Now I need to change perspective: is there a way to let me get back to my old workflow? perhaps disabiling the toolbar by default but making it possible to enable it from the "Customize perspective" window?

Thanks!

**Comment by serge-rider** [comment]
This was removed from other perspectives because some of them become messy (too many different actions not related to perspective itself).
Well, we can make this configurable. Add some option which will enable/disable toolbar visibility in other perspectives. WDYT?

**Comment by p91paul** [comment]
That would be perfect. I don't care about the default settings as long as I can tweak them!

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/35349876-3c6e6cec-014d-11e8-9fa7-1c3486b02fb3.png)

**Comment by p91paul** [comment]
Thanks!

**Comment by pengster-com** [comment]
I have DBeaver 6.1 (Eclipse plugin) 
but my Navigator dialog does not have the "show database toolbar always" checkbox

How can I turn off all DBeaver toolbars in all other perspectives?
I know how to use the "Customize Perspective" dialog
but I cannot uncheck any DBeaver related toolbars


![Screenshot ](https://user-images.githubusercontent.com/7651454/62577858-a9f9e100-b854-11e9-8eb4-8faa0983aeff.png)

**Comment by serge-rider** [comment]
Toolbar visibility settings have been moved to Database->Editors preference page.

What exactly DBeaver toolbars do you mean? (the ones visible in other perspectives)

**Comment by pengster-com** [comment]
Thanks serge, I've found the visibility setting where you said but it's already un-checked.
I've removed/turned-off literally all toolbars in my Java Perspective. What's left are the toolbars I'm trying to remove. 
![Screenshot1](https://user-images.githubusercontent.com/7651454/62641686-04e51400-b8f9-11e9-9668-0bf2fc2163a1.png)

**Comment by serge-rider** [comment]
Well, these toolbars are linked to the active editor (SQL editor or database object editor). If you will open some Java file they must disappear.

Also I see a glitch with multiple connection selector toolbars. It may happen after numerous version upgrades. Reset workspace UI to fix it (https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings - it works for Eclipse workspaces as well although workspace path differs)

**Comment by pengster-com** [comment]
The screenshot I uploaded shows my Java perspective and I think I had a python file active behind the Preference dialog. But no, those toolbars never goes away no matter what file nor perspective I switch to.

btw. I am using DBeaver 6.1 plugin in STS v4.22

Removing the workbench.xmi didn't work either, at first. But I did several things and not sure which one finally fixed it, sort of. In no particular order,...
1. I don't have a DBeaverData folder, so I searched my filesystem and found several workbench.xmi
2. deleted/renamed each one and restarting Eclipse/STS each time
3. Reset DevStyle to default, because I was playing around with it few days back
4. uninstall/reinstall DBeaver plugin via Marketplace
5. uninstall/reinstall DBeaver plugin via direct update site
6. closed all SQL Editors

So now, those toolbars still do not go away, not easily.
Opening an SQL Editor makes them active (as you've clued me in)
Switching away from DBeaver plugin do not remove those toolbars
Switching to a Java file makes them inactive (greyed-out), but they remain

The trick to making them go away,...
1. Switch away from SQL Editor (to any non-sql file)
2. Switch away from DBeaver perspective
If that still does not work,
3. Make sure your SQL Editor is not active
4. Switch back to DBeaver perspective, and then away from DBeaver perspective again
Not sure why but this trick seems to work for me.
Based on your explanation and my experimentation. I think the SQL Editor makes them appear but only switching to/from DBeaver perspective can remove them.

bug?, go figure

**Comment by serge-rider** [comment]
Indeed, at least connection/schema selector toolbar is glitchy. Definitely a bug but I can't relaize where exactly. Eclipse most likely but probablly it is possible to find a workaround.
Pleae create new ticket for this issue.

**Comment by pengster-com** [comment]
Connection/schema selector toolbar in non DBeaver perspective #6488
created
