### ISSUE TITLE
password storage format? 

### ISSUE THREAD

**Issue by benyanke** [dbeaver/dbeaver#2901]
What's the password storage format? I'd like to use DBeaver as my main connection manager for databases, but I need to be able to read the DB passwords back as needed, to avoid the need for storing everything else again in another location.

**Comment by serge-rider** [comment]
DBeaver uses proprietary algorithm for password encryption. You can find it in sources. In fact it is not secure (as it can be easily hacked). Write me on serge@jkiss.org if you need more details.

In order to use more secure password storage you can use secure storage with master password (optional, available in EE version). There is no algorithm to get passwords from this storage.

**Comment by benyanke** [comment]
Excellent, thank you. I assumed it was some sort of symmetric function, given that it needs to be retrieved back.

**Comment by the-morpheus1** [comment]
Can you tell me where to find the sources from?
