### ISSUE TITLE
Unable to read databricks table, error reads: Unable to read this table because it requires reader table feature(s) that is unsupported by this version of Databricks: deletionVectors

### ISSUE THREAD

**Issue by alexis-serafin** [dbeaver/dbeaver#29314]
### Description

I am unable to read a databricks table, the error I get says: Unable to read this table because it requires reader table feature(s) that is unsupported by this version of Databricks: deletionVectors . I am able to read other tables from Azure Databricks

### DBeaver Version

Community Edition 23.1.1.202306251800

### Operating System

Windows 10 Enterprise version 10.0.19045

### Database and driver

Database name and version: Not available
Driver name and version: Azure Databricks version 42-2.6.36.1062

### Steps to reproduce

I connect to the database using a JDBC url and am able to browse available schemas and tables. I have read access to other tables that I need but one table gives me an error of Unable to read this table because it requires reader table feature(s) that is unsupported by this version of Databricks: deletionVectors. I've updated the databricks driver to the latest version.

**Comment by Destrolaric** [comment]
@alexis-serafin Hi, to be sure, can you provide the Databricks database version? This issue may be related to some features implemented recently.

**Comment by Destrolaric** [comment]
```
When you enable deletion vectors, the table protocol is upgraded. After upgrading, the table will not be readable by Delta Lake clients that do not support deletion vectors. See [How does Databricks manage Delta Lake feature compatibility?](https://docs.databricks.com/en/delta/feature-compatibility.html).
```

**Comment by psupriya1991** [comment]
Hello, I am facing the same issue while trying to read the tables created through SQL Warehouse through JDBC driver. 

Error : "Unable to read this table because it requires reader table feature(s) that are unsupported by this version of Databricks: v2Checkpoint."


I see in the documentation that these deletion vector, v2 checkpoint etc features are enabled by default for SQL Warehouse version  2024.25 while table creation. But reading these Delta tables using JDBC driver gives the aforementioned error. I am using `databricks-jdbc` driver with version `2.6.34`. As dropping the properties is not an option, what will be the way to read these tables using JDBC driver? Do we need to pass anything in the connection string of JDBC? 

Thanks!

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
