### ISSUE TITLE
certificate issues with downloading drivers behind corporate firewall

### ISSUE THREAD

**Issue by gcorboz** [dbeaver/dbeaver#2932]
Before the change from http://dbeaver.jkis.org/files/jdbc/ to https:// I was able to download drivers within the Driver Manager without any issues.

Now that driver files are downloaded via https:// I'm getting the following error.

I'm sitting behind a corporate proxy which I think must have a lot to do with the error.

sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
  PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    unable to find valid certification path to requested target
    unable to find valid certification path to requested target

**Comment by fancywriter** [comment]
The issue is that dbeaver uses it's own JRE to run, not the one which is already installed by system.
Using system JRE/JDK might resolve such issue.
@serge-rider, what is the exact reason including another JRE to run dbeaver instead of using system one?

**Comment by johnradke** [comment]
Am also encountering this issue inside corporate proxy -- I think the issue is that our proxy decrypts & scans SSL traffic, then re-encrypts it with a new cert signed by our internal root authority. I've tried adding the root cert to the Trusted Certificates using javacpl, but still getting the exact same exception as above.

As far as I can tell, it's using the system JRE -- I chose not to install the JRE when installing DBeaver, and I don't believe I have any JDK installed.

Am running DBeaver 5.2.2 on Windows 10 x64.

**Comment by johnradke** [comment]
I did actually get this working yesterday using keytool to import my company's root signing cert.

Javacpl.exe is a utility I found in the Windows Start menu as "Configure Java", and is located in the bin/ directory of the JRE that DBeaver is using, but it's unclear where certs imported using that utility actually end up :/.

All is working now.
