### ISSUE TITLE
Oracle -> problem with filter

### ISSUE THREAD

**Issue by jad986** [dbeaver/dbeaver#2989]
Hi,

thanks for your work !

When I run sql query like this below and try use filter on column RESULT1 and choose e.g ONE value I get an error that you can see on below image. I work on Oracle Database. 

SQL:

`SELECT
	CASE
		WHEN NUMBER_1 = 1 THEN 'ONE'
		WHEN NUMBER_1 = 2 THEN 'ELSE'
	END RESULT1
FROM
	(
		SELECT
			1 NUMBER_1,
			1 NUMBER_2
		FROM
			dual
	UNION ALL SELECT
			1 NUMBER_1,
			2 NUMBER_2
		FROM
			dual
	UNION ALL SELECT
			2 NUMBER_1,
			1 NUMBER_2
		FROM
			dual
	UNION ALL SELECT
			2 NUMBER_1,
			2 NUMBER_2
		FROM
			dual
	)`

![obraz](https://user-images.githubusercontent.com/17430370/36320708-5c303798-1347-11e8-8ab7-05c53ad14da2.png)

**Comment by serge-rider** [comment]
DBeaver generates incorrect WHERE clause in the final filter SQL.

**Comment by serge-rider** [comment]
In fact this is more complicated than I thought.
Using sub-select for filters isn't always good. For example subselect may change results ordering (Oracle?). Also sub-selects may fail in some dialects in some cases.

For now I've made this configurable. New option "Always use subselect for filters" (perhaps we need better name for it) will force subselects. Otherwise DBeaver will try to patch original query WHERE clause (default behavior).

![image](https://user-images.githubusercontent.com/6398845/37560837-bab6677c-2a50-11e8-85ba-91eeb0325fa5.png)
