### ISSUE TITLE
Enable Auto-save editor on close  by default

### ISSUE THREAD

**Issue by nyurik** [dbeaver/dbeaver#29925]
**Is your feature request related to a problem? Please describe.**
Recently there has been a lot of crashes on Linux Mint, e.g. #25134, which causes loss of scripts.  Please automatically save all script files before running any query or after some time after last save to prevent data loss.

**Describe the solution you'd like**
Save all script files.

**Describe alternatives you've considered**
I manually save my files as often as possible... brings back memories of old DOS days...

**Additional context**
See #25134

**Comment by LonwoLonwo** [comment]
Hello @nyurik 

One of these settings may be helpful for you.

![2024-05-07 08_36_42-Grammarly Anchor Window](https://github.com/dbeaver/dbeaver/assets/45152336/2d4f6d8b-a21a-490c-873d-fa601b40cb9f)

**Comment by nyurik** [comment]
@LonwoLonwo thanks!!! i wasn't aware of this.  Do you think it might make sense to enable them by default? Other common editors (like IntelliJ's) do that out of the box...

**Comment by LonwoLonwo** [comment]
Related ticket with implementation: https://github.com/dbeaver/dbeaver/issues/9608

**Comment by nnd-support** [comment]
The knee jerk reaction to the QUESTION "Do you think it might make sense to enable them by default?" to just enable it without warning to people using the product is ridiculous.  The proper reaction should have been to THINK about the question posed and realize that, while there are some use cases where having the option enabled is a good idea, there are others where enabling it by default would be (and has been) disastrous.  Please put more thought into future product changes...

**Comment by BenjaminWKI** [comment]
This change is a horrible **HORRIBLE** decision just for the convenience of the entitled few who cbf to turn the setting on themselves!

**Comment by SenCodeMaker** [comment]
hello everyone,

 as far as I'm concerned what I see fit is dbeaver editor to have the same behaviour as notepadd++ which **is just wonderfull**. I really wonder how they do that: the file is not precisely saved by default but it's in some kinda cache in a way that when the program is closed the content is not lost. But yet it's not yet stock in a permanent file. 

That's behaviour is really pleasant for the end user. You don't have to bother thinking about shoud I save this or not and you don't lose anything. Every time you finally decide to save something it's there waiting for you. Whn uou decide to delete it, it's not already saved.

Today I lost a big sql file containing several queries worth 2 days of work because windows decided that when the battery is getting low it's better to just switch off my computer instead of putting in deep sleep...

Now my file is gone and I tried for couple hours to find something in logs or temp files but it seems I'm set to restart fresh.

I think **notepad++ behaviour** could help a lot without bringing problems for those who don't what to sav by default

**Comment by Frogman-v11** [comment]
This feature is great for users dealing with crashes or who prefer automatic protection.
But **turning it on by default** feels like a practical joke on those of us who rely on deliberate, manual saving to protect versioned SQL scripts.
A default that silently overwrites published or tracked files is genuinely risky — it helps one group of users by unintentionally sabotaging another. A prompt or opt‑in would avoid that tradeoff entirely.

**Comment by const-cast** [comment]
I don't understand why this request is approved. For those who want to auto-save, you can enable it. If you don't, dbeaver will warn you about unsaved changes when closing and you can always save it, then turn on auto-save the next time. For those like me who constantly experiment on scripts and don't want auto-save enabled by default, why is this decision forced upon me?
