### ISSUE TITLE
[Question] What cross sign means on materialized view icon?

### ISSUE THREAD

**Issue by ceyhunnabiyev** [dbeaver/dbeaver#3044]
I don't have any errors when I created materialized view. But I see cross sign on  materialized view icon. What it means? Error or refresh on demand option or another one?

![screenshot from 2018-02-26 16-51-58](https://user-images.githubusercontent.com/5506156/36671724-2d24959e-1b16-11e8-8554-f21ecdb81b88.png)
```
create MATERIALIZED view full_reporting
cache
NOLOGGING
as
SELECT ....
```

**Comment by serge-rider** [comment]
This means that view has errors or needs to be compiled. I.e. it is in invalid state (column COMPILE_STATE in SYS.ALL_MVIEWS table).

**Comment by ceyhunnabiyev** [comment]
I compile it, it says successfuly compiled, I don't see any error in it. Maybe related to refresh on demand option(message like needs refresh)?

**Comment by serge-rider** [comment]
Maybe some depndent object is in invalid state.

https://docs.oracle.com/cd/B28359_01/server.111/b28320/statviews_1140.htm#REFRN20139

COMPILE_STATE

Validity of the materialized view with respect to the objects upon which it depends:
- VALID - Materialized view has been validated without error, and no object upon which it depends has changed since the last validation
- NEEDS_COMPILE - Some object upon which the materialized view depends has changed. An ALTER MATERIALIZED VIEW...COMPILE statement is required to validate this materialized view.
- ERROR - Materialized view has been validated with one or more errors
