### ISSUE TITLE
Can't install update 24.0.4 on Mac OS Catalina 10.15.7

### ISSUE THREAD

**Issue by one-none** [dbeaver/dbeaver#30700]
### Description

Starting DBeaver warns that update 24.0.4 is available.
After downloading it and mounting the DMG arrchive, the installation programs warns that this version requires macOS 11. Have systems requirements changed recently? If so, can you please report the correct System Requirements web page?

### DBeaver Version

Community 24.0.3.202404211624

### Operating System

macOS Catalina 10.15.7

**Comment by dayfuaim** [comment]
Second this.
I have the same problem.

UPDATE:
Same with 24.0.5.
I see this while opening `.dmg`.
![Снимок экрана 2024-05-20 в 15 55 11](https://github.com/dbeaver/dbeaver/assets/1274699/126eceaa-e34b-4ca5-bbab-9a0b863a9656)

**Comment by E1izabeth** [comment]
Thank you for your report. We have reproduced the issue and are investigating.

**Comment by E1izabeth** [comment]
Similar issue with old versions of Windows #34034

**Comment by one-none** [comment]
Same issue on version 24.1.0

**Comment by kleyber-ribeiro** [comment]
Any news about this on MacOS Catalina? I am with the same situation...

**Comment by arhayka** [comment]
Unfortunately, after upgrading to Eclipse 2024-06, the following OS are no longer supported: Windows 8, macOS 10, and Windows Server 2012. This issue is not on DBeaver side, you can see the details here: https://github.com/eclipse-platform/eclipse.platform.swt/issues/1252.

We have already added the system requirements to the download pages and [are working on ways to warn users before the update](https://github.com/dbeaver/dbeaver/issues/34315).

However, we will keep an eye on the situation and try to do something if possible.
I’m closing the current ticket as a duplicate: https://github.com/dbeaver/dbeaver/issues/34034

**Comment by sryze** [comment]
It's not cool to do breaking changes like this in a patch release.
