### ISSUE TITLE
cannot persist any changes- syntax errorrs

### ISSUE THREAD

**Issue by gkoumantaris** [dbeaver/dbeaver#3136]
Hello,

I have purchased EE 5.0 edition to test the product in order to purchase more licenses for my team.
I have issues persisting changes in mariadb.

For example:

When i add some grants for a user (from UI):

GRANT File ON rundeckdb.* TO 'rundeck'@'%' ;
GRANT Lock tables ON rundeckdb.* TO 'rundeck'@'%' ;
FLUSH PRIVILEGES ;

I get this error:

SQL Error [1221] [HY000]: (conn:588820) Incorrect usage of DB GRANT and GLOBAL PRIVILEGES
Query is : GRANT File ON rundeckdb.* TO 'rundeck'@'%'
  (conn:588820) Incorrect usage of DB GRANT and GLOBAL PRIVILEGES
Query is : GRANT File ON rundeckdb.* TO 'rundeck'@'%'
    Incorrect usage of DB GRANT and GLOBAL PRIVILEGES
Query is : GRANT File ON rundeckdb.* TO 'rundeck'@'%'
    Incorrect usage of DB GRANT and GLOBAL PRIVILEGES
Query is : GRANT File ON rundeckdb.* TO 'rundeck'@'%'

**Comment by serge-rider** [comment]
`File` and `Lock tables` privileges are database-level privileges, you can't grant them on some particular table.
Select % instead of tables and you will be able to grant this privilege.

Note: different MySQL/MariaDB servers (different versions) have different set of privileges and privilege contexts.

**Comment by serge-rider** [comment]
However we should remove File and Lock privileges from table-level preference list.

**Comment by serge-rider** [comment]
Should work in 5.0.3
