### ISSUE TITLE
Can't find load row count button

### ISSUE THREAD

**Issue by zelding** [dbeaver/dbeaver#3233]
Since the 5.0 update I can't find the load row count button.

It used to be in the low-right corner in the results window.

Is it removed (for some reason) or just moved ?

**Comment by offstate** [comment]
Sometimes it hide and appear again after window resized
![screenshot_20180403_10 05 12](https://user-images.githubusercontent.com/16996529/38222164-98870ade-3726-11e8-9096-1a2113600ef9.png)
![screenshot_20180403_10 05 36](https://user-images.githubusercontent.com/16996529/38222166-9c8c0daa-3726-11e8-8cc5-731f8a063bcd.png)

**Comment by zelding** [comment]
Thank You!

**Comment by offstate** [comment]
Nevertheless I treat it as a bug. You should have left the issue open

**Comment by serge-rider** [comment]
Could you post steps to reproduce?

**Comment by offstate** [comment]
Screen resolution of my laptop is 1600x900
1) open DBeaver
![default](https://user-images.githubusercontent.com/16996529/38280962-8953f3a4-37eb-11e8-9ae6-5c0bf0abf6a9.png)
2) do any select query (row count is hidden due to the appearance of buttons grid/text)
![default](https://user-images.githubusercontent.com/16996529/38280971-a2e37092-37eb-11e8-84d7-0f334f0485bd.png)
3) change window size (second line of the toolbar appears and row count )
![default](https://user-images.githubusercontent.com/16996529/38281063-2a591126-37ec-11e8-9b1f-4938cc71b24d.png)

**Comment by zelding** [comment]
I think I was able to do it, because I opened the issue

**Comment by offstate** [comment]
I tried on my closed issues )

**Comment by serge-rider** [comment]
@offstate Thanks for details. This happened only in some screen particular resolutions.
