### ISSUE TITLE
Feature Request - influxdb connector

### ISSUE THREAD

**Issue by nmat** [dbeaver/dbeaver#3276]
Would like to request a influxdb odbc connector.

**Comment by serge-rider** [comment]
You could try to use ODBC bridge driver (already in DBeaver). 
Works only n Windows.

**Comment by nmat** [comment]
I have tested the odbc bridge but do not seem to be able to figure out how the connection should look. Do you have some example of using a url to connect to with a specific port that I can test?

Just a example that I can go by.

**Comment by serge-rider** [comment]
In order to use ODBC driver you need to configure it in Windows DataSource manager (odbcad32.exe). You will need to specify all actual connection parameters there.

Then you can use just datasource name in DBeaver:
![image](https://user-images.githubusercontent.com/6398845/38580381-754cf65e-3d12-11e8-9749-301c1bcaab78.png)

**Comment by nmat** [comment]
Closing this request since its the same as https://github.com/dbeaver/dbeaver/issues/1675

I was never able to get it to work unfortunately so therefore closing the question. Thank you.
