### ISSUE TITLE
Accessing SQL Server via Windows Authentication from Linux

### ISSUE THREAD

**Issue by auspex** [dbeaver/dbeaver#3320]
I'm running dbeaver on Ubuntu 17.04 

It appears I should be able to run `kinit` and then `dbeaver` and connect, but no such luck.

```
derek@043SC646:~$ kinit derbro
Password for derbro@MBA.AC.UK: 
derek@043SC646:~$ klist
Ticket cache: FILE:/tmp/krb5cc_1000
Default principal: derbro@MBA.AC.UK

Valid starting     Expires            Service principal
13/04/18 15:13:43  14/04/18 01:13:43  krbtgt/MBA.AC.UK@MBA.AC.UK
        renew until 20/04/18 15:13:35
derek@043SC646:~$ /usr/share/dbeaver/dbeaver      
2018-04-13 15:14:00.044 - Create display
2018-04-13 15:14:00.110 - DBeaver 5.0.2 is starting
2018-04-13 15:14:00.111 - Install path: '/usr/share/dbeaver'
2018-04-13 15:14:00.111 - Instance path: 'file:/home/derek/.dbeaver4/'
```
with the `jtds` driver, I get:
```
2018-04-13 15:14:29.233 - Connect with 'jdbc:jtds:sqlserver://cprdatabase.mba.ac.uk/master' (mssql_jdbc_jtds-162bf5b8666-1fbf43ea0d700a20)
2018-04-13 15:14:29.315 - Connection failed (mssql_jdbc_jtds-162bf5b8666-1fbf43ea0d700a20)
2018-04-13 15:14:29.316 - org.jkiss.dbeaver.model.exec.DBCConnectException: I/O Error: GSS Failed: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
org.jkiss.dbeaver.model.exec.DBCConnectException: I/O Error: GSS Failed: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:191)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.openConnection(GenericDataSource.java:126)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCExecutionContext.connect(JDBCExecutionContext.java:79)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.initializeMainContext(JDBCDataSource.java:115)
        at org.jkiss.dbeaver.ext.generic.model.GenericDataSource.<init>(GenericDataSource.java:108)
        at org.jkiss.dbeaver.ext.mssql.model.SQLServerDataSource.<init>(SQLServerDataSource.java:43)
        at org.jkiss.dbeaver.ext.mssql.model.SQLServerDataSource.<init>(SQLServerDataSource.java:35)
        at org.jkiss.dbeaver.ext.mssql.SQLServerDataSourceProvider.openDataSource(SQLServerDataSourceProvider.java:123)
        at org.jkiss.dbeaver.registry.DataSourceDescriptor.connect(DataSourceDescriptor.java:752)
        at org.jkiss.dbeaver.runtime.jobs.ConnectJob.run(ConnectJob.java:70)
        at org.jkiss.dbeaver.ui.dialogs.connection.ConnectionWizard$ConnectionTester.run(ConnectionWizard.java:216)
        at org.jkiss.dbeaver.model.runtime.AbstractJob.run(AbstractJob.java:95)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:56)
Caused by: java.sql.SQLException: I/O Error: GSS Failed: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
        at net.sourceforge.jtds.jdbc.TdsCore.login(TdsCore.java:654)
        at net.sourceforge.jtds.jdbc.JtdsConnection.<init>(JtdsConnection.java:371)
        at net.sourceforge.jtds.jdbc.Driver.connect(Driver.java:184)
        at org.jkiss.dbeaver.model.impl.jdbc.JDBCDataSource.openConnection(JDBCDataSource.java:177)
        ... 12 more
Caused by: java.io.IOException: GSS Failed: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
        at net.sourceforge.jtds.jdbc.TdsCore.sendMSLoginPkt(TdsCore.java:1976)
        at net.sourceforge.jtds.jdbc.TdsCore.login(TdsCore.java:617)
        ... 15 more
```
With the Microsoft driver it's more onimous because it's asking for a DLL, which isn't ever going to be found on a Linux system, but in any case I don't seem to have anything named sqljdbc_auth on my system:
```
2018-04-13 15:21:18.335 - Connect with 'jdbc:sqlserver://cprdatabase;databaseName=master' (mssql_jdbc_ms_new-162bf61c476-4e0f91af488ac42e)
Apr 13, 2018 3:21:18 PM com.microsoft.sqlserver.jdbc.AuthenticationJNI <clinit>
WARNING: Failed to load the sqljdbc_auth.dll cause : no sqljdbc_auth in java.library.path
```
https://blogs.msdn.microsoft.com/psssql/2015/01/09/jdbc-this-driver-is-not-configured-for-integrated-authentication/ implies that this means it's trying to connect with a connection string containing `authenticationScheme=NativeAuthentication` (either explicitly or implicitly--which would only work on Windows) and requires `authenticationScheme=JavaKerberos` (which should work on any OS). I expect I could set that in the driver advanced parameters, but I'm not sure where--and also rather expect that if I did, I'd just end up with the same problem as with the jTds driver.

**Comment by serge-rider** [comment]
Could you try solution proposed in https://stackoverflow.com/questions/35797992/kerberos-and-integrated-security-using-jtds-driver :
```
Use property useKerberos=true in the Connection String

Source: https://sourceforge.net/p/jtds/patches/101/

Pass VM Argument -Djavax.security.auth.useSubjectCredsOnly=false

So, finally after applying the above changes my Connection String looked like below:

jdbc:jtds:sqlserver://<serverName>:<port>;databaseName=<DBName>;useKerberos=true;
Arguments List:

-Djava.security.krb5.debug=true 
-Djava.security.auth.login.config="C:\login.conf" 
-Djava.security.krb5.conf="C:\krb5.conf
-Djavax.security.auth.useSubjectCredsOnly=false
```

Driver properties can be set in connection properties dialog->Driver properties.
Command line parameters can be added in dbeaver.ini (in the end, after -vmargs)

**Comment by auspex** [comment]
Thanks. That gets me past the `Failed to find any Kerberos tgt` error. Now I'm onto `Server not found in Kerberos database` which is definitely a problem at my AD domain controller, not the dbeaver configuration.

**Comment by auspex** [comment]
I'll try that but that's NOT "integrated authentication". With integrated authentication, you don't need to keep passing usernames and passwords around. I'd be really surprised if this works, though, because that looks like the method for using SQL Server logins, not Windows logins.

**Comment by kafran** [comment]
> I'll try that but that's NOT "integrated authentication". With integrated authentication, you don't need to keep passing usernames and passwords around. I'd be really surprised if this works, though, because that looks like the method for using SQL Server logins, not Windows logins.

No no, thats gonna use Windows Authentication. For SQL Server Login you can you the MS JDBC driver, which is open source now. But using the MS JDBC you need to use Kerberos which could be a little complicated. Developers are bringing NTLM to MS JDBC as well: https://github.com/Microsoft/mssql-jdbc/issues/696; when this is working then you wouldn't need jTDS anymore.

**Comment by erindru** [comment]
I had this exact problem and stumbled across this thread, so I thought i'd record my solution in case someone else also has this problem.

The 'sqljdbc_auth.dll' thing appears to be Windows-specific - those DLL's are distributed as part of the JDBC driver download *if you get it from the Microsoft download center*, whereas i'm pretty sure the version distributed with DBeaver is the fully open source version.

Anyway - they are not required. I added them to the classpath but it kept saying it it couldnt find them.

I was eventually able to connect by doing the following:

1. In "Driver Properties" for the connection, setting the Driver Properties "authenticationScheme=javaKerberos", "integratedSecurity=true"
2. In the "User Properties" (on the same page), creating properties for "USER=<kerberos principal name, as produced by running `kinit`>" and "PASSWORD=<AD password>".

I was then able to connect to the SQL Server using the 'Windows Authentication' method.

I realise that there appears to be some duplication with the system kerberos and JavaKerberos - I was not expecting to have to supply my credentials again in DBeaver as they're already supplied at the system level. I have a suspicion that DBeaver creates a whole new Kerberos context with the supplied information and ignores the system one. Anyway - it worked, and I don't care about the duplication because im just happy its working.

As a sidenote - I was running the Flatpak version of DBeaver on Fedora 29.

**Comment by auspex** [comment]
But once again, this isn't "integrated authentication". It allows you to
use your Windows id and password to login, but what's the point of Kerberos
if you have to provide (and potentially store insecurely) a password
_after_ Kerberos authentication.

**Comment by erindru** [comment]
"Windows Authentication" and "Integrated Security" are the same thing - see https://docs.microsoft.com/en-us/dotnet/framework/data/adonet/sql/authentication-in-sql-server

My understanding is that in a "normal" scenario (Windows, logged in as domain user, using SSMS as the SQL client) is that it uses your Kerberos ticket that you got from logging in to Windows to authenticate against the SQL server - rather than submitting your username/password directly to the SQL server.

In my current scenario, I have a Linux machine joined to the Windows domain using 'realmd', and I have a Kerberos ticket which I can view using `kinit`. I'm referring to this as a "system-level" Keberos ticket,

I am sure that I can trigger DBeaver to use the system-level keberos tickets by specifying the JavaKeberos options so it can find the `krb5.conf` file (as mentioned here: https://docs.oracle.com/javase/8/docs/technotes/guides/security/jgss/tutorials/KerberosReq.html ), however since i'm running it in Flatpak it's not as easy as editing a config file.

Therefore, I used the other method of JavaKeberos to get a ticket - that is, it establishes a new context separate from the system-level context (using the supplied credentials), gets a ticket and uses that to authenticate against the SQL Server.

**Comment by auspex** [comment]
Clearly, in practice, they're **not** the same thing. "Windows authentication" means you can log in with your Windows user ID and password. Otherwise you need to have a SQL Server ID and password. "Integrated Security" means that if you are _already_ logged in (ie, you have the Kerberos ticket), it will not ask for a password. "Integrated security" is not working at all.

I am _not_ sure I can trigger DBeaver to use the Kerberos ticket--at least without Domain administrator access. I've tried everything. I can access anything else that requires Windows authentication (all of my SAMBA shares, for instance), but not SQL Server.

**Comment by s-nt-s** [comment]
@auspex can you finally use DBeaver with "Windows authentication" from Linux? I have the same problem.

**Comment by auspex** [comment]
No, I've flat out given up trying to use Integrated Security to access SQL Server from any Linux application. Anything else, piece of cake. SQL Server always ends up with the `Server not found in Kerberos database`. If I have to specify my Windows credentials in the connection string, then sooner or later they're going to have to end up in a git repo.

**Comment by s-nt-s** [comment]
> No, I've flat out given up trying to use Integrated Security to access SQL Server from any Linux application. Anything else, piece of cake. SQL Server always ends up with the `Server not found in Kerberos database`. If I have to specify my Windows credentials in the connection string, then sooner or later they're going to have to end up in a git repo.

@auspex In my case specify my Windows credentials in the connection string shouldn't be a problem.  But specifying my Windows credentials in the connection string I don't get any difference, ends up with the `Server not found in Kerberos database`.
Could you connect specifying Windows credentials in the connection string? how?

**Comment by terrymunro** [comment]
It seems like people are resigned to it not being possible in Linux/Mac.

But how does the [go-sqlcmd](https://learn.microsoft.com/en-gb/sql/tools/sqlcmd/go-sqlcmd-utility?view=sql-server-ver16&tabs=linux) utility do it?

Using that CLI tool on Linux I can connect to an MS SQL Server without any Kerberos or anything else needed.

Either way this isn't a dbeaver problem its in the jdbc driver 😭

**Comment by auspex** [comment]
I'm sure it doesn't do Windows authentication. It will work with "SQL
Server authentication". That's trivial.

**Comment by auspex** [comment]
Well, I have to eat crow. `go-sqlcmd` does work, and it's completely opaque to me how it can, as it has no idea where my AD server is to do the authentication.

However, that doesn't do anything to solve the fact that I'm unable to use Integrated Authentication.  I am not trying to avoid Kerberos—I **am** logged in and have the Kerberos ticket. I'm trying to avoid having to give my username/password again.

It's so long now since I abandoned this that I'm unsure, but I think I have managed to use a JDBC driver with integrated authentication with other tools, which is why it seems like a DBeaver issue, not a JDBC one (it definitely is a problem with both the MS driver and the jTDS driver).
