### ISSUE TITLE
Exporting from DB2 to MS SQL maps Numeric to bit(2)

### ISSUE THREAD

**Issue by codezy89** [dbeaver/dbeaver#3344]
I am migrating data from a old as/400 iseries.  Most of the auto mappings for datatypes are what I would expect.  Except for the Numeric to bit(2),bit(3),etc..  MS SQL has a datatype of bit, but it does not have a length.  Is there a way to change this mapping in the application?  Unfortunately I have a lot of tables with many of these values and updating each mapping for each column in each table manually will take a long time.

![image](https://user-images.githubusercontent.com/38444038/38839149-2cf0b5fa-418e-11e8-9a39-2d6969e0bcad.png)

**Comment by LonwoLonwo** [comment]
In DBeaver 21.0.0 it's Decimal(Numeric) type from DB2 and decimal target type in MSSQL.
https://www.ibm.com/support/knowledgecenter/SSEPEK_12.0.0/intro/src/tpc/db2z_numericdatatypes.html (about numeric/decimal types)

![2021-03-18 10_49_05-Map columns of IMPORT_TEST](https://user-images.githubusercontent.com/45152336/111590965-d703c900-87d7-11eb-8065-73c06c76c0bf.png)

So, I think - this is perfect match and It looks like the problem was solved. This issue will be closed.
