### ISSUE TITLE
MYSQL date display bug

### ISSUE THREAD

**Issue by yanzibugui** [dbeaver/dbeaver#3357]

**Comment by serge-rider** [comment]
Could you post any details?

**Comment by serge-rider** [comment]
This is so-called "zero date", it is MySQL specific. Its presentation is controlled by driver property zeroDateTimeBehavior:
![image](https://user-images.githubusercontent.com/6398845/39073143-79be8bea-44f5-11e8-83b1-cb54421678a5.png)

It can't be printed as 0000-00-00 using JDBC driver, because it is not correct date value.

**Comment by yanzibugui** [comment]
OK,I see,Thank u very much!!!
