### ISSUE TITLE
FATAL: Ident authentication failed for user "postgres"

### ISSUE THREAD

**Issue by kamrava** [dbeaver/dbeaver#3361]
I'm using Fedora 27 + DBeaver 5.0.3

I'm trying to connect to PostgreSQL via DBeaver.
When I fill my postgres connection info and click on Test Connection..

It returns this error:

> FATAL: Ident authentication failed for user "postgres"

while I can connect successfully with psql and pgadmin4 and pgweb and etc... with the same connection info.
Any help would be great appreciated.

**Comment by serge-rider** [comment]
DBeaver uses JDBC driver which only supports TCP/IP. Maybe it is the case.
Check this: https://jdbc.postgresql.org/documentation/head/prepare.html

**Comment by tomascg2309** [comment]
Hey! I know probably is too late to help, but I've managed the solution to deal with that (because just happened to me while using WSL). I hope it could help someone in the future. Open the WSL terminal:
1. Be sure the postgresql is running: type sudo service postgresql start
2. Connect to postgresql: type sudo -u postgres psql
3. Create a user: create user {USERNAME} with encrypted password {'PASSWORD'};
Then, when you configure your DB connection on DBeaver, use the USERNAME and PASSWORD keys to connect.
Cheers!

**Comment by tomascg2309** [comment]
Hey! I know probably is too late to help, but I've managed the solution to deal with that (because just happened to me while using WSL). I hope it could help someone in the future. Open the WSL terminal:

1. Be sure the postgresql is running: type sudo service postgresql start
2. Connect to postgresql: type sudo -u postgres psql
3. Create a user: create user {USERNAME} with encrypted password {'PASSWORD'};

Then, when you configure your DB connection on DBeaver, use the USERNAME and PASSWORD keys to connect.
Cheers!

**Comment by git-thebit** [comment]
thanks for the help @tomascg2309
