### ISSUE TITLE
Transaction Log empty upon start - BUG

### ISSUE THREAD

**Issue by romad17** [dbeaver/dbeaver#3423]
Hello,

My Transaction Log is empty, every time I open the DBeaver.
How can I make DBeaver to remember queries even if I closed the application?

Thank you.

**Comment by p91paul** [comment]
Use Query Manager instead of transaction log. You can see the query manager using Window -> Show view -> Query Manager.

Make sure you check "Save log to file(s)" in preferences like below:

![schermata del 2018-05-03 21-35-50](https://user-images.githubusercontent.com/2157006/39598784-01eda95a-4f1a-11e8-900c-81de4b251afe.png)

**Comment by romad17** [comment]
Thanks Paolo
I see the log and the queries, thank you!

**Comment by serge-rider** [comment]
This feature will be significantly improved in #178.
Query search will be integrated in UI + persistent query history browser will be added in EE version.
