### ISSUE TITLE
DBeaver does not display new tables created in DuckDB databases connected via ATTACH

### ISSUE THREAD

**Issue by pbrady32** [dbeaver/dbeaver#34304]
### Description

When I use the ATTACH statement to connect another DuckDB database and run a create table statement, the DBeaver Database Navigator for the attached database does not show the new table even though the create table statement runs successfully.

I'm able to query the newly created table, but I can't view it in my DBeaver side panel window. 

Sometimes I can get one new table to show up, but any subsequent create table statements result in no new tables showing up in the attached database's Database Navigator window. It also doesn't show up even after rebooting DBeaver.

I have tried this with multiple versions of DuckDB.

Cross posted to DuckDB Git because I'm not sure if this is a DBeaver bug or DuckDB bug.

https://github.com/duckdb/duckdb/issues/12326

### DBeaver Version

24.1.0

### Operating System

macOS Sonoma 14.5

### Database and driver

DuckDB 1.0.0

### Steps to reproduce

Open up a new SQL script for a current DuckDB database. Let's refer to this initial DB as duck1. Run the following:

```
attach '/path/to/duck_database2.db' as duck2;

-- confirm two database are connected to our session
show databases;

create table duck2.new_table as 
select * from duck1.table limit 10;
```

Once the code runs, attempt to view the newly created `new_table` in the Database Navigator. The first attempt at this may work as expected, but subsequent `create table` statements have not been working for me.

**Comment by Matvey16** [comment]
@pbrady32 I'm not sure if this is a bug. This looks like an expected dbeaver behaviour. WHen you create a new table with a query in SQL Editor it won't be shown in the navigator until you manually refresh it by selecting `Refresh` in the context menu or pressing F5 on the tables folder or any higher level node.
It seems to work for you the first time because table list is still not loaded, so it is loaded for the first time after you run the create query, hence why it shows the table. Every subsequent create statement won't affect the current state of the navigator until it is refreshed


https://github.com/dbeaver/dbeaver/assets/82543000/a7cc33d4-8db4-48cc-a188-e1a3bab8b787

**Comment by pbrady32** [comment]
@Matvey16 thanks for mentioning that. I completely forgot to say that refreshing the database and table views does not help. It still doesn’t show the newly created tables. 

When I run show tables; in DuckDB it does indeed show that new tables are being created in the attached database as expected. They just refuse to show up in the Navigator.

**Comment by Matvey16** [comment]
@pbrady32 And would a select on this new table work in SQL editor?

**Comment by pbrady32** [comment]
@Matvey16 yes a select on the new table does work as expected.

**Comment by Matvey16** [comment]
@pbrady32 can you please record a video like in my comment where I can see that you create a new table and it doesn't show in the navigator after refresh? Maybe I would be able to see what we are doing differently.

Also one more question. Will the table still be invisible after disconnect and reconnect?

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.

**Comment by pbrady32** [comment]
@Matvey16 @E1izabeth I'll check this soon. I've been on leave for a few weeks, so I haven't worked with our data since early July.

**Comment by E1izabeth** [comment]
@pbrady32 
Sure, we're waiting :)

**Comment by cemhany** [comment]
I have the same issue. New tables **_sometimes_** don't appear when using DuckDB javascript driver or CLI tool as well.

```sql
SELECT * FROM AA;
```

works and lists the rows while

```sql
SELECT * FROM information_schema.tables
```

won't show the newly imported table. I am creating the tables using the CSV import feature with the following query:

```sql
CREATE TABLE ${tableName} AS SELECT * FROM read_csv('${filePath}')
```

So this might not be a dbeaver issue.

**Comment by ikario404** [comment]
Had sometimes the problem : refreshing db doesn't reloaded correctly new tables // disconnect-reconnect not refreshed neither. For me only shutdown Dbeaver worked when it happened. Hope it helps

**Comment by pbrady32** [comment]
@Matvey16 Here is the video you requested. Refreshing and disconnecting both do not fix the issue. 

I am on DBeaver Version 24.2.0.202409011551 (installed today) and latest DuckDB 1.0.0

https://github.com/user-attachments/assets/423ee58b-c5eb-45c7-9a6e-0aea155fe885

**Comment by Matvey16** [comment]
@pbrady32 Thank you for the video. Now I can see the difference in our cases. On your video I see that you actually check tables in not only different databases, but actually different connections.
My first idea is that the attached databse in your script is called `.../duck2.db` and possibly the path for the database in connection settings can be `.../duck2` which means those are two different files and therefore different databases. It looks likely because I see that you can simultaniously attach a database in one connection and also connect to it in another wich is impossible for me if it is the same file.

While you check this I would also like to ask you to look at this feature for DuckDB in DBeaver. YOu don't need to create a new connection if you are working with attached database. It will appear in the navigator in the same connection you are working in (After refresh)


https://github.com/user-attachments/assets/624fe81e-9fb3-48ea-b356-9a9bf7fac2ec

**Comment by pbrady32** [comment]
@Matvey16 Ahh got it! That makes sense. When I looked at the DuckDB documentation for the attach statement it wasn't clear to me that the other database should **not** be in another connection. This is super helpful. Thanks for the clarification!

**Comment by E1izabeth** [comment]
@pbrady32 so the issue can be closed, right?

**Comment by pbrady32** [comment]
@E1izabeth yes it can, thanks!
