### ISSUE TITLE
Table ddl preview

### ISSUE THREAD

**Issue by xiamuban** [dbeaver/dbeaver#34372]
I wish there was support for previewing the table ddl on mouse hover. 
thank you.

**Comment by E1izabeth** [comment]
Reading ddl is an expensive operation, which often requires executing a query to the database. It will lead to a noticeable  
delay.

**Comment by arhayka** [comment]
We could add a special shortcut for DDL generation. It could be done in this ticket: https://github.com/dbeaver/dbeaver/issues/34945

**Comment by ask9** [comment]
> Reading ddl is an expensive operation

Why don't you want to cache the DDL of the whole database automatically periodically in background how it is done in "SQL Complete" / "DbForge for PostgreSQL"?
In general, it is totally OK for a user that sometimes the cache becomes a bit outdated for some period of time.
Because the next refresh will refresh it.
In many work scenarios the DDL is changed very seldom (nothing to refresh = no expensive operation).
These users give the most benefits with minimal impact on CPU usage.

In these applications it takes not more than about 5-10 seconds and it is noticeable only when it is done on user's demand (when automatically it was not triggered for some reason).
But most of time it works seamlessly and unnoticeably for a user.

See what it gives for a user:

https://github.com/user-attachments/assets/8a1eca17-296e-4afb-9323-4d5ccefeea37

**Comment by E1izabeth** [comment]
Thanks for your comment.
We tried to find a roots of this request, because DDL is avaiulable in the context menu and can be easily opened. And also we already have a special window to view DDL with several options and buttons. So, we have concluded, that the reason for this request is the long way to the item in a context menu.

However, I see your point. Maybe we need to re-review our decision, because adding shortcut and adding tooltip is quite different approaches.
