### ISSUE TITLE
Unwanted vertical line appears in code editor when typing a symbol '

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34559]
### Description

When typing symbol ' the vertical line appears in code editor.
If it is a feature, could you please explain the meaning?
If it is a bug, I suggest to remove it because it distracts attention.

### DBeaver Version

Community Edition 24.1.2

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

### Steps to reproduce

1. copy-paste this code:
`select public.hello_world();`

https://github.com/dbeaver/dbeaver/assets/33929221/96ad4b16-196e-42e2-81e6-61914c83b29f

**Comment by E1izabeth** [comment]
It's expected behavior, which comes from the Eclipse platform, on which DBeaver is based.
Example from Eclipse IDE:
![image](https://github.com/dbeaver/dbeaver/assets/28875055/fe7ee145-0de3-448c-ac00-c422faa400d3)

This green cursor indicates that some symbols was inserted automatically by IDE -  second `'` in your case.
I believe we don't want to remove it as it's a basic platform functionality.

**Comment by E1izabeth** [comment]
Let's keep it open and wait if someone else is interested in this issue.
