### ISSUE TITLE
Dbeaver don't finish "Discover atribute {field}" - Redshift

### ISSUE THREAD

**Issue by alejandro-fiel-stori** [dbeaver/dbeaver#34657]
### Description

Even on simple queries like:
select * from stl_query where query=887227603
it stays forever on this message
![image](https://github.com/dbeaver/dbeaver/assets/153534002/5c1eeed5-2122-4641-b54c-dcae6be94061)
I'm getting only the first 200 rows for big queries, and in this particular case, only one row.

Other clients get that info almost instantaneously.

The error log I get from Window->show view->error log
[Error log.log](https://github.com/user-attachments/files/16100305/Error.log.log)

### DBeaver Version

24.1.1

### Operating System

macOS 14

### Database and driver

Redshift
com.amazon.redshift:redshift-jdbc42:RELEASE 2.1.0.29

### Steps to reproduce

It happens randomly, makes me restart Dbeaver

**Comment by serge-rider** [comment]
Thank you for the report.

From log file I can see that Redshift connection constantly fails with timeout errors.
This may be caused by your network configuration or by driver itself.
We had several reports about issues with the latest version of Redshift driver (2.1.0.29). 
Could you try to downgrade driver version to 2.1.0.22? if it won't help try 2.1.0.9

If this will help we will try to investigate and fix the issue.

![image](https://github.com/dbeaver/dbeaver/assets/6398845/2cc8dbc3-843c-402f-aa31-b7dc7728e09b)

**Comment by alejandro-fiel-stori** [comment]
Downgraded to 2.1.0.9.
This error is random, so I will try a little more, but this downgrade apparently solves https://github.com/dbeaver/dbeaver/issues/34275

**Comment by serge-rider** [comment]
It looks that latest Redshift drivers work badly in multithreaded mode (when queries are executed simultaneously).
It somehow breaks active connection.

Investigating..

**Comment by alejandro-fiel-stori** [comment]
I had some issues in the pass when opening 4 or 5 tables at same time to look at the table description. it felt random but with your input, that makes a lot more sense. Thanks
