### ISSUE TITLE
Hotkeys "Ctrl + Alt + Left / Ctrl + Alt + Right" don't work

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#34663]
### Description

Pressing it doesn't do anything.

Another possible issue (but maybe it is a feature) = there are two hotkeys "from out the box" for the same action.

![изображение](https://github.com/dbeaver/dbeaver/assets/33929221/51cef4d0-07d2-426c-ad35-fc08a8f37cbb)

### DBeaver Version

Community Edition 24.1.2

### Operating System

Windows 10

### Database and driver

PostgreSQL 16
PostgreSQL JDBC Driver 42.7.2

**Comment by ask9** [comment]
![изображение](https://github.com/dbeaver/dbeaver/assets/33929221/c0fc509a-67b8-4041-bdfd-4012dedda3b5)

It is also suspicious that the hotkey for "Next Edit Location" is not shown in a menu.
Tell me if it is a separate issue but looks like the issues are related

**Comment by ask9** [comment]
If I remap the hotkey in settings (for example to: Ctrl + Alt + Shift + H / Ctrl + Alt + Shift + J), it works but inconsistently.
I don't understand, but sometimes it jumps to the location, and sometimes it is not.
But if I click the appropriate menu item instead using a hotkey, it jumps.
Please also check for the weird behavior.

**Comment by TB-HunBoka** [comment]
I suggest you turn on the show key binding when command is invoked for keyboard option, so you can see if another combination is conflicting with your current settings. I had the same issue with ctrl+alt+, it was conflicting with ctrl+alt+; as they are the same key on my keyboard, and it was replaced in newer versions.
For me the ctrl+alt+right is showing that this is the next row shortcut, not next edit location. However ctrl+q works as previous edit location.
So I figured it out that this is because there are 2 "result viewer context" option in the when condition.
![image](https://github.com/dbeaver/dbeaver/assets/126617861/28b334dd-db39-43ce-8383-af54df591135)

The upper one is the default one and I think it is incorrect as I was clearly in the SQL Editor and still jumped to the next result row.

Selecting the second "result viewer context" for Next row and Previous row, fixed the issue for me.
Therefore, it is related to #34674

**Comment by TB-HunBoka** [comment]
I suggest you turn on the show key binding when command is invoked for keyboard option, so you can see if another combination is conflicting with your current settings. I had the same issue with ctrl+alt+, it was conflicting with ctrl+alt+; as they are the same key on my keyboard, and it was replaced in newer versions.
For me the ctrl+alt+right is showing that this is the next row shortcut, not next edit location. However ctrl+q works as previous edit location.
So I figured it out that this is because there are 2 "result viewer context" option in the when condition.
![image](https://github.com/dbeaver/dbeaver/assets/126617861/28b334dd-db39-43ce-8383-af54df591135)

The upper one is the default one and I think it is incorrect as I was clearly in the SQL Editor and still jumped to the next result row.

Selecting the second "result viewer context" for Next row and Previous row, fixed the issue for me.
Therefore, it is related to #34674

**Comment by E1izabeth** [comment]
Thank you for bug report and investigation. I confirm that I reproduced all mentioned issues.

**Comment by TB-HunBoka** [comment]
Made some code change locally and checked the conflict.

I moved the default key bindig under contextId="org.jkiss.dbeaver.ui.context.resultset.focused" for the following keys:
org.jkiss.dbeaver.core.resultset.row.first
org.jkiss.dbeaver.core.resultset.row.previous
org.jkiss.dbeaver.core.resultset.row.next
org.jkiss.dbeaver.core.resultset.row.last
So these will be only active in the result tab.

Works for me.
