### ISSUE TITLE
Can't generate sql from a simple select statement with "with ur"

### ISSUE THREAD

**Issue by filipemanuelofs** [dbeaver/dbeaver#3478]
I'm not able to generate sql from a simple select statement with "with ur" at the end, but works fine if removed, e.g:
* SELECT * FROM MYSCHEMA.MYTABLE WHERE ID = 1 WITH UR;
  * Can't generate
* SELECT * FROM MYSCHEMA.MYTABLE WHERE ID = 1;
  * It works

**Driver name:** DB2 / DB2 LUW
**Library:** db2jcc4-10.1.jar

_(Unfortunally I'm not able to upload image of this process)_

**Comment by serge-rider** [comment]
What exactly "generate SQL" means? 
I can execute query WITH UR in SQL editor and then run one of Generate SQL from context menu in results viewer.
Please provide a bit more details

**Comment by filipemanuelofs** [comment]
Using version DBeaver Community Edition 5.0.2 

![dbeaver_without_withur](https://user-images.githubusercontent.com/1047292/40624651-2d0a1a10-6284-11e8-92ba-696bf37c49b9.png)
Without "with ur".

![dbeaver_with_withur](https://user-images.githubusercontent.com/1047292/40624657-39d4c204-6284-11e8-8863-754b74d5d281.png)
With "with ur".

**Comment by serge-rider** [comment]
Yep. That's a bit more complicated.
This is what I see:
![image](https://user-images.githubusercontent.com/6398845/40629797-35b0c068-62d6-11e8-812b-abd141516c95.png)

DBeaver needs to extract query metadata (source table name, schema, etc) in order to be able to generate SQL for it.
There are two ways to extract metadata:
1. Parse query itself. This doesn't work if you have `WITH UR` clause. Because JSQLParser library doesn't support it (yet).
2. Get driver-provided metadata. This is very depends on driver itself. I'm using driver 4.19.49:
![image](https://user-images.githubusercontent.com/6398845/40629858-9221e2fa-62d6-11e8-93c8-2ad21c2fe4c8.png) and it provides correct query metadata. Maybe your driver doesn't.
This is what I see in metadata penel:
![image](https://user-images.githubusercontent.com/6398845/40629881-b1564f80-62d6-11e8-8219-001e7bf33947.png)
Table name (COLUMNS) is specified. But other driver may omit it. 

Please check your driver version and metadata panel.

**Comment by filipemanuelofs** [comment]
Can you share this driver? Not sure if I'm testing correctly.

**Comment by uslss** [comment]
Cannot reproduce the issue on current version.
There is no update on ticket more than a year - ticket is closed.
If issue is still actual for you feel free to reopen the ticket or open the new one.
