### ISSUE TITLE
Cannot inline edit geometry cell contents

### ISSUE THREAD

**Issue by ontheway16** [dbeaver/dbeaver#34849]
### Description

Formerly I was able to edit geometry fields. Now its not letting me inline edit the contents of cells containing POINT or POLYGON definitions.

### DBeaver Version

Community edition Version 24.1.2.202407071610

### Operating System

Windows 10

### Database and driver

Postgresql 12

### Steps to reproduce

Open table containing polygon or point geom. fields.
Double click to edit, it does not allow.
Right click to select edit/inline edit, also fails.
Editing another (non geometry) field in same table, no problems.

**Comment by Matvey16** [comment]
@ontheway16 Thank you for the report. As a temporary workaround you can edit geometry values in Value panel or by chossing `Edit cell` in the context menu
![image](https://github.com/user-attachments/assets/491fc26c-eeff-42b4-820a-c0e5d05dbd0e)

**Comment by ontheway16** [comment]
@Matvey16 , I am seeing it as the following :
![image](https://github.com/user-attachments/assets/7779310c-4a1c-4928-94cb-cdd637bf1a8e)

When I click somewhere else (a nearby db.field's cell) and comeback to geom cell, and then go to same menu, then it allows me to select (not ghosted this time), but nothing happens after selecting it. The edit cell or inline edit is not functioning. Tried this in both windows and linux computers.
**edit.** edit cell opens a view pane, but no place to edit polygon coords.
![image](https://github.com/user-attachments/assets/65003598-9adc-4646-bf89-0924f6dc1d77)

**Comment by Matvey16** [comment]
@ontheway16 Can you tell me when were you able to edit geometry values inside the cell itself? I've checked 22.0.0 and 23.0.0 version and it's not possible there.

But the greyed out items in the context menu is indeed a bug, it happens exectly because of the double-click on the cell. Dbeaver for some reason thinks that the cell is being edited and greys out the options. We need to fix that.

As for the actual ability to change geometry values, you need to change value presentation from `Map` to `Text`. Map is for the visualisation and text is for manipulation

![dbeaver_hwrJ1EtQWz](https://github.com/user-attachments/assets/096ab459-dd65-4ccb-a6e3-88b31193c7d9)

You can see how it works on this video

https://github.com/user-attachments/assets/34acca85-6325-49f1-92e8-25924e2f5110

**Comment by ontheway16** [comment]
@Matvey16 Hi, I did editings in the past, may be I misremember about in-cell editing (somehow my memory says there was editing in-cell, but probably misremember if its not available in former versions). It appears the "text" button completely missed from the eye this time. Since "edit cell" menu item also shows the map display in the window, under "value", and cannot be switched to "the value" in that editing window, as seen in my previous message's image.
May be, a true in cell editing might still be valuable since the other method can be easily missed.
