### ISSUE TITLE
Web Browser Setting Does Not Work

### ISSUE THREAD

**Issue by BenjaminWKI** [dbeaver/dbeaver#34948]
### Description

I've configured my DBeaver to use my system's configured default browser, in this case it is the BrowserPicker Windows app that is a "middle-man" that allows me to choose which browser to open the link with.
Since installing the latest version of DBeaver along with the latest version of Chrome v126.0.6478.183 (64-bit) I've found that DBeaver immediately opens all links in Chrome. 
I've already made sure that my Windows default browser settings are set to "BrowserPicker". 
I've tried changing the settings in Preferences > User Interface > Web Browser to all other options: 
"Default system web browser", "Firefox", "Microsoft Edge", even setting it to use the internal web browser 
but DBeaver seems to ignore this setting and continues to open links in Chrome. 
I'm not sure if this is a bug caused by the latest version of DBeaver or the latest version of Chrome being intrusive with the default browser settings. 

### DBeaver Version

24.1.3.202407211303

### Operating System

Windows 11

### Database and driver

MariaDB JDBC driver

### Steps to reproduce

1. Select a web browser in Preferences > User Interface > Web Browser.
2. Retrieve/generate a URL in Database results. 
3. Click on Open URL shortcut in the results view grid.

### Additional context

Edit: Additional findings: Only the first (left-most) data column in the results display that is a URL would immediately open in Chrome. Subsequent data columns containing a URL would load in the "Browser Picker" app as per configured as my Windows default browser. It still ignores whatever web browser is selected in DBeaver's Preferences setting.

**Comment by Destrolaric** [comment]
@BenjaminWKI Hi, DBeaver doesn't use Chrome. It relies on Microsoft Edge for the internal browser functionality. Web Browser page is part of the Eclipse functionality and doesn't change any internal browser settings. 
Unfortunately, Firefox is not a choice for our graphic framework. 
Our platform also supports changes to Internet Explorer for Windows. However, because it is outdated, I would not recommend using it. 

Also, regarding the external browser, DBeaver mostly uses the default system URI handler, so if Chrome is configured as a default browser, the link will open through Chrome.

**Comment by BenjaminWKI** [comment]
Hi @Destrolaric 
For some reason the bug no longer occurs after I powered up my system back on at the start of today. 
Seems like this bug isn't consistent and disappears after a reboot/program restart. 
You may close the ticket. 
Thanks for your time.

**Comment by dangelsaurus** [comment]
so what is the point of the Browser Picker?
