### ISSUE TITLE
DELETE key not deleting text in SQL Editor

### ISSUE THREAD

**Issue by RazvanModex** [dbeaver/dbeaver#35094]
### Description

DELETE key not deleting text in SQL Editor

### DBeaver Version

Community 24.0.5.202405191503

### Operating System

Windows 10 Business - 19045.4651 (22H2)

### Database and driver

Irrelevant

### Steps to reproduce

1. Open SQL Editor
![image](https://github.com/user-attachments/assets/0cba1b4a-524f-49ca-86b6-3b88ba863f90)

2. Select some SQL and press DELETE key
![image](https://github.com/user-attachments/assets/69700e83-0708-4336-8858-38944910bf82)

3. Hotkey configuration
![image](https://github.com/user-attachments/assets/080c0018-57b0-4e01-88ff-682ddc4f63ef)

### Additional context

The expected behavior is to have the SQL Editor look like:
![image](https://github.com/user-attachments/assets/c1042eec-48f9-41ab-9452-74918b7287a7)

Also, DELETE key not deleting next character if no text is selected in SQL Editor.

Lastly, DELETE key works as expected when renaming table, for example.

**Comment by TB-HunBoka** [comment]
Looks like you have another key binded on the delete key, can you show all keys listed in the keys preferences searching for delete? (the same printscreen but scroll down, or resize the window)
Also, please turn on the check box at the bottom of the keys preferences that says: "Through keyboard".
Then go back to the editor, try to delete something, and check the popup window at the bottom of the screen. It will tell you what kind of keybinding were triggered.
I got newer version, but it should look like this:
![kép](https://github.com/user-attachments/assets/b58499dd-2173-4d6b-8078-677706d0efac)

**Comment by atr0000** [comment]
I have the same problem.

![s1](https://github.com/user-attachments/assets/2a42a06f-3740-4807-a2a7-43f3bef4e3bc)

First time i open dbeaver and go into an editor text i can only delete 1 character, i mean only one press of the delete button works after that nothing works.

If i activate "Through keyboard" when i press delete key for the first time "delete is shown" but at the second press nothing is shown.

If i close Dbeaver or restart PC i can again delete 1 character and nothing more. i tried uninstalling and installing and still the same thing.

Everywhere else the delete key works. (i mean notepad++, pycharm, vscode, etc)

Edit: Maybe some info that is important.
If i map delete next to CTRL+Delete. Now it works to delete the next character. If i use delete in windows (inside dbeaver i mean) as mapped it works. If i try to map just the delete key it doesn't work (i select it and map it but it doesn't work)

So delete key works in other programs and delete key works in dbeaver windows and delete key works only in combination with other key in editor. 

Edit 2: Just found out this is eclipse ... i have the same issue in eclipse as well ... the only two programs i have this issue. i fixed it in eclipse ... i just switched to netbeans :)) ... probably no luck fixing this in dbeaver as it's a known and unfixable issue in eclipse ... such a shame 

Edit 3: It's known issue here too .. pfff ... https://github.com/dbeaver/dbeaver/issues/22581

**Comment by TB-HunBoka** [comment]
Might be a different issue as the eclipse bug mentioned it is not working when they keep the del key down, but single press works.

@atr0000 as you can reproduce the issue, can you check if changing the "when" has any impact on the delete key behavior?
Like limiting it to the editor with the second SQL Script Editor Context:
![image](https://github.com/user-attachments/assets/ca7c795c-55cd-4d4b-915b-a69f141e4472)

Do you experience the same spamming the delfete key fixin the problem? _Press the [delete] key fourteen more times. (After the 15th press, the character after the cursor will be deleted and the [delete] key will start behaving normally.)_ 

Also, is there any error message in the error log?
Windows -> show view -> Error log

Can you please also try to delete with windows on-screen keyboard?

Assigning something else to delete key will also break it?

As ctrl+delete fixed the problem, we might find a good workaround for people impacted by this issue. Which is somehow very limited.

**Comment by TB-HunBoka** [comment]
Just a foot note about a strange behavior.
Open the keys, search for delete -> you will see the delete key binded to delete.
Change the Scheme to emacs or dbeaver keyboard only.
Change the Scheme back to dbeaver -> the delete key became unbinded. What?

**Comment by atr0000** [comment]
Hey. Ok, this got weirder for me. 
First i restarted DBeaver and restored the bindings.
Spamming does nothing for me. Still after the first stroke the delete doesn't work. I tried changing "when" as instructed (and some others) but nothing changed. 

I really want to mention that for example if i write something for example in "Database navigator" where it says "Enter a part of object name here" delete works great and any other location inside Dbeaver works perfect except sql editor.

Now that being said things got weirder.

I tried the On-Screen Keyboard as requested and to my disbelieve it worked perfectly. 

A little context of my setup is necessary. I have two laptops with peripherals connected together through a software kvm called "Input Director". On both i have DBeaver. One is win 10 and the other is win 11. Similar specs, same manufacturer. Only on one laptop i have the delete issue in DBeaver and eclipse, the "child" laptop. Child laptop does not have plugged in the keyboard and mouse. No problem on parent laptop only on child.

After trying on-screen keyboard i tried the laptop onboard keyboard and shockingly it worked so only with wireless logitech keyboard i experience the issue. 

After that i decided to put in the child laptop a keyboard laying around and the delete key works perfectly then i connected the keyboard from parent laptop and again everything works.

**So for some reason when using the software kvm "Input Director" and ONLY when the keyboard is not connected directly to the laptop in question only then the delete key doesn't work in sql editor and ONLY in sql editor.**

Because everything everywhere else works i never questioned the implication of the kvm software. My bad .. 

Very weird still that everything everywhere works except the sql editor. **Is it an eclipse bug?** 

Probably my scenario is not relatable with many others and my issue is so particular that i don't know if it's worth investigating.

Edit: No erros in log

**Comment by arhayka** [comment]
@RazvanModex Could you please send me the log files? To do so, go to the main menu, Help -> Collect diagnostic info. Thank you.

Some notes:
- We reproduced one of the bugs described here: when you change key schemas, the Delete binding disappears. We think that this is an eclipse issue.
- We can't reproduce the bug when the Delete button is not working in SQL Editor. However, we also suppose that this is an eclipse issue.

**Comment by E1izabeth** [comment]
It's been a while since no update here. If the issue is still actual please let me know and provide additional information.
