### ISSUE TITLE
Data Compare Tool - Change/Bug on Constraint

### ISSUE THREAD

**Issue by JasonLeClair** [dbeaver/dbeaver#35598]
### Description

Before updating to DBeaver EE v 24.2.0 (Sept '24), I was able to specify a composite primary key in the Data Compare tool, for both tables and views as the objects.  I am now being prompted to "Choose only one column for both sources as a constraint" when trying to do the same function in the newest version.  As a Data Engineer using a modern approach, I no longer prescribe to the Kimball method of a unique, indexed ID for every record rather than allowing the server to process on composite keys (modern servers are way better than in Kimball's day).  This change is forcing me to do much more coding work just to get to a data comparison.

### DBeaver Version

Enterprise Edition, v 24.2.0

### Operating System

Windows 10

### Database and driver

Teradata JDBC v 17.20.x

### Steps to reproduce

Comparing two tables or views, where the primary key is a composite of more than one feature.

**Comment by ShadelessFox** [comment]
Hello @JasonLeClair,

The Data Compare feature has never worked correctly with composite keys, that's why we decided to finally restrict users from choosing multiple columns.

We have a ticket about implementing support for composite keys on our internal board. Please contact us via https://dbeaver.com/tickets so we can increase the priority of the ticket.
