### ISSUE TITLE
Feature to show conflicted hotkeys in Keys in Preferences doesn't work as expected

### ISSUE THREAD

**Issue by ask9** [dbeaver/dbeaver#35634]
### Description

Here on the video I show that there is already a default hotkey Ctrl + Shift + D, and assigning the same hotkey to "Disconnect"-command doesn't warn a user that the hotkey is already in use in the "Conflict"-area.

https://github.com/user-attachments/assets/9da94a85-0123-4e62-b1c1-b1d728d60dd4

### DBeaver Version

Enterprise Edition 24.2.1-202409122322

### Operating System

Windows 10

**Comment by ged-yuko** [comment]
1. Hotkeys are managed by the underlying Eclipse platform, so if this is a real problem, the issue should go somewhere there.
2. I personally don't see this as problem because, as far as i know, hotkeys are just triggers for commands, commands are being served by handlers, and handlers are being dynamically activated and deactivated according to the particular UI context (which is related not only to "When" and "Category" columns of this preferece editor, but also to the internal command providing plugin configuration specified in its plugin.xml, and also by concrete handlers implementation at run time), so even if it looks like there is a conflict, there might not be any conflicts in fact. And it cannot be inferred at all, because you can have any combination of Eclipse plugins. Some of them can even provide hotkeys based on key-press handlers, which you will never ever see in the preference settings. Summing it up, it is both useless and impossible to really detect hotkey conflicts in Eclipse platform.

**Comment by E1izabeth** [comment]
The conflict checker compares three columns: "When" "Category" and "User" and shows a warning only if values in all three columns are equal. When you add a new shortcut for a command, the User column is marked as U. However, there is no such flag for commands with default shortcuts. You can check it by adding the same shortcut, for example, for Connect
![image](https://github.com/user-attachments/assets/a371511c-37d4-447a-9587-4040864c4269)


The whole settings page and the logic behind it come from Eclipse. I'm not sure we can and want to change something here.
