### ISSUE TITLE
Problem with P2 repository (301 and HTTPS)

### ISSUE THREAD

**Issue by zulus** [dbeaver/dbeaver#3570]
I used p2 from website: http://dbeaver.jkiss.org/update/latest/

Result:

```
HTTP Server Unknown HTTP Response Code (301):`/content.xml
General connection error with response code=301 and header(0)=HTTP/1.1 301 Moved Permanently
```

If I set https://dbeaver.io/update/latest connection is extremely slow:

```
Unable to read repository at https://dbeaver.io/update/latest/content.xml.
Read timed out
```

Note: By default p2 ignore 301 redirects. They works (partially) with ECF Apache HTTP Client implementation. It's enabled by default since Oxygen but due many proxy issues might be disabled.

In general p2 with 301/302 and HTTPS is bad idea and often doesn't work.

http://dbeaver.jkiss.org/update/latest/ should have compositeArtifacts.xml and compositeContents.xml linked to http://dbeaver.io/update/latest/ (no HTTPS).

**Comment by serge-rider** [comment]
Correct URL is https://dbeaver.io/update/latest/
We've updated all old references (jkiss.org) we found + jkiss.org redirects are working. However I understand that old repository URL is saved in existing Eclipse installations.
compositeArtifacts.xml and compositeContents.xml are missing but it is not an issue in most cases.
And we do not have plain http repository for a long time (because of security concerns).

Please try it again, yesterday we had a big release and sometimes dbeaver.io server is overloaded, today/tomorrow it should be much faster. 
We are planning to move to a faster server.

**Comment by zulus** [comment]
This page still have old url : https://dbeaver.io/download/

**Comment by serge-rider** [comment]
Fixed)
Thanks for noticing.

**Comment by zulus** [comment]
With new url works fine.
