### ISSUE TITLE
font preview in preferences menu shouldnt be translated

### ISSUE THREAD

**Issue by bytechaocai** [dbeaver/dbeaver#35886]
**Is your feature request related to a problem? Please describe.**
when i set fonts in preferences, i see "The quick brown fox jumps over the lazy dog" was translated.  this sentence is used to see fonts effects of a to z.  as this sentence was translated, i cant see fonts effects.
![图片](https://github.com/user-attachments/assets/24924961-4d39-4512-bc8c-853a15309927)
![图片](https://github.com/user-attachments/assets/b72db38e-4922-4781-bcf9-b1692283cedf)

**Describe the solution you'd like**
cancel translate this sentence.

**Describe alternatives you've considered**

**Additional context**

**Comment by E1izabeth** [comment]
Thanks for the request. I agree with you. However, the issue comes from [Eclipse ](https://github.com/eclipse-platform)- the platform on which DBeaver is based. This string is not only translated to different languages there but even internationalized, according to this solved issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=421579
