### ISSUE TITLE
New autocomplete does not insert table name correctly

### ISSUE THREAD

**Issue by MashaKorax** [dbeaver/dbeaver#36041]
### Description

Type `select from a` .  from the props select the table name

https://github.com/user-attachments/assets/03596c48-5c88-4ce1-a070-4d88a268729e

![dbeaver_HYVQUU8IVJ](https://github.com/user-attachments/assets/6c9411be-11ff-4d13-958b-eee6493135a1)

### DBeaver Version

DBeaver 24.2.4

### Operating System

windows 10

**Comment by ask9** [comment]
Just a small warning about this issue: it is quite painful because it breaks normal query typing and happens nearly after choosing every item from the autocomplete list.
I believe this issue should not get into the stable release at all.

It was introduced in one of the previous early access versions (checked on community ver):
Version 24.2.4.202410172322  no bug
Version 24.2.4.202410262322  there is a bug
Version 24.2.5.202410300022  there is a bug

It also seems to be, all new issues of the last week about "autocomplete" have the same or similar root cause (something has been broken).

**Comment by E1izabeth** [comment]
New autocompletion engine is still under development. It's still turned off by default

**Comment by E1izabeth** [comment]
We haven't released this new autocompletion yet, so just switch the setting back to default
