### ISSUE TITLE
Non public schema missing in PostgreSQL connections since 24.2.3

### ISSUE THREAD

**Issue by coleman-rik** [dbeaver/dbeaver#36091]
### Description

The recent dBeaver update has caused some problematic behavior in regards to being able to see custom schema.
Prior to this update expanding the schema tree looked like this:
![dBeaver_all_schema_20241021_131506](https://github.com/user-attachments/assets/34838f84-62e7-41ae-ad86-7affc44a3adc)

Since the update, the exact same connection object with the exact same setting now looks like this:
![dBeaver_new_schema_20241021_131506](https://github.com/user-attachments/assets/ccc01918-f580-4cc6-8c73-18359c551690)

The difference appears to be what database is listed in the Connection Settings ->Main->Database field.  Whichever database is listed in that field displays all of the schema.  The rest of the databases accessed via that connection only list the information_schema, pg_catalog, and public schema.  

Most of my PostgreSQL connections contain multiple databases, anywhere from two to ten databases.  Since upgrading to the current version of dBeaver I have to reset the connection to point to a different database, save the connection, and then reconnect.  Unfortunately this will now hide all of the non default schema of the previous database.

Is there anyway to revert to the previous behavior of showing all of the schema of all of the databases accessed via a connection?

Thanks.

### DBeaver Version

Community Edition 24.2.3

### Operating System

Windows 10

### Database and driver

PostgreSQL 15 / 16

### Steps to reproduce

1. have a PostgreSQL connection object
2. let there be multiple databases on that PostgreSQL instance
3. let there by multiple custom schema in each database
4. construct a dBeaver connection object with one of the databases as the value in Connection Settings->Main->Server->Database
5. check the Show all databases checkbox in the same location
6. establish the connection
7. notice that all of the schema are listed for the database from step 4 and only the default schema are shown for the rest of the databases.

**Comment by serge-rider** [comment]
It looks like dbeaver connects to a wrong database.

Please write how you configure the connection. Do you use host based config or JDBC URL?
Also could you check debug log (https://github.com/dbeaver/dbeaver/wiki/Log-files#standard-log-file-paths) for any errors/warnings?

**Comment by Matvey16** [comment]
Also I see that on your second screenshot the database is the default one (it's name is in bold). Can you please do the following?
1. Connect to the database
2. Expand the connection
3. Expand any non-default database (not in bold)
4. Verify that you don't see any schema that should be there
5. Show me what is in Query manager with such settings

![image](https://github.com/user-attachments/assets/31ae75c4-e698-4e09-a24e-43fc27874da1)

Do you have anything set in this field?

![image](https://github.com/user-attachments/assets/293379bb-63f9-4990-8fae-8cfb611a7b0c)

**Comment by coleman-rik** [comment]
@Matvey16,

1 - 4 were covered in my initial ticket. Regardless if the database is the default database or not, the only database whose non default schema you can see is the one listed in the Connection settings->Main->Server->Database field.

Usually one of the databases in the Connection settings->initialization->Default database is set to one of the databases accessible via that connection. The value in this field is irrelevent to this problem.

As this problem has nothing to do with running queries, there can be no SQL Editors open and this problem still exists (it's a Database Navigator problem) I'm not sure what the Query Manager has to do with it, but here's what mine looks like anyway.
![dBeaver_query_manager_20241029_113731](https://github.com/user-attachments/assets/02061881-689c-4ed8-936a-a9e5e49fd6dd)

**Comment by Matvey16** [comment]
I asked you those questions, because this issue is not reproduceble for us under normal circumstances. When you connect in multi-database mode, in order to populate the navigator with schemas of the database that is not used for initial connection (that is set in `Connection settings->Main->Server->Database`), DBeaver needs to open another session with a connection to another database. If you check `Sessions` for object types in query manager settings, I will be able to see if the correct databases are used to open new sessions. For that I need to see the results in your query manager after you go through steps mentioned in my comment.

We have found a bug that may have the same cause as your issue and it is caused by having a different database in `Initialization -> Default database`, than the one that is filled in general connection settings. So to check if those issues are connected I would ask you to leave that field (Initialization -> Default database) empty and check if your issue will still persist with those settings.
