### ISSUE TITLE
Table or subquery "alias" not found

### ISSUE THREAD

**Issue by nataklug** [dbeaver/dbeaver#36272]
### Description

After updating, the system now do not understand alias for some reason. I can still run the query, and it is working, but the alias on the SQL editor is giving me many errors and becoming unstable. Maybe it is something related to subqueries inside the select.
![Captura de tela 2024-11-18 114032](https://github.com/user-attachments/assets/f29fca18-e9ca-480b-abd3-f028772e59e8)

### DBeaver Version

Community Edition 24.2.5

### Operating System

Windows 11

### Database and driver

MariaDB

### Steps to reproduce

Just open the query.

### Additional context

I am sending the query itself in ZIP if needed.
[EXP0010_atendimentos-fechados.zip](https://github.com/user-attachments/files/17802008/EXP0010_atendimentos-fechados.zip)

**Comment by E1izabeth** [comment]
Thanks for the bug report. I reproduced the issue

**Comment by E1izabeth** [comment]
Parser can't handle the following part of the query
`SUM(CAST(REPLACE(SUBSTRING(spc.descri_com,LOCATE('R$', spc.descri_com) + 3,LOCATE(',', spc.descri_com, LOCATE('R$', spc.descri_com)) - (LOCATE('R$', spc.descri_com) + 3)),'.', '') AS DECIMAL(10, 2)))  AS MET_spcValorRecuperado,` because of the usage of REPLACE function
