### ISSUE TITLE
Error describing object created outside of DBeaver

### ISSUE THREAD

**Issue by bobf32** [dbeaver/dbeaver#3760]
DBeaver 5.1.1

1. Connect to an Oracle DB in DBeaver. 
2. Issue CREATE TABLE foo... outside of DBEAVER (e.g. sqlplus)
3. Ctrl-click on new table name in DBeaver SQL editor

Gives message box with text:

<Quote>
Problem Occurred

'Find object node by reference' has ancountered a problem. 

Table 'FOO' not found in schema '<current DBeaverschema>'
<Quote>

Workaround is to disconnect and reconnect (Invalidate/Reconnect doesn't work).

Weirdly, can select from foo, just can't describe it.

**Comment by serge-rider** [comment]
DBeaver doesn't refresh database meta objects  (tables, procedures, etc) by itself. You have to perform refresh - select schema/database and press F5 (or context menu -> Refresh).

Invalidate/Reconnect just checks connection health, it doesn't refresh navigator.

**Comment by bobf32** [comment]
Doing an F5 on the relevant DB connection in in Database Navigator doesn't help. Am I doing something wrong?

**Comment by pyrocks** [comment]
I am also facing this error very often - would be nice to have a fallback to refresh the specific object  requested in case it is not found instead of manually having to refresh the entire database, or at least add such an option [feature request].
specifically - when working with AWS RDS in a region not close to you these full refreshes can take a >10 seconds.
In Oracle the lookup of a specific object can be done using all_objects, in postgres pg_class and pg_proc etc.
