### ISSUE TITLE
DB name format in 'Read data in SQL console'?

### ISSUE THREAD

**Issue by jimpriest** [dbeaver/dbeaver#3841]
My typical workflow...  I will do a "Read data in SQL console" and get a query

SELECT foo,bar
FROM my_database.dbo.my_table

And I'll tinker on this for a bit, maybe format it then copy it into my code which breaks because my code is just expecting

SELECT foo,bar
FROM my_table

Is there a way to strip off that initial 'my_database.dbo.' text?  I dug through settings but not really sure what that is called...

Thanks!

**Comment by workguy66** [comment]
I don't know what that entire bit is called, but the my_database in `my_database.my_table` is the database schema where that table is stored, you need to specify it, otherwise dbeaver does not know what database to fetch the data from, unless you execute `use my_database;` beforehand, then it will know and you will be able to skip it in your query.

**Comment by serge-rider** [comment]
I understand why it could be useful. I'm sure that by default catalog/schema names must be in the table name. So potentially it is possible to make this configurable. But I can't figure out some easy and obvious UI to configure this. 
Making yet another option somewhere deep in editor preferences doesn't look helpful..

**Comment by jimpriest** [comment]
No worries.  Was just curious if something already existed.  I agree - not worth adding.  

I think I will hack up my clipboard utility to strip out that string when I copy/paste.
