### ISSUE TITLE
Filter Database Objects does not work

### ISSUE THREAD

**Issue by erlangp** [dbeaver/dbeaver#3875]
Filter Database Objects does not work.. i type database name, still showing all database.. it's not showing/finding what i type..
help

**Comment by erlangp** [comment]
https://github.com/dbeaver/dbeaver/issues/3831

**Comment by serge-rider** [comment]
Database/catalog filter (on General page of connection properties dialog) works fine.

Do you mean quick filter in the top of database navigator? It is not filtering databases/schemas and other "container" objects. 
Because this will make tables filtering not-possible (it will filter catalogs first so you won't be able to see tables in catalogs which doesn't match entered table name)

**Comment by erlangp** [comment]
owh sorry.. i still dont understand how to use the filter form.. please tell me an axample.. thanks :)

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/43680986-f062d62c-984f-11e8-85b8-86a6b34ec680.png)
![image](https://user-images.githubusercontent.com/6398845/43680988-029e0898-9850-11e8-873f-bf48c67c8045.png)

**Comment by erlangp** [comment]
thanks very much sir.. :) :+1:
