### ISSUE TITLE
DB2 Dbeaver Explain Plan - Not allowed to create new EXPLAIN tables

### ISSUE THREAD

**Issue by dipasi** [dbeaver/dbeaver#3905]
Question: 

When I run an explain plan in DB2 command line, DB2 uses a temporary tbs to provide the results. When using Dbeaver, it tries to insert the results in a table within my schema or in SYSTOOLS, which results in an error as table does not exist and I'm not allowed to create these EXPLAIN tables. 

![dbeaver_ep_error](https://user-images.githubusercontent.com/22104926/43549099-bef1d948-95ad-11e8-8ad4-8cf39c5a9c34.jpg)

Is there a way to tell Dbeaver to use the temporary tbs instead, same as command line tool does?

Thanks in advance.

Dbeaver 3.7.7 - DB2 LUW 10.5 SP9

**Comment by titou10titou10** [comment]
What do you mean by *"Is there a way to tell Dbeaver to use the temporary tbs instead"*? 

If you mean DB2 System or User temporary tablespaces, then it is not possible. 
This kind of tablespaces are only used internally by DB2 and a user can not create directly create tables in those.

If you try to do so, you'll receive an -284 SQL Error: *Table creation failed because the table space "xxx" that was specified in the statement after the clause "IN" is not a supported type of table space for that clause.*

More [information here](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_10.5.0/com.ibm.db2.luw.admin.dbobj.doc/doc/c0004975.html)

**Comment by dipasi** [comment]
Hi titou10

Thank you for your answer. Let me rephase my previous comment: seems like I can successfully get an explain plan in DB2 command line with limited permissions (Production environment / read only access), is there a way to get the same thing using DBeaver?

Thanks,
dipasi

**Comment by titou10titou10** [comment]
For DB2, in order to build the "explain view", DBeaver just executes an "EXPLAIN PLAN SET QUERYNO = \<n> FOR \<query>" statement. Then it reads the EXPLAIN tables in order to aggregate the results

So if you can execute this statement outside DBeaver (ie with DB2 CLI), you should be able to do it through DBeaver, with the same user you use to connect to DB2 of course.

One particularity is that before teh EXPLAIn statement, DBeaver performs a call to "SYSPROC.SYSINSTALLOBJECTS" to check if the explain tables exist and where they exist (Current schema, then "SYSTOOLS" schema)



You can see what SQL stateemnt DBeaver issue to the database in the "Query Manager" view:
  `Menu > Window > Show View > Query manager`, then click on the "filter" icon in this view ((or right click in the list) ) and check `"Util"` (or `"Utility Function"`)

Denis

**Comment by dipasi** [comment]
Ok, I see, that's helpful.

In DB2 command line I'm running this command: 

"db2expln -d [db]-u [user] [passwd] -t -g -q "select [...]" 

If I try to use the "db2 explain plan" I get an error similar to the one I see in Query Manager. Any change to make DBeaver run this db2expln command instead of the explain plan? I guess that the answer will be no, but worth try asking.

Thank you Denis

**Comment by titou10titou10** [comment]
Indeed. `"db2expln"` is a DB2 tool that is bundle  with DB2 fat clients (and servers..) and not an SQL statement

DBeaver connects to the database via` JDBC` and so does not have access to DB2 "tools", as it does not communicate with an eventual DB2 fat client installed on the machine DBeaver is running. It does not need it

In your case, if you want to use DBeaver to visualize explains plans, you need to ask to the person in charge 
of the security to give you the authorities to run the DB2 SQL EXPLAIN statement as [listed here in the DB2 doc](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_10.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0000952.html)

Thank you for using DBeaver.

Denis

**Comment by DanielAdeniji** [comment]
Enabling "Read-only connection" can cause lead to this issue, as well.

Please read more here...

Db/2 – LUW – Error – "SQL Error [25000]: Operation invalid for application execution environment."

[link](https://learningintheopen.org/2018/09/28/db-2-luw-error-sql-error-25000-operation-invalid-for-application-execution-environment/)
