### ISSUE TITLE
[ER Diagrams][.graphml] Incorrect layout when opened in yEd Live editor

### ISSUE THREAD

**Issue by alexsh2** [dbeaver/dbeaver#3968]
DBeaver - **Version 5.1.5 EE**
OS - **Windows 10**
Graphical Editor - [yEd Live](https://www.yworks.com/yed-live/)
Browsers: **Chrome, Firefox, Edge**

**Steps to reproduce:**
1. Save ER diagram as .graphml file
2. Using any browser navigate to [yEd Live](https://www.yworks.com/yed-live/) editor
3. Open saved ER diagram in the editor

**Expected result:**
The diagram is displayed in proper layout

**Actual result:**
The layout is broken
![image](https://user-images.githubusercontent.com/41971602/43991495-ad9d8f2c-9d76-11e8-8f6b-46a649d02fd2.png)

**Comment by fskpf** [comment]
I'm part of the developer team of yEd Live. Can you attach the GraphML of the above image? I guess this is related to the layout parameter of the label.  Does it look the same in the [yEd Desktop](https://www.yworks.com/products/yed) application?

**Comment by Bullnados** [comment]
@fskpf 
for me in offline yed it works without problems
https://www.yworks.com/yed-live/?file=https://gist.githubusercontent.com/Bullnados/88da2d137b24ee60a93a0ee2b5213466/raw/rental


[rental.graphml.zip](https://github.com/dbeaver/dbeaver/files/2447384/rental.graphml.zip)

**Comment by fskpf** [comment]
The difference between yEd Desktop and yEd Live originates from the coordinates that are provided with the <y:NodeLabel>
```
<y:NodeLabel ... x="1612" y="1553">_pg_foreign_data_wrappers</y:NodeLabel>
<y:NodeLabel ... x="1612" y="1580">oid: oid.....
```
yEd Desktop ignores them entirely and places the labels according to the given label model (ErdAttributesNodeLabelMode) and some additional configuration (configuration, alignment, etc.).

yEd Live, however, uses the coordinates to place the labels **relative** to the node's top-left corner. So for the snippet above, the following would work in both, yEd Desktop and yEd Live:
```
<y:NodeLabel ... x="2" y="4">_pg_foreign_data_wrappers</y:NodeLabel>
<y:NodeLabel ... x="2" y="30">oid: oid.....
```
Though the name won't be centered because of x="2".

Also, opening the file in yEd Desktop and saving it again will created a file that works in yEd Live, too.
