### ISSUE TITLE
Problem connecting to CockroachDB....

### ISSUE THREAD

**Issue by natiki** [dbeaver/dbeaver#4067]
Hi,

- DBeaver 5.1.5.201808130751 Community Edition

On my Windows 10 system I followed the instructions to spin up a 3 node cluster in secure mode (using their SSL generation option not OpenSSL) https://www.cockroachlabs.com/docs/stable/secure-a-cluster.html which ultimately means I am looking to use the following connection string:

```
postgresql://root@localhost:26257?sslcert=certs%5Cclient.root.crt&sslkey=certs%5Cclient.root.key&sslmode=verify-full&sslrootcert=certs%5Cca.crt
```

However after configuring a PostgreSQL connection as I think they should be I get:

![image](https://user-images.githubusercontent.com/4738140/44518967-0bda3d00-a70f-11e8-8598-619052f279d9.png)

Any suggestions on how to get this working?

**Comment by serge-rider** [comment]
Will check this in #4140

**Comment by serge-rider** [comment]
Try to install SSHJ extension, it will setup advanced security libraries.

However I can't initiate SSL connection to Cockroach.
1. I've configured certificates:
![image](https://user-images.githubusercontent.com/6398845/45390347-8966de00-b627-11e8-94d2-d5c2c6a6f5d8.png)
2. Set default connection settings:
![image](https://user-images.githubusercontent.com/6398845/45390415-db0f6880-b627-11e8-9049-4e51c4f61673.png)

3. When I connect I see error `The server requested password-based authentication, but no password was provided.`
Just our of curiosity I've tried to set any password and now I see error `ERROR: user root must use certificate authentication instead of password authentication`.
So I stuck here. Once I enable SSL it complains that no password specified. Once I specify password itr says that I can't use password in secure mode.

**Comment by mberhault** [comment]
The original error reported (`Could not read SSL key file ...`) is due to the fact that JDBC wants PKCS#8 keys. You can convert DER-encoded PEM keys using:
```
openssl pkcs8 -topk8 -inform PEM -outform DER -in client.root.key -out client.root.pk8 -nocrypt
```

**Comment by JackHerring** [comment]
Having had this same issue I can confirm that creating the `.pk8` key file and connecting as above but with that instead of the `.key` file does indeed work.
