### ISSUE TITLE
Use DBeaver as a Read Only SQL Query Tool

### ISSUE THREAD

**Issue by coryroyce** [dbeaver/dbeaver#4112]
Hi All,

Are there any settings that would make it easy to use DBeaver as a Read Only SQL Query Tool?

I have several employees who need to create SQL statements (Select Only) and export the results, but I want to configure this so that they have read only rights and no ability to change/harm the database they are connected to.

I really appreciate any feedback.

**Comment by michelvosje** [comment]
For the PostgreSQL driver you can configure the **readOnly** driver property.
![image](https://user-images.githubusercontent.com/5354633/44801688-0327b200-abba-11e8-9860-2881ff5e02b7.png)

When i tried to create a table or insert a record:
![image](https://user-images.githubusercontent.com/5354633/44801657-eab79780-abb9-11e8-98b4-5c806880d6cc.png)

![image](https://user-images.githubusercontent.com/5354633/44801764-38340480-abba-11e8-85ab-1f4b23627ee2.png)

But i don't recommend to do it this way, because they can still change the configurations. Why not let them connect to the database with a different user which has limited access rights. You should be able to configure this in the DBMS.

**Comment by coryroyce** [comment]
Thanks for getting back to me michelvosje.

That makes sense and I wasn't sure if there was a built in way of doing this through DBeaver.

**Comment by serge-rider** [comment]
You also can set connection read-only in database independent way:
![image](https://user-images.githubusercontent.com/6398845/44878688-30ef2280-acb0-11e8-93ee-173b8edf138a.png)

**Comment by EGrunzke** [comment]
2025 Update - These settings are now in `General`:
- Set the `Connection Type` to `Production`
- Enable the `Read-only connection` checkbox

<img width="1012" height="828" alt="Image" src="https://github.com/user-attachments/assets/87bc791c-022e-42bf-b930-c4054cd8b1ce" />

This probably isn't bulletproof; a role in the db is better for truly untrusted access. But I'm a dev and I just want to protect myself against accidental writes!
