### ISSUE TITLE
Database connections keep failing?

### ISSUE THREAD

**Issue by dooferorg** [dbeaver/dbeaver#4123]
DBeaver 5.1.6.201808262133

Working in this program is kind of frustrating. It seems nearly every time I'm trying to run a query, or refresh a table list, I'm getting an error pop up about connection failed. 'Can not read response from server. Expected to read 4 bytes, read 0 bytes before connection was unexpectedly lost.' 

Currently I'm using a MySQL database. I found an option to re-connect on failure and sometimes it does (and tells me about it with the little pop-up)  and sometimes it just errors out.

My question is why it's even happening at all? The connection timeout on the MySQL server is 10 minutes and this is happening when leaving the program for only a minute or two. Can't the program just reinitialize the connection without whining about it? It's TCP for goodness sake.

This is on a computer that has had no problems maintaining connections when using MySQL Workbench or SQLServer Management Studio.

**Comment by serge-rider** [comment]
I'm quite sure this is result of some misconfiguration. 
Do you use SSH or SOCKS proxy?
Did you change any network configuration (keep-alive)?

For example such error happens in almost 100% cases if you use SSH and wrong database host name (usually it should be localhost).

**Comment by dooferorg** [comment]
It's not over SSH, no. I did find an older article about an issue with that (https://github.com/dbeaver/dbeaver/issues/1965) but couldn't find a dialog for keep-alive.

I did now just find the option to 'Invalidate connection before executing' and that seems to do the trick. Is that the recommended thing to do with MySQL?

Initially I only just connected to the MySQL database and didn't alter any options and was getting that error (and started trying to see what I could do about it)

**Comment by serge-rider** [comment]
No, it is not a recommended option. In most cases MySQL connections works just fine with default settings.
Note: there are 3 different MySQL drivers (3.x+, 5.x+, 8.x+). It is better to use a driver matching your server version. This is because Oracle changed client driver recently and it is not 100% backward compatible. And 5.x driver doesn't fully support 8.x server.
Also there is MariaDB driver which is also slightly different.

Here is Keep-Alive configuration:
![image](https://user-images.githubusercontent.com/6398845/44880733-0a33ea80-acb6-11e8-895c-93a7604aa5dd.png)
Here is auto-recovery option:
![image](https://user-images.githubusercontent.com/6398845/44880770-1d46ba80-acb6-11e8-9f43-2c3bacf0a9b0.png)

**Comment by szhong20** [comment]
I had also facing this problem on latest version of dbeaver
![image](https://user-images.githubusercontent.com/78476461/148155396-291f8903-aa15-4a95-9f29-21b99f1cb230.png)

Actually, I've connect to the remote database through SSH tunnel.
![image](https://user-images.githubusercontent.com/78476461/148155869-77909afe-b8b3-41dc-a417-3396027bc046.png)

The solution works for me.
