### ISSUE TITLE
Can not setup client timezone

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#4181]
In the conection properties did not find how to setup client's timezone

Even starting transaction in a tab did not help:
```sql
begin;
SET TIME ZONE 'UTC';
select ..... ;
```

so I get wrong (not desired) results:
http://joxi.ru/vAWMwOZI1L0Ejm (sorry, text is not copied)

but in the `psql` I get for same query:
```
       startdate        |        enddate         | amount | amount |          valid          
------------------------+------------------------+--------+--------+-------------------------
 2018-08-01 00:00:00+00 | 2018-08-02 00:00:00+00 |     14 |     14 | [2018-08-01,2018-08-02)
 2018-08-02 00:00:00+00 | 2018-08-03 00:00:00+00 |     14 |     14 | [2018-08-02,2018-08-03)
 2018-08-03 00:00:00+00 | 2018-08-04 00:00:00+00 |     14 |     14 | [2018-08-03,2018-08-04)
```

**Comment by serge-rider** [comment]
AFAIK there is no such connection parameter for PostgreSQL.
But you can set client timezone for whole DBeaver process by adding -Duser.timezone parameter in dbeaver.ini or passing it in command line.
```
-Duser.timezone=UTC
```

**Comment by KES777** [comment]
As workaround , I think, it will be OK.

But with `SET TIME ZONE 'UTC'` there is another issue.

If I want to set different timezone for a session/local I run next SQLs:

 1. BEGIN
 2. set local time zone 'UTC'
 3. select * from consumed_resource

And the last query return dates not in 'UTC'

**Comment by jbrechtel** [comment]
@KES777  the issue is that DBeaver is formatting the time to your user timezone and then *HORRIBLY* not including the offset or timezone abbreviation in the output. You should see a timezone abbreviation in the bottom of your status bar that indicates this. This results in *very* confusion output from UTC datetimes from PostgreSQL as you're running in to.

I've not been able to affect the `user.timezone` system property with DBeaver command line arguments in Linux.   


```
export JAVA_OPTS="-Duser.timezone=UTC"
export _JAVA_OPTS="-Duser.timezone=UTC"
dbeaver -vmwargs -Duser.timezone=UTC
dbeaver -vmwargs=-Duser.timezone=UTC
dbeaver -vmwargs="-Duser.timezone=UTC"
```

will all result in DBeaver still reporting the timezone as "EST" upon startup and formatting `Timestamps` accordingly.

The only way I've found that can actually change DBeaver's timezone is by editing the *system* dbeaver.ini file to add `-Duser.timezone=UTC`

It would be a much less confusing default if DBeaver would at least put the timezone name or offset that it is applying to datetime/timestamp values when formatting them.

**Comment by serge-rider** [comment]
DBeaver doesn't show timezone for particular timestamp values because PostgreSQL doesn't provide such information.
But you can see current client timezone in the status bar:
![image](https://user-images.githubusercontent.com/6398845/45448444-01421080-b6db-11e8-93d9-dcd891ca8e53.png)

Regarding command line - it should be `dbeaver -vmargs -Duser.timezone=UTC`
JAVA_OPTS variable has no effect for DBeaver.

**Comment by jbrechtel** [comment]
@serge-rider Thanks! I see my typo now. 🤦‍♂️

**Comment by jbrechtel** [comment]
@serge-rider 

   DBeaver doesn't show timezone for particular timestamp values because PostgreSQL doesn't provide such information.

I don't understand. I'm suggesting that DBeaver's timestamp formatting simply include the UTC offset that *DBeaver* is applying to the timestamp when *DBeaver* formats it. I'm suggesting that default data format for date values be `yyyy-MM-dd z` instead of `yyyy-MM-dd`. This can already be changed by a user from the Preferences dialog via `Database -> Result Sets -> Data Formats`. 

The current default is very misleading because it is not obvious (despite the timezone abbreviation in the toolbar) that the user is seeing a `Timestamp` values in their local time.

**Comment by serge-rider** [comment]
@KES777 EEST time zone is a bit tricky (as it is the same as EET but for Summer time). However actual time shift should be correct.
Passing `-Duser.timezone=EEST` parameter will convert local time zone to GMT+3 (this is some Java magic, I'm not sure that this is the best behavior but I can't affect it).

**Comment by jbrechtel** [comment]
@serge-rider Displaying the value in UTC would also result in less confusion IMHO.

The problem, to me, comes into play mostly if set my session timezone to UTC (the same way that @KES777 did in their original example) and then insert a date

`insert into foo values ('2018-08-08T12:00:00')`
then run
`select * from foo`
and I see
`2018-08-08 08:00:00`

How are users supposed to know that dates are being converted to something other than the timezone that they're stored in? It seems like it'd be better to either not convert them or to show an unambiguous (i.e. with the offset) date value.

This is a solved problem for me by simply changing the date formatting and updating my command line to execute DBeaver with the vmargs flag. I worry about other users that are working closely with dates, though.

**Comment by serge-rider** [comment]
I'm a bit confused now )

@jbrechtel Situation you described shouldn't happen in normal circumstances. Internally PostgreSQL keeps timestamps in UTC timezone. And returns them in UTC timezone. DBeaver shows timestamp values returned by driver as is without any timezone conversions.

Changing client timezone (in command line) shouldn't affect values which are already saved in the database.

In fact I can't reproduce the problem you described. At least with  the recent driver (42.2.3).
And I can't realize how to resolve such problem on DBeaver side.

**Comment by jbrechtel** [comment]
@serge-rider I'm not suggesting that DBeaver is changing the value stored in PostgreSQL.

I'm saying that the combination of the following two facts results in very misleading behavior with DBeaver defaults
- PostgreSQL has a connection-specific timezone setting which affects how it interprets `timestamp` values
- That connection specific timezone settings can be out of sync with the `user.timezone` System property which affects the timezone that DBeaver translates Postgres's UTC `timestamp` values into

To recreate the scenario I'm describing simply launch DBeaver with a `user.timezone` of something other than UTC (anything with a non-zero UTC offset will do). Potentially your system default is already suitable.

Here's the problematic SQL
```
set time zone 'UTC';
create table foo (mydate timestamptz);
insert into foo values ('2018-08-08T12:00:00');
select * from foo;
```
I'm in `EST` and I see `2018-08-08 08:00:00`.

The value you'll see (presuming your `user.timezone` system property is not one with a 00:00 UTC offset) will NOT match the literal you entered. Even IF you specify a `+00:00` offset in your `timestamp` literal then the selected value from the last line will not display as you expect because DBeaver is converting it to your `user.timezone`.

At the end of the day it simply seems misleading to convert a zero offset value to a non zero offset value and *not display the offset you've applied*.

**Comment by KES777** [comment]
@serge-rider
>And returns them in UTC timezone

Postgres does not return timestamp in 'UTC' it return in what 'timezone' setting is
```
select current_setting( 'timezone' );
 current_setting 
-----------------
 US/Central
(1 row)
```
When the client connects to server it MUST setup/adjust connection setting to its timezone. Thus if DBeaver detect that current system timezone is 'EEST' it MUST setup `timezone` connection setting to it. https://www.postgresql.org/docs/10/static/sql-set.html

Thus in DBeaver you must not do any math for timestamps. The postgres will do all for you.

**Comment by serge-rider** [comment]
Since 5.2.3 we support native date/time formatting. This should resolve big part of problems with timestamp conversions.
Could you check it? (in any recent version)

![image](https://user-images.githubusercontent.com/6398845/47922575-73a7c380-dec8-11e8-98a8-61b344eeed3c.png)

**Comment by KES777** [comment]
@serge-rider Would be cool if you post how to find this preferences.

**Comment by KES777** [comment]
@serge-rider 
1. compare for example how preferences are implemented in FF on windows and linux.

2. Would be cool if all preferences are available at once

**Comment by serge-rider** [comment]
This is no clear. We have global and connection-specific prefs. 
I don't see how it is possible to show them at once.

I don't think that we can compare DBeaver prefs to FF (or Chrome). We have many more prefs + global/connection prefs. 
Also some people (including me) don't like prefs organization in FF/Chrome, it is very hard to find something there without using search.

I'm not saying that prefs organization in DBeaver is perfect (it is definitely not) but if we want to improve it then we need some particular suggestions. And a separate ticket :)

**Comment by Mynameismynameis** [comment]
Hello @KES777 and @serge-rider : could you see my problem #8297 and tell me if you have an idea to answer my question (posted today) ? ► https://github.com/dbeaver/dbeaver/issues/8297
