### ISSUE TITLE
SQL Server: Stored procedure not refreshed after drop/create; hangs when trying to manually refresh

### ISSUE THREAD

**Issue by anophelesgreyhoe** [dbeaver/dbeaver#4184]
SQL Server 2014 - 12.0.2000.8 (X64)
DBeaver 5.2.0

NB: This is an issue that I think has applied to multiple recent versions of DBeaver.

After dropping and re-creating a stored procedure, then opening it from the DB navigator, the source doesn't update. I then press F5 to refresh the view and DBeaver hangs with "Load SQL source" and the animated 'action in progress' indicator at the bottom right. These 2 indicators remain as I navigate around the database, query windows, etc.

After this, other operations in the same database also hang, such as opening the _dbo_ schema and pressing F5 to refresh objects.

Could it be that on dropping and recreating the stored procedure, the cached element for that SP is no longer valid, causing DBeaver to choke? The only way I know of to fix this is to disconnect and reconnect to the database.

**Comment by serge-rider** [comment]
I can't reproduce the hanging. However it may happen if you work in transactional mode. You need to perform Commit after saving the procedure. Otherwise refresh will stuck forever, waiting for another transaction to finish.

Workaround: disable "Open separate connection for metadata read" option (on Metadata preference page)
