### ISSUE TITLE
Discover Owner Identity - Slow

### ISSUE THREAD

**Issue by dabocla** [dbeaver/dbeaver#4193]
![image](https://user-images.githubusercontent.com/1686584/45365236-b40e5380-b5a1-11e8-9916-7b2ed085cb0c.png)

I would like to know what's going on here, and why it's taking so long.  In my last session, this took 800 seconds.

I'm currently connecting to a vertica database. 

If I can provide any additional details, I would love to.  This is currently preventing me from being productive with this otherwise fantastic database client.

Kindest regards...

**Comment by serge-rider** [comment]
Do you use the most recent DBeaver version? We have fixed performance issue in Vertica in #3981

If it is still slow in 5.2.0 - could you check what exactly query is executing during metadata read? You can see it in Query Manager view (enable all object types and query types in query manager filter settings).

**Comment by serge-rider** [comment]
Thanks for details.
Could you check how simplified query `SELECT p.*,c.comment FROM v_catalog.projections` works? 
If it is still slow then we'll need to remove projections reading from default configuration.

Actually I can't realize why it is slow (in our test DB we have a few projections and it works very fast). Maybe it depends on Vertica service version though.

**Comment by dabocla** [comment]
That query by itself is referencing comments, is that the full query that you want me to run?  Should I remove the reference to comments?

**Comment by serge-rider** [comment]
Sorry, it should be `SELECT * FROM v_catalog.projections`.

**Comment by dabocla** [comment]
Took about 10 seconds.

More details for you:  Vertica Analytic Database v8.1.1-14, 40 node cluster.

**Comment by serge-rider** [comment]
Thanks.
Generally we shouldn't read projects without explicit request so this is a bug.

**Comment by dabocla** [comment]
Thank you, and I appreciate the quick responses.

**Comment by jonmarksearle** [comment]
This issue appears to have been solved a number of times, but it's still occurring on AWS Athena.  What work-arounds where used previously? Is there a setting that we can use to turn off the "discover owner entity" process?

**Comment by dertodestod** [comment]
@jonmarksearle 
I was able to fix this by unchecking this checkbox (second one gets grey/inactive automatically):
![image](https://github.com/dbeaver/dbeaver/assets/72194738/51c7179a-0769-4583-a896-501912d3f043)

See also this comment https://github.com/dbeaver/dbeaver/issues/11338#issuecomment-781237475

I haven't seen any downsides so far. I don't think `foreign key navigation` for Athena works anyways and not sure what `results edit` is about. If someone can find a downside please let me know.

**Comment by SU-R27** [comment]
The option to disable "Read table metadata" is missing on the latest version (24.1.1)

![image](https://github.com/dbeaver/dbeaver/assets/56205113/1b84f87a-43e5-4b9a-837e-24e9956899ef)

**Comment by yippikayeSD** [comment]
> The option to disable "Read table metadata" is missing on the latest version (24.1.1)
> 
> ![image](https://private-user-images.githubusercontent.com/56205113/342445783-1b84f87a-43e5-4b9a-837e-24e9956899ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzYzMjcsIm5iZiI6MTcxOTQ3NjAyNywicGF0aCI6Ii81NjIwNTExMy8zNDI0NDU3ODMtMWI4NGY4N2EtNDNlNS00YjlhLTgzN2UtMjRlOTk1Njg5OWVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA4MTM0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4ZjgxNmJkYTIzN2M1ZDc5NDUxMTlmNTI1N2JkNjFmZDZlYThjMmNkODk1ZmZhZjFmMDkxMjc3YTU1ZjFkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ALKWWJ9lbSJHltgj3K-WK__2jsckKTKV044gn8rYbMg)

Does anyone know how to disable this on 24.1.1?

**Comment by martindelaherran** [comment]
Same issue here - with BigQuery it gets stuck on discover owner entity.
It seems like a regression - on 24.0 the option "Read table metadata" is there but not on following versions, and with that option un-selected I can work with BigQuery properly (else results get stuck on the "discover owner entity" phase like in 24.1)

**Comment by dertodestod** [comment]
> Same issue here - with BigQuery it gets stuck on discover owner entity. It seems like a regression - on 24.0 the option "Read table metadata" is there but not on following versions, and with that option un-selected I can work with BigQuery properly (else results get stuck on the "discover owner entity" phase like in 24.1)

I think this was changed in https://github.com/dbeaver/dbeaver/issues/23203#issuecomment-2061113653 (PR should be https://github.com/dbeaver/dbeaver/pull/34255). 

I think the settings were a bit 'streamlined' and moved to the 'Metadata' tab:
![image](https://github.com/dbeaver/dbeaver/assets/72194738/8ee663fc-ed14-47ae-affc-d2813d718906)

Can you try this setting and see if it works for you? It helped for me.

**Comment by martindelaherran** [comment]
Yes, it seems to work. But if I use that, intellisense/autocompletion is mainly lost.
The case is, with the "do not read tables information...." not checked, sometimes the wait upon "discover owner entity" and "discover attribute" does indeed finish, and in that case things seem to continue working well. It is not always consistent (when it does not work, a restart generally solves it), but I'll see if I can continue working as it is.

What i have done by the way is manually making sure that in the file workspace6\.metadata\.plugins\org.eclipse.core.runtime\.settings\org.jkiss.dbeaver.core.prefs , put the following to false as in the previosu 2.4.0 version. 

resultset.read.metadata=false
resultset.read.references=false

Maybe that helps others too? Because that setting is diferent from the overall "do not read tables information..." right?

Thanks!

**Comment by dertodestod** [comment]
> Yes, it seems to work. But if I use that, intellisense/autocompletion is mainly lost. The case is, with the "do not read tables information...." not checked, sometimes the wait upon "discover owner entity" and "discover attribute" does indeed finish, and in that case things seem to continue working well. It is not always consistent (when it does not work, a restart generally solves it), but I'll see if I can continue working as it is.
> 
> What i have done by the way is manually making sure that in the file workspace6.metadata.plugins\org.eclipse.core.runtime.settings\org.jkiss.dbeaver.core.prefs , put the following to false as in the previosu 2.4.0 version.
> 
> resultset.read.metadata=false resultset.read.references=false
> 
> Maybe that helps others too? Because that setting is diferent from the overall "do not read tables information..." right?
> 
> Thanks!

From what I have seen, the time it takes for "discover owner entity" depends on how many tables you have in the schemas/databases which the SQL is using and/or how your query engine is detecting (e.g. DESCRIBE, SHOW) these tables. Once it finishes, it will work for this table until the connection is reset. But for us, for some queries it can make a difference of minutes so disabling these metadata queries was really important for our users as a query which takes 1 second in Athena might take minutes to come back in DBeaver which is obviously a big issue.

I wasn't aware of this disabling auto-completion (which I think did not happen before) and as this version was pushed to our users in the last days we will now get many complaints I assume. To me this does indeed look like a regression because before we could at least keep the auto-completion and its metadata queries if we wanted them.
