### ISSUE TITLE
Plugins added to DBeaver eclipse framework are removed on new install

### ISSUE THREAD

**Issue by kiravi** [dbeaver/dbeaver#4207]
5.2.

Adding support for an eclipse plugin in DBeaver is removed on running windows executable to update installation.

**Comment by serge-rider** [comment]
If you use Windows installer or MacOS pkg then yes, installer removes previous version completely. It is made on purpose because quite often old plugins will become incompatible with new DBeaver API.
And this may produce tons of hard-to-reproduce bug reports.

So, basically it was done purpose to simplify our (developers) life. Hopefully will have more resources in future and will freeze API at least for optional extensions.
