### ISSUE TITLE
DBeaver convert my text to uppercase automatically

### ISSUE THREAD

**Issue by len-ny** [dbeaver/dbeaver#4212]
Whenever I 'Create New Table' or 'Create New Column', the gui will change the table/column name (which I typed with lower case) to upper case. Even though I go back to the 'Properties' tab to change, it still reverted to uppercase. In Preferences>SQL Editor>SQL Completion, I had changed the insert case from 'Default' to 'Lower case' & unchecked the 'Convert keyword case' of SQL Formating. But it doesn't help.    
How can I stop this auto conversion?
FYI I used DBeaver 5.2.0 Community & H2 1.4.197 Embedded.

**Comment by serge-rider** [comment]
In H2 all identifiers are stored in database in upper case. It doesn't matter how you specify them in DDL - they will be converted in upper case by server (or by embedded SQL engine).
If you want to create a table/column in lower case or you want to use any special characters, spaces, etc - use quotes. So table name will be "newtable".

Note, that you application will need to use quotes as well, otherwise engine won't find this table/column.

**Comment by Ethelber** [comment]
The automatic upper case of identifiers is great, except when it's in a comment. Could DBeaver recognize a comment and not do the automatic upper case?
