### ISSUE TITLE
ENUM types not available Postgres Mac

### ISSUE THREAD

**Issue by inventionlabsSydney** [dbeaver/dbeaver#4216]
DBeaver Community Edition	5.2.0.201809092115.
Postgres version: 10

When trying to create tables in DBeaver, trying to add an enum column type results in 
![screen shot 2018-09-14 at 12 28 49 pm](https://user-images.githubusercontent.com/2543079/45526456-7700c600-b81a-11e8-9549-25e17593e549.png)

How can I add enums?
Thanks,
Karl.

**Comment by lemon-juice** [comment]
This problem is not only on Mac, it looks like DBeaver doesn't support creating enum columns in Postgres. But you can create enums manually (it's pretty easy) and once you do that DBeaver will work with them very well.

First of all, in Postgres you don't create enum types like in MySQL, so you cannot add a column of type `enum` to your table. First, you have to create a an enum data type for your schema, name it as you wish, and then you can use that data type in all your tables in the schema. This a 2-step process but is more powerful than enums in MySQL.

For example, let's create an enum data type and name it `device_status`:
```sql
CREATE TYPE public.device_status AS ENUM
    ('on', 'off', 'suspended');
```
Once you do that you can add columns to your tables in DBeaver - when creating a column simply type `device_status` as the data type and it will work fine.

`device_status` will now appear under the Data Types item in the schema object tree - you will be able to view it but not change it or delete it. This might be a feature request to support creating and altering data types.

**Comment by inventionlabsSydney** [comment]
I should have realised that, I've been using Postgres for a few years now and I feel like I have had a brain fart! 🥇

**Comment by uslss** [comment]
seems issue duplicates #72
