### ISSUE TITLE
Unnecessary error window when you stop a query

### ISSUE THREAD

**Issue by offstate** [dbeaver/dbeaver#4227]
Could you please hide the error window that appears when I stop a query execution. It has no purpose, just waste time to close.

![default](https://user-images.githubusercontent.com/16996529/45604091-5fbd1500-ba74-11e8-9820-4d1fe140f64d.png)

**Comment by serge-rider** [comment]
This is controversial. Sometimes you need to know for sure how did query ended (no data returned or it was just canceled).
I can try to suppress all "request canceled" errors (although this can't be done in a universal way because many driver just don't support standard SQL states). But this can make life more complicated for some people..

**Comment by offstate** [comment]
We can move such errors to notification pop-up (option in config), but there is a problem.
If result section contained some data from previous execution you can miss the notification and take old result as new. 

I just wanted the app doesn't tell me what I have just done. If it's too much trouble, I'll tolerate

**Comment by antoniodemora** [comment]
Is there any way for the notification pop up to show a link which opens a frame/dialog showing the data returned? I'm looking for my first issue, so I think this is a good starting point.

**Comment by maln0ir** [comment]
In case of scripts _Execution Log_ tab may be used instead of notification popup. Just make it open automatically on error.
