### ISSUE TITLE
date format

### ISSUE THREAD

**Issue by omni123** [dbeaver/dbeaver#4228]
Hey,
I've got the newest version of DBeaver (Version 5.2) and got a problem with the date format. I've got it set to "dd.MM.YYYY" and in the older versions it worked fine. But now I've seen that if I filter a date it sometimes switches the values of date and month. For example: The real date is "2018-07-02" and in the result set it shows "07.02.2018" and if I filter it goes for "2018-02-07" (which is shown in the result set) and shows me totally different data, because it's a different date.

**Comment by serge-rider** [comment]
In filter DBeaver uses native database data format (if it can determine it). Because your custom format won't work on the server side. Generally filter must work correctly (although it differs from the date format you see in results).
Maybe I'm missing something but I can't figure out how it may work with your custom format.
BTW what is your database?

**Comment by omni123** [comment]
I'm using a MS SQL Express Server.

I've tried to understand the problem a bit more and I discovered that the filter works fine if I just want to filter a date that wasn't converted. But if I convert something it doesn't work. If the day is less than 13 it just switches the day and month (for example it shows the 11.January instead of the 01. November). If the day is greater than 12 it shows the right date in the result set but if I want to filter it shows an error (can't convert varchar to date).

This is the function I use:

convert(datetime,dateadd(day,datediff(day, '1899-12-30', sh.ABFAHRT),t.DATUM),104) as FAHRT_DATUM

In older Versions of DBeaver it worked just fine.
