### ISSUE TITLE
No execution feedback with multiple tabs

### ISSUE THREAD

**Issue by premyslc** [dbeaver/dbeaver#4274]
For example. I have two tabs with result set and second tab is active and pinned. When i execute query (Ctrl + Enter), then i don't have feedback about execution because, it is executing hidden on first tab.
Same situation is with "Server output console". It's little confusing.

**Comment by serge-rider** [comment]
First problem (with pinned tab) is a bug. It will be fixed in the next version, thanks for the bug report.

Server output console is different. It was made on purpose - sometimes you need to execute queries and monitor server output they produce. Auto-switching to results tab will make this very inconvenient. just hide output if you don't need it.
