### ISSUE TITLE
Feature request : replacing Oracle JAVA with OpenJDK

### ISSUE THREAD

**Issue by Petrouchka** [dbeaver/dbeaver#429]
Are you planning to replace JAVA.COM with Zulu http://www.azul.com/downloads/zulu/zulu-windows/ (OpenJDK version of Azul System) or with https://github.com/alexkasko/openjdk-unofficial-builds ?

**Comment by carlosjrcabello** [comment]
Hi there,

I think that's not a good idea, does it JDK implementation free or LTS?

Actually, let's dbeaver switchable to Oracle JDK and OpenJDK much better.
But you can also use version without JRE embedded.

On Mon, May 9, 2016 at 5:21 AM, Petrouchka <notifications@github.com> wrote:

> Are you planning to replace JAVA.COM with Zulu
> http://www.azul.com/downloads/zulu/zulu-windows/ (OpenJDK version of Azul
> System) or with https://github.com/alexkasko/openjdk-unofficial-builds ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/serge-rider/dbeaver/issues/429>
>



-- 
Atenciosamente,
Carlos Alberto Junior Spohr Poletto

carlos.inf.br

**Comment by Petrouchka** [comment]
Zulu is a implementation of Oracle OpenJDK made by Azul System company. It is free software.

**Comment by serge-rider** [comment]
It is possible but what's the point?
Oracle JRE is free to redistribute and it is a reference Java implementation.
If, for some reason, Oracle JRE isn't good enough then you can disable JRE installation in installer (or download zip archive) and run DBeaver with your system default JRE.

**Comment by Petrouchka** [comment]
Oracle JRE isn't a free software, as OpenJDK. Zulu and Alex KASKO OpenJDK are the only Windows version of OpenJDK. They work together on it and sometimes solve issues on OpenJDK.

**Comment by serge-rider** [comment]
Oracle JRE is definitely not open source and not free in terms of GNU.
But you can freely use it without any payments/charge.
However Oracle license has some export restrictions, some US laws restrictions and some other lame restrictions. These restrictions could be a problem for some users.
From the other hand DBeaver doesn't depend on Oracle JRE, you can use your system default JRE so I don't see a real problem here.

One thing which stops me from replacing Oracle JRE in Windows installer is that I'm not sure about Zulu quality/compatibility. I don't want to care about potential bugs in JRE. 
But you could try to convince me ;)

**Comment by Petrouchka** [comment]
I tried it with Areca Backup, FAR, Freeplane, Globonote, OpenConcerto and other free softwares and it works fine. I will distribute it in next version of my free software compilation : http://www.numopen.fr/compilibre-en
It doesn't work with FullSync but Azul System is working on it.

**Comment by serge-rider** [comment]
Yeah, I know. Java 10 means Java 10+. Hopefully 11 will be released at that moment.

**Comment by p91paul** [comment]
I dislike Azul since I saw one of their members publicly discredit the work of the Debian community just to promote their product. Relevant link: https://blog.takipi.com/running-java-on-docker-youre-breaking-the-law/ (see the discussion between me and Gil Tene in the comments, the article is about something else). The way he behaved, not even going against another company, but going against a not for profit organization which did nothing bad...I found that terribly disturbing. However, the competition here is Oracle which motto is "be evil" so...

**Comment by serge-rider** [comment]
Yep. 
After all it is OpenJDK. We don't have much choice here.

**Comment by georgethemarmot** [comment]
FYI
Public updates for Oracle Java SE 8 will remain available for individual, personal use through at least the end of 2020. 
Public updates for Oracle Java SE 8 released after January 2019 will not be available for business, commercial or production use without a commercial license.
https://java.com/en/download/release_notice.jsp

**Comment by infectormp** [comment]
As an experiment I replaced bundled JRE with AdoptOpenJDK JRE and do not experience any problems.

**Comment by jniggemann** [comment]
A lot has happened since this issue was raised and there are multiple choices.
I recommend reading https://blog.joda.org/2018/09/time-to-look-beyond-oracles-jdk.html,

Oracle JDK  => no longer free
Oracle OpenJDK => only 6 month of support
SAP SapMachine => longterm support unkown
AdoptOpenJDK builds => 4 years support, GPL, maybe passes TCK ([here they say they don't](https://adoptopenjdk.net/support.html), [here they say they do](https://blog.adoptopenjdk.net/2018/03/jck-certification-and-an-anniversary-of-sorts))
Amazon Corretto => 4 years support, passes TCK, GPL

From my POV it would be best to either use AdoptOpenJDK or Corretto.

**Comment by infectormp** [comment]
https://www.opennet.ru/opennews/art.shtml?num=50532

**Comment by serge-rider** [comment]
Starting from version 6.1.1 DBeaver Windows and MacOS installers will be bundled with OpenJDK 11.
