### ISSUE TITLE
Results panel won't show along side script

### ISSUE THREAD

**Issue by jwil100** [dbeaver/dbeaver#4290]
Can't get the results panel to stay pinned when I use dbeaver. Tried toggling and maximizing the results but still can't get it to show underneath the script. it creates a triangle type arrow to the right of the screen and I can press it and it will show the results in a maximized view.

**Comment by ghenry74** [comment]
I have a similar issue. When I started using DBeaver, I had the query on top and the results panel below the query, and all was well. While working on (or with) a lengthy query, I dragged the top of the results panel down, thinking the drag would stop when the panel was almost invisible, but the panel disappeared entirely. and since then I can display it only in maximized form. I do not want this. I want the original arrangement of panels back. Again, nothing I can find in the DBeaver UI has enabled me to restore the former layout since the results panel disappeared. (The setting illustrated above has no effect on the situation.)
