### ISSUE TITLE
"SQL Editor" command don't open existing scripts

### ISSUE THREAD

**Issue by rafaelmembrives** [dbeaver/dbeaver#4299]
When I press on "SQL Editor" (button or menu), first time create a new script, but on succesive clicks nothing happens but recent script should be opened, isn't it?

I´m using dbeaver-ce-5.2.1-macos version.

Thanks in advance!

**Comment by serge-rider** [comment]
"SQL Editor" (<kbd>F3</kbd>) command creates new script if there are no scripts exist for current connection. Otherwise it shows a dialog like this:
![image](https://user-images.githubusercontent.com/6398845/46213157-83b80a80-c340-11e8-9aad-6e455d8e341a.png)

In order to open recent (last edited) script use "Recent SQL Editor" command (<kbd>ctrl+enter</kbd>).

**Comment by serge-rider** [comment]
I can't reproduce this. Have no clues so far.

Could you check debug/error log (https://github.com/dbeaver/dbeaver/wiki/Log-files) - maybe something is failing.

**Comment by rafaelmembrives** [comment]
The log view don't shows any errors... but I removed .dbeaver4 folder, restarted and configured databases. Now the 'Choose SQL' dialog shows again.

Thank you very much!
