### ISSUE TITLE
Allow manual fetching first result-set in Data tab

### ISSUE THREAD

**Issue by ghost** [dbeaver/dbeaver#4357]
This is to avoid accidentaly running query on big/wide table or heavy view without filters. This is especialy useful on slow connections.

To fetch first result-set you could use progress bar like below, but with different message i. e. _Click to fetch data_. 
![obraz](https://user-images.githubusercontent.com/20753183/46669678-67ce2780-cbd0-11e8-9e09-2ef9153d2182.png)

**Comment by serge-rider** [comment]
Could you please clarify. As I see you fetch all data manually or you set fetch size to zero (i.e. this was not done accidentally).
So I'm a bit confused. What exactly are you proposing?

**Comment by maln0ir** [comment]
DBeaver remembers last selected tab in object definition window, so for example if previous table/view window was opened on Data tab, new one also opens on this tab and DBeaver automatically runs query to fetch some data from this table/view - first 200 rows by default.

This automatic behaviour sometimes makes trouble, because:
- you may work on slow connection and don't really want to query data from table or view just because DBeaver opened Data tab first.
- you may work with large amounts of data and don't want accidentaly run query on views that, for example, aren't designed do be queried with `select *` without conditions.

So, I propose to add an option to disable running query automaticaly when Data tab is opened.

> As I see you fetch all data manually or you set fetch size to zero (i.e. this was not done accidentally).

I fetched all data from some table just to make that _progress bar_. The point was that if table grid is not displayed yet, you could reuse that _progress bar_ in different context (if you can).

**Comment by uslss** [comment]
will be tracked in #7151
