### ISSUE TITLE
Tab title resets on refresh

### ISSUE THREAD

**Issue by powelleric** [dbeaver/dbeaver#4459]
On a previous version, if I set the tab title, then I refresh the result set (F5), the tab title would stay.  Now, when I refresh, the tab title goes back to 'Results...'.

I like the old way because I can keep several common queries pinned and titled.  Then, if I want to check for new changes I just refresh that tab.  It is kind of like a dashboard for me.

Thanks for all your amazing work!  I love dbeaver :)

**Comment by BobKnip** [comment]
This is also/still an issue in DBeaver version 6.0.5.201905192012 . 

When you refresh the result set (with the corresponding button, or by changing the filter), the set name is replaced by (apparently) the first table in the FROM statement of the query that created that result. 

Example: I work with multiple subsequent queries/views to break down a complex calculation. When creating/debugging the next view, I pin any previous views it uses, and set the names of the corresponding tabs to the names of those views. This name resetting is very confusing, especially because what is shown afterwards is also the name a view (from even earlier), apparently the first table in the FROM statement. 

TESTED: This behavior occurs regardless of whether you pin the tab or not, and regardless of whether you pin the tab before or after setting the tab title. 

(BTW: I think automatically setting the tab title to the first table in the FROM is about the most unfortunate and confusing choice possible to begin with. Possibly just use an increasing number or a timestamp per query/refresh. Set title only first call: tab title stays the same; (re)set on every call: tab title changes - matter of taste which is best.)

**Comment by powelleric** [comment]
Regarding the setting of the tab title:  In case you didn't know you can
control the auto tab title by putting this (comment) on a on a line just
before the query itself.  Hope that helps a bit.

-- name: MyTitle

**Comment by BobKnip** [comment]
> Regarding the setting of the tab title: In case you didn't know you can control the auto tab title by putting this (comment) on a on a line just before the query itself. Hope that helps a bit.
> […](#)
> -- name: MyTitle

That is indeed somewhat useful. Thanks. 
However, the tab title is still replaced when you apply a filter to the results.

**Comment by uslss** [comment]
verified
