### ISSUE TITLE
FR: right-aligned numbers in the plain-text view

### ISSUE THREAD

**Issue by dejlek** [dbeaver/dbeaver#4512]
I find plain-text view very useful when I have data to share on Slack/IRC with colleagues. However, at the moment numbers are left-aligned and it is causing confusion...

Look at the example:

    2018-10-10 |3,066,827 
    2018-10-11 |1,210,524 
    2018-10-12 |1,085,641 
    2018-10-13 |2,219,962 
    2018-10-14 |1,435,806 
    2018-10-15 |869,495   
    2018-10-16 |928,310

It gets even more messy when we have fractions.

So, could we please have ability to configure the view so the numbers are right-aligned?

**Comment by jetzerb** [comment]
Right-aligning numeric data would be an improvement, and works great for integers and columns with a fixed number of decimal places, but if possible, alignment on the decimal point is preferred:

Example (executed against MSSSQL):
```sql
select * from (values (1234.5678),(cast(12.3 as float))) num(val);
```
Plain text results are currently left-aligned and look like this, similar to what @dejlek shows above:
```
val       |
----------|
1234.5678 |
12.3      |
```
Right-alignment would look like this, and wouldn't be much better in this case:
```
val       |
----------|
1234.5678 |
     12.3 |
```
Aligning on the decimal point is ideal:
```
val       |
----------|
1234.5678 |
  12.3    |
```
Implementing this may be more difficult since the amount of left-padding to add can't be determined without inspecting every row in the resultset.  But, should be doable since something similar is already done with string-based results:
```sql
select * from (values ('foo'),(cast('The quick brown fox jumps over the lazy dog' as varchar(1000))))dat(val);
```

```
val                                         |
--------------------------------------------|
foo                                         |
The quick brown fox jumps over the lazy dog |
```

**Comment by dejlek** [comment]
Yep, I agree - aligning real numbers on decimal point would be great as well!

**Comment by serge-rider** [comment]
Right-justified number and date/time values will be supported in 5.2.5.

Aligning on the decimal point won't be supported for now (it is tricky indeed). Anyone who is interested - check printGrid method in PlainTextPresentation class (https://github.com/dbeaver/dbeaver/blob/78fc4fdf0b53e25e000bc4d617ce2aea54b3e306/plugins/org.jkiss.dbeaver.core/src/org/jkiss/dbeaver/ui/controls/resultset/plaintext/PlainTextPresentation.java#L248)

**Comment by jetzerb** [comment]
@serge-rider: I'm trying to follow the instructions for [developing in Eclipse](https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse), but am running into some problems.
On step 9, very few boxes are checked:
![image](https://user-images.githubusercontent.com/36859020/49195262-f1d27b00-f34b-11e8-821a-be993909aff5.png)

Then, after clicking "Finish", I get an error
![image](https://user-images.githubusercontent.com/36859020/49195311-2b0aeb00-f34c-11e8-97cf-8cdcbf9de59c.png)

Something to do with the Community Edition vs the Commercial Edition?

Can you clarify? If not, all the changes to be made are in the one file. I can get by just a text editor. I verified that the build instructions work (running `mvn package` from the commandline).

thanks
--Bill
