### ISSUE TITLE
Password Handling in Driver Properties

### ISSUE THREAD

**Issue by jetzerb** [dbeaver/dbeaver#4527]
I use DBeaver to connect to MS SQL Server via Windows Authentication.  I do this by checking the "Windows Authentication" box and then entering my DOMAIN, PASSWORD, and USER in the _Driver Properties_ section.

There are several problems related to the password:
1. The PASSWORD value is displayed in plain text here, instead of obscured as a series of dots like on the main connection properties section. Any co-workers looking over my shoulder in our open floor plan office space can see my network password: ![image](https://user-images.githubusercontent.com/36859020/47863847-4377fc00-ddc6-11e8-8313-0236699332b9.png)
1. The PASSWORD value is stored as plain text in `.dbeaver-data-sources.xml`, as pointed out in #3066.  This is less of an issue, because I can lock down the permissions on that file, but I still worry.
1. For the above reasons, I tried leaving the PASSWORD value blank, but then I got a generic error message `Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.`  Issue #3460 asks that DBeaver prompt for username and password if missing.  I believe that issue specifically refers only to the fields on the main connection properties section 
![image](https://user-images.githubusercontent.com/36859020/47865398-188fa700-ddca-11e8-9d58-991c2d2bbbb6.png)
but it would be great if it applied to the username & password in the _Driver Properties_ section as well, as a workaround to items 1 and 2 above.

**Comment by serge-rider** [comment]
Generally I agree that keeping password as plaintext is a very bad idea. But I don't understand why you don't use standard password field on the connection property page. 
Driver properties isn't the right place for password. Is this because of some specific SQL Server configuration?

For this particular problem I could mask all driver properties with "password" string in the name but this won't cover all possible cases if secured data in properties.

**Comment by jetzerb** [comment]
This is for _**Windows Authentication**_, not SQL Authentication.  AFAIK, the only way to utilize Windows Authentication is
1. check the box on the connection property page, which _disables username & password_
1. go to the driver properties and specify DOMAIN, USER, and PASSWORD

If I'm doing this wrong, please let me know.

**Comment by serge-rider** [comment]
Well, if you are on Windows then you can just check option "Windows authentication": 
![image](https://user-images.githubusercontent.com/6398845/47879260-37755400-de31-11e8-9a48-885ea8b109c6.png)

Otherwise you could try to set `integratedSecurity` to true in driver properties. + set `DOMAIN` in driver properties.
And specify user name/password in appropriate connection fields.

**Comment by jetzerb** [comment]
Ah, sorry.  I'm running DBeaver on a _Linux_ machine that is not integrated into any windows domain.

Having the ability to specify different Windows credentials for each connection while running a single instance of DBeaver is very convenient.  Using [SSMS](https://docs.microsoft.com/en-us/sql/ssms/sql-server-management-studio-ssms?view=sql-server-2017) on windows, the only way to connect to multiple servers with different Windows credentials is to launch multiple instances using the "run as different user" option.

**Comment by serge-rider** [comment]
Agreed. Moving to 5.2.5. Actually maybe we should make some special UI for that (keeping passwords in properties is still a bad idea).

**Comment by serge-rider** [comment]
I'll add masking of `*password*` properties. It is the easiest solution for now.
Then we'll improve this in #4552
