### ISSUE TITLE
Dbeaver 5.2.4 - Foreign keys doesn't appear anymore in the new version.

### ISSUE THREAD

**Issue by 15avr74** [dbeaver/dbeaver#4575]
Hello,

I have just updated my dbeaver version (from 5.1.2 to 5.2.4) and have noticed that's not more possible to view foreign keys

I'm connected to the same database and used the same driver DB2 z/OS driver for the both versions.

![image](https://user-images.githubusercontent.com/13747991/48187784-68c3b780-e33c-11e8-937a-1413b7515342.png)

![image](https://user-images.githubusercontent.com/13747991/48187990-dbcd2e00-e33c-11e8-984d-c7a120823613.png)

![image](https://user-images.githubusercontent.com/13747991/48188149-56964900-e33d-11e8-949c-ee7cb28e459c.png)

**Comment by serge-rider** [comment]
It is a bug in recent version, DB2 z/OS driver is incorrectly configured. This will be fixed in the next version, thanks for the bug report.

As a workaround you can fix config manually in the driver editor dialog: 
![image](https://user-images.githubusercontent.com/6398845/48245866-1fd43780-e3fe-11e8-8aea-e818bd08fb8d.png)

**Comment by 15avr74** [comment]
Thks @serge-rider
