### ISSUE TITLE
DBeaver: Download of SQL Server jTDS driver broken in DBeaver 5.2.5

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4641]
DBeaver - **Version 5.2.5 CE**
DBeaver JDBC driver: **jTDS Driver**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014**

**o** Start _DBeaver_ and create a new SQL Server connection using the **jTDS Driver**

**o** Try to connect.

**o** The drivers try to download, but that result in an error message:

Error resolving driver libraries
```
Reason:
Error resolving dependencies.

Error resolving dependencies.
Maven artifact 'maven:/net.sourceforge.jtds:jtds:RELEASE' not found.
```

**Comment by serge-rider** [comment]
I can't reproduce this (on fresh machhine). Sometimes such error may happen due to some network issues.

Could you restart DBeaver and try again? Can you download any other driver?

**Comment by nanny07** [comment]
I also had this problem, but after restarting DBeaver it downloaded correctly the driver.
Now the question: why it prompted us a new release of the driver when the last one was done on 2013?

And something must be changed because when I try to execute a query, the result are all like this instead the real value:
![image](https://user-images.githubusercontent.com/17173586/48780710-d37cd780-ecda-11e8-9c7c-5a152e23f170.png)

**Comment by serge-rider** [comment]
@nanny07 At  asks to re-download driver because driver definition was changed in 5.2.5 and DBeaver needs to validate jars.
Problem with Clob values is actually a bug in new extension, thanks for the bug report.

A a workaround you can switch to `SQL Server Legacy` driver (it is the same driver which was used in 5.2.4  and earlier.

**Comment by serge-rider** [comment]
@nanny07 also you can use Microsoft driver (as far as i know it never returns string values in CLOB form).
In fact we plan to deprecate jtds driver for SQL Server (it is way too old and nowadays when MS driver became open source it dosn't make much sense).

**Comment by nanny07** [comment]
> also you can use Microsoft driver

@serge-rider that's what I've done even if I had to manually recreate all the connections because I haven't found a way to change the driver (maybe I'm missing something)

**Comment by serge-rider** [comment]
@nanny07 You can chhange connection's driver using main menu Database->Migrate Connection(s)

**Comment by nanny07** [comment]
@serge-rider thanks you, I was sure I was missing some features

**Comment by pdanie** [comment]
I think the new and the old Microsoft driver collide in some way. If I have one connection of each type in the same _DBeaver_ project they don't live to happily. I have to restart _DBeaver_ after been connected with the old before I connect with the new.

With a bit of luck when _DBeaver_ **5.3.2** is released is a "nothing" problem. There will be no need to use the old driver.

As far as I'm concerned. This isue can be closed.
