### ISSUE TITLE
Cannot Connect My Oracle Database from My Main Machine.

### ISSUE THREAD

**Issue by aiak0s** [dbeaver/dbeaver#4679]
Hello,
Problem,
I'm using Oracle Linux 7.4 operation system on VirtualBox. And my Main Machine's OS is Windows. I can connect my Oracle Database from my Virtual machine.

I can ping to my Virtual Machine from my Main Machine. But i cannot connect my database from my Main Machine.

Thats my error; 
![error](https://user-images.githubusercontent.com/23744523/48972643-a7958500-f03f-11e8-94a3-d7a817a18648.png)

**Comment by infectormp** [comment]
Can you make telnet 192.168.1.31 1521?

**Comment by aiak0s** [comment]
> Can you make `telnet 192.168.1.31 1521`?

How can i do that ?

**Comment by aiak0s** [comment]
> [Test your network connection](https://support.code42.com/CrashPlan/4/Troubleshooting/Test_your_network_connection)

i can access my virtual machine with telnet. But still cannot access my Oracle-DB with DBEAVER.

**Comment by uslss** [comment]
cannot reproduce.
if it is still actual - feel free to reopen

**Comment by enkracken** [comment]
This problem is happening to me now. I have used bridged network adapter in Virtualbox. The problem was exactly as @aiak0s described, but I've Oracle XE 21c on Windows 10 as guest in VM. I've run `lsnrctl` then `start` too. @uslss please tell me how can you connect Dbeaver to Oracle XE in Virtualbox? The host is Kubuntu 22.04
