### ISSUE TITLE
SQL editor: save query results in variable

### ISSUE THREAD

**Issue by Barosky** [dbeaver/dbeaver#4750]
Hello,

I often write insert queries, then copy the inserted id to use it in another insert or update query.
In my opinion it would be useful to have the possibility to assign to named parameters the result of a scalar query. 

For example:
@set **param1** = insert into test_table (field1, field2) values (value1, value2) returning id;
insert into table2 (field1,field2) values (value1, **:param1**)

Best regards,
Cristiano

**Comment by surpavan** [comment]
#4337

**Comment by drawnfallow** [comment]
Is this feature being dropped?  It's been carried over milestone to milestone and now it isn't attached to anything.

**Comment by uslss** [comment]
implemented in #11533

**Comment by cristianodri** [comment]
#11533 does not work for my request https://github.com/dbeaver/dbeaver/issues/4750#issue-388689202

**Comment by uslss** [comment]
@Barosky works for me (picture below, query ends up with an error due to absence of the mentioned tables, but the variable is set and variable value was copied to query)
![image](https://user-images.githubusercontent.com/31996417/141997803-4031b3c3-253c-441f-a39c-bfc3d18c2d5a.png)
in case, the feature doesn't work for you, please create a new issue with steps to reproduce.

**Comment by cristianodri** [comment]
@uslss this one does not work:

@set xx = INSERT INTO test (valore) VALUES ('test') RETURNING id   --valore is a varchar field
SELECT :xx
xx is not set: I think the problem is the string value.

also this one does not work for me:
@set xx = INSERT INTO test (numerico) VALUES (1) RETURNING id   --numerico is an int field
SELECT :xx
in this last case, xx is set, but when I execute SELECT :xx I get this error:
```
Error occurred during SQL query execution

Reason:
SQL Error [42601]: ERRORE: errore di sintassi a o presso "("
  Position: 25
```

So, by the error my understanding is that :xx does not contain the result of the insert, but the whole statement. IMHO this is not the correct behaviour
