### ISSUE TITLE
Add a way to specify WHERE clause when exporting data

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#4833]
When exporting data from table/view/query there is no option to limit amount of data exported. This forces to export data using queries (one by one) or by creating views (this can be problematic when user can't create view).

**Comment by serge-rider** [comment]
You can export from SQL query. Just open SQL editor, set cursor into your query and execute "Export from query":
![image](https://user-images.githubusercontent.com/6398845/50546370-d521af80-0c37-11e9-8cd0-826a01850cba.png)

Also you can export from query execution results:
![image](https://user-images.githubusercontent.com/6398845/50546417-f2567e00-0c37-11e9-8f4a-eeafd1dd65a5.png)

**Comment by p91paul** [comment]
From this statement "This forces to export data using queries (one by one)" I presume the OP means the issue is when you are exporting multiple tables/views at once and you cannot specify a where clause for them. Instead you have to open each table, apply a where condition, then export.

It would be useful to have the possibility to specify where conditions in export wizard (with a way to apply the same condition to all exported tables).

**Comment by maln0ir** [comment]
I checked what is planned for the next release and I think implementing #2855 could be much more flexible solution.

**Comment by p91paul** [comment]
Maybe more flexible, but a bit less convenient

**Comment by serge-rider** [comment]
@p91paul I'm quite sure that WHERE condition won't be enough. Some people will need to use LIMIT conditions (like @maln0ir ) others will need GROUP BY etc. Eventually we'll come to any custom SQL queries.
So I'd better make it possible to export from multiple queries.
