### ISSUE TITLE
Auto marking block for execution (squirrel sql - like)

### ISSUE THREAD

**Issue by maciey** [dbeaver/dbeaver#4869]
I just discovered Dbeaver and must say I love it! 

But there is 1 feature in Squirrel I do really miss here - I call it a**uto block marking for potential execution**. (Sorry I dont know official name)

Let me explain that in detail - assume I have in editor something like:

```
QUERY1;

QUERY2;
QUERY3;
QUERY4;
```

(Multiple queries ended by ';'.  Empty line between Query1 and Query2)
If i've place cursor somewhere in  eg in 'Query3' line, Squirrel will mark entire Query2- Query4 block for potential execution (so I dont need to manually mark 3 lines)

Logic is: auto mark all adjacent lines, ended by ';'. Empty lines (new lines / spaces) breaks block

Would this be possible ?

**Comment by maciey** [comment]
bump...

**Comment by ceinmart** [comment]
I'm also SquirrelSQL user and this feature make a lot of difference on my efficiency on Dbeaver.

My suggestion is in option: **Database -> SQL Editor -> SQL Processing -> Delimiters** 
Change the check : "Blank line is statement delimiter" to a combo box with options : 

- Blank line is statement delimiter
- Blank line is SQL statement block separator

Since these options can't be checked together, they are mutually exclusive.

Where the second option should behave like squirrel , where blank lines separate the statements which should be executed.
