### ISSUE TITLE
DBeaver: Remove annoying popup for SQL script parameter values when moving to next segment

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4887]
DBeaver - **Version 5.3.2 Beta CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver**
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

There is an annoying behaviour in _DBeaver_ if I have a SQL command containing "colon parameters" and I scroll to the next resul set segmenet. Then _DBeaver_ ask for the "colon parameter" values again when I move to the next segment.

My guess is that the **Refresh data on next page reading** property/setting rerun the SQL command, and then _DBeaver_ needs the SQL "colon parameter" values again.

_DBeaver_ ought to remember and use the old SQL "colon parameters" without any need to popup the **Bind parameter(s)** dialog again.

**o** Start _DBeaver_

**o** Change the property/setting **Auto-fetch next segment** to **checked**.

**o** Change the property/setting **Refresh data on next page reading** to **checked**.

**o** Run the SQL command below in a SQL Editor:
```
SELECT * FROM sys.messages
 WHERE message_id < :MessageId;
```
**o** _DBeaver_ pops up the **Bind parameter(s)** dialog.

**o** Enter the value **1000** for th colon parameter **:MessageId**.

**o** Scroll in the result grid beyond the default 200 rows.

**o** _DBeaver_ pops up the **Bind parameter(s)** diaog again.

The unecessary pop up of the **Bind parameter(s)** dialog is really annoying.

**Comment by pdanie** [comment]
Is it possible to get a new EA build? I would like to test it.

**Comment by serge-rider** [comment]
New EA is ready

**Comment by pdanie** [comment]
In EA **02-Jan-2019 09:26** this still **DOES NOT WORK**. 

The **Bind parameter(s)** dialog is still shown multiple times.

**Comment by serge-rider** [comment]
Can't reproduce. 
Maybe you doing it differently, could you post a gif video?

**Comment by pdanie** [comment]
Hmmmm. I made a clean installation, and tried out the EA from **02-Jan-2019 14:26**, and it still fails.

**o** Start _DBeaver_

**o** Change the **global** property/setting **Auto-fetch next segment** to **checked**.

**o** Change the **global** property/setting **Refresh data on next page reading** to **checked**.

![2019-01-02 17-51-45](https://user-images.githubusercontent.com/31191374/50602486-afa2d900-0eb7-11e9-86bf-1a48c7548983.png)

**o** Open a SQL Editor in _DBeaver_.

**o** Execute the SQL command below in a SQL Editor (if you are running **SQL Server**):
```
SELECT * FROM sys.messages
 WHERE message_id < :MessageId;
```
**o** Execute the SQL command below in a SQL Editor (if you are running **PostgreSQL**):
```
SELECT * FROM generate_series(1, 1000)
 WHERE generate_series < :MaxSeries;
```
**o** _DBeaver_ pops up the **Bind parameter(s)** dialog.

**o** Enter the value **1000** for the colon parameter.

**o** Scroll in the result grid beyond the default 200 rows.

**o** _DBeaver_ pops up the **Bind parameter(s)** diaog again.

The above steps when connected to a Microsoft SQL Server fails 100% of the times I try it. You ought to be able to repeat it.

**Comment by serge-rider** [comment]
Yep. The problem is in "Refresh data" option..

**Comment by serge-rider** [comment]
please check in the new EA

**Comment by pdanie** [comment]
I have tried the EA from 02-Jan-2019 17:36 , and **it workes**. Great work!

**Comment by michael95621** [comment]
Hello,

I think I may have found a bug, or really dumb user error on my part and just need some education please.

#### System information: 
- Windows 10 Enterprise Build 17134
- DBeaver Enterprise 6.3.0.202001141657
- Java 8u261

#### Connection specification:
- Netezza Database - Not sure on version, but it's the Db2 one
- NetezzaSQL
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No, just VPN for network

#### Describe the problem you're observing: 

I use the following syntax
@set VAR1 = '12/31/2020'
;
SELECT *
FROM MY_TABLE
WHERE MY_FIELD = :VAR1
;
There is no problem with the above, but if I capitalize the SET command I get the bind parameters box or an error if I try to run just the @SET line of code. It's as if DBeaver doesn't recognize the command. My suspicion without having any insight into the backend workings is either;
1. I'm doing something dumb or missing something obvious and need some help
2. @set and SET are 2 different commands in the backend language for DBeaver, so when I combine @SET it's not able to parse between the two which is why I get an error if I try to run just @SET but no error if I try to run just @set.

Assuming #2 is correct, I believe this would be a bug, as capitalization really shouldn't matter in SQL.

- Michael

**Comment by mrcolumbia** [comment]
I hate to resurrect this but I'm using Version 7.1.0.20200531173 and am having the same issue as OP. In what release version was this fixed?
