### ISSUE TITLE
DBeaver: The Panels -> Count -> Minimum/Maximum should not see (N)VARCHAR column as a numeric value

### ISSUE THREAD

**Issue by pdanie** [dbeaver/dbeaver#4899]
DBeaver - **Version 5.3.2 Beta CE**
DBeaver driver: **MS SQL Server  / Microsoft Driver**, **PostgreSQL Driver**, etc.
Operating System: **Windows 7 / Windows 8.1 / Windows 10**
Database Server: **Microsoft SQL Express 2014, 2016, 2017**

_DBeaver_ group (N)VARCHAR string containing numbers in the **Values** -> **Count** tab for the **Maximum** / **Minimum** function as it was numbers. It should handle them as strings nothing else.

![2019-01-02 20-51-52](https://user-images.githubusercontent.com/31191374/50610200-5eeca980-0ed2-11e9-80bd-cbd2162dc783.png)

If the (N)VARCHAR column contain letters and such, the **Maxium** / **Minimum** function works as expected. Also for DATE, DATETIME etc columns everything works ok.

**Comment by serge-rider** [comment]
This is controversial.
Quite often people keep numbers in varchar columns and it is convenient when strings are converted automatically. Maybe this should be configurable though.

**Comment by pdanie** [comment]
Maybe. In our case we keep social security numbers (12 digits with no separator). Looks really strange when I see the **Maximize** / **Minimize** value. I would count it as a bug.

If people want to handle them as numbers then they ought to save it in INTEGER columns instead or cast the string to INTEGER to have it grouped by _DBeaver_. The current behaviour does not feel logical. This since a VARCHAR column in a resultgrid that contain numbers is not grouped and therefore the maximize/minimize number should neither. No configuration ought to be necessary.

**Comment by serge-rider** [comment]
Unfortunately life is more complicated than a theory.  There are databases like SQLite where don't have strict data types. There are lots of legacy databases which can't be changed (and we can't make people to write custom SQL). There are NoSQL databases which keep data in json-like structures without any type system at all. Et cetera.

In fact I don't see why anybody would use Max/Min function for non-numeric columns and how this may cause any harm..

**Comment by p91paul** [comment]
Varchar max-min does sometimes make sense. Even if they map to numbers. What about fixing the current max-min behavior, as suggested by @pdanie, and provide 2 new calc functions, "numeric max" - "numeric min" with the current behaviour (max and min after conversion to number)?
This way everyone should be able to get the desired result, whereas a global configuration option could be too broad (I might have 2 varchar columns for which I want different behaviours)

I'm suggesting to change the current behaviour and provide new functions because I'd prefer  functions named "max" and "min" to be consistent with sql MAX and MIN functions, but the other way around (provide new functions with @pdanie suggested behaviour and keep current functions untouched) is fine.

**Comment by tati-kru** [comment]
Let's add a special toggle option to switch between numbers and strings.

**Comment by serge-rider** [comment]
![image](https://user-images.githubusercontent.com/6398845/55484428-25425080-5631-11e9-905d-9f07b150b048.png)

**Comment by uslss** [comment]
verified
