### ISSUE TITLE
Question: Oracle SQL parameters like in SQL Developer/PLSQL Developer

### ISSUE THREAD

**Issue by momoie** [dbeaver/dbeaver#4937]
Dear all,

I am new in the community and I have started developing small queries from the local ERP we use in my work. I am used to the SQL syntax of Oracle SQL Developer or PLSQL where you ask for a parameter with the character '&'

For example, if you have a table (SALES) with the columns CUSTOMER and PRODUCT like this:

**CUSTOMER**  ---                      **PRODUCT**
A  ---                                                         1  
B  ---                                                         2
C  ---                                                        3

You can ask with a parameter wich customer do you want to specify like this:

**SELECT * from SALES where CUSTOMER = '&CUSTOMER'**

Where a window is poped up and it asks for the Customer you want to specify. Is the same syntax than the ERP.  The issue is that in DBeaver, which it works incredible good for the rest of the topics I have worked with, it asks for this syntax:

**SELECT * from SALES where CUSTOMER = :CUSTOMER**

Do you know how I can work with the way I mentioned? We have a lot of SQL Queries with this syntax and it would be a nightmare to change everything. Also, ERP does not interpretate this syntax.

Thanks for everything and kind regards.

PD: Sorry if it is a stupid question, I am newbie in this :)

**Comment by pdanie** [comment]
You can try to use the "out of the box" settin/parameter below:

**o** Right click on your Oracle connection in the **Database Navigator**.
**o** Choose **Properties** in the context menu.
**o** Go to the **Editors** -> **SQL Editor** -> **SQL Processing** node.
**o** Check the **Datasource "XXXXX" settings** on the top left in the dialog (this so that you can
&nbsp;&nbsp;&nbsp;override the global settings for this connection).
**o** Change the **Parameters** -> **Named parameter prefix** from "**:**" to "**&**".

**PS**. There are no stupid questions! Not ever! 

**PPS**. If there where such a thing as stupid questions, those questions are asked by both newbies and seniors.

**Notes**

**o** If you only connect to Orace databases, you can change the **Global** setting for the above value instead.

**o** If you later want to remove the override for the connection setting, uncheck the **Datasource "XXXXX**"
&nbsp;&nbsp;&nbsp;setting you changed above.

**Comment by momoie** [comment]
Hi Pdanie,

First of all, thanks for your fast and kind reply :)

It worked partially, in the example I put before it would be in Oracle SQL Developer:

SELECT * from SALES where CUSTOMER = '&CUSTOMER'

The way you have described, it works but without ' being slightly different:

SELECT * from SALES where CUSTOMER = &CUSTOMER

I could substitute but it seems that in the case when it is not an equal, is a LIKE it is mandatory for us to put '' at the beginning and ending of the parameter.

Kind regards.

**Comment by shungabubus** [comment]
Hello All, nice chat, let me join, as this is the only one thing missing for me at first sight using this great tool, too. So practically it is highly irrelevant to have or not to have the apostrophe in PL SQL, lately to avoid confusion I started to use just as you suggested, but I haven't tried it with LIKE. If the tool enforces it maybe we can request a feature here? 
Cheers: Tamas

**Comment by serge-rider** [comment]
@momoie @shungabubus You can set parameter value to a quoted string literal (e.g. `'Some String'`). 
In fact you can set parameter to any value, including expressions, sub-queries, etc.
