### ISSUE TITLE
Table is created instead of view

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#4962]
#### System information: 
- win 10 x64
- DBeaver version 5.3.2

#### Connection specification:
- SQLite

#### Describe the problem you're observing:
Table is created instead of view.

![2019-01-10_10h11_39](https://user-images.githubusercontent.com/31996417/50952037-35c6ad00-14c0-11e9-9d40-4ed9dedc2476.gif)

**Comment by serge-rider** [comment]
Similar to #3633

**Comment by Santirulo** [comment]
I confirm version 5.3.4 on Windows 10 x64 has the same behavior. I'm using this driver for Sqlite: sqlite-jdbc-3-25.2.jar.
Thanks for such a great tool !

**Comment by Santirulo** [comment]
I recently updated both the Sqlite driver to version 3-27-2 and DBeaver itself to version 6.0 (x64, CE) but the issue is still there.

Driver config:
![image](https://user-images.githubusercontent.com/47663608/54528185-7a693b80-497c-11e9-8baf-d31c6714190a.png)

DBeaver version:
![image](https://user-images.githubusercontent.com/47663608/54528237-a4226280-497c-11e9-8b1c-4d9ea91a8498.png)

Thanks!

**Comment by serge-rider** [comment]
This bug common for all Generic drivers.
We need to separate GenericTable and GenericView classes

**Comment by kseniiaguzeeva** [comment]
Verified: checked SQLite, MariaDB on DBeaver6.1.2.201907021224
