### ISSUE TITLE
Postgis support

### ISSUE THREAD

**Issue by Jeetah** [dbeaver/dbeaver#500]
Postgis support would be really cool. E.g. showing coordinates as Lat / Long or even on a map.

**Comment by Jeetah** [comment]
Postgis support would be really cool. E.g. showing coordinates as Lat / Long or even on a map.

**Comment by serge-rider** [comment]
Sounds interesting. Although I think this feature is bigger than just Postgis. 
We need a general support of spatial data types.

**Comment by ideamotor** [comment]
Something that would go a long way would be custom function autocomplete (code/content assist) since PostGIS has [so many functions](http://postgis.net/docs/reference.html). As well, if a user could associate help text with each custom function they have listed for auto-completion. Something similar to the template functionality where they can add keywords and descriptions, export, import, etc. It wouldn't need to know the surrounding code, just the partial word they have typed. That could be useful for users of any less common functions (MADlib comes to mind, as well as user-created functions). 

FWIW, I imagine viewing spatial data directly in the application would be a massive undertaking, as the user would want to style and compare different intermediate results. If the user creates throwaway tables for these steps, they can view these in QGIS (or any GIS software offering a database connection). Support for shp2pgsql/pgsql2raster/etc would enable a different workflow but that is PostGIS specific.

Finally, I just wanted to add - I just found out about this software today and I'm immediately switching over.

**Comment by serge-rider** [comment]
We'll add basic Postgis support in 4.3.5.
Show maps and other fancy stuff should be tracked in separate tickets (now it should be easy).

**Comment by imajic-unimelb** [comment]
Postgis support was announced for release 4.3.5 in [https://github.com/dbeaver/dbeaver/releases](https://github.com/dbeaver/dbeaver/releases). However, I'm using that release installed from Ubuntu ppa repo and I still don't get autocomplete for postgis functions.
PostgreSQL version: 9.5
PostGIS version: 2.4.2

**Comment by dpsspatial** [comment]
Adding that the support for evaluating spatial functions is there for both MSSQL and PostGIS, but the missing feature is the auto-complete of the spatial functions while typing the query. Great piece of software, and holds up to all our workflows so far!!

**Comment by serge-rider** [comment]
Cold you create a separate feature request.  It differs from Postgis implementation itself.

**Comment by dpsspatial** [comment]
@serge-rider Done. https://github.com/dbeaver/dbeaver/issues/4047

**Comment by chriszrc** [comment]
pgadmin just added a spatial viewer. I'd love to never have to open pgadmin again, is a spatial viewer here yet for dbeaver? Is there an issue I can upvote?

http://www.bostongis.com/blog/index.php?url=archives/272-pgAdmin4-now-offers-PostGIS-geometry-viewer.html

**Comment by serge-rider** [comment]
This can be added in DBeaver, and this is not too hard as there are map widgets already.
Please create the feature request.

**Comment by dpsspatial** [comment]
@chriszrc Chris, let me know if you do this, or if you want me to. Thanks, all!! This will be a great feature for DBeaver!!

**Comment by chriszrc** [comment]
@dpsspatial hi, I'm relatively new to dbeaver, and I'm not even aware of the map widgets, so maybe you would be better suited to create the feature requests? Also, any links to these map widgets?

**Comment by dpsspatial** [comment]
I can add the request. The map widgets are what you've referenced in the Boston GIS article, so I'll include that too.

**Comment by chriszrc** [comment]
@dpsspatial Hi, just curious if you made the feature request? Could you include the link here? Thanks!

**Comment by dpsspatial** [comment]
@chriszrc here you go: https://github.com/dbeaver/dbeaver/issues/4222, which I see you've commented on!

**Comment by chriszrc** [comment]
@dpsspatial lol, this link came up first in the google searches, well, now I'll know where to go, thanks!
