### ISSUE TITLE
DBeaver 5.3.3 EE SSL error connecting to an AWS Aurora database

### ISSUE THREAD

**Issue by dejlek** [dbeaver/dbeaver#5071]
Linux, 64bit, Fedora 29
Java 8 and 11 (tried both)
Database: AWS Aurora

NOTE: 5.2 works well.

Error:
````
Error connecting to datasource

Reason:
SSL error: java.security.cert.CertificateException: Certificates do not conform to algorithm constraints
````

Details:
````
SSL error: java.security.cert.CertificateException: Certificates do not conform to algorithm constraints
  java.security.cert.CertificateException: Certificates do not conform to algorithm constraints
  java.security.cert.CertificateException: Certificates do not conform to algorithm constraints
    Certificates do not conform to algorithm constraints
    Certificates do not conform to algorithm constraints
      Algorithm constraints check failed on keysize limits. RSA 1024bit key used with certificate: C=US, ST=Washington, L=Seattle, O=Amazon.com, OU=RDS, CN=**HIDDEN**.us-east-1.rds.amazonaws.com.  Usage was tls server
      Algorithm constraints check failed on keysize limits. RSA 1024bit key used with certificate: C=US, ST=Washington, L=Seattle, O=Amazon.com, OU=RDS, CN=**HIDDEN**.us-east-1.rds.amazonaws.com.  Usage was tls server
````

**UPDATE**:
Works with Java 9 somehow... Which is weird.

**Comment by serge-rider** [comment]
Do you use PostgreSQL driver?

This is related to SSL and controlled by Java security configuration:
https://support.pingidentity.com/s/article/Connection-to-external-server-via-LDAPs-not-working

**Comment by dejlek** [comment]
Yes, I was connecting to one of our AWS Aurora instances...

**Comment by jamesvl** [comment]
This believe this bug is actually Fedora 28+ specific to RDS instances (whose server-side SSL mode is "prefer"). It's not Aurora specific - it happens to with RDS Postgres as well.

I finally resolved with help from [this StackOverflow](https://stackoverflow.com/questions/14149545/java-security-cert-certificateexception-certificates-does-not-conform-to-algori) where one of the answers pointed out that Fedora 28 introduced its own java security config file at `/etc/crypto-policies/back-ends/java.config`

```
jdk.tls.ephemeralDHKeySize=1024
jdk.certpath.disabledAlgorithms=MD2, MD5, DSA, RSA keySize < 2048
jdk.tls.disabledAlgorithms=DH keySize < 1024, SSLv2, SSLv3, <snipped>...
```

To resolve, change the restrictions on the RSA algorithm key size:
`jdk.certpath.disabledAlgorithms=MD2, MD5, DSA, RSA keySize < 1024`

(More details about the settings are in the Oracle [JDK Configure Crypto](https://www.java.com/en/configure_crypto.html) documentation page.)

And for Fedora users, this means that the fix done for Issue #4928 is insufficient if you _do_ want encrypted connections - changing the mode to "allow" simply changes whether or not SSL is even tried. If a non-encrypted connection works, then it's allowed through.

**Comment by dejlek** [comment]
As I said, it all works with JDK 9 (which is also from Fedora repos)... I do not think it is caused by what you wrote above. I will close the ticket.

**Comment by yspolat** [comment]
I found following [Stackoverflow](https://stackoverflow.com/questions/21218217/ssl-handshake-exception-algorithm-constraints-check-failed-md5withrsa) thread, but it didn't work. After @jamesvl suggestions, It works like charm. Thanks a lot.
