### ISSUE TITLE
Export / Data Transfer to new Vertica table not working.

### ISSUE THREAD

**Issue by chomam** [dbeaver/dbeaver#5087]
#### System information: 
Dbeaver CE 5.3.3
#### Connection specification:
Vertica 9.0
#### Describe the problem you're observing:
Export Data transfer  to Vertica fails when creating new target table and 'create' mapping.

New table is actually created but I think verification query in metadata fails.

Looking at query history, TABLE_NAME is not properly set:

select * from (select '..' as catalog_name, schema_name, table_name, table_type, remarks from v_catalog.all_tables order by table_type, catalog_name, schema_name, table_name) as vmd where 
TABLE_NAME ilike '%' escape E'\\' and SCHEMA_NAME ilike '..' escape E'\\' 

#### Include any warning/errors/backtraces from the logs
Error:
Can't start data transfer
Reason:
New table new_table_name  not found in container " .. "

**Comment by mdahlman** [comment]
I'm getting the same behavior in a different environment. I'm using DBeaver CE version 6.0.3.201904211926
with PostgreSQL 9.6.11 

Error:
Can't start data transfer
Reason:
New table my_table_name not found in container "RDS us-west-1 - my_schema"

Despite the error, it successfully creates the table with the correct columns. So my workaround is to backup in the wizard. Change the mapping from "create" to "existing". Then continue to the end of the wizard again.

In case the issue is linked to my settings, here's what I'm using for the CSV source and Database target:

Source settings:
Table settings:
	Open new connection(s): No
	Extract type: SINGLE_QUERY
	Select row count: No
	Selected rows only: No
	Selected columns only: No

Target settings:
Database settings:
	Open new connection(s): No
	Use transactions: No
	Truncate before load: No

(But I have tried variations on these settings, and I haven't found a variation that works correctly for me. NOTE: I have had success in the past, so I suspect that this is a regression somewhere.)

**Comment by uslss** [comment]
cannot reproduce it for now.
If it is still actual - feel free to reopen the ticket

**Comment by mdahlman** [comment]
Confirmed: I cannot reproduce the issue either. It works nicely now!
