### ISSUE TITLE
DBeaver, null, DBeaver in certificate for Eclipse

### ISSUE THREAD

**Issue by dashorst** [dbeaver/dbeaver#5143]
When updating DBeaver plugin in Eclipse you get asked to accept the certificate of DBeaver company, but it has a null value somewhere resulting in "DBeaver, null, DBeaver".

Not critical, but good to be fixed, as your DBeaver_news twitter account requested to be reminded of...

https://twitter.com/dbeaver_news/status/1090227749179084802

**Comment by serge-rider** [comment]
Well, this is a known issue. Eclipse shows certificate fields CN,OU,O (Common Name, Organization Unit and Organization) in this dialog.

We use our Symantec code sign certificate which doesn't have Organization Unit field at all. Not sure that we can fix this before we'll switch to another code sign certificate (in the end of this year I think).

Basically this looks more like Eclipse bug. Because OU is optional field.

Thanks for reminding about this issue.

**Comment by p91paul** [comment]
Can't DBeaver installer somehow mark his own certificate as trusted by default?

**Comment by serge-rider** [comment]
@p91paul As I understand @dashorst installs DBeaver into some Eclipse IDE. We can't make it trust DBeaver certificates.
Although we could try to do this in standalone version (as we have the same dialog when installing optional extensions in CE).

**Comment by p91paul** [comment]
Oh yes I did not get the "Eclipse plugin" part, sorry, I was OFC talking about standalone version :smile:.
