### ISSUE TITLE
Add option to move scripts to Recycle Bin when deleted.

### ISSUE THREAD

**Issue by spinjector** [dbeaver/dbeaver#5204]
When *.sql files are deleted from the Projects window, it seems they don't go to the OS Recycle Bin. They're permanently deleted. Which I just discovered the hard way. Please add an option to change this behavior. =-(

**Comment by serge-rider** [comment]
We can't use recycle bin as it is OS-specific.

We'll enable "local history" option in the next version of DBeaver. You'll be able to restore deleted scripts directly from DBeaver. right click on folder->Restore from local history.

![image](https://user-images.githubusercontent.com/6398845/52570025-8b75d880-2e23-11e9-9e0a-d0b19d954b0d.png)

**Comment by serge-rider** [comment]
Eclipse bug about this feature - https://bugs.eclipse.org/bugs/show_bug.cgi?id=70810 (delete to native recycle bin won't be implemented)

**Comment by SethArchambault** [comment]
So I have no idea how dbeaver's default project ended up the same as this folder to a project I was working on, but after tiring of continually removing the dbeaver project file from git commits - I went into dbeaver, set another folder as the primary, and deleted the project. I saw the checkbox saying it was destructive, but since I had already deleted the .dbeaver countless times, and has just committed my code in git, I wasn't worried about that. Instead it recursively deleted about 1000 files including the .git folder of the project I was working on, which I had not had a chance to push yet. Very frustrated as now I have to try and find a backup and piece together my work from my clipboard and some .vimundo files.

This is pretty scary behavior! If you're going to have such intense consequences for such a trivial action (deleting project files in most apps is something I do all the time without fear) then I'd recommend that dbeaver create it's own folder, rather than be able to expose the user to deleting a whole lot more damage. Imagine if I used my User director for these simple .dbeaver files.. It would have deleted 1/4 of my drive!

Update: Phew - timemachine saved me. I thought it only backed up when I had the drive plugged in, but forgot about the hourly snapshots..
