### ISSUE TITLE
FR: raw data preview everywhere

### ISSUE THREAD

**Issue by maln0ir** [dbeaver/dbeaver#5280]
Add option to preview raw data (in hexadecimal) for any field in result set. Currently it works only for some data types.

Reason for this is ability to inspect exact data returned by database, useful for debugging encoding problems or rough whitespaces.

#### System information:

* Operating system (distribution) and version: Windows 10
* DBeaver version: DBeaver CE   5.3.5.201902121907
* Java version: 1.8

**Comment by serge-rider** [comment]
I'm afraid it is not possible in general case. We use JDBC driver for most databases. JDBC doesn't support raw data view. It returns table columns in string/numeric representation.

This looks more like a task for network traffic sniffer.

**Comment by p91paul** [comment]
it could still be useful for string values. For example I sometimes need to understand if the field contains windows or unix newlines. Also sometimes you can encounter some characters that resemble a '-' but are in fact something else. Hex view should be useful in those situations...or are you afraid that it could lead to confusion since you see something that might have been already converted by JDBC and as such the hex representation is not accurate anymore?

**Comment by serge-rider** [comment]
We already have hex view for strings:

![image](https://user-images.githubusercontent.com/6398845/52916358-78657b80-32ef-11e9-8f9e-6e206df953e2.png)
