### ISSUE TITLE
DBeaver 5.3.3 does not import existing license

### ISSUE THREAD

**Issue by ppine7** [dbeaver/dbeaver#5330]
Hi, I've just updated DBeaver to the latest EE version , 5.3.3, from 5.3.1 which had a NPE bug opening license stuff...
Anyway, I'm trying to start DBeaver now and it cannot find my license - prompts to import/buy new one. I do have a perpetual license bought , and when I go to "License Manager" it correctly shows it in the list of available licenses. But then if I click on Import it again asks me to upload/paste a license. I don't know where the license is on the disk, so cannot copy/paste it - would expect the product to be able to correctly apply it, since it clearly sees it in the list of available licenses.

How do I proceed now?
Thanks,
Marina

**Comment by serge-rider** [comment]
Hello, 
generally it is much faster to solve such questions using tickets system on dbeaver.com or by email on support@dbeaver.com .

Please send your license ID on support@dbeaver.com.
Maybe you have too old license, it is perpetual but only for versions released during one year after license issue time (https://dbeaver.com/products/dbeaver-ee/). In this case you can download previous version of DBeaver from https://dbeaver.com/files and keep using it.

In order to use new versions you will need to extend your license or to purchase a new one.
