### ISSUE TITLE
Create New Oracle Table / CSV Import

### ISSUE THREAD

**Issue by tfarkas86** [dbeaver/dbeaver#5354]
I have seen many questions and responses about importing data in a CSV into a database. The general protocol is to make a JDBC connection to CSV file, then export the CSV data into a database table with the Export Wizard. However, all the descriptions of this process assume that a table already exists in the database, but I'm always interested in creating a new table when I import a CSV. I'm unclear about whether the Export Wizard is capable of creating a table (as with eg SQL Developer), or whether I have to have a pre-existing table. If I have to have a pre-existing table, must it have the correct dimensions and data-type specifications, or can the Export Wizard create columns according to the structure of the CSV. If so, could somebody please outline the steps to import a CSV, assuming no table yet exists, describing in detail the process of creating a table that will permit a successful CSV import? If possible, consider assuming the CSV file is very wide, so that manually specifying column names and data types would be silly. The bottom line is that an Import Wizard like the one available in SQL Developer would be very nice in DBeaver, if it does not already exist. Presently, I use SQL Developer solely to import data (it works very well), and would like to fully transition to using DBeaver.

**Comment by p91paul** [comment]
Perhaps this can be helpful: https://github.com/dbeaver/dbeaver/wiki/Data-transfer

**Comment by p91paul** [comment]
Also, if you select database table in the export wizard from a csv source, choosing a nonexistent table should create it; however, it doesn't look it is possible in the import wizard.

**Comment by tfarkas86** [comment]
I've discovered a process that works for my purposes. 

1. Make new CSV connection. 
2. Right-click desired CSV file and choose Export Data. 
3. Choose database.
4. Choose desired Target Container (Database and Schema).
5. Select New (may need to deselect Target field) and name new table. 
6. Select Columns to specify column names and change data types from VARCHAR(4000) default.
7. Click through to Finish.

**Comment by mdahlman** [comment]
This request is currently called "Create New Oracle Table / CSV Import", but I think it should be "Create New Table using CSV Import" since it applies to any database technology.

The solution from tfarkas86 is good. It's what I use as well. But it's has important limitations.
1. It's MUCH faster than CSV import. Roughly 10x faster for me. OK, this doesn't sound like a limitation. ;-)  ... but see the next point.
2. It does not have the option to treat empty strings as NULL values.

So I either get a lot of empty strings that I wish were NULL values... or I need to take 2 minutes instead of 12 seconds to load my table. Clearly this is not blocking. But it would be nice to get the best of everything.

**Comment by mdahlman** [comment]
I'm curious about why this got closed. It still seems like a useful feature.
@uslss, what was the motivation for closing?
