### ISSUE TITLE
Show start time on query execution results

### ISSUE THREAD

**Issue by caladfelipe** [dbeaver/dbeaver#5450]
After query execution (MySQL), it shows a tab with "Statistics" or results (updated rows, query, finish time). Would be great if we could also see the **start time** of the query. It would be also cool to see elapsed time.

**Comment by jetzerb** [comment]
I would also find the addition of Start Time useful.

And I'll add a clarifying point that information on elapsed time is printed _if multiple statements are executed_.

Currently (Version 21.3.2.202112271055), the Statistics pane includes the following information:

#### Single Statement is Executed
1. Updated Rows
2. Query
3. Finish time

#### Multiple Statements are Executed
1. Queries (_i.e._, the _number_ of queries executed)
2. Updated Rows
3. **Execute time (ms)**
4. **Fetch time (ms)**
5. **Total time (ms)**
6. Finish time

It would be great if items 3-5 were _always_ displayed, instead of just when multiple queries/statements are executed.
