### ISSUE TITLE
SQL-Server: Reference to declared variable gives error

### ISSUE THREAD

**Issue by stipe42** [dbeaver/dbeaver#5458]
#### System information: 
- MacOS Mojave
- DBeaver version 6.0.0
- 1.8

#### Connection specification:
- Driver name: Provided MS-SQL driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
`declare @column1 varchar(255) = 'mySortColumn';`
`declare @column2 varchar(max) = @column1;`
`GO`

gives following error when executed (whole script):
`SQL Error [137] [S0002]: Must declare the scalar variable "@column1".`

Other SQL-Editors working fine with these statements.

**Comment by serge-rider** [comment]
In order to execute TSQL scripts as a whole you need to select it (select both lines) and execute as a single statement (ctrl+enter).

Another way: in connection settings->SQL Editor->SQL Processing remove statement `;` and replace it with GO. Now dbeaver will execute your queries as a single statement automatically.

**Comment by kseniiaguzeeva** [comment]
Please reopen the ticket if you have additional questions.
