### ISSUE TITLE
SQL Scripts are overwritten by other users HELP!

### ISSUE THREAD

**Issue by Arthur60** [dbeaver/dbeaver#5606]
#### System information: 
- Operating system : W7-64
- DBeaver version : 6.00 (Edit: upgraded to 6.02.20190407 with no luck)

#### Describe the problem you're observing:
When creating a new script, I think dbeaver picks up first available script# in the shared folder.
When another user in the dev team does the same, the same script # is picked because I didn't save an empty script immediately.
This leads to one of us loosing his script when saving.
Wouldn't it be easy to create an empty .sql file in order to save the script # from beeing given to another user ?
When I close my script without saving it, dbeaver should see the corresponding file # in the shared folder has a null length, then just has to delete it so the # is available to the next user.

#### Steps to reproduce, if exist:
Two users, with shared dbeaver scripts folder.

First user creates a new script (F3, new script),
writes down state-of-the-art sql query.

Second user creates a new script (F3, new script)

First user saves his work, then quits, eventually.

Second user writes down crappy code, saves his "work", overwriting first user's masterpiece...
;)
Thx!

**Comment by Arthur60** [comment]
Hi every one.

Sorry to to be the only one in the conversation, this doesn't seem to ring a bell to anyone down here :(

The bad news are my latest modifications to our configuration didn't help either.
We all have to deal with sql files being overwritten by other users, even when we use one directory per connexion.

Help, please!
Thank you.

**Comment by p91paul** [comment]
I don't know if the developers are willing to support your use-case, but I'll just give my 2 cents: have you guys considered using a VCS (version control system - git is the industry standard, but there are other options as well) instead of a shared folder? Benefits include, apart from solving this issue:

* History of modifications
* Handling of conflicts
* If your VCS is distributed, like git, you also get free backups :)
* Advanced features like branches and many more

It does require a bit of training, but I think the benefits overwhelm the cost.

Oh and dbeaver (read: eclipse) has plugins for virtually every VCS.

**Comment by Arthur60** [comment]
Thank you p91paul for your thoughts.
Our IDE already imbeds CVS like tools and we don't need to learn another one in order to make dBeaver behave properly.
Sorry if this seems obvious to you and others, but it is not for us.
Don't think I dislike your idea, I just don't want to add layers to a tool that shouldn't need third party extra software to be cured.
Thanks :)
