### ISSUE TITLE
Special pattern characters s _ and % in JDBC meta-calls are not escaped

### ISSUE THREAD

**Issue by costin** [dbeaver/dbeaver#5618]
While trying out DBeaver I've noticed what looks like a bug in how DbVis performs columns discovery. Namely it does NOT escape characters _ and % in pattern arguments leading to unexpected results.

#### System information: 
- Operating system (distribution) and version
Win 10
- DBeaver version
6.0.1
- Java version 
12
- Additional extensions

#### Connection specification:
- Database name and version
Elasticsearch 6.7
- Driver name
Elasticsearch JDBC
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
no

#### Describe the problem you're observing:
The JDBC DatabaseMetaData documentation [1] indicates in its header that:

"Some DatabaseMetaData methods take arguments that are String patterns. These arguments all have names such as fooPattern. Within a pattern String, "%" means match any substring of 0 or more characters, and "_" means match any one character."

These two characters,`%` and `_`, should be escaped by using the dedicated escape character indicated through DatabaseMetaData#getSearchStringEscape [2]. To quote again the docs:

> This is the string that can be used to escape `_` or `%` in the catalog search parameters that are a pattern (and therefore use one of the wildcard characters). The `_` character represents any single character; the `%` character represents any sequence of zero or more characters.

Lastly, the DatabaseMetaData#getColumns() documentation [3] has the following signature:

```java
ResultSet getColumns(String catalog,
                     String schemaPattern,
                     String tableNamePattern,
                     String columnNamePattern)
              throws SQLException
```            

Where "tableNamePattern - a table name pattern; must match the table name as it is stored in the database".
The issue I've encountered with DbBeaver is that since it passes the table names as is, without escaping, more information then expected is being returned.

[1] https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html
[2] https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getSearchStringEscape--
[3] https://docs.oracle.com/javase/8/docs/api/java/sql/DatabaseMetaData.html#getColumns-java.lang.String-java.lang.String-java.lang.String-java.lang.String-

#### Steps to reproduce, if exist:
In a databaset with 3 tables: a_b, a1b and a2b, when I click on a_b DbBeaver incorrectly invokes `#getColumns(<catalog>,<schema>, "a_b", "%")` thus essentially asking for information on a_b, a1b and a2b since all tables match the pattern (again the string is considered a pattern and thus _ matches any one character). In fact, assuming the escape string is |, the tableNamePattern should be "a|_b": `#getColumns(<catalog>,<schema>, "a|_b", "%")`.

**Comment by serge-rider** [comment]
In fact it does. But optionally. There is a special parameter for that: 
![image](https://user-images.githubusercontent.com/6398845/55263145-1c442e80-5281-11e9-974a-e7f8a49e63b0.png)

This parameter is disabled by default because in real life big number of existing JDBC drivers doesn't support it. I.e. they do not try to unmask these parameters. In the same time most of drivers work fine without parameter masking (maybe not 100% correctly but correctly in 99.990 percents).

Anyhow, you can just set this option on for your driver.

And I'll enable this parameter for Elasticsearch by default, thanks for reporting!

**Comment by uslss** [comment]
verified

**Comment by omeuid** [comment]
> In fact it does. But optionally. There is a special parameter for that:
> ![image](https://user-images.githubusercontent.com/6398845/55263145-1c442e80-5281-11e9-974a-e7f8a49e63b0.png)
> 
> This parameter is disabled by default because in real life big number of existing JDBC drivers doesn't support it. I.e. they do not try to unmask these parameters. In the same time most of drivers work fine without parameter masking (maybe not 100% correctly but correctly in 99.990 percents).
> 
> Anyhow, you can just set this option on for your driver.
> 
> And I'll enable this parameter for Elasticsearch by default, thanks for reporting!

I was trying that 'Escape LIKE mask in search queries' parameter and I notice the following behaviour:

- The _ and % characters are escaped using the char returned by the getSearchStringEscape method of DatabaseMetadata class.
- The returned char by the getSearchStringEscape method is not being escaped.

I this the expected behaviour? If it is, How the driver could know when the escape char is escaping the next character or is not escaping anything? 

For example, if the getSearchStringEscape method returns the char '\' and a JDBC client wants to ask for the metadata of all views with a name that starts with the char '\'; the pattern used should be '\%' but if the client does not escape both characters the driver will not be able to know for sure what is the real query that the client is performing.

I hope the example could help to understand the scenario where I think DBeaver is not working as it should be.

Regards.
