### ISSUE TITLE
Dbeaver AppImage

### ISSUE THREAD

**Issue by tradewatcher** [dbeaver/dbeaver#5620]
It would be great to see an official AppImage of Dbeaver.

Supporting AppImage is the way for cross-platform support of Software.

**Comment by serge-rider** [comment]
This makes sense.
However I'll need some assistance in this task..

**Comment by tradewatcher** [comment]
I would like to help you but I dont have enough experience at this time. Else I wouldn't ask for an AppImage. I think it works like .dmg files on OSX.

Helpful Links: 
https://github.com/AppImage/AppImageKit
https://github.com/AppImage/AppImageKit/releases (AppImage of Kit)
https://discourse.appimage.org/t/how-to-create-an-appimage/155 (Help Board)

I'm sure Probono will help and assist you if you ask him on discourse.appimage.org

**Comment by tradewatcher** [comment]
Developers will assist you if you join IRC freenode #AppImage

**Comment by brotenet** [comment]
Hi, I've been packaging DBeaver (and some other tools) as AppImage for some time now but recently I stopped because besides me and my colleagues, no one was really downloading it because it was an unofficial package.

You can find the packaging script here: https://github.com/brotenet/AppImageTemplates/blob/master/package_DBeaver.sh

All you need to do is set the VERSION variable and the execute the package_DBeaver.sh script as follows (in the checked out repository directory):

`./package_DBeaver.sh`
--or if you wish to also upload it to a BinTray repository
.`/package_DBeaver.sh your_bintray_user your_bintray_repository your_bintray_api_key`
* You should probably need to also update the _res/**AppRun** with the a fresh build from the https://github.com/AppImage/AppImageKit repository

If you're looking for a maintainer of the AppImage then I'm willing to help :)

**Comment by serge-rider** [comment]
@tradewatcher @brotenet Thanks for the information.
I'll examine scripts above - we can use AppImage published in the default DBeaver packaging process.
Scheduling on 6.1.1 (which means "after 6.1 release").

**Comment by brotenet** [comment]
Do let me know for any help you might need. DBeaver is my go-to SQL client, so, I'm more than willing to help in any way I can. :)

**Comment by zot** [comment]
Great, I see that it's in the milestone for 6.3.0!

I use the appimage (thanks, @brotenet!), so I haven't upgraded yet (@brotenet, if you happen to have a more recent one, I'll certainly download it!).

Other people at the office are starting to use DBeaver but I'm the only Linux user here...

**Comment by serge-rider** [comment]
Unfortunately we can't do it in 6.3. Moving to 6.3.x

**Comment by serpro69** [comment]
Hi. Any updates on this?

**Comment by tradewatcher** [comment]
I'm also still waiting for an AppImage.

**Comment by yusiwen** [comment]
Any news on this?

**Comment by FKereki-DeepSee** [comment]
Will there be an appimage file?

**Comment by catpreneur** [comment]
Any updates?

**Comment by martinandersen3d** [comment]
Use github action to pack the appimage

https://github.com/marketplace/actions/build-appimage

**Comment by asjur** [comment]
This please.

**Comment by speatzle** [comment]
would help me allot

**Comment by catpreneur** [comment]
For those wondering, there's an appimage for DBeaver available here https://apprepo.de/appimage/dbeaver

**Comment by karam72** [comment]
It would be great If DBeaver will support officially appimage build. We can not trust 3rd parties.

**Comment by AlexWoroschilow** [comment]
@serge-rider  if you need an example how to build a dbeaver AppImage, you will find it here: 
https://github.com/area-of-dev/DBeaver.Appimage

**Comment by flambchap** [comment]
Since we use Java 17 now, maybe we can use `jpackage` for that.

**Comment by Akshaybun** [comment]
Any update on this?

**Comment by serge-rider** [comment]
Moved into #15185
