### ISSUE TITLE
Ubuntu 32-bit dbeaver-ce:i386 package not found

### ISSUE THREAD

**Issue by sandeep-khanna** [dbeaver/dbeaver#5642]
#### System information: 
- Ubuntu 18.04 32-bit
- DBeaver version - Unable to install
- openjdk version "10.0.2" 2018--7-17 
- `dpkg --print-architecture` returns i386

#### Describe the problem you're observing:
Unable to install DBeaver-CE on Ubuntu 18.04 LTS 32-bit

#### Steps to reproduce, if exist:
Added the dbeaver.gpg.key
Added a new apt source 'dbeaver.list'
Updated apt using 'apt update'
`apt install -y dbeaver-ce` return package not found!

**Comment by serge-rider** [comment]
We stopped delivering 32-bit packages of DBeaver CE since 6.0.1. Mostly because Eclipse platform stopped supporting 32-bit and because Java stopped this was well.

There is not much we can do about it. 

Although we'll probably will keep building 32-bit versions of EE using older Eclipse and Java (as long as we can, at some moment this may become impossible due to APIs incompatibility).

**Comment by KOLANICH** [comment]
>Although we'll probably will keep building 32-bit versions of EE using older Eclipse and Java (as long as we can, at some moment this may become impossible due to APIs incompatibility).

Is it still possible to have 32 bit builds?

>because Java stopped this was well.

It is available: https://packages.debian.org/ru/sid/i386/openjdk-11-jdk/download

The fact Oracle has dropped means nothing, there are plenty other sources to get 32-bit builds.
