### ISSUE TITLE
Prompt for parameters

### ISSUE THREAD

**Issue by Cha0sSoul** [dbeaver/dbeaver#5743]
Installed the new 6.0.2 version and now whenever I trie to run my previously fine working scripts I get a prompt to bind parameters:
![image](https://user-images.githubusercontent.com/49717958/56287928-4ffad180-6126-11e9-8032-5246f985afe5.png)
Previously this part was working fine:
![image](https://user-images.githubusercontent.com/49717958/56287973-6739bf00-6126-11e9-8087-44aa475213ec.png)
Now I get an error:
![image](https://user-images.githubusercontent.com/49717958/56287986-728cea80-6126-11e9-9d42-a77521b09743.png)
Can you please tell me what has changed, where is the problem now ?

**Comment by ced75** [comment]
Hi,

I have exactly the same issue with PostgreSQL and the "$" character.
With PostgreSQL, it is possible to use double dollar as character string delimiter.
For example, the following query is syntaxically correct:
`SELECT $$A text$$, col1
FROM table1;`

But when I try to execute the query, DBeaver asks for bind parameters, since there is no bind parameters, because it automatically detects $ as a bind parameter.

Is it possible to choose its own character as bind parameter character? 
Thanks in advance for your help.

Regards,
Cedric

**Comment by ced75** [comment]
Ok, I have found that it is possible to inactivate variables in the SQL settings.

**Comment by serge-rider** [comment]
the problem was in incorrect parameter prefix config in SQL Server extension. Now resolved.
