### ISSUE TITLE
How to open parquet files from local folder

### ISSUE THREAD

**Issue by Smart-Bird-ADM** [dbeaver/dbeaver#5821]
Is there a way to create connection to a local folder and read parquet files stored in it as a table just like CSV connection?

**Comment by flambchap** [comment]
I think we can do it by writing our own custom JDBC driver. Unfortunately, since we only ship our own JDBC drivers in commercial products, this feature won't be available in the DBeaver Community. I submitted this issue for a discussion with our product team.

**Comment by DeflateAwning** [comment]
One workaround, for anyone wondering, is to use an in-memory DuckDB database, and then do:

```sql
SELECT * FROM read_parquet('path_to_parquet');
```

**Comment by DeflateAwning** [comment]
@manticore-projects, hoping to move the discussion over here.

> Feel free to make a case ... for a discussion about writing an open source Parquet JDBC Driver.

The main benefit I see it providing is the ability to browse 10s of parquets in a single folder via the GUI, without having to type out the path for each (in a very similar way to the way the CSV driver reads all parquets in a folder, and displays them each in a table).

Ideally the JDBC driver would, over time, grow to support `SELECT` statements with `ORDER BY` and `WHERE` clauses, as well as the value counts in the filter pane.

Previewing/reviewing the data types for the columns in the parquet file is also a useful feature above what's provided by using DuckDB.

**Comment by manticore-projects** [comment]
> The main benefit I see it providing is the ability to browse 10s of parquets in a single folder via the GUI, without having to type out the path for each (in a very similar way to the way the CSV driver reads all parquets in a folder, and displays them each in a table).

Yes, this is what the ExcelSheet JDBC driver achieves.

> Ideally the JDBC driver would, over time, grow to support `SELECT` statements with `ORDER BY` and `WHERE` clauses, as well as the value counts in the filter pane.

It should be possible to support (very simple) joins and filters with a slow and simple (stupid) Query Engine.
But again: why, when there is DuckDB or other Java only in memory databases (like H2). The solution would neither be meat or fish (a German proverb we use for half-bake things, that fall short in every aspect).

> Previewing/reviewing the data types for the columns in the parquet file is also a useful feature above what's provided by using DuckDB.

Yes, that's the Meta-Data information.

Have a look at the Excel [SQLSheet](https://github.com/manticore-projects/sqlsheet) repository. We use and maintain this solely for ETL purpose (since it makes data import from Excel into DB very easy).
You can achieve similar things for Parquet by simply dropping Apache POI using the Parquet Libraries and this is it.

Since I do not have any use for it myself (yet), I would work on it only when a sponsor shows up (since its a lot of work with little gain over the DuckDB scenario),

**Comment by E1izabeth** [comment]
Now DBeaver supports it https://github.com/dbeaver/dbeaver/wiki/Database-driver-Parquet

**Comment by DeflateAwning** [comment]
I still don't see this in DBeaver CE version 24.3.2 (the latest in the apt software repo). Can you please confirm what version this will be released in?

**Comment by E1izabeth** [comment]
It's available in DBeaver PRO versions

**Comment by DeflateAwning** [comment]
I want this in CE. I use parquets in my personal life. Do you no longer improve CE?

**Comment by E1izabeth** [comment]
We don't plan to include this feature in CE

**Comment by DeflateAwning** [comment]
Why not? As an avid contributor to CE, I need to make sure that CE's objectives continue to align with mine

**Comment by E1izabeth** [comment]
We don't add PRO versions features to the Community Edition

**Comment by DeflateAwning** [comment]
Well how do you decide if it's a PRO version feature?

**Comment by LonwoLonwo** [comment]
Hello @DeflateAwning 
Thank you for your interest in the new features of DBeaver and for being an active member of our community! 
Indeed, some new features and enhancements are added exclusively to our Enterprise version. This is because their development and maintenance require significant resources and effort from our team, which we compensate through the paid subscription.

This allows us to continue actively developing and supporting the free Community version, which also receives important updates and new features. If you have any questions or need further information, please don't hesitate to reach out to us. Thank you for your understanding and support!

**Comment by manticore-projects** [comment]
Greetings @LonwoLonwo, I do fully support your stance since someone has to pay the bills after all and you must be able to afford any subsidies.

That said, please allow me to ask: what was the easiest way to write a Plugin for DBeaver. Is there any guide or documentation on developing and publishing plugins?

Thanks in advance for your time.

**Comment by LonwoLonwo** [comment]
Hello @manticore-projects 
Nice to see you again.

Which type of plugin do you want to write? 
We usually suggest looking at previously successfully merged PRs for new databases. (like this https://github.com/dbeaver/dbeaver/pull/22106)

However, we do not have working algorithms for contributors yet for other types of plugins.
All documentation that we have now is here - https://github.com/dbeaver/dbeaver/wiki/Contribute-your-code.

So, you can describe - what you want to see in our documentation, and I will think about how we can add it.

**Comment by manticore-projects** [comment]
Thanks @LonwoLonwo  and Team.

I have a few items in mind:
- JSQLFormatter (for proper statement formatting)
- JSQLTranspiler (for transpiling SQL dialects and supporting "Piped SQL")
- SQLSheet (for reading/writing Spreadsheets via SQL)

Let me see, what I can derive from your entry points and I would open a separate case/discussion.

All the best and cheers!

**Comment by arhayka** [comment]
Hi @manticore-projects 
Thank you for your interest in DBeaver and your willingness to contribute!

These two features sound interesting:
- JSQLFormatter (for proper statement formatting)
- JSQLTranspiler (for transpiling SQL dialects and supporting "Piped SQL")

We may consider supporting them in the future, and we'd also be happy to see your contribution.
You can check how DBeaver supports external formatters here: https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.model.sql/src/org/jkiss/dbeaver/model/sql/format/external/SQLFormatterExternal.java

How to add an external formatter:
```
<!-- SQL Formatters -->
<extension point="org.jkiss.dbeaver.sqlFormatter">
    <formatter id="default" class="org.jkiss.dbeaver.model.sql.format.tokenized.SQLFormatterTokenized" label="%sql.formatter.default.name" description="%sql.formatter.default.tip"/>
    <formatter id="compact" class="org.jkiss.dbeaver.model.sql.format.tokenized.SQLFormatterCompact" label="%sql.formatter.compact.name" description="%sql.formatter.compact.tip"/>
    <formatter id="external" class="org.jkiss.dbeaver.model.sql.format.external.SQLFormatterExternal" label="%sql.formatter.external.name" description="%sql.formatter.external.tip"/>
</extension>
```

Hope this helps!

Currently, we don’t have official documentation on developing plugins for DBeaver, but we are considering adding it in the future to better support contributors.

Regarding the last feature you mentioned - SQLSheet (for reading/writing Spreadsheets via SQL). DBeaver already supports working with [CSV](https://dbeaver.com/docs/dbeaver/Database-driver-CSV/) and [XLSX](https://dbeaver.com/docs/dbeaver/Database-driver-XLSX/) files as databases. We also plan to expand support for other file formats in the future.

Looking forward to your thoughts and contributions!
