### ISSUE TITLE
Postgis: layer switcher issues

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#5823]
Implemented in #4222
Issues:
- Incorrect rendering;
- Not all needed projections are shown;
- Probably, the icon for defined control is missed;
- The active layer isn't checked by default
and other

**Comment by rbovard** [comment]
Yes, I've noticed those elements here https://github.com/dbeaver/dbeaver/issues/4222#issuecomment-485665885

**Comment by serge-rider** [comment]
Layers icon was fixed.
Do you know what other projection we could add there?

**Comment by rbovard** [comment]
@serge-rider Sorry for the delay, I was out the office.

> Do you know what other projection we could add there?

`EPSG:4326` and `EPSG:3857` are a good choice as default values as they are "global".

> The active layer isn't checked by default and other

Is it fixed? Because I still see this issue in 6.0.4:

![image](https://user-images.githubusercontent.com/4549666/57453430-ab703900-7266-11e9-9640-d0aec37e01eb.png)
