### ISSUE TITLE
DBeaver 6.0.4 sometimes crashes on startup when old .plugin data is present

### ISSUE THREAD

**Issue by codebling** [dbeaver/dbeaver#5899]
After running DBeaver 6, closing it, running DBeaver 5.3.5, closing it, running DBeaver 6, DBeaver crashed on startup. This seems like an edge case and is probably not worth fixing, feel free to close. Otherwise the `workspace.xml` which causes the crash is attached below and can be used to reproduce the issue on DBeaver 6.0.4. 

[Log file](https://github.com/dbeaver/dbeaver/files/3175680/dbeaver.log) shows two NPEs on start-up.

To reproduce, extract [dbeaver4.zip](https://github.com/dbeaver/dbeaver/files/3175745/dbeaver4.zip) from your home directory and it will extract and overwrite your `.dbeaver4/.metadata/.plugins/org.eclipse.e4.workbench/workbench.xmi` with my bad copy, causing DBeaver to crash on startup.

**Comment by serge-rider** [comment]
This happens because 5.x and 6.x are based on different Eclipse platform versions. Generally there is no backward compatibility in workspace binary format (although it usually works for sibling version it may fail if version are too different).

Unfortunately we can'f fix it from DBeaver side.
Thanks for the report anyway.
