### ISSUE TITLE
Repaint ERD without changing the order of current already painted ERD

### ISSUE THREAD

**Issue by tchibatron** [dbeaver/dbeaver#6008]
Problem:
DBeaver changes tables order when I click on refresh button.

Imagine, I spent one hour for arranging tables in ERD to fit all of them into the one screen. After that I've noticed, that I have a misprint in column name of a table contains only two simple columns. But I'm preparing a ERD for my customer (seems it's really important to change the name of a column). I'm going to correct this misprint. Do this. And I have to refresh ERD, to apply my changes. After refresh all tables are arranged by default arrangement strategy.

Is it possible to refresh ERD and do not change places of tables if no relations were  added to them?

**Comment by tati-kru** [comment]
@tchibatron when you use Refresh button for the real diagram it's actually will be completely redrawn because it's not obvious for DBeaver what was changed. Maybe, we need to keep the layout in somewhere.

As a workaround, you can use Custom diagrams (https://github.com/dbeaver/dbeaver/wiki/Custom-Diagrams). It has refresh button for columns' name updates as well.

**Comment by serge-rider** [comment]
Indeed, this is a quite nasty glitch.
We have to keep all diagram elements where they were.

**Comment by serge-rider** [comment]
Done (for both custom diagrams and automatic ones)

**Comment by serge-rider** [comment]
Fix can be tested in EA version

**Comment by uslss** [comment]
reopened. issue appears if custom diagram wasn't previously saved
![erd](https://user-images.githubusercontent.com/31996417/59569278-ab4a3100-908f-11e9-8cc9-f687bbd2fb77.gif)

**Comment by serge-rider** [comment]
Let's track thi issue in a separate ticket
