### ISSUE TITLE
Can not copy all result data as text

### ISSUE THREAD

**Issue by KES777** [dbeaver/dbeaver#6238]
DBeaver trunc data:
![_2](https://user-images.githubusercontent.com/799021/60811192-6e0d2680-a197-11e9-9621-b323b17f5f14.jpg)

`psql` does not:
![_3](https://user-images.githubusercontent.com/799021/60811204-75343480-a197-11e9-94a0-1875fc940ad2.jpg)

If there only one result row I can select cell and copy it, but when there is many rows
I can not switch to text and copy all.

Copy as CSV also does not work:

![_4](https://user-images.githubusercontent.com/799021/60811476-fdb2d500-a197-11e9-99a1-8a761c6ed175.jpg)
![_5](https://user-images.githubusercontent.com/799021/60811478-00152f00-a198-11e9-8193-64fd296a6ec6.jpg)

**Comment by serge-rider** [comment]
You can configure maximum width of plaintext column in preferences (database->editors->data editor->Presentation). It is 255 by default.
In grid mode you can run command "Columns pack: fit values" in order to see full string values.

Please write some details about what is wrong with Copy as CSV (does it truncate values?)

**Comment by KES777** [comment]
On line 3 and 13 additional quotes appear. Where they from?

**Comment by KES777** [comment]
>Please write some details about what is wrong with Copy as CSV (does it truncate values?)

It adds extra quotes
