### ISSUE TITLE
DB2 iSeries: routine list read

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#6241]
We need to use custom SQL query instead of JDBC driver-provided procledure list.
See #1857 for details

**Comment by Condor70** [comment]
Posted this in #1857, but it seems that it belongs here:

There is an error in the 6.1.2 implementation which results in:
```
/* ERROR WHILE READING SOURCE:

SQL Error [42704]: [SQL0204] SYSROUTINES in MYSCHEMA type *FILE is niet gevonden.
*/
```

Line 55 in org.jkiss.dbeaver.ext.db2.i.model.DB2IMetaModel is:
`SELECT ROUTINE_DEFINITION FROM SYSROUTINES`
but should be:
`SELECT ROUTINE_DEFINITION FROM QSYS2.SYSROUTINES`

([reference](https://www.ibm.com/support/knowledgecenter/en/ssw_ibm_i_74/db2/rbafzcatalogtbls.htm))

**Comment by serge-rider** [comment]
@Condor70 thanks for checking this

**Comment by Condor70** [comment]
Unfortunately this is not the only fix that is needed. Function sources are now shown correctly, but stored procedures show nothing.

I suspect that this is caused by the way the Database Navigator shows functions and stored procedures, e.g.:
```
[Connection]
- [Schema]
--Procedures
---Function1
---Function2
---[Servername]
----Procedure1
----Procedure2
```
(Procedures are in an extra [Servername] container - not sure why)

Db2IMetaModel fills the schema parameter of the query with:
`dbStat.setString(1, sourceObject.getContainer().getName());`
I assume this references the [Servername] container for stored procedures instead of the [Schema] container.

**Comment by serge-rider** [comment]
It is definitely a bug (caused by legacy code).
Now fixed, please check how it works in Early Access version (https://dbeaver.io/files/ea)

**Comment by Condor70** [comment]
Thanks, that fixes it!
