### ISSUE TITLE
During 6.1.3 data migration to new location, a strange directory is selected

### ISSUE THREAD

**Issue by jest** [dbeaver/dbeaver#6316]
#### System information: 
- Operating system (distribution) and version: *Linux Mint 18.3 (Ubuntu 16.04-based)
- DBeaver version: 6.1.3
- Java version: 1.8

#### Describe the problem you're observing:

When starting DBeaver updated to 6.1.3 for the first time, a migration to OS-specific is proposed. After migration the data is moved to `$HOME/.local/share/.DBeaver`. As much as `.local/share` part is OK (although I expected `.config`), the initial dot in `.DBeaver` looks like an artifact from the older version, or from Windows-specific location config.

I propose to use `DBeaver` dir name, without the starting dot.

**Comment by serge-rider** [comment]
Agreed. We should use folder `$HOME/.local/share/DBeaver`.
However if somebody installed 6.1.3 and wrong path was used then it will be used anyway (with leading dot). You can delete this folder and DBeaver will re-migrate data from previous versions in the new folder.

Note: we don't use .config folder because there are not just configs. But entire workspace (scripts, diagrams, embedded databases and other user files).

**Comment by jest** [comment]
Right, I didn't think of all other workspace data in `.config`, as I use external locations for projects.

Thanks!

**Comment by uslss** [comment]
verified
