### ISSUE TITLE
Build 6.1.3 DB2 connection initialization settings lost

### ISSUE THREAD

**Issue by LutzBehrens** [dbeaver/dbeaver#6356]
#### System information: 
- Windows 10
- Build 6.1.3 CE
- Java Comming with 6.1.3 CE
- DB2 LUW 10.5 HF10 jdbc driver

#### Connection specification:
- DB2 LUW 10.5 HF10
- db2jcc4.jar
- No Proxy No tunnel

#### Describe the problem you're observing:
The initialization settings in the connection settings for all DB2 LUW connections get lost when closing and restarting DBeaver 6.1.3. Such as auto commit flag, standard schema, isolation grade etc.

#### Steps to reproduce, if exist:
Well, change the initialization setting of a DB2 connection, then klick ok. close DBeaver, restart DBeaver, change is lost...

**Comment by olivierFr** [comment]
Exactly the same problem with Sqlite.

Dbeaver 6.1.3
Sqlite 3.28
Mac OS X 10.13.6

**Comment by serge-rider** [comment]
I can't reproduce this (with any database).
Please send error and/or debug log file. https://github.com/dbeaver/dbeaver/wiki/Log-files

**Comment by olivierFr** [comment]
Thank you Serge!

Unfortunately, there are no errors, you will find the attached file.
This is what I do:

- I'm launching Dbeaver
- I open my sqlite database
- In the connection settings of this database, "initialization", I choose an isolation level "Serializable" and in bootstrap requests, I type "PRAGMA page_size = 8192;", I confirm.
- I'm testing the connection: okay.
- I click on "ok". Dbeaver informs me that he will have to reconnect the database because the connection has been modified.
- I confirm that
- Dbeaver opens my sqlite database again
- I check the connection settings: everything is ok, my settings are there.
- I leave Dbeaver and relaunch it
- I open my database, check the connection settings: it's empty, my settings are no longer there.

Thank you
Olivier

[log.txt](https://github.com/dbeaver/dbeaver/files/3464072/log.txt)
<img width="1399" alt="capt1" src="https://user-images.githubusercontent.com/6524347/62414601-f4454d00-b61d-11e9-970a-60a8392a8e89.png">
<img width="581" alt="capt2" src="https://user-images.githubusercontent.com/6524347/62414603-fdceb500-b61d-11e9-9f8d-b49106a644fd.png">
<img width="539" alt="after-reopen" src="https://user-images.githubusercontent.com/6524347/62414612-1fc83780-b61e-11e9-814e-994965817a2b.png">

**Comment by serge-rider** [comment]
Thanks for details. now I can reproduce this.

**Comment by uslss** [comment]
verified
