### ISSUE TITLE
PostgreSQL enum might be displayed in the wrong order

### ISSUE THREAD

**Issue by Teelevision** [dbeaver/dbeaver#6477]
#### System information: 
- Operating system (distribution) and version
  MacOS Version 10.14.6
- DBeaver version
  6.0.3 (installed via homebrew)

#### Connection specification:
- Database name and version
  PostgreSQL 9.5

#### Describe the problem you're observing:

When editing an enum like below, in the type properties view the enum values are listed in the wrong order. AFAIK it's not stated anywhere that they should be in the right order, but it is confusing to have it any other way.

#### Steps to reproduce, if exist:

```sql
create type testenum as enum ('second');
alter type testenum add value 'first' before 'second';
select enum_range(null::testenum); -- outputs: {first,second}
```

Observe that in the type properties view the enum values are listed out of order as `{second, first}`.

<img width="248" alt="Screenshot 2019-08-08 at 15 58 57" src="https://user-images.githubusercontent.com/4125691/62709352-7acea580-b9f5-11e9-82ee-62629b914126.png">
<img width="499" alt="Screenshot 2019-08-08 at 16 01 01" src="https://user-images.githubusercontent.com/4125691/62709487-bd907d80-b9f5-11e9-990a-0bcb14ad1bc3.png">

**Comment by serge-rider** [comment]
Thank you for the bug report. Indeed, we didn't respect the order of enum values.

**Comment by kseniiaguzeeva** [comment]
Verified

**Comment by nVlast** [comment]
It seems that this change results in errors when trying to connect to older Postgres versions (8.4 in my case) because `pg_catalog.pg_enum.enumsortorder` doesn't exist (by looking at the Postgres documentation it seems that it was added in 9.1). This only happens when there are enums in the database at the time of the connection.

(Not sure if I should create a new issue for this, adding it here as a comment for context)
