### ISSUE TITLE
Feature Request: ER Diagram: Horizontal scroll with Shift + Mouse Scroll

### ISSUE THREAD

**Issue by erlangparasu** [dbeaver/dbeaver#6544]
Horizontal scroll with: Shift + MouseScroll

**Comment by r-richmond** [comment]
This has worked for as long as I can remember? What platform are you on / version are you running?

**Comment by erlangp** [comment]
Windows 8, DBeaver v6.1.4, sir

**Comment by mtricht** [comment]
I can confirm this does not work on windows but it does on linux, so I would say this is a bug.
I'm unfamiliar with dbeaver but what I managed to find out is:

1. Dbeaver uses the eclipse GEF
2. The class responsible for rendering the ERD viewer is this: https://github.com/dbeaver/dbeaver/blob/devel/plugins/org.jkiss.dbeaver.ext.erd/src/org/jkiss/dbeaver/ext/erd/editor/ERDGraphicalViewer.java#L86
3. The line I linked to is commented out, probably because it contains invalid code. The  `MouseWheelHorizontalScrollHandler` class does not exist and I am not sure why as it should be part of the GEF.
4. After adding the class manually and uncommenting the line it does work on windows: https://github.com/mtricht/dbeaver/commit/3fd31e7a76d1242a7c5f2f1f7c4b819b60554bd2

This does not seem like an elegant solution, the GEF should be providing this imo, so I'm not sure how to continue fixing this bug.

**Comment by erlangp** [comment]
thanks @mtricht

**Comment by rsprinkle** [comment]
This works for me now.  

DBeaver Community Edition
Version 21.1.0.202106012023

on Windows 10

**Comment by uslss** [comment]
will be implemented in #13002
