### ISSUE TITLE
exec sp_help tablename - not showing column names result (MS SQL)

### ISSUE THREAD

**Issue by surpavan** [dbeaver/dbeaver#6554]
exec sp_help tablename - not showing column names result;
when the above command is executed in ms sql (sql management studio) -  it returns several result sets; one of them being the name of the columns and the data types set; in my cases it returned 7 sets.

When this command is executed in Dbeaver -  it returns only 4 result sets -  3 sets are missing. And even the columnnames dataset did not return.

**Comment by serge-rider** [comment]
This is a known bug in SQL Server JDBC driver: https://github.com/microsoft/mssql-jdbc/issues/969

It was fixed in latest driver version (I've tested it on 7.4.1 and now I can see all 7 resultsets). Try to update driver version in driver edit dialog.
We'll change default driver version in the next DBeaver release.

Thanks for the bug report.

**Comment by surpavan** [comment]
> This is a known bug in SQL Server JDBC driver: [microsoft/mssql-jdbc#969](https://github.com/microsoft/mssql-jdbc/issues/969)
> 
> It was fixed in latest driver version (I've tested it on 7.4.1 and now I can see all 7 resultsets). Try to update driver version in driver edit dialog.
> We'll change default driver version in the next DBeaver release.
> 
> Thanks for the bug report.

Thank you, will try.

**Comment by uslss** [comment]
verified

**Comment by surpavan** [comment]
Worked for me after updating the driver.  Thank you.

**Comment by surpavan** [comment]
Issue persists again.
