### ISSUE TITLE
cant find attribute binding for ref attribute 'X'

### ISSUE THREAD

**Issue by afwebdev** [dbeaver/dbeaver#6614]
MySQL, localhost, MAC OS 10.14.6 (18G87)

![Screen Shot 2019-08-23 at 7 14 41 PM](https://user-images.githubusercontent.com/42923864/63628620-769cad80-c5db-11e9-88ba-ea9d22d175a1.png)

Two tables: **users, posts.**

**users** table creation:
```
CREATE TABLE users
(
	id INT AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(30),
	last_name VARCHAR(30),
	date_added DATETIME DEFAULT CURRENT_TIMESTAMP
)
```

insert data to **users**:

```
INSERT INTO users(first_name, last_name)
VALUES
('first1', 'last1'),
('first2', 'last2'),
('first3', 'last3'),
('first4', 'last4');
```

**posts** table creation:

```
CREATE TABLE posts
(
	id INT AUTO_INCREMENT PRIMARY KEY,
	user_id INT,
	title VARCHAR(30),
	body TEXT,
	date_added DATETIME DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(user_id) REFERENCES users(id)
);
```

insert data to **posts**:

```
INSERT INTO posts(user_id, title, body)
VALUES
(1, 'title1', 'body text 1'),
(2, 'title2', 'body text 2'),
(1, 'title3', 'body text 3'),
(4, 'title4', 'body text 4');
```

**SELECT query, gives error upon clicking entries in returned table.**

```
SELECT
users.first_name,
users.last_name,
posts.title,
posts.body
FROM users
INNER JOIN posts
ON posts.user_id = users.id;
```

When reference set to posts:
![Screen Shot 2019-08-23 at 7 14 41 PM](https://user-images.githubusercontent.com/42923864/63628620-769cad80-c5db-11e9-88ba-ea9d22d175a1.png)

When reference set to users:
![Screen Shot 2019-08-23 at 8 28 47 PM](https://user-images.githubusercontent.com/42923864/63630032-b4ea9a80-c5e4-11e9-8995-e7d73a7da8df.png)

Errors only happen when references pane is open.

**Comment by serge-rider** [comment]
I can't reproduce this. Your tables don't have any foreign keys so it is not even clear how References panel may be involved.

Anyhow, I believe something like this may happen if database metadata was partially loaded. You need to refresh database metadata after you create your tables in SQL script. 
DBeaver doesn't perform automatic schema refresh (mostly because is quite expensive operation in many environments).
So just select you schema/database in the navigator view and press F5. And the re-run your SQL queries.
