### ISSUE TITLE
Spatial lite

### ISSUE THREAD

**Issue by solisgb** [dbeaver/dbeaver#6619]
Hi there

There is anyway to use Spatialite spatial functions in sql pane?

I have tried with select "fid, st_astext(GEOMETRY) as geom from table;"
but I have the following error message "SQL Error [1]: [SQLITE_ERROR] SQL error or missing database (no such function: st_astext)". 

Do you know a way Spatialite extension can be added or recognized by Dbeaver? I'm using Windows 10

**Comment by serge-rider** [comment]
As far as I know standard SQLite doesn't support it. However if you keep geometry data in WKT/WKB format then you can see it on map. 
Right click on the geometry column->Column View->Set format->Geometry.

**Comment by solisgb** [comment]
Thanks four your answer.
Spatialite is a kind of Sqlite add-on; something similar to spatial extensions for postgres, etc. /wiki/SpatiaLite-on-Windows)
BD Browser for Sqlite supports it:
Spatialite. (https://github.com/fulcrumapp/spatialite-bin, https://github.com/sqlitebrowser/sqlitebrowser
Even GepPackage. https://www.fulcrumapp.com/blog/working-with-geodata/
I don't know if some body has some experiences using Spatialite in Dbeaver.

**Comment by geostonemarten** [comment]
@serge-rider  st_astext work perfectly but it's not an slite base same has postgresql you need load spatialite module.
http://www.gaia-gis.it/spatialite-2.4.0-4/spatialite-sql-2.4-4.html#p3

**Comment by tannenfreund87** [comment]
> It is possible to load mod and install cooresponding dll?

I had success under Linux to ``SELECT load_extension('mod_spatialite');`` in the SQL Terminal. In fact I just used it today to transfer data from a legacy software, that only saves in a jet(mdb) database. I imported all the tables into my 200 MB (and counting) spatialite database, created and dropped views and tables in dbeaver. I also did spatial operations and successfully loaded the new tables and views as layers into QGIS. The geometry view inside dbeaver doesn't work, neither does autocomplete for ``ST_*`` commands. Still, a way more comfortable way of developing than with the included DB manager of QGIS.

I installed spatialite and ``mod_spatialite.so`` through my package manager. Your experience under Windows might be widely different (dll hell, compilers, paths). Also, as far as I know, there is no native 100 % Java driver available for Spatialite, so you need a spatialite driver compiled for your processor architecture and OS.

Generally, I would recommend to just use PostGIS. On Linux and MacOS you can easily install it in a docker container locally. Because it's a client-server architecture, DBeaver doesn't need a special PostGIS driver, as PostGIS is an enhancement on the PostgreSQL server and not on the client.

**Comment by grundb** [comment]
Thanks @tannenfreund87 for the tip! On Ubuntu 24, all I had to do was install the `libsqlite3-mod-spatialite` package. Then it all just worked, didn't even have to restart DBeaver

**Comment by grundb** [comment]
FWIW, if you want to use geometrical functions on GPKG data in DBeaver, you also need to enable one of the Spatialite GPKG modes. These modes are documented [here](https://www.gaia-gis.it/fossil/libspatialite/wiki?name=4.3.0+functions). For example, `SELECT EnableGpkgMode();` enables GeoPackage mode and `SELECT EnableAmphibiousGpkgMode();` enables the more lenient GPKG amphibious mode. If none of these are enabled, geometries will generally be considered invalid (since they have the special GPKG binary format).
