### ISSUE TITLE
JDBC Fetch size does not work

### ISSUE THREAD

**Issue by petrvalkoun-gooddata** [dbeaver/dbeaver#6622]
We have finally added JDBC fetch-size to our proprietary ADS diver (wrapper around HP vertica driver), only to discover it does not work under DBeaver. **I have tested our driver it in SQuirreL and DataGrip and it works out of the box**: it fetched first 100-200 rows from large table and displays them in cca 5-7s.

In DBeaver 6.1.5, not matter what options I use, it always takes cca 2 minutes (whole table is fetched). **Logs on our server shows the fetch size send by DBeaver in the request is always set to 0**.

I am running following query "SELECT * FROM test;"
This is my setting:
![fetch_size](https://user-images.githubusercontent.com/22544158/63681455-1b92d280-c7f6-11e9-9bbd-a15d982a4cc0.png)

I tried using Use SQL to limit fetch size, but did not help.

Any help would be appreciated.

system: Windows 10 x64

UPDATE: we are investigating on our end, its possible that there is a bug on our side. Is it possible that the other clients ( SQuirreL and DataGrip) are able to show first 100 rows even without  fetch-size support in JDBC driver?

**Comment by serge-rider** [comment]
DBeaver use setFetchSize only if option "Use fetch size" was enabled". This s because some JDBC drivers behave incorrectly with explicit fetch size (e.g. some drivers limit resultset size according to fetch size which is definitely not what we need). 
"Use SQL to limit fetch size" is not needed here.

I can clearly see (in debugger) that JDBC api function setFetchSize is called when this option is enabled. 

DBeaver can fetch first X rows without fetch size support. Most of JDBC drivers don't support fetch size so it is definitely not a problem.
Can you trace API calls on driver side?

**Comment by pmsgd** [comment]
DBeaver 6.1.1 calls only setMaxRows with all combinations of "Use SQL to limit fetch size" and "Use fetch-size". setFetchSize is never called. Each step is separate sql execution with different setMaxRows value. You can override these methods in Statement class for any JDBC driver, add logging and test it yourself.

**Comment by serge-rider** [comment]
Well, fetch size is used when you read data directly from a table (on tab Data) but it is not called when you execute a custom SQL query.

I'll fix this.

**Comment by uslss** [comment]
verified
