### ISSUE TITLE
Using ORACLE connection sometime inline editor doesn't work

### ISSUE THREAD

**Issue by Diego-Gasparin** [dbeaver/dbeaver#6649]
#### System information: 
- Operating system: Windows 10
- DBeaver version: dbeaver-ce-6.1.5-x86_64
- Additional extensions: none

#### Connection specification:
- Database name and version: Oracle 11g
- Driver name: downloaded with dbeaver
- Do you use tunnels or proxies (SSH, SOCKS, etc): NO 

#### Describe the problem you're observing:
Sometime and only in some tables, is not possible to change fields values in a select resultset.
No warning or error are reported, simply fields appear as "read only".
Using SQL UPDATE command all works fine.

#### Steps to reproduce, if exist:
Is quite impossible to replicate the error. 
In the same ORACLE schema some tables show this situation other work with no problems

**Comment by serge-rider** [comment]
This may happen if DBeaver can't find table from your query in the system catalog. Usually because you don't use fully qualified table names. Try to use FQ names like schema.table.
Also some complicated SQL queries can't be parsed at all. 

Unfortunately Oracle driver doesn't provide valid information about source tables and we have to extract this info from query itself.

**Comment by Diego-Gasparin** [comment]
Hi Serge,
I use fully qualified tabels names.
The query I was speaking about is:
SELECT * FROM LEII.RECQ 
WHERE ID_RECQ = 69625

**Comment by kseniiaguzeeva** [comment]
@Diego-Gasparin Is this issue still actual for you? I cannot reproduce it in version 7.0.1

**Comment by uslss** [comment]
there is no update on ticket for a long time. ticket closed.
if issue is still actual for you - feel free to reopen the ticket
