### ISSUE TITLE
How to change colors of autocomplete suggestion metadata box

### ISSUE THREAD

**Issue by jim256** [dbeaver/dbeaver#6653]
**System information:**

10.14.6 (18G87)
DBeaver version 6.1.5
Additional extensions: Excel / Office extension

**Connection specification:**

Snowflake
Snowflake JDBC 3.8.8
Do you use tunnels or proxies (SSH, SOCKS, etc)? No

**Question:**
How can I change the colors of the box that pops up with metadata when you highlight an entry in the autocomplete box? In the Dark Windows Theme (Default colors and font), both the background color and text color are very dark, making it essentially a literal black box. Almost impossible to read.

**Comment by uslss** [comment]
Hi @jim256 
Unfortunately, the color of mentioned box cannot be changed in Dark theme because it is standard Eclipse Platform control.
But you could try to use Darkest theme if you want where this problem is fixed. 
You could find here how to install it: https://github.com/dbeaver/dbeaver/wiki/Eclipse-extensions

**Comment by jim256** [comment]
Awesome! Thank you. Closing.
