### ISSUE TITLE
Entering parameters in quotos

### ISSUE THREAD

**Issue by oguzgogus** [dbeaver/dbeaver#6799]
TABLEX >to_date(:as_of_date, 'dd/mm/yyyy')

This works however if i use this i need to enter the input like '20/09/2019' however i want to enter the input like 20/09/2019 without  the " ' ".

I tried to use  TABLEX >to_date(':as_of_date', 'dd/mm/yyyy') but it does not work.

I used to get parameter with Toad even with out to_date function simply like '&as_of_date''.

Thank you for your help!

**Comment by serge-rider** [comment]
You can use any SQL expression as parameter value. Even a sub-select. This is why you need to enter parameter values exactly as they should look in the final SQL query.

In order to use syntax `TABLEX >to_date(':as_of_date', 'dd/mm/yyyy')` you can use variables syntax:
TABLEX >to_date('${as_of_date}', 'dd/mm/yyyy')
Variables are substituted even in strings and comments.

**Comment by oguzgogus** [comment]
Thank you for the response. Is it possible to change $ sign with another one

also  is there a way without using to_date function

thanks a lot

**Comment by oguzgogus** [comment]
thank you for the help. This helped a lot :)
