### ISSUE TITLE
How to set relative drivers path for portable use?

### ISSUE THREAD

**Issue by lemon-juice** [dbeaver/dbeaver#6841]
I'm trying to use the zip download to use DBeaver in portable mode on Windows. I am able to pass the relative data folder to dbeaver.exe and it works fine but I don't know how to configure DBeaver to also use a relative path for the drivers. There is a setting in the options to set the path for drivers and it appears to be saved in ui.drivers.home pref. The setting accepts a relative path but as soon as I start DBeaver it is overwritten with an absolute one, which means if I later start DBeaver from another location or drive it will not find the drivers folder. Is there a way to set it permanently relative to dbeaver.exe?

**Comment by uslss** [comment]
is it still actual?

**Comment by lemon-juice** [comment]
I've tried it with 7.2.1 and the pref ui.drivers.home does not exist any more in any of the files and the path to the drivers appears to be relative to dbeaver.exe as it changes when I move the location on the drive. So it looks like it was fixed at some point and works well now.

**Comment by Kyogre** [comment]
hi guys! I have got dbeaver fully portable (workspace + relative drivers) on Windows:

1. Make dbeaver use portable workspace folder with one of this ways:
- Create a .bat file inside dbeaver's folder with this command:
`start "%~dp0" "dbeaver.exe" -data workspace`
- Create shortcut to dbeaver with argument `-data workspace`. In `Target` of your shortcut you will got something like this: `"C:\...\dbeaver\dbeaver.exe" -data workspace`

2. Launch dbeaver with one of the ways from step1. Don't close dbeaver.
3. Put the subfolder which contains jar-file of your driver (for example I named my folder `jaybird3` because it will contain firebird3 driver) into `...\your dbeaver folder\drivers\`. Thus we will got something like `C:\...\Portable soft\dbeaver\drivers\jaybird3\jaybird-full-3.0.12.jar`.
4. Create the driver through the dbeaver's UI (if you creating firebird3 driver I recommend you just copy default Firebird driver and delete everything from `Libraries` section) and specify absolute path to the jar-file (on this step we need specify absolute path only to complete driver configuration creation, so don't mind for now). Don't close Driver manager yet. Find your newly created driver from the list -> Edit -> Libraries -> Find class -> select class -> OK -> close Driver manager.
5. Close dbeaver.
6. Open `...\your dbeaver folder\workspace\.metadata\.config\drivers.xml` -> locate section of your driver (if you have more than one driver added) -> in `path` change path to relative path like `${drivers_home}\jaybird3\jaybird-full-3.0.12.jar` (but you can be lucky and it will be already specified correctly) -> save changes.
7. Open `...\your dbeaver folder\workspace\.metadata\.plugins\org.eclipse.core.runtime\.settings\org.jkiss.dbeaver.core.prefs` -> remove path from parameters `dialog.default.folder=` and `ui.drivers.home=`. Don't delete parameters itself.
8. Now you can launch your dbeaver.
