### ISSUE TITLE
Can DBeaver display multiple query results vertically like MS SQL server management studio?

### ISSUE THREAD

**Issue by eslamenginelab** [dbeaver/dbeaver#6861]
#### System information: 
- Operating system (distribution) and version
- DBeaver version

#### Connection specification:
- Database name and version

#### Describe your question:
If I execute multiple queries, multiple result sets appear in different tabs so its hard to compare the results as you have to switch tabs. In SSMS, multiple query results appear vertically so comparing results is easier. Does db support viewing multiple query results vertically?

**Comment by serge-rider** [comment]
No, we don't support this.
Workaround: open SQL editor, main menu Window->Editor->Toggle Split Editor (Vertical/Horizontal).
Now you can execute you queries and compare results on one screen.

This also works with table editors (data view)

**Comment by eslamenginelab** [comment]
Okay, thank you. This works for the moment.

**Comment by craig-tx** [comment]
Ugh this is a near-deal-killer feature for someone thinking about replacing SSMS with dBeaver. Is there a feature request somewhere for this that I could vote on? 

The reason why split editor is not even close to as nice is that I then have to copy/move my SQL queries around
Thanks!

**Comment by guntribam** [comment]
This is the only feature that keeps me on ssms

**Comment by E1izabeth** [comment]
Now we have an option to Detach result set tabs. It looks like this.
![image](https://github.com/dbeaver/dbeaver/assets/28875055/f5488d62-2b32-46fb-b941-e283bd7e4d72)

And you can even make it to be a separate window by drag-n-dropping to outside DBeaver
![image](https://github.com/dbeaver/dbeaver/assets/28875055/6b6eb9da-e4af-4046-97f2-327232f2a7b6)


Does it satisfy your needs?

**Comment by craig-tx** [comment]
Thank you Elizabeth for the suggestion. I updated to the latest version and tried the detach functionality. I noticed that the detached results window gets "separated" from the query that was executed. Meaning a subsequent re-execution of the query does not update the detached result. This means it does not work for me since I want to be able to tweak the query and execute again and see updated results -without having to go through the tedious process of detaching windows. 

One use case is this: I have a set of 4 queries that pull useful information about a customer, where each query has results with typically one to a few rows each. A variable (Customer ID)  is set at the beginning and then the queries show results based on the Customer ID. I will run this query dozens of times per day and highly value the ability to quickly process the results by having them all visible (sample screenshot attached).

I also have several use cases querying different things. I have one use case per tab. Depending on what I need, I  visit the correct tab, plug in the ID and execute and see the results neatly organized and all visible at once. This is what SSMS is able to do.

The main problem, even if "separation" was solved, is that trying to manage many detached windows removes the neatly organized aspect. So the main goal would be that results be stacked vertically and completely contained within the tab structure. While my use case is very specific, I think the overall idea of stacked results contained within the tab would be useful across the board. Thanks for your consideration.

![image](https://github.com/dbeaver/dbeaver/assets/16706018/3c0a15c1-a38b-49ef-a155-d6c88f7fe17e)

**Comment by E1izabeth** [comment]
Thank you for feedback. I hope we will improve it.

**Comment by E1izabeth** [comment]
Probably, connected with #6195

**Comment by cig-npledger** [comment]
Definitely need this feature and find myself pining for SSMS, something I thought I'd never do!

My scenario is to generate queries over the day, including multiple queries and being able to set variables and have that variable effect subsequent queries, eg. (in T-SQL):

DECLARE @contactId INT
SET @contactId=1234
SELECT * from Contacts where ID=@contactId
SELECT * from MoreContactDetail where ContactID=@contactId

**Comment by E1izabeth** [comment]
You can vote for this feature with thumbs up emoji under the issue description.

**Comment by marvin-me** [comment]
Is this feature intended to only work on "Execute SQL Script"? I can't seem to get the new orientation working with "Execute SQL querry"

**Comment by E1izabeth** [comment]
@MarvinMetz 
This feature allows you to display all the results of one execution on one tab.

**Comment by marvin-me** [comment]
@E1izabeth Marking multiple querries and pressing "Execute SQL Querry" to execute them all at once keeps opening multiple tabs. Only the button "Execute SQL Script" works with the new orientation option.

**Comment by E1izabeth** [comment]
@MarvinMetz yes, it's expected

**Comment by bbiswas01** [comment]
FYI this needs a change to the Windows preferences to show a new button on the query editor interface:

https://www.linkedin.com/posts/dbeaver_our-community-including-users-migrating-activity-7127327392221528064-yw5z

**Comment by E1izabeth** [comment]
@bbiswas01 it can also be doe from the context menu 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/bf27e7e2-68c1-442d-bd6e-306cfaeb2f03)

Or main menu 
![image](https://github.com/dbeaver/dbeaver/assets/28875055/f1749b54-8e33-4660-bd04-6a726d3f555a)

**Comment by SFhockey7** [comment]
Hi @E1izabeth. Loving the new layout option, but it seems as though vertical scrolling with the mouse wheel is disabled when in the multiple-tab layout. I've directly compared functionality to the single tab layout, which is still scrollable. I hate to compare to SSMS, which scrolls any results on hover, but ideally it could at least scroll after activating the specific result pane.

Is anyone else experiencing this? Maybe I'm missing a setting somewhere.

**Comment by E1izabeth** [comment]
@SFhockey7 I reproduced it, thank you. Could you create an issue about it please?

**Comment by jjICP** [comment]
I would like to use this feature but I set up a query simply

```
select 1;
select 2;
select 3;
```

(in postgres) and then clicked the "Show results in a single/multiple tabs" via the context menu (by the way, does it show you the status of the toggle somewhere?) but it keeps showing multiple tabs instead of results in a single tab. I _am_ hitting the "Execute SQL Script" button as well. Do I need to change some other setting? Thanks for this - assuming I get it working, it's a huge factor that would contribute to me switching to this product.

**Comment by E1izabeth** [comment]
@jjICP you can put this command in the toolbar

![Image](https://github.com/user-attachments/assets/aab75074-4042-4220-a0ba-d1b88ab3ac9e)

in Preferences->User Interface -> Toolbar Customization

![Image](https://github.com/user-attachments/assets/fe18bac9-9abb-4c43-98fb-9b4a3ad660bd)

This command works only with `Execute SQL script`; a single query execution will lead to a single result on a tab.

Could you record a video showing how it doesn't work for you? I need to see where you click and in which order. It will help me to reproduce your issue

**Comment by jjICP** [comment]
Thanks for that! I don't really know how to explain this but since I made that change for the Toolbar customization it's working correctly now. Even if I remove the option it still works fine.  I swear I tried this for like 10 minutes before posting this lol. Is it perhaps some kind of preference reload needed to happen? I don't know - weird.  In any case, it's working for me now.  Again, thanks for this change!

**Comment by E1izabeth** [comment]
I don't think it's related to some preference reload. I'll try to reproduce it.
If you meet this again, please let me know

**Comment by ask9** [comment]
@jjICP  Perhaps your issue looks similar to this one: #36592

**Comment by jjICP** [comment]
> [@jjICP](https://github.com/jjICP) Perhaps your issue looks similar to this one: [#36592](https://github.com/dbeaver/dbeaver/issues/36592)

Unfortunately it wasn't JUST the first time I executed it. I was attempting to do it for about 10 minutes - even restarting DBeaver and clearing out all the tabs and disconnecting/reconnecting to a server - nothing worked, it just stayed multi-tab until I changed that preference. I don't know why that would make any sort of impact but it's what solved it for me
