### ISSUE TITLE
All tabs in the left sidebar have labels overlapping the icons

### ISSUE THREAD

**Issue by 18549** [dbeaver/dbeaver#6890]
#### System information: 
- Win 10
- DBeaver version: 6.2.1 x64 Community
- Additional extensions: None

#### Describe the problem you're observing:

All tabs in the left sidebar have labels overlapping the icons.

#### Steps to reproduce, if exist:

It's like that the whole time.

#### Include any warning/errors/backtraces from the logs

There's nothing in the log.

![dbeaver](https://user-images.githubusercontent.com/46347740/65963933-b1ec9080-e453-11e9-91e4-8cb595356145.jpg)

It's not just the sidebar, the problem appears to be affecting all trees throughout thre application.

![dbeaver2](https://user-images.githubusercontent.com/46347740/65964646-4c999f00-e455-11e9-8a94-6d8de19fd97b.jpg)

Look between the node expand triangle and and the icon for the SQL Editor node, there is a second very tiny node expand triangle after the correctly sized node expand triangle, which makes me suspect it's possibly a problem with the hidpi implementation.

**Comment by uslss** [comment]
Thanks for bug report!

**Comment by serge-rider** [comment]
This is a known issue in Eclipse (SWT) platform.
There is a bug about it: https://bugs.eclipse.org/bugs/show_bug.cgi?id=496849
It has to be fixed in 2019-09 but we can't migrate to this version because it has another bug (windows version is buggy and crashes all the time). So, waiting for the next version (2019-09+), this bug will be fixed automatically once we'll migrate.
