### ISSUE TITLE
Query editor - SQL Assist does not work if query includes blank line

### ISSUE THREAD

**Issue by tphillipvidea** [dbeaver/dbeaver#6981]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 6.2.2 
- Additional extensions

#### Connection specification:
- Database name and version: postgresql 9.6
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 

#### Describe the problem you're observing:
In query editor, if query includes a blank line below typing, SQL Assist does not return any suggestions.

#### Steps to reproduce, if exist:
Open new SQL Query window
Type any select statement:
SELECT 
field1, field2, field4
from tablename

Press enter twice after "field2," to insert 2 blank lines:
SELECT 
field1, field2, 
<BR><BR>
field4
from tablename

Scroll up to first blank line
type field3 (notice no suggested field names)
SELECT 
field1, field2, 
field3,

field4
from tablename

If you remove the blank line, SQL Assist works perfectly.  

This appears to be a problem anywhere in the query, not just before FROM.

**Comment by uslss** [comment]
Hi @tphillipvidea ,
probably issue appears because "Blank line is statement Delimeter" option is enabled.
You could disable it in **Preferences - Database - Editors - SQL Editor - SQL Processing**
![image](https://user-images.githubusercontent.com/31996417/66838216-f8221380-ef6c-11e9-98ee-3dba1ae1f515.png)
