### ISSUE TITLE
Tilde character not working in SQL editor

### ISSUE THREAD

**Issue by hackenspp** [dbeaver/dbeaver#7092]
#### System information: 
- Windows 10
- DBeaver 6.2.3

#### Connection specification:
- Postgres 9.6
- SSH

#### Describe the problem you're observing:
The tilde (~) character isn't working anymore in SQL Editor window (French keyboard).
It is useful for regexp search in Postgresql.
I'am able to enter it using Alt+126, but I have to do it twice!

**Comment by kseniiaguzeeva** [comment]
Unfortunately cannot reproduce it nighter on 6.2.3 nor 6.3.3 version. Is it still actual?

**Comment by hackenspp** [comment]
Yes, this behavior is still present in 6.3.2.
On my keyboard the shortcut is "Alt Gr" + "=" and then a space. It's also used to produce the Spanish "ñ", which doesn't work either.
The shortcut worked before and works in others applications.

**Comment by kseniiaguzeeva** [comment]
Unfortunately while can not reproduce.

**Comment by TinusVL** [comment]
I have the same problem using DBeaver 6.3.2, on Windows 10, using an azerty keyboard where "~" is also typed as "Alt Gr" + "=" and then a space. 

I noticed that I can't type "´" (typed as "Alt Gr" + "ù" and then a space) or "`" (typed as "Alt Gr" + "µ" and then a space) either.

These three symbols are accents that can be combined with a letter or a space. Combining these accents with a letter instead of a space doesn't work either. E.g. "Alt Gr" + "=" and then "n" should give "ñ" but gives "n".

This works fine in most applications, but there are similar problems in Eclipse 4.8.0.

**Comment by bnserig** [comment]
I have same problem. I use a Belgian Azerty keyboard. I can't write "~" ("AltGr" + "=" or "Ctrl" + "Alt" + "=").
I use it as statement separator.
Same problem with "´" and "`" which are on "ù" and "µ".

**Comment by TinusVL** [comment]
@kseniiaguzeeva, you might be able to reproduce this if you temporarily change your keyboard layout to azerty.

**Comment by kseniiaguzeeva** [comment]
Yes, finally I reproduced it. Thank you for your advice.
_Steps:
1 Change the keyboard layout to azerty.
2. Try to type "~" in SQL Editor._

**Comment by kseniiaguzeeva** [comment]
It is not DBeaver bug, it is Eclipse/Java issue.

**Comment by hackenspp** [comment]
Fixed in version 7.0.3 👍
