### ISSUE TITLE
Content between $$ and $$ is styled green

### ISSUE THREAD

**Issue by mutigozel** [dbeaver/dbeaver#7124]
DBeaver started to style all the content between $$ and $$ as green for any stored procedure or function create script for. Here is an image of the behavior below.

#### Steps to reproduce, if exist:
1) Save create script of func/sp to a sql file.
2) Close the editor.
3) Open the file.

![a](https://user-images.githubusercontent.com/27290658/67901227-82e53f80-fb23-11e9-9b28-a8db4884b1f5.png)

#### System information: 
- OS: Win 10 Enterprise x64 latest version
- DBeaver version: 6.2.3
- Database: PostgreSQL

**Comment by serge-rider** [comment]
This is not a bug. It is expected behavior.

In fact double dollar quotes work just like regular single quotes and used to enclose strings. And many people use it this way.
In the same time we need to support functions/procedures definition edit (although function body is just a string from PG perspective).

In order to keep SQL syntax highlighting use named tags around function body. For example:

```sql
CREATE OR REPLACE FUNCTION public.xxxx()
 RETURNS boolean
 LANGUAGE plpgsql
 STRICT
AS $function$
   // Function body
$function$
```

**Comment by mutigozel** [comment]
Thanks for the clarification. The syntax highlighting were kept before the last update even for $$ ... $$.

**Comment by pyrocks** [comment]
@serge-rider why force me to change all my code to use named tags?
It worked perfectly fine with $$ in 6.2.2.
