### ISSUE TITLE
DDL in Edit table is not good for hive.

### ISSUE THREAD

**Issue by javalover123** [dbeaver/dbeaver#720]
1. Column or table has no comment.
2. Length of string type is too large, 2147483647

**Comment by javalover123** [comment]
Export to mysql error using UTF, Can't create target table:
  SQL error [1074] [42000]: Column length too big for column 'dt' (max = 21845); use BLOB or TEXT instead
    com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Column length too big for column 'dt' (max = 21845); use BLOB or TEXT instead

**Comment by javalover123** [comment]
Can't create target table:
CREATE TABLE test(
dt VARCHAR(2147483647)
)

**Comment by serge-rider** [comment]
You can change target column data type in data transfer wizard. On columns mapping page. Just click on column type and set it to TEXT.

**Comment by javalover123** [comment]
Thanks! And the comment?

**Comment by serge-rider** [comment]
What is the problem with comments? Can you see them in navigator?

Or do you mean that comments aren't used in target table DDL? This feature is not supported (because target DDL in data transfer wizard is database independent).

**Comment by javalover123** [comment]
Column in Edit table can see comment for hive, DDL in Edit table can not, and data transfer wizard

**Comment by javalover123** [comment]
![20160912232940](https://cloud.githubusercontent.com/assets/9191388/18441856/2461dcbe-7941-11e6-9e52-1b5c2a89e20d.png)
![20160912233124](https://cloud.githubusercontent.com/assets/9191388/18441855/244707b8-7941-11e6-9b68-e8fae51f24ef.png)

**Comment by LonwoLonwo** [comment]
As I can see, DDL for Hive tables has both table comments and column comments.
And we also had many changes in data transfer, which should have helped with situations above.
It looks like the problem was solved. This issue will be closed.
Feel free to reopen it, if problem occurs again.

![2021-03-19 13_16_14-DBeaver Enterprise 21 0 0 - newtable_1](https://user-images.githubusercontent.com/45152336/111765805-de010900-88b5-11eb-8cd6-d93e3f8d6f61.png)

![2021-03-19 13_16_31-DBeaver Enterprise 21 0 0 - newtable_1](https://user-images.githubusercontent.com/45152336/111765808-de010900-88b5-11eb-89c9-5f362d333a56.png)
