### ISSUE TITLE
import database connections from xml especially old configuration file

### ISSUE THREAD

**Issue by hginzel** [dbeaver/dbeaver#7248]
#### System information: 
- dbeaver-ce-6.2.5-win32.win32.x86_64.zip

#### Connection specification:
- General – Import connections

#### Describe your question:
There is, in [Admin Manage Connections](https://github.com/dbeaver/dbeaver/wiki/Admin-Manage-Connections), a sentence “You can import connection from CSV or XML files.” But it is no described _how_. Please add a note about how to import connections from xml file, especially from old configuration file (`.dbeaver-data-sources.xml`).
For example after a computer migration / OS upgrading/reinstallation from backuped/saved configuration.
I have tried File → Import → Third Party Configuration → Custom. But why should I select a driver for import from a xml file?

#### Related issues:
- https://github.com/dbeaver/dbeaver/issues/6624
- https://github.com/dbeaver/dbeaver/issues/6599#issuecomment-524571243
- https://github.com/dbeaver/dbeaver/issues/6415

**Comment by serge-rider** [comment]
Import connections from xml file and importing old (legacy) dbeaver config files are very different. Import doesn't support old dbeaver config format (because it is not needed).

DBeaver still supports old connections config format by itself. I.e. if you have old project with xml configuration you can just open this project in new dbeaver  version and it will see it and parse it. 
But then all changes will be saved in new format and any changes in xml files won't affect configuration.

On project load dbeaver checks for `.dbeaver` folder and `data-sources.json` file existence. If they are there then new format is used. Otherwise dbeaver parses config in old format. Once you do any config changes dbeaver saves everything in new format.

So.. It means you can emulate 'config import' using following steps:
1. Create some folder, say LEGACY_PROJECT_DIR.
2. Copy old .dbeaver-data-sources.xml into LEGACY_PROJECT_DIR
3. In DBeaver switch to Projects view, click on Create Project icon in toolbar.
4. Specify any project name, turn off 'Use default location', enter LEGACY_PROJECT_DIR in Location field.
5. Click Finish

That's it. You can see your old connection in your new project. Now you can view them, copy-paste them, drag-n-drop them between projects and do other cool things.
