### ISSUE TITLE
Unable to connect to DB2 LUW database with authentication setting DATA_ENCRYPT

### ISSUE THREAD

**Issue by ingemarmagnusson** [dbeaver/dbeaver#7250]
#### System information: 
- Operating system (distribution) and version
**Windows 10 Enterprise Version 1903 OS-version 18362.476**
- DBeaver version
**Version 6.2.5.201911171645**

#### Connection specification:
- Database name and version
**IBM DB2 LUW version 10.5.8**

#### Describe your question:
I am unable to connect to a DB2 database on a server with DB2 setting AUTHENTICATION=DATA_ENCRYPT.
I have read the DB2 [Driver documentation](https://www.ibm.com/support/knowledgecenter/en/SSEPGG_10.5.0/com.ibm.db2.luw.apdv.java.doc/src/tpc/imjcc_r0052038.html) and added User Property securityMechanism with value 13.
When I test connection I get error message "[jcc][1071][10615][4.19.66] Caught java.security.InvalidAlgorithmParameterException while initializing EncryptionManager.  See attached Throwable for details. ERRORCODE=-4223, SQLSTATE=null
  DH key size must be multiple of 64, and can only range from 512 to 8192 (inclusive). The specific key size 256 is not supported"

If I change setting on server to AUTHENTICATION=SERVER_ENCRYPT and User Property securityMechanism to value 9 the connection is successful.

What is missing for the DATA_ENCRYPT connection to work?

**Comment by ingemarmagnusson** [comment]
Can this issue be labeled "feature request"?
With dbeaver I need to be able to connect to databases on DB2 server with authentication setting DATA_ENCRYPT.

**Comment by imavo** [comment]
This ticket should be closed.

Because the symptom is caused by a deliberate change by IBM .

There is no possible change in dbeaver than can alter this behaviour .

IBM  no longer supports the specific kind of authentication (data_encrypt) in Db2, and it has been removed from the code.

So applications that try to use that style will instead get an exception (sqlcode -4223 DH key size must be multiple of 64, and can only range from 512 to 8192 (inclusive). The specific key size 256 is not supported" )

Instead, you need to arrange to reconfigure the Db2-server to use a supported authentication method for the Db2-server version,  and if you want an encypted connection then IBM requires that you configure for SSL/TLS.


https://www.ibm.com/support/pages/jdbc-data-encrypt
