### ISSUE TITLE
file enconding ansi not supported

### ISSUE THREAD

**Issue by ramunozp** [dbeaver/dbeaver#7453]
#### System information: 
- Operating system (distribution) and version: OSX
- DBeaver version: 6.3.0
- Additional extensions: none

#### Connection specification:
- Database name and version: DB2
- Driver name: DB2 iSeries/AS 400
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : no

#### Describe the problem you're observing:
does not interpret the characters correctly in as400. Ansi must be used and dbeaver does not support it.

#### Steps to reproduce, if exist:
1- record a sql with accent on the letter for Spanish, for example, "café"
2- open in the sql file in an editor that reads it in formatop ansi.
example:
'@ ESCRITORIO CASAIDEAL CHAPLIN CAFÃ‰' --> text converted by ansi editor
'@ ESCRITORIO CASAIDEAL CHAPLIN CAFÉ' --> Original text

**Comment by serge-rider** [comment]
Probably your default file encoding doesn't support it.
You can see fiel encoding in file properties (alt+enter in SQL editor or in the Project explorer view when file is selected).
Also you can change default encoding in the preferences:
![image](https://user-images.githubusercontent.com/6398845/71375115-328fd880-25ce-11ea-8195-78f61edea4ba.png)

**Comment by ramunozp** [comment]
Exactly, but there is no option to put ANSI.

**Comment by patrickmdnet** [comment]
"ANSI encoding" is ambiguous.  See [this stackoverflow discussion](https://stackoverflow.com/questions/701882/what-is-ansi-format) and [this explanation by Raymond Chen.](https://devblogs.microsoft.com/oldnewthing/20040531-00/?p=39103).

This string you wrote above, `CAFÃ‰`, is what happens when a UTF-8 encoded file is viewed as US-ASCII.  [See debugging chart here.](https://www.i18nqa.com/debug/utf8-debug.html)

Try having your SQL files treated as UTF-8 and see what happens.
