### ISSUE TITLE
Scroll past last line in script editor

### ISSUE THREAD

**Issue by zkirkland** [dbeaver/dbeaver#7631]
Many text editors allow for the user to scroll past the last line of the editor but I am unable to find any setting to allow me to do this.

It would be nice to have this feature in the SQL Script editor window.

**Comment by uslss** [comment]
seems to be related to #10950

**Comment by hernancerm** [comment]
@uslss is https://github.com/dbeaver/dbeaver/issues/10950 actually a duplicate for this feature request? The issued that is marked as duplicate could be solved otherwise (e.g. by adding some margin at the bottom of the editor), not necesassarily implementing the feature asked here, which is scrolling past the last line as in VSCode. As an example:

![Screen Recording 2022-05-31 at 06 38 27 p m](https://user-images.githubusercontent.com/42811720/171300911-7cf3f01c-e3b5-4032-8beb-e71a33b6ca20.gif)

So https://github.com/dbeaver/dbeaver/issues/10950 might implement this, but it might not, I guess it depends on the solution choice. Until a PR is merged for that issue, I think it would be nice to keep this one open to track this. Could you please reopen this issue?
