### ISSUE TITLE
Sat active database missing

### ISSUE THREAD

**Issue by andrejCepl** [dbeaver/dbeaver#7639]
Set active database is missing, Can't change database to execute sql. My version is 6.3.3 and database is posgresql.

**Comment by cwhite31** [comment]
Me too

**Comment by vincentvanvugt** [comment]
Same here. When downgrading to 6.3.2 the "set active" option becomes available again. I've only tested postgresql databases.

**Comment by nmat** [comment]
Not sure if this is the same thing but on MSSQL the selection of active schema is different and not fast as it was before.

Before I could Ctrl+0 and select the current instance to enter. Now however it is not as intuitive. My suggestion would be to:

1. Have 2 option of how to change the schema
  1.1 Option 1: Ctrl+0 - Change current instance only and not have to think about the schema
  1.2 Option 2: Ctrl+Shift+0 - Change schema and instance
 
The first option also uses focus of filtering out instance just like it did in older version. Sometimes you have a large amount of instances in one database connection and so fast switching between the different instances makes sense.

This is my 2 cents though. Also might be good to have a "Ok" and "Cancel" button in the popup window.

**Comment by serge-rider** [comment]
You can change active database for SQL editor using main toolbar or main menu (see @nmat comment).
Each SQL editor has its own active database/schema now.
"Global" active database doesn't make sense now - that's why we removed this action. However you still can change it (as it is a default active database for new SQL editors) in connection settings.

**Comment by nmat** [comment]
@serge-rider correct, however the selection if you would only like to Ctrl+0 and select a instance or search for a instance is not very "easy" or understandable at the moment.

I actually still do not know how to say OK when selecting a instance through Ctrl+0 because there is no OK or cancel buttons. Before I could search for the item or just hit arrow down until I found the right one and hit Enter and I would change the instance. Now that is not possible it seems.

**Comment by andrejCepl** [comment]
It works for schema but I can't change instance. Is it ok that different instance can be changed only via 'Edit Connection' and disconnect and connect? I am on ubuntu is that a problem?

**Comment by andrejCepl** [comment]
Found! Problem is on ubuntu(I am on 16.04). On Ctrl + 0 can't change instance, When click on instance window closes. I

**Comment by coleman-rik** [comment]
@serge-rider your comment isn't applicable in 6.3.3 with postgreSQL databases.  Running on Windows 10 Enterprise, I have three connections in my navigator 2 postgreSQL 10 and 1 MSSQL Server 2016. Each has at least two databases, some more, under each connection.  The toolbar for MSSQL lets you choose between the databases on that server.  There is **no** such option (at least in 6.3.3) for postgreSQL.  Since the "Set active" menu item has been removed, the **only** way to change between postgreSQL databases under a connection is to set it as the default database and reconnect.

This makes the current version of dBeaver (at least for postgreSQL) a decided step backwards.
![dBeaver_error](https://user-images.githubusercontent.com/3697063/72841246-99e78980-3c5b-11ea-8f29-bc30d6df52db.png)

Notice the **lack** of carrot '>' near the two postgreSQL connections.

**Comment by MintPlayer** [comment]
Wow I'm totally not impressed...

You have to Disconnect, Edit Connection, Initialization, set Default Database to **postgres**, then reconnect and finally rename your database. Impressive

**Comment by uslss** [comment]
Already implemented.
![image](https://user-images.githubusercontent.com/31996417/79775492-ff234780-833c-11ea-9a7b-6e9a5bf3f25b.png)
