### ISSUE TITLE
Miss selected/current database (combo) after changing tab

### ISSUE THREAD

**Issue by carlosspohr** [dbeaver/dbeaver#7774]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: ```6.3.4 (EA)```
- Additional extensions: none

#### Connection specification:
- Database name and version: MySQL, 5.6
- Driver name: mysql-connector 5.6
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
As soon as DBeaver starts, it loads last used database in that combo on the top of window, so, I if click on my connection on database navigator, then click on button to open a new tab, that combo is cleaned. So, if I come back to previous tab, that combo loads selected database again.

**PS:** my database connection doesn't have specified default database filled.

#### Steps to reproduce:

1. Open DBeaver, he loads the last database that I used/selected;
![image](https://user-images.githubusercontent.com/637767/73448864-97162400-4340-11ea-89ad-00a5cf1b7208.png)
2. So, just click on your connection at database navigator, then click to open a new tab;
![image](https://user-images.githubusercontent.com/637767/73448890-ad23e480-4340-11ea-9595-4c4bc6dcc3a5.png)
3. Now, that combo on top will be empty:
![image](https://user-images.githubusercontent.com/637767/73448951-d17fc100-4340-11ea-83bc-4729e0ab4508.png)
4. So, switch to previous tab and this new one, and that combo will load the last database (step 1);
![image](https://user-images.githubusercontent.com/637767/73448995-ef4d2600-4340-11ea-86b6-d06f1d1ae012.png)

**PS: ** when I click on combo to specify some database, this situation doesn't appears anymore.

#### Logs
I didn't find any error log about this.

**Comment by uslss** [comment]
It is expected behavior.
Database is kept for every script.
If you have no default db and open connection with no db chosen in db navigator(like it is shown on picture below) - SQL editor opens with 'N/A'.
![image](https://user-images.githubusercontent.com/31996417/73480759-95357a80-43ab-11ea-972c-cd13357aafbe.png)
If you have some db (or item from it) chosen in db - SQL editor opens with this db chosen.
![image](https://user-images.githubusercontent.com/31996417/73480900-ce6dea80-43ab-11ea-82ab-338a9a54361c.png)
If you change default db in db navigator when some SQL editor is opened - it will be changed to default for the active editor

**Comment by carlosspohr** [comment]
Hi @uslss ,

Thanks for your answer.
