### ISSUE TITLE
[SQLite] Views are always displayed in ERD

### ISSUE THREAD

**Issue by kseniiaguzeeva** [dbeaver/dbeaver#7776]
#### System information:  
- Operating system (distribution) and version Win 10
- DBeaver version 6.3.4

#### Connection specification:
- Database name and version SQLite

#### Describe the problem you're observing:
Views are displayed in ERD when function "show views" is disabled.
#### Steps to reproduce, if exist:
1. Open a ERD with views
2. Disable function "show views" in Configuration and press "Apply and close"

Actual result: views are displayed (also after reopening ERD, relaunching DBeaver)

**Comment by mkgrgis** [comment]
Not only SQLite, the same with PostgreSQL (Ubuntu, DBeaver 6.3.3)

**Comment by serge-rider** [comment]
Fixed

Workaround: refresh diagram after settings change

**Comment by kseniiaguzeeva** [comment]
Unfortunately views are still displayed  after their disabling and refreshing.
Steps to reproduce, if exist:

1. Open a ERD with views
2. Disable function "show views" in Configuration and press "Apply and close"
3. Press Refresh btn

![j1sbT8GDB5](https://user-images.githubusercontent.com/51405061/74219044-ae4bfe80-4cbc-11ea-924e-97427cc93180.gif)

**Comment by serge-rider** [comment]
I see. This happens because your diagram was re-layouted and saved in dbeaver configuration.
Once this happened you cannot affect initial diagram contents.

We need a workaround for that as currently it is not possible to reset diagram saved state.

I've added new toolbar action "Persist diagram". It is enabled if diagram state was saved. If you want to reset persisted state and refresh diagram for database then you should "untoggle" it.

![image](https://user-images.githubusercontent.com/6398845/74236477-5922e380-4ce2-11ea-9df2-d700670af78a.png)

Then you can uncheck "Show views", refresh diagram, etc.

**Comment by kseniiaguzeeva** [comment]
verified.
