### ISSUE TITLE
Advanced Copy with Postgres changes editor to manual commit mode

### ISSUE THREAD

**Issue by antoniustefan** [dbeaver/dbeaver#7788]
Using Advanced Copy when connected to a Postgres database changes the editor to manual commit mode.

Steps to reproduce:
1. run a select against a Postgres database
2. right click in the result set and select Advanced Copy > Copy as SQL (or any other advanced copy option)
3. notice that the current editor is now in manual commit mode.

DBeaver 6.3.3
Postgres driver 42.2.9

**Comment by kseniiaguzeeva** [comment]
Thank you for the bug report.

**Comment by antoniustefan** [comment]
One more thing to add: I just noticed this only happens when copying the entire result set. If I select just some rows and use Advanced Copy for those selected, it will not trigger the bug.

**Comment by serge-rider** [comment]
Fixed.
This happened because dbeaver switches to manual commit mode when exporting data from PG database. Because some data types (like LOBs) can be read only in txn mode.

There were several changes:
- If resultset is long (longer than fetch size) then dbeaver will open a new connection (only if option "Open separate connection for each editor" is on).
- After copy end dbeaver will return to original txn mode (autocommit).

**Comment by kseniiaguzeeva** [comment]
verified
