### ISSUE TITLE
 Schema setup problem when connecting to Database(Oracle)

### ISSUE THREAD

**Issue by podoni** [dbeaver/dbeaver#7899]
* System Information:

* Operation System
 Windows 10
* DBeaver version
 6.3.4
* Additional extensions
 No

* Connection specification:
* Database name and version
 Oracle 12c
* Driver name
 Oracle JDBC Driver
* Do you use tunnels or Proxies(SSH, SOCKS, etc) ?
 No

Schema is not changed when Active Database is changed.
In the previous version (Dbeaver 6.3), it was set as the user name of the Connection Settings, but it does not seem to work in the Dbeaver 6.4 version.
Previously selected Schema seems to be selected

* Connection Settings
![image](https://user-images.githubusercontent.com/59002295/74389636-27c12980-4e42-11ea-809f-0d8015cb2fbf.png)

* Schema actually connected
![image](https://user-images.githubusercontent.com/59002295/74389640-2b54b080-4e42-11ea-904e-8f8786ad0523.png)

> Previously reported bug reports were caused by this problem.
> Schema was not checked when executing SQL.

https://github.com/dbeaver/dbeaver/issues/7872

**Comment by serge-rider** [comment]
There is a bug in Oracle active schema determine function in 6.3.1+.
Thanks for the bug report.

Also, since 6.3.4 DBeaver restores active schema in SQL editors. 
I.e. once you change schema it remembers your choice and restores it on next script open.

We will add the preference option for this behavior in 6.3.5:
![image](https://user-images.githubusercontent.com/6398845/74424176-84ccd780-4e62-11ea-9830-038677bf8fa7.png)

**Comment by kseniiaguzeeva** [comment]
verified

**Comment by podoni** [comment]
thanks.
