### ISSUE TITLE
Smart commit mode by default

### ISSUE THREAD

**Issue by PesterevViacheslav** [dbeaver/dbeaver#7912]
Smart commit mode very useful option, how can i set this mode by default? When i create new database connection smart commit mode is off.

**Comment by serge-rider** [comment]
You can set it in preferences.
![image](https://user-images.githubusercontent.com/6398845/74538461-57108d00-4f4d-11ea-90ea-c7e792ee14ee.png)

We won't enable this mode by default yet because it is not well tested. 
DBeaver doesn't detect data modification statements good enough yet (e.g. CTE queries are not recognized).

**Comment by PesterevViacheslav** [comment]
Thank you.
In that case also not detect data modification
`select  my_schema.my_dml_procedure();
`
