### ISSUE TITLE
Public Snapcraft config

### ISSUE THREAD

**Issue by serge-rider** [dbeaver/dbeaver#7988]
We need to put snapcraft.yaml in public repo.
As it is used for dbeaver-ce publishing and external PRs may be useful.

**Comment by galgalesh** [comment]
:+1: for this. I was investigating why the `dbeaver-ce` snap starts so slow and I found a few issues.

* It includes a bunch of icon themes in the snap itself without caches. These caches are generated when the snap first starts up.
* It includes a bunch of libraries in the snap which are already available in the `gnome-3-28-1804` content snap. This increases startup time because the dynamic linker has a bunch more libraries to iterate over and the snap size is a lot bigger which increases decompression time.

I'm happy to fix these issues in the `snapcraft.yaml` file myself when it's online somewhere.

**Comment by riednyko** [comment]
snapcraft.yaml now in the public repo:
https://github.com/dbeaver/dbeaver/blob/devel/product/snapcraft/snapcraft.yaml
