### ISSUE TITLE
Export: new "file name pattern"

### ISSUE THREAD

**Issue by tomaszkane** [dbeaver/dbeaver#8033]
**Describe the solution you'd like**
All my project have three environments: dev, stage production - like DBs in Dbeaver.
I would like to have file name pattern for export database like:
`${database}-${environemnt}-${timestamp}.sql`

**Comment by uslss** [comment]
thanks for suggestion

**Comment by juarezr** [comment]
## Additional Request

### Context

Currently when using `Execute > Export from Query` in `Data Transfer` window the filenames are generated using the text from `File name pattern` field mixed with the following variables:
- ${datasource}
- ${catalog}
- ${schema}
- ${table}
- ${timestamp}
- ${date}
- ${index}
- ${project}

### Proposal

1. Allow a new variable `${title}` for the  `File name pattern` field 
2. It's value may be retrieved from a tagged comment placed before the query being executed
3. This tagged comment must be formatted as `--title:<text>` using the same mechanism described in [#3151](https://github.com/dbeaver/dbeaver/issues/3151#issuecomment-374383784)
4. It should work when exporting multiple queries each one with a specific `--title` comment as currently is the case of `${index}` variable
5. Optionally the contents of  `--title` comment may have other variables that are expanded after `${title}
6. Optionally the tooltip int the `File name pattern` field may contain some description of the variable because this is the fastest and less complicated way of getting the meaning of the field.
7. Invalid filenames resulting from the `${title}` variable expansion should not be restricted for easing the development. They are the same case as typing `/` in the `File name pattern` currently.

### Details

Example `File name pattern`:

``` 
Export-${datasource}-${title}-${index}
``` 

Example Queries:

``` sql
-- title: Users 
select username, name, title, department from APP_USERS where department_code='EE'; 

-- title: Department-${timestamp}
select name, director, faculty from DEPARTMENT  where department_code='EE'; 
``` 

Example tooltip: 

``` 
${title}: expands from the tagged comment --title:<text> placed before the query
``` 
### Related

- This mechanism can meet the needs of issue #6965 also.
- There are any suggestion where an how in the source code this can be develop?

**Comment by kseniiaguzeeva** [comment]
New variable ${connectionType} is implemented.

**Comment by tomaszkane** [comment]
Hm, @kseniiaguzeeva how to use it?

1. connect to some "production" environment
2. dump database
3. file pattern `${database}-${connectionType}-${timestamp}.sql`
4. got `test-${connectionType}-202010221146.sql` file

DBeaver 7.2.3

**Comment by kseniiaguzeeva** [comment]
It was implemented only in Export wizard. I will create new FR to add to dump wizard too.
![dbeaver_C6g2hO4rh6](https://user-images.githubusercontent.com/51405061/96857394-9e013b80-1467-11eb-8191-74c558808fdb.png)

**Comment by cvargas-xbrein** [comment]
${schema} not work in porstgresql

**Comment by ShadelessFox** [comment]
Hello @cvargas-geo,

This issue is closed. Please create a new one.
