### ISSUE TITLE
Performing a dump of live database kills the server.

### ISSUE THREAD

**Issue by chrisjimallen** [dbeaver/dbeaver#8089]
#### System information: 
- Operating system (distribution) and version - Ubuntu 20.04 daily
- DBeaver version - Version 7.0.0.202003021717

#### Connection specification:
- Database mySQL and version - mysql8-16fa8d9f735-43acae96f0b627fe

#### Describe your question:

When I perform a SQL dump by right-clicking the database and choosing `Tools > Dump Database`, it causes the websites on the server to crash, which is nginx/mariadb10. This results in a 502 bad gateway at worst, and a very slow website at best. Is there a way of throttling the connection somehow or am I better off doing a server-side dump from command line?

**Comment by serge-rider** [comment]
This looks like a mariadb internal bug. Perhaps it caused by mismatch of client version and mariadb server version.
Because dbeaver just calls mysqldump and passes dump parameters (you can see them in dump wizard in the first line of dump log). This mustn't lead to server crash in any case.

As a workaround you could try to install proper native client version (the same version as your server) and configure it in dbeaver.
Or use server-side dump.
