### ISSUE TITLE
Unreal combination scheme + database in SQL window

### ISSUE THREAD

**Issue by mkgrgis** [dbeaver/dbeaver#8145]
#### System information: 
- Operating system (distribution) and version
Linux Mint
- DBeaver version
7.0.0
- Additional extensions
No

#### Connection specification:
- Database name and version
PostgreSQL 12
- Driver name
default
- Do you use tunnels or proxies (SSH, SOCKS, etc)? 
No

#### Describe the problem you're observing:
The combination scheme@database may not exists.

#### Steps to reproduce, if exist:
In pg connection "Show databases" = on
Create databases: A, B
Create schemes: A: C, B: D
Set active database A
Set active scheme D (from tree databases/schemes)
Open new SQL window
In SQL window will be D@A. This combination is unreal.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by tsheyman-crisp** [comment]
I've experienced the same/a similar issue 

System information:
Operating system (distribution) and version
macOS Catalina version 10.15.3
DBeaver version
7.0.0
Additional extensions
No


![datasource_schema](https://user-images.githubusercontent.com/62023184/76323283-23095d00-62aa-11ea-80a4-af7d5768c553.png)

In the image: 
Active Datasource = Roxberry
Active catalog/schema is from instance Swig

To fix, I must manually select the correct catalog/schema anytime the active datasource is switched.

**Comment by hartenberger** [comment]
Dear all I have a similar issue:
3 Connections with using the same SQL Server INSTANCE but different databases within the INSTANCE in a Availibility Group.
![image](https://user-images.githubusercontent.com/24831132/76353234-a6f63000-6310-11ea-9e96-aa1a29837965.png)
The only difference between the connection definitions is the databaseName for each connection. Same Hostname, same port, same instanceName, same failoverPartner. 

The problem is that for each database there might be a different primary node. So for example mawista1 database runs on node1 as primary and mawista2 database runs on node2 as primary within the availibility group at some point in time. When switching from connection mawista1  to connection mawista2 it seems that the same connection(session?) is used, because the connection is still targeting to the node1 instead of node2. In addtion the "active catalog/schema" does not switch to the defined database. 

The error can be avoided by defining a new database to an completly other server. When switching the active connection to this different database in between switching from mawista1 to mawista2 database everything works as expected. Connect to mawista1 database connect to newDatabase connect to mawista2 database works as expected.
I tried with Windows and SQL Server auth. No difference. I tryped with jdbc 7.4.1 and jdbc 8.2.1. but this makes no difference. DBeaver seems to hash and cache a connection maybe depending on the INSTANCE id of the sql Server or other criteria  and does not really switch the connection to the selected connection.

**Comment by mkgrgis** [comment]
MariaDb, Postgres, Oracle, MsSQL... There is issue for all DBMS, haves "schema" object.

**Comment by serge-rider** [comment]
Fixed.

@hartenberger this seems to be very different issue. Did you try to enable "Open separate connection for each editor" option in SQL editor preferences?

@mkgrgis how can Maria/MySQL and Oracle have this problem if they don't have such thing as "database"? This problem may happen only if there are databases AND schemas and both of them can be changed. At the moment PostgreSQL is the only database that supports it,

**Comment by uslss** [comment]
verified

**Comment by mkgrgis** [comment]
@serge-rider In Oracle it can be access to more than one databases in 1 connection. There is a simple syntax https://stackoverflow.com/questions/12580057/connect-two-oracle-databases, but it is not the same with Postgres group of databases. Full list of DB is unaccessable in Oracle.
In MariaDB/MySQL there is SHOW DATABASES for list all of databases https://mariadb.com/kb/en/show-databases/ , but it claimed as equivalent for schema https://mariadb.com/kb/en/schema/ . I don't verify english terminology in DBeaver, but You are right. There is full support both databases AND schemas only in PostgreSQL now. It can be problems if english terminology was not strongly  verified for all relational DB.
