### ISSUE TITLE
How to turn off automatic connection

### ISSUE THREAD

**Issue by jdvor** [dbeaver/dbeaver#8193]
I've got a lot of saved connections to local databases (docker); dbeaver remembers the one I've worked with last before exiting dbeaver. On next start-up it tries to automatically re-connect to such connection.
Is there a way in Preferences to turn off such automatic re-connect on dbeaver start-up?

**Comment by uslss** [comment]
seems to be similar to #8405 
ticket closed

**Comment by jdvor** [comment]
The solution suggested in #8405 does not fix the issue.

**Comment by n8-mills** [comment]
This should not have been closed, it's a profound annoyance to have to delete a connection and rebuild it later once [whatever issue] has been resolved, simply because DBeaver feels like it needs to try and activate every possible connection.  We should be able to put connections to "sleep" when they aren't behaving instead of being required to delete them.
