### ISSUE TITLE
Cannot create table using GUI, No Column Tab.(see the image)

### ISSUE THREAD

**Issue by CodeChari** [dbeaver/dbeaver#8369]
![Screenshot 2020-04-07 at 6 37 30 PM](https://user-images.githubusercontent.com/31309131/78673197-6b468a00-78ff-11ea-83cf-a0114dba894d.png)

**Comment by kseniiaguzeeva** [comment]
It is due to new simplified view feature.
Please change Navigator view on Advanced in connection settings:

1. Press **Edit connection** in context menu of a connection;
2. Select **General** tab
3. Select **Advanced** in **Navigator view** dropdown
4. Press Ok

![YC37Oht8J7](https://user-images.githubusercontent.com/51405061/78675238-6c6ebb80-78ed-11ea-8c9b-2c7cc30dced0.png)

**Comment by CodeChari** [comment]
> It is due to new simplified view feature.
> Please change Navigator view on Advanced in connection settings:
> 
> 1. Press **Edit connection** in context menu of a connection;
> 2. Select **General** tab
> 3. Select **Advanced** in **Navigator view** dropdown
> 4. Press Ok
> 
> ![YC37Oht8J7](https://user-images.githubusercontent.com/51405061/78675238-6c6ebb80-78ed-11ea-8c9b-2c7cc30dced0.png)

Thanks, It worked.
