### ISSUE TITLE
is Dbeaver  support arm platform currently? 

### ISSUE THREAD

**Issue by peiouya** [dbeaver/dbeaver#8403]
Help
currently, ecplise has runned on arm successfly (down from deepin system)。Dbeaver， please tell me  how to build to support arm ? 

thanks.

![image](https://user-images.githubusercontent.com/19821938/78949843-76680880-7aff-11ea-9058-55ec1fe2c4e3.png)

#### System information: 
- Operating system (distribution) and version
- DBeaver version

#### Connection specification:
- Database name and version

**Comment by mkgrgis** [comment]
ARM and i686 deb will be useful. What about auto generating for release of DBeaver?

**Comment by peiouya** [comment]
I mean that if i want to run dbeaver on arm，how should i do it.

Cuerrently, the binary executable files generated by Dbeaver are support x86，x86_64  etc, without arm. 

I see #552.  #552 says that ecplise running on arm not available on the eclipse.org web site.  
One question more ?  Based on ecplise supporting arm,  whether the dbeaver suporting arm can be obtained?  if possible, how and what todo ?

Thanks.

**Comment by kseniiaguzeeva** [comment]
Now we have Eclipse plugin only. 
Please reopen the ticket or create a new one if you have any questions.

**Comment by serge-rider** [comment]
ARM support was added in version 21

**Comment by strangan** [comment]
While the Beaver MacOS ARM build installs and launches correctly, it errors out when trying to query a table in Snowflake. It complains about the JDBC driver (despite updating it to be the latest) and says "cannot fetch due to max row count" -- I'm paraphrasing since I don't remember the exact error. 

When I replaced it with the Intel x86 version on my M1 MacBook Pro, it works fine to query a table in Snowflake.

So I believe there are still some errors to be patched with the MacOS M1 Arm version for Snowflake specifically.

Thanks

**Comment by peiouya** [comment]
你好，邮件已收到。谢谢联系！
