### ISSUE TITLE
How can I start a ext plugin develop to support new database?

### ISSUE THREAD

**Issue by notpdpton** [dbeaver/dbeaver#8425]
#### System information: 
- Windows 10 Professional x64
- DBeaver 7.0.2

#### Connection specification:
- New database product like mysql/postgres

#### Describe your question:

Hello, DBeaver team!

DBeaver is a cool tool, which I use it as my database manage client.
I want develop a plugin to support our company database, but I can not find any document about it. Could you give me any suggestions to do it?

Thanks very much!

**Comment by serge-rider** [comment]
There is a general info about dev environment: https://github.com/dbeaver/dbeaver/wiki/Develop-in-Eclipse
In order to create new db-specific plugin you can check other database plugins. E.g. SAP HANA or MySQL. 
Plagin nature depends on how different your plugin will be. Will it use JDBC driver (then examples above are good enough) or some proprietary protocol/API. And other things.

**Comment by notpdpton** [comment]
@serge-rider OK, I will try it. Thanks!
