### ISSUE TITLE
Postgres casting not working in result view

### ISSUE THREAD

**Issue by Jnb2387** [dbeaver/dbeaver#8523]
#### System information: 
- Operating system (distribution) and version  Linux Mint 19.2
- DBeaver version 7.0.3
- Additional extensions

#### Connection specification:
- Database name and version Postgres 12 or 9.5
- Driver name
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:

Writing a simple query to cast an integer to varchar or varchar to integer does not work when view the data in the result tab. 

#### Steps to reproduce, if exist:

SELECT sis_id::integer
FROM sm.sm_400_check_04_20_2020

This query will return a varchar column.
I tried casting all different ways. The only one that seemed to work was casting to boolean but this even showed the wrong data type in the column header.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
Does it cause any problems? Except wrong icon.
Metadata panel still contains correct data type of query results.

When DBeaver detects source table and column in result set it uses actual column data type instead the query metadata (because driver often doesn't provide correct data type information).

Workaround: use column alias:
```sql
SELECT sis_id::integer as sis_id_int
FROM sm.sm_400_check_04_20_2020
```

**Comment by Jnb2387** [comment]
Thank you adding the alias does work. I just thought in an older version I could add or remove commas by just casting but with the alias no issue now.

**Comment by kseniiaguzeeva** [comment]
closed.
