### ISSUE TITLE
Can't Delete Database

### ISSUE THREAD

**Issue by fferguso11** [dbeaver/dbeaver#8541]
#### System information: 
- MacOS Mojave 10.14.6
- DBeaver version 7.0.3.202004191823

#### Connection specification:
- Postgres
- SSH

#### Describe the problem you're observing:
Since updating to version 7.0.3.202004191823, can't delete a specific database. No matter what, I receive error message
` Can't delete object 'warehouse_labs'
Reason:
Cannot drop the currently open database.
Switch to another database and try again
(Note: enable 'Show all databases' option to see them).`

In the old version, could just set another database active and delete any open tasks on this database, but new version seems to have removed option to set databases active. Instead can set other dbs as default, but this doesnt solve the problem. There are no open tasks of any kind. 

This only seems to apply to one specific database, so implies new version won't switch which database is active.

#### Steps to reproduce, if exist:
1. Open connection
2. Right click on database and click delete
3. Await error message

#### Include any warning/errors/backtraces from the logs
`Reason:
Cannot drop the currently open database.
Switch to another database and try again
(Note: enable 'Show all databases' option to see them).`

![image](https://user-images.githubusercontent.com/44494546/80195487-d1c3eb80-8613-11ea-9cdd-3387d38b5383.png)

**Comment by kseniiaguzeeva** [comment]
I cannot reproduce the issue. My steps:
1. I open a connection
2. Set database A as default > trying to delete> Error message appears
3. Set database B as default
4. Delete database A > the database is deleted.

What do you do differently? Isn't your database set as default in Connection settings (select a connection and press F4 to open them)?

**Comment by fferguso11** [comment]
the database was set as default in connection settings, but despite clicking 'set as default' for other databases and bolding those names (implying it had worked), i was still not able to delete database. So step 4. in your example continues to break. It may have something to do with the database given in the connection being the one I want to delete, but surely i should be able to vary which database is active without modifying the connection?

**Comment by kseniiaguzeeva** [comment]
Set as default differs a little from default database in connection settings. Remove the database from connection settings, set some other as a default and it can be deleted.

**Comment by kseniiaguzeeva** [comment]
Please reopen the ticket if it is still actual for you.

**Comment by huolijian** [comment]
How to do delete?I can't delete it.

**Comment by kseniiaguzeeva** [comment]
Please try:
1. Remove the database from connection settings.
2. set some other database as a default in DB Navigator tree.
3. Delete the database

**Comment by huolijian** [comment]
OK.

Thanks.


 
---Original---

**Comment by Instrumedley** [comment]
this still doesn't work for me

**Comment by kseniiaguzeeva** [comment]
@Instrumedley please write steps to reproduce.

**Comment by zyrconium13** [comment]
What if the database I want to delete is the last one (I have no other database to switch to). How do I delete that?

**Comment by kseniiaguzeeva** [comment]
You should create a second database, make it default (via the database context menu) and delete.

**Comment by Tectract** [comment]
I'm stuck here. I also can't delete a database with dbeaver. 

>> Cannot drop the currently open database.

I have no idea what to do.

1. Remove the database from connection settings.

ok

2. set some other database as a default in DB Navigator tree.

I don't see any option for "default" connection. Where is that? I'm stuck here.

**Comment by mahsanamin** [comment]
It is quite very old but it also took me a few minutes to figure it out.

**Important Part:** 
You must need to enable this checkbox in dbever->postgreSQL->connection-properties-> "show all databases" so you can also see the one you want to delete.

By default dbever will connect with one database configured in connection properties. If you mentioned the one you want to delete it won't allow you to delete it. Just change the database name to some other and later delete it. Must enable "show all databases", otherwise you won't see it in the list

![Screenshot 2023-06-07 at 10 35 33 AM](https://github.com/dbeaver/dbeaver/assets/4756877/fbe9ba3c-c583-42f6-aaa8-20ce0f74b1c8)

**Comment by BuistvoPloti** [comment]
for datagrip do the same as in the comment above
![2024-02-26 09 57 17](https://github.com/dbeaver/dbeaver/assets/32066150/f06d82dc-2332-413b-89e0-77fdd21d5062)

**Comment by SufyanAbbada** [comment]
I have three databases open in DBeaver (Version 26.1.1.202606211757). I just want to delete a database. I have three connections and each one has multiple databases in it. I want to delete a database from one of the connections, how can I do that? In order to visually delete the database, I have to open up the connection. If I do, I cannot delete the database, as I get `Cannot drop the currently open database. Switch to another database and try again (Note: enable 'Show all databases' option to see them).` I don't know what it means by 'Switch to another database'. If I do switch (by going to another database or even turning off the connection, I cannot see the database to delete until it is not connected). I have even tried to use a script `drop database abc;` with various variations like `drop database public@abc;` and `drop database public.abc;` but nothing's working, and I either get `SQL Error [3D000]: ERROR: database "abc" does not exist` if I open the script from another database and `SQL Error [55006]: ERROR: cannot drop the currently open database` if I run the script from the database itself.
I tried to follow all the steps shared above, but I believe the version of the database has changed and I cannot reproduce them but nothing's working. Please suggest a way to delete it.
