### ISSUE TITLE
ER Digram expoert has no space on right side

### ISSUE THREAD

**Issue by jernejkubuntu** [dbeaver/dbeaver#8788]
#### System information: 
- linux kubuntu 20.04
- DBeaver version 7.0.5

#### Describe the problem you're observing:
when exporting ER diagram to png  there is an edge on 3 sides (top, left, bottom)
there is **no edge** on the **right** .[resources]

Withot the minimum edge the right border of the right most table is not visible.

#### Include any warning/errors/backtraces from the logs
![resources](https://user-images.githubusercontent.com/43403419/82797952-21e2d780-9e78-11ea-90c2-9b69b3d7b799.png)
![resources-screen-shot](https://user-images.githubusercontent.com/43403419/82798015-3c1cb580-9e78-11ea-9605-f5d31d1175f1.png)

**Comment by uslss** [comment]
thanks for the bug report

**Comment by tonb** [comment]
I think the problem is that the print area is cropped around the tables you want to export, but then that area is exported as if it was top-left. If you place a table in the middle of the screen, an empty png is written.

**Comment by kaperusov** [comment]
Hey, look at this: #3099 (closed). But, I can that reproduced! 
DBeaver version: 7.2.2 
OS: Debian 10 (buster)

**Comment by williamszostak** [comment]
It's also happening for me in DBeaver 7.3.2, on Ubuntu 20.10.
It happens when the ERD boxes are not aligned against the left and top edges of the ERD space.
Much more than just the right edge of the right-most table can be cut off, depending on how much empty space there is on the left side.
The work-around described by @dgilman in #3099 fixes it.

Examples:

When the left-most entity is aligned to the left edge of the canvas, the exported image is complete:
![whole-diagram](https://user-images.githubusercontent.com/68549091/104104475-7192d980-5276-11eb-856a-b8635f2eb5a2.png)

When there is space between the left edge of the canvas and the entities, the exported image is cut off on the right:
![right-side-cut-off](https://user-images.githubusercontent.com/68549091/104104479-748dca00-5276-11eb-9bcd-67f82e16a530.png)

When there is more space on the left edge, the exported image is cut off even more on the right:
![right-side-cut-off-even-more](https://user-images.githubusercontent.com/68549091/104104481-78215100-5276-11eb-85f6-a1ed433a9391.png)

**Comment by knbknb** [comment]
This does hold for the PNG-file writer, but does not hold for the SVG plugin, here the image is still cropped.

**Comment by uslss** [comment]
verified
