### ISSUE TITLE
Can't use PgPass file for PosgreSQL user authentication in DBeaver 7.1.0 (from Snap Store)

### ISSUE THREAD

**Issue by bloopeti** [dbeaver/dbeaver#8864]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04.4 LTS
- Window manager: gdm3
- DBeaver version: 7.1.0.202005311732
- Additional extensions: - (fresh install from Snap Store)

#### Connection specification:
- Database name and version: PostgreSQL 9.1.24
- Driver name: PostgreSQL JDBC Driver
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : SSH (shouldn't matter according to repro steps)

#### Describe the problem you're observing:
I am unable to configure a PostgreSQL database connection using a PgPass file as the authentication method for the database user. Attempting to do so gives an error message noting that the pgpass file was not found (in the wrong location).

#### Steps to reproduce:
- Install DBeaver from the "Ubuntu Software" manager
- Open DBeaver
- Open "Connect to database" window
- Select "PostgreSQL"
- Fill in the fields in the "Server" section with valid data (configured with the username below in the pgpass file)
- Fill in the "Username" field in the "Authentication" section with valid data (configured with the connection data above in the pgpass file)
- Change "Authentication" to "PgPass"
- Click the "Test Connection ..." button
- **Notice that an error popup appears saying "_PgPass file '/home/<current_user>/snap/dbeaver-ce/59/.pgpass' not found_"**

**Comment by uslss** [comment]
hi @bloopeti ,
sorry for the late response. Is it still actual against the recent version?

**Comment by uslss** [comment]
cannot reproduce it, dbeaver successfully connect to postgres using pgpass in mentioned case

**Comment by melo0187** [comment]
Actually I just had the same issue with the current version 21.0.3.202104181339 installed as snap.

At the company I work we use scripting to generate short lived database credentials that are stored in `~/.pgpass`.
The dbeaver snap however looks for the pgpass file in `~/snap/dbeaver-ce/110`. Is it possible to change the location used by dbeaver to look for the pgpass file?
For now I work around the issue by copying the pgpass file into dbeaver's snap home folder. Symlinking did not work, I assume because of the snap's strict mode.

**Comment by erwiese** [comment]
I use DBeaver inside Eclipse on rhel8 (not snap) and it does not work for me.
org.jkiss.dbeaver.model.exec.DBCException: Authentication error: Couldn't get password from PGPASS file

So where does DBeaver expect to find the pgpass file? 
Obviously not in ~/.pgpass
