### ISSUE TITLE
Can't use BigQuery Variables

### ISSUE THREAD

**Issue by SQLCodeMonkey83** [dbeaver/dbeaver#9115]
I have a SQL script that contains variables and executes fine natively in the BigQuery Cloud console but when I run the script or just a simple DECLARE statement in DBeaver I get the following error:

SQL Error [HY000]: [Simba][JDBC](11380) Null pointer exception.

You should be able to reproduce the issue running the following SQL in DBeaver against a BigQuery project:

DECLARE var_table_name STRING;

I'm using DBeaver community Version 7.1.1.202006231904.

**Comment by uslss** [comment]
thanks for the bug report

**Comment by serge-rider** [comment]
This looks like internal error in Symba JDBC driver.
Perhaps upgrading driver version will help.

@SQLCodeMonkey83 could you try to upgrade version to the most recent (1.2.4_1007 at the moment)?
I will update driver in default dbeaver configuration if it will help.
See JDBC driver downloads page: https://cloud.google.com/bigquery/providers/simba-drivers

If it won't help - please post error log for this error (https://github.com/dbeaver/dbeaver/wiki/Log-files)

**Comment by SQLCodeMonkey83** [comment]
Thanks Serge! Yes, updating the driver in the default  dbeaver configuration would be super helpful as I haven't manually configured a JDBC driver before (the ODBC driver has an executable for install whereas the JDBC appears to be all manual).

**Comment by serge-rider** [comment]
Driver version has been updated

**Comment by uslss** [comment]
verified

**Comment by binary-search-tree-01** [comment]
4 years later, I know...but I'm new to DBeaver/BigQuery, so this issue is brand-spankin' new to me! (Resolution below)

To enable the use of variables in DBeaver - you must enable sessions first:

1) Open the Connection settings window by either
       a) Right click the connection in the Database Navigator pane and then
          clicking "Edit Connection".
    or b) Hit F4
2) Click the Driver Settings button (lower right).
3) This opens the "Edit Driver 'Google BigQuery'" window.
4) Click the "Driver Properties" tab.
5) Right click in the empty space (under User Properties).
6) Click on "Add new property".
7) Type EnableSession and click OK.
8) You should now see this property listed.
9) Set this property's value to 1 by
       a) Click on the empty space to the right of this property (in the Value column)
       b) Type 1, followed by enter/return.
10) Click OK to close the Edit Driver window.
11) Click OK to close the Connection settings window.

Please note that, in order for this change to take effect, you must reconnect to BigQuery.
