### ISSUE TITLE
Cancelling a query doesn't do anything

### ISSUE THREAD

**Issue by robrousejr** [dbeaver/dbeaver#9121]
#### System information: 
- Amazon Linux (RHEL)
- 7.1.1
- None

#### Connection specification:
- updocm 
- JDBC
- No

#### Describe the problem you're observing:
I'm connected to a remote database, and want to run a MySQL query. However, sometimes I'll run a query which normally takes a split second and it'll last over 100 seconds. At this point, I click "Cancel" to cancel the query and it'll show "cancelled" while still trying to execute the query. It would be nice if it would just completely abort the execution of the query.

#### Steps to reproduce, if exist:
* Connect to a remote database
* Minimize DBeaver and don't use it for 15-60 minutes
* Try to execute any query (sometimes it works, but usually this is where the issue occurs)
* If the query takes a long time, try to cancel. This is where the bug occurs.

**Comment by serge-rider** [comment]
This happens because server closes idle connection.
DBeaver tries to run new query and fails (hangs) because socket was closed.

Although we can't change this (dbeaver hangs in socket operation till timeout, it may take several minutes) we can try  to handle this in UI.

Workaround: set Keep-Alive interval in the connection settings to prevent idle connection close.

**Comment by uslss** [comment]
verified.
The next query after canceling could be executed after connection invalidation only. Related issue #9142
