### ISSUE TITLE
UI changed from blue to grey after update

### ISSUE THREAD

**Issue by Xymanek** [dbeaver/dbeaver#9180]
#### System information: 
- Operating system (distribution) and version: Windows 10
- DBeaver version: 7.1.2

#### Connection specification:
- Database name and version: Irrelevant

#### Describe your question:

After the latest update, the UI theme changed on its own, and I would prefer to revert to the old one (but I can't find a way to do so).

This is the one I want/had before (blue): https://dbeaver.io/product/dbeaver-ss-classic-new.png
Current look (grey-ish): https://user-images.githubusercontent.com/2865341/86627780-82b21380-bfd1-11ea-971c-90553cb6e235.png

Things I tried (didn't help):

* Changing Preferences -> General -> Appearance -> Theme + Color and Font theme to all possible values
* Restarting DBeaver
* Deleting `workbench.xmi` as per https://github.com/dbeaver/dbeaver/wiki/Reset-UI-settings

**Comment by uslss** [comment]
Eclipse version was updated in the scope of 7.1.2. Seems that this is a side-effect. Unfortunately, we cannot resolve it. :(

**Comment by humphreygao** [comment]
See https://github.com/dbeaver/dbeaver/releases/tag/7.1.2
`- We upgraded Eclipse platform version to 2020-06. It affects dark theme and General preferences and fixes several minor bugs`

See 
https://bugs.eclipse.org/bugs/show_bug.cgi?id=551462
https://www.eclipse.org/eclipse/news/4.16/platform.php#light-theme-win10.

DBeaver is based on Eclipse platform and Eclipse tries to pursue a system's native look and feel. The blue-ish theme is not in accordance with Windows 10 default look and feel, so they updated the default theme under Windows 10 since the latest release.

**Comment by serge-rider** [comment]
Besides that 2020-06 has several issues with Dark theme. 
I'm thinking about reverting back to 2020-03.

PS I  think that grey background is ok. Consistent with base OS look and feel.

**Comment by Xymanek** [comment]
Thanks for the explanation!

> I think that grey background is ok. Consistent with base OS look and feel.

I personally preferred the blue one, so if it's possible to bring it back as a separate option, I would appreciate
