### ISSUE TITLE
Row Colors don't working very well

### ISSUE THREAD

**Issue by lestevam** [dbeaver/dbeaver#9221]
- Windows 10

- DBeaver 7.1.2

- Microsoft SQL Server 2017 (RTM-CU8) (KB4338363) - 14.0.3029.16 (X64) - Developer Edition (64-bit) on Linux (Ubuntu 16.04.4 LTS)

- Problem
When I colorized the row and the row is a link to another table, the text in the row is blue, therefore which I use a strong color behind of row, the text is hidden. It would be great if we could change the color of the link as well.

- Steps to reproduce

Panel Result
Select a column in the result panel and right-click
Choice View/Format and after in "Row Colors ..."
Select column and click in "Add"
Below, input the value for compare and choice the colors

**Comment by kseniiaguzeeva** [comment]
If I understand you correctly, it is not a bug, because the function (to change link color when row color is changed) is not implemented.
You can change cell data color using **Foreground** field in **Row colors...**

![dbeaver_rGuNvKkOLo](https://user-images.githubusercontent.com/51405061/87157250-a5407700-c2c6-11ea-99f3-5154d6e05b6a.png)

Please ask if you have additional questions.

**Comment by lestevam** [comment]
I understand your point of view, but this causes a bug in the visualization of the row, but ok.
So I believe I should open as a new feature?

**Comment by kseniiaguzeeva** [comment]
Yes please
