### ISSUE TITLE
User Settings changes reverts incorrectly

### ISSUE THREAD

**Issue by uslss** [dbeaver/dbeaver#9264]
#### System information: 
- Operating system (distribution) and version win10 x64
- DBeaver version 7.1.3

#### Connection specification:
- Database name and version Mysql, MariaDB

#### Steps to reproduce, if exist:
1. Open some existing user properties
1. Change some settings like password, limits
1. Press Save button and then press cancel
1. Click Revert button

**Actual result**
Changes isn't reverted

**Comment by akilovich** [comment]
Fixed the issue on Windows and Linux, but the issue is still present on mac. Previously, following STR from above crashed UI. After the fix, UI does not crash, however, the revert button still works incorrectly. I consider the work on this ticket to be done, the remaining mac problem deserves a different ticket.
