### ISSUE TITLE
Can not connect to Oracle DB via socks proxy

### ISSUE THREAD

**Issue by anatoly-kireev** [dbeaver/dbeaver#9543]
#### System information: 
- Windows 10 Pro
- DBeaver version 7.1.0.202006031909

#### Connection specification:
- Oracle 12c
- oracle.jdbc.OracleDriver 12.2.0.1
- Do you use tunnels or proxies (SSH, SOCKS, etc)? Yes

#### Describe the problem you're observing:
Connection attempts end up with a connection timeout.

#### Steps to reproduce, if exist:
Create connection, fill out connections details, hit "Test connection" button, get a timeout.

#### Include any warning/errors/backtraces from the logs

Can't find any as the path from the guide (%APPDATA%\DBeaverData\workspace6\.metadata) doesn't exist on my disk.

#### Additional information
There is a PostgreSQL DB sitting near Oracle right behind that socks proxy and I can connect to it with no issues, so proxy is not a problem in this case.

**Comment by wolferikg** [comment]
I'm seeing the exact same issue.
PostgreSQL works fine via socks. Oracle in the same destination network does not.

**Comment by kseniiaguzeeva** [comment]
Please try to set connection Proxy settings in 7.2.0 release https://dbeaver.io/
![dbeaver_NTF427D1Eu](https://user-images.githubusercontent.com/51405061/92247425-e2dd0d00-eecf-11ea-8b54-90a7983d546e.png)

**Comment by wolferikg** [comment]
Unfortunately the problem persists for me with the latest DBeaver version as well (Version 7.2.0.202008302047).

**Comment by kseniiaguzeeva** [comment]
Where did you set PROXY? In Proxy tab of connection configuration?
![dbeaver_rCpGASXTaO](https://user-images.githubusercontent.com/51405061/92370350-d8568980-f102-11ea-86f6-c2ce5f602cd3.png)

**Comment by uslss** [comment]
there aren't any updates for a long time.
Issue closed. If it is still actual for you - feel fee to reopen it

**Comment by lalvesl** [comment]
Hello everyone!
First of all, thank you to the DBeaver developers for this amazing database management tool!

I'm experiencing the exact same issue. PostgreSQL connections through a proxy (using a domain) work fine, but Oracle connections (also using a domain) do not.

When I connect without the proxy (from within the correct subnetwork) Oracle works perfectly.

In my case, I discovered that the problem is related to DNS resolution through the proxy. For some reason, **Oracle server domains are not being resolved correctly by the proxy** and any another domains works fine.

**This is not a DBeaver issue**, so there's no need to reopen the ticket. I’m just sharing this to help guide others who might encounter the same problem.
