### ISSUE TITLE
Auto install needed drivers

### ISSUE THREAD

**Issue by SriwanKm** [dbeaver/dbeaver#9576]
**Is your feature request related to a problem? Please describe.**
Notice that onboarding a lot of our developers have issues manually installing Vertica driver .jar 
other database tools (e.g. dataGrip) can do this automatically. Would like to add functionality for automatic installation of needed drivers to streamline setup process 

**Describe the solution you'd like**
Expected result is when you select the database type it would have a popup to ask you if you would like to search for and install the driver. Then it would do that for you and alert that it was successfully installed. (Similar to flow in dataGrip)

**Describe alternatives you've considered**
N/A

**Additional context**
Just from monitoring slack channel for a few months have noticed dozens of help requests which may have been avoided removing this manual driver installation step.
<img width="378" alt="Screen Shot 2020-08-18 at 2 03 33 PM" src="https://user-images.githubusercontent.com/47290627/90554648-cdd84e00-e15b-11ea-9102-1ee53b92b764.png">

**Comment by kseniiaguzeeva** [comment]
Thank you for the suggection.

**Comment by serge-rider** [comment]
Vertica JDBC driver is not publicly available - i.e. it is not published in any public Maven repository.
And there is no any direct download link on the official Vertica web site.

In fact this driver was published in http://maven.icm.edu.pl/artifactory/repo/ Maven repo - but it is not official and (most important) it doesn't support https. That's why we can't include it in the default dbeaver configuration.

**Comment by E1izabeth** [comment]
Can't reproduce against DBeaver 23.0.5
