### ISSUE TITLE
Auto completion of Oracle package method - since ver. 7.x.x show parameters data types instead of names

### ISSUE THREAD

**Issue by bcm5645** [dbeaver/dbeaver#9578]
#### System information: 
- Operating system (distribution) and version: Win10
- DBeaver version - since 7.x, in 6.x works fine

#### Connection specification:
- Database name and version - Oracle 12g

#### Describe your question:

Hi,
In dBeaver 6.3.5 (and earlier) as a auto-completion of packages methods, it used to show parameter names.
Since ver 7.x.x it shows parameter data types instead

So, instead of: 
work_time_calendar_api.IS_WORKING_DAY(**:CALENDAR_ID_, :WORK_DAY_**)
now it shows:
work_time_calendar_api.IS_WORKING_DAY(**VARCHAR2, DATE**)

Can this be changed? I haven't found any setting on this

/Wiktor

**Comment by LonwoLonwo** [comment]
@bcm5645 how does the whole query usually look, where autocomplete does not work correctly?

**Comment by LonwoLonwo** [comment]
Fixed in 7.2.3 
But it will work correctly just in special cases.
- First, the 'Show stored procedures in column list' item must be enabled in the settings (Preferences->Database Editors->SQL Editor->SQL Completion)
- Second, use ctrl+space in SQL Editor, to see all package methods for autocomplete
![2020-10-05 09_30_01-Preferences](https://user-images.githubusercontent.com/45152336/95047158-3d939f80-06ee-11eb-8d71-67c4c5e0a40b.png)

**Comment by bcm5645** [comment]
Works great!
Thanks a lot.
