### ISSUE TITLE
ER Diagram does not show the table name of related tables

### ISSUE THREAD

**Issue by linoba** [dbeaver/dbeaver#9582]
#### System information: 
- Operating system (distribution) and version: Ubuntu 18.04.5 LTS
- DBeaver version: Version 7.1.5.202008170457
- Additional extensions: n/a

#### Connection specification:
- Database name and version: MySQL 5.7
- Driver name: MySQL 8+, mysql-connector-java 8.0.21
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

#### Describe the problem you're observing:
When opening the `ER Diagram` tab, only the table title of the current table is loaded. Every other title line is blank, which is very annoying.

I noticed this first a few minor versions back. Maybe around 7.1.2. Not sure exactly when it stopped working.

#### Steps to reproduce, if exist:
- Connect to a database
- Double click a table
- Choose tab `ER Diagram`
- Look at the (missing) table names

#### Include any warning/errors/backtraces from the logs
Nothing in the logfiles. I looked in the `Error Log` window and in `dbeaver-debug.log`

**Comment by kseniiaguzeeva** [comment]
Please check which attributes are selected in ERD (can be selected in ERD context menu)?
![dbeaver_gbSeds5MAC](https://user-images.githubusercontent.com/51405061/90621036-e314b180-e21b-11ea-9201-b5b3a79450ea.png)
If it doesn't help is it possible to send a screenshot?

**Comment by linoba** [comment]
`All` are marked. Screenshot attached. The spacing between the left box edge and the table symbol is partially filled with random spaces for the tables that are connected.
![Screenshot from 2020-08-19 13-06-56 cut](https://user-images.githubusercontent.com/4362763/90628486-fb85cb80-e21d-11ea-9ea5-d9c9144aba49.png)

**Comment by linoba** [comment]
View for another example if `None` selected. Again, only the title of the centered table shows.
![Screenshot from 2020-08-19 13-16-42 None selected](https://user-images.githubusercontent.com/4362763/90628768-7b139a80-e21e-11ea-8bdc-96b28889a684.png)

**Comment by ircsasw** [comment]
**System information:**

- Operating system (distribution) and version: Debian GNU/Linux bullseye/sid GNOME X11 
- DBeaver version: Version 7.1.5.2020081806
- Additional extensions: n/a

**Connection specification:**

- Database name and version: MySQL 5.7
- Driver name: MySQL 8+, mysql-connector-java 8.0.21
- Do you use tunnels or proxies (SSH, SOCKS, etc)? No

**Describe the problem you're observing:**

The problem is in table name of related tables in ER digram

![image](https://user-images.githubusercontent.com/919978/90834477-fe60e900-e30f-11ea-859a-c2a69ad2f1c6.png)

**Comment by kseniiaguzeeva** [comment]
Could you please test the latest release https://dbeaver.io/download/? I stil cannot reproduce it in different enviroments.

**Comment by linoba** [comment]
Works great in `7.2.4.202011011603` :+1:
