### ISSUE TITLE
SQLite Upsert Doesn't Work

### ISSUE THREAD

**Issue by natohutch** [dbeaver/dbeaver#9729]
#### System information: 
- Windows 10 - 10.0.18363 Build 18363
- DBeaver 7.2.0.202008302047

#### Connection specification:
- SQLite

#### Describe the problem you're observing:

When I try to use the upsert functionality of sqlite I get an error with using the excluded functionality, saying that the column does not exist. The functionality is well documented for sqlite, and when I use their cli it works perfectly fine, it's just the script editor in dbeaver that doesn't like it.
sqlite doc here: https://sqlite.org/lang_UPSERT.html

#### Steps to reproduce, if exist:

INSERT INTO targetTable (datetime, columna)
SELECT datetime, columna from Import WHERE TRUE
ON CONFLICT(datetime) DO UPDATE SET
    columna=excluded.columna;

#### Include any warning/errors/backtraces from the logs

SQL Error [1]: [SQLITE_ERROR] SQL error or missing database (no such column: exluded.columna)

Thanks for the help ;)

**Comment by LonwoLonwo** [comment]
Can't reproduce in current version DBeaver 7.3.0

![2020-12-02 12_39_32-DBeaver Enterprise 7 3 0 - _none_ Script-54](https://user-images.githubusercontent.com/45152336/100855748-963baa80-349b-11eb-8fc1-93926815c37d.png)

All examples from the documentation work well.

@natohutch is this problem is still actual for you? 
Thanks in advance.

**Comment by LonwoLonwo** [comment]
Fell free to reopen the ticket, if the problem occurs again
