### ISSUE TITLE
Why datetime value cannot be NULL while importing data ?

### ISSUE THREAD

**Issue by xpharsh** [dbeaver/dbeaver#9734]
#### System information: 
- Operating system (distribution) and version : MacOS
- DBeaver version: Version 7.2.0.202008302047

#### Connection specification:
- Driver name: MySql
- Do you use tunnels or proxies (SSH, SOCKS, etc)? : No

#### Describing the problem:
When I try to import data from CSV file to a table then DBeaver shows an error says Incorrect datetime value which is NULL.
When i try to insert data manually through DBeaver in the same table then it's working just fine.

Because of that i am unable to import data from CSV. please Resolve it ASAP.

#### Include errors from the logs
Data truncation: Incorrect datetime value: 'NULL' for column `DatabaseName`.`TableName`.`deleted_date` at row 1

**Comment by kseniiaguzeeva** [comment]
Could you please send a CSV file example?

**Comment by xpharsh** [comment]
Please find the file as ZIP in attachment

[Table & Data File.zip](https://github.com/dbeaver/dbeaver/files/5200171/Table.Data.File.zip)

**Comment by kseniiaguzeeva** [comment]
Seems NULL is recognized as a string value, that's why SQL error is displayed. Looks like an enhancement rather then a bug.
As a workaround you can skip [NULL] during export. 
![dbeaver_KRVhmfy9Ep](https://user-images.githubusercontent.com/51405061/92706915-91180500-f35d-11ea-948f-435b6f7a57af.png)
Then enable **Set empty strings to NULL** in import wizard
![dbeaver_iallqtFTA5](https://user-images.githubusercontent.com/51405061/92707277-d3d9dd00-f35d-11ea-9c30-1b2bfa3c0a68.png)

**Comment by xpharsh** [comment]
Still Facing Same error:-
SQL Error [1292] [22001]: Data truncation: Incorrect datetime value: 'NULL' for column ..

Here is my settings:-

![Screen Shot 2020-09-10 at 2 57 46 PM](https://user-images.githubusercontent.com/2133724/92711728-6a19fd00-f376-11ea-9e0d-e52d30a0917d.png)

![Screen Shot 2020-09-10 at 2 53 32 PM](https://user-images.githubusercontent.com/2133724/92711782-756d2880-f376-11ea-8a6f-1fe89b280c2e.png)

**Comment by xpharsh** [comment]
We have generated backup file (CSV) from PHPMyAdmin. I think this will not be an issue, File (CSV) suppose to work for importing data right?

**Comment by xpharsh** [comment]
I inserted a blank column and try to insert NULL manually even then also DBeaver gives an error. The same error which was generated when I try to import data from a CSV file which was generated from PhpMyAdmin Web Panel.

here is the screenshot of the blank column
![Blank Colum](https://user-images.githubusercontent.com/2133724/92727994-a3119c00-f38d-11ea-9dd4-5d491bb9406d.png)

**Comment by kseniiaguzeeva** [comment]
Yes, CSV file is used for import and I can import Cpanel-NAME-test_prices.csv to the table
I just go through the wizard steps:
![1](https://user-images.githubusercontent.com/51405061/93077926-40bce200-f692-11ea-8b63-db40814b1cf1.png)
![2](https://user-images.githubusercontent.com/51405061/93077959-4dd9d100-f692-11ea-8a09-7f88119278dd.png)
![33](https://user-images.githubusercontent.com/51405061/93077961-4f0afe00-f692-11ea-81e0-d58ec16f5f4c.png)
![4](https://user-images.githubusercontent.com/51405061/93077931-4286a580-f692-11ea-91c7-b0f8479659ce.png)
![5](https://user-images.githubusercontent.com/51405061/93077932-4286a580-f692-11ea-86a5-bfc125fc006d.png)![4](https://user-images.githubusercontent.com/51405061/93077929-41ee0f00-f692-11ea-9b2a-c0653e5324ae.gif)

Where is the difference?

**Comment by xpharsh** [comment]
i can also able to import from Cpanel-NAME-test_prices.csv because it doesn't contain any NULL column.

Please try this file.
[NAME-test_prices.csv.zip](https://github.com/dbeaver/dbeaver/files/5218028/NAME-test_prices.csv.zip)

**Comment by kseniiaguzeeva** [comment]
Now I see. It is the expected behavior. Just export table with empty column instead of NULL (I described above how to do it via DBeaver). Please write if you have additional questions.

**Comment by xpharsh** [comment]
> Now I see. It is the expected behaviour. Just export table with empty column instead of NULL (I described above how to do it via DBeaver). Please write if you have additional questions.

I have exported that table from **PhpMyAdmin** web panel, they usually export it with NULL because the default value is set to NULL.
If you have any solution then can you please show me how you did that step by step. if possible then a video will be perfect?

Why dbeaver don't have a facility to import this type of file without any issue?

**Comment by kseniiaguzeeva** [comment]
The reason is that a lot of special cases exist in data tranfer. DBeaver has selected this representation as a default one.
To export a table with an empty column please:
1. Open export wizard
2. Select CSV
3. Leave NULL string empty in exporter setting
![dbeaver_bNMaOFUSJW](https://user-images.githubusercontent.com/51405061/93087302-09096680-f6a1-11ea-96c0-58a461e59c8a.png)
4. Select a directory
5. Check settings
6. Start export

Result:
"id","test_id","lab_id","lab_price","lab_discounted_price","special_discount","slug","deleted_at","created_at","updated_at"
1,2,4,2000,1500,5.00,cce72c8ab8e96c6b22973f35c1833a90,,"2020-09-01 10:43:06.0","2020-09-01 10:43:06.0"
3,2,3,1340,515,15.00,e3027c574fad6a6993b88f3934295e2a,,"2020-09-01 10:58:16.0","2020-09-01 11:02:19.0"
4,2,1,1200,395,0.00,dd4ce3f819ef2318250758a8e049369c,,"2020-09-01 11:06:53.0","2020-09-01 11:07:35.0"
5,5,4,5250,870,52.00,"33c857782d66a8d32b593792f5a533c4",,"2020-09-03 15:29:16.0","2020-09-03 15:29:16.0"
6,4,4,4315,750,51.00,"7e21438eeac41660becc2e31f625eeb7",,"2020-09-03 15:30:37.0","2020-09-03 15:30:37.0"
7,3,4,3025,570,49.00,"66c123a71a4b77111f0bd245a4a3a308",,"2020-09-03 15:31:40.0","2020-09-09 06:48:17.0"
8,6,4,600,220,0.00,"5becd17f4b9a1d92f8fa0fbd0d6e5c4d",,"2020-09-04 10:47:13.0","2020-09-09 10:33:04.0"
9,6,5,400,180,0.00,"35c0f10b613069fdc236f597bcbab5d2",,"2020-09-04 10:47:47.0","2020-09-09 10:32:54.0"
10,6,1,450,200,0.00,abaa0f402816af35f3cde857bbbf6664,,"2020-09-04 10:48:17.0","2020-09-09 10:32:44.0"
11,7,5,500,150,0.00,d3e0bc4fce683e41d8b258a9969ab956,,"2020-09-04 10:54:12.0","2020-09-09 10:32:33.0"
12,7,4,550,200,0.00,"6a6ba45d1ca45a3dfb88844cbba64231",,"2020-09-04 10:55:28.0","2020-09-09 10:32:23.0"
13,7,1,450,170,0.00,e156226ca1152c396a23c761893409e2,,"2020-09-04 10:55:55.0","2020-09-09 10:32:13.0"
14,7,2,500,200,0.00,acdcc5c6ce911c52d15838b923d74d64,,"2020-09-08 16:07:39.0","2020-09-09 10:32:02.0"

**Comment by xpharsh** [comment]
Thanks for your support, can you please also guide me using **PhpMyAdmin**  to export empty Colum instead NULL?

**Comment by kseniiaguzeeva** [comment]
Unfortunately I do not use PhpMyAdmin.

**Comment by xpharsh** [comment]
ok No issue, Thanks for the support.

**Comment by xpharsh** [comment]
one more question. can dbeaver (free) Open-source version connect to live server (Shared Hosting)?
